<?if(isset($this->noticeMessage)){?>
<div class="message notice"><strong><? echo $this->noticeMessage;?></strong>.</div>
<?}?>
<?if(isset($this->noticeSuccess)){?>
<div class="message success"><strong><? echo $this->noticeSuccess;?></strong>.</div>
<?}?>
<?if(isset($this->noticeError)){?>
<div class="message error"><strong><? echo $this->noticeError;?></strong>.</div>
<?}?>



<?   if($this->type != 'exam'){ ?>
<div class="message toolbar">
	<h2><?php echo $this->title; ?></h2>
	<div class="toolbar-button">
		
	</div>
</div>

<div align="center" style="background:#ebebeb; height:30px;">
<ul class="steps">
	<li class="prevDone">
		<span>1</span> Company Identity Number
	</li>
    <li class="prevDone">
		<span>2</span> Company Particular
	</li>  	
	<li class="current">
		<span>3</span> Confirmation of Registration
	</li>
</ul>
<br class="clear" />
</div>
<BR>
<? } ?>
<div>

<?php echo $this->emailTemplate;?>
</div>