
<div class="message toolbar">
	<h2><?php echo $this->title; ?></h2>
	<div class="toolbar-button">
		<ul>	
		  
			<li>
				<a href="#" >
					<span class='info'></span>
					Info
				</a>
			</li>
		</ul>
	</div>
</div>
<br><br>

	<fieldset>
	<legend><?php echo $this->translate("Search Options");?></legend>
    <?php echo $this->form;?>
    </fieldset>
    <br/>
	<fieldset>
		<table class="table" width="100%" cellpadding="5" cellspacing="1">
		
		  	<tr>
	            <th><?php echo $this->translate("Student Name");?></th>
	            <th><?php echo $this->translate("No. Fomulir");?></th>    
		    	<th><?php echo $this->translate("NIM");?></th>
		    	<th><?php echo $this->translate("Awards");?></th>
		    	<th><?php echo $this->translate("Organization Experiences");?></th>
		    	<th><?php echo $this->translate("International Language");?></th>
		    	<th><?php echo $this->translate("Character Building");?></th>
		    	<th><?php echo $this->translate("Professional Practices");?></th>
	    	</tr>

	    	<?php 	    	
	    	if (count($this->paginator)){	    		
	        foreach ($this->paginator as $lobjstudents){
	        ?>
	  		<tr style="background-color:<?php echo $this->cycle(array("#F0F0F0","#FFFFFF"))->next()?>">	  		
	        	<td><a href="<?php echo $this->baseUrl();?>/graduation/skpi/skpi/id/<?php echo $this->escape($lobjstudents['IdStudentRegistration']);?>/name/<?php  echo $this->escape($lobjstudents['appl_fname'].' '.$lobjstudents['appl_mname'].' '.$lobjstudents['appl_lname']);?>/nim/<?php echo $this->escape($lobjstudents['registrationId']);?>"><?php echo $this->escape($lobjstudents['appl_fname'].' '.$lobjstudents['appl_mname'].' '.$lobjstudents['appl_lname']);?></a></td>
	        	<td><?php echo $this->escape($lobjstudents['at_pes_id']);?></td>
	        	<td><?php echo $this->escape($lobjstudents['registrationId']);?></td>
                <td><?php if ($lobjstudents['Honors']!='') {?>
                <a href="<?php echo $this->baseUrl();?>/graduation/skpi/skpi/id/<?php echo $this->escape($lobjstudents['IdStudentRegistration']);?>/name/<?php  echo $this->escape($lobjstudents['appl_fname'].' '.$lobjstudents['appl_mname'].' '.$lobjstudents['appl_lname']);?>/nim/<?php echo $this->escape($lobjstudents['registrationId']);?>/#Tab2"><img src='<?php echo $this->baseUrl();?>/images/free.png' border=0 width='20' height='20' title='<?php echo $this->translate("do you want to approve ?");?>' ></a></td>
	        	<?php } ?>
	        	<td><?php  if ($lobjstudents['Organisasi']!='') {?>
	        	<a href="<?php echo $this->baseUrl();?>/graduation/skpi/skpi/id/<?php echo $this->escape($lobjstudents['IdStudentRegistration']);?>/name/<?php  echo $this->escape($lobjstudents['appl_fname'].' '.$lobjstudents['appl_mname'].' '.$lobjstudents['appl_lname']);?>/nim/<?php echo $this->escape($lobjstudents['registrationId']);?>/#Tab3"><img src='<?php echo $this->baseUrl();?>/images/free.png' border=0 width='20' height='20' title='<?php echo $this->translate("do you want to approve ?");?>' ></a></td>
	        	<?php } ?>
	        	<td><?php if ($lobjstudents['Language']!='') {?>
	        	<a href="<?php echo $this->baseUrl();?>/graduation/skpi/skpi/id/<?php echo $this->escape($lobjstudents['IdStudentRegistration']);?>/name/<?php  echo $this->escape($lobjstudents['appl_fname'].' '.$lobjstudents['appl_mname'].' '.$lobjstudents['appl_lname']);?>/nim/<?php echo $this->escape($lobjstudents['registrationId']);?>/#Tab4"><img src='<?php echo $this->baseUrl();?>/images/free.png' border=0 width='20' height='20' title='<?php echo $this->translate("do you want to approve ?");?>' ></a></td>
	        	<?php } ?>
	        	<td><?php  if ($lobjstudents['Softskill']!='') {?>
	        	<a href="<?php echo $this->baseUrl();?>/graduation/skpi/skpi/id/<?php echo $this->escape($lobjstudents['IdStudentRegistration']);?>/name/<?php  echo $this->escape($lobjstudents['appl_fname'].' '.$lobjstudents['appl_mname'].' '.$lobjstudents['appl_lname']);?>/nim/<?php echo $this->escape($lobjstudents['registrationId']);?>/#Tab5"><img src='<?php echo $this->baseUrl();?>/images/free.png' border=0 width='20' height='20' title='<?php echo $this->translate("do you want to approve ?");?>' ></a></td>
	        	<?php } ?>
	        	<td><?php  if ($lobjstudents['Internship']!='') {?>
	        	<a href="<?php echo $this->baseUrl();?>/graduation/skpi/skpi/id/<?php echo $this->escape($lobjstudents['IdStudentRegistration']);?>/name/<?php  echo $this->escape($lobjstudents['appl_fname'].' '.$lobjstudents['appl_mname'].' '.$lobjstudents['appl_lname']);?>/nim/<?php echo $this->escape($lobjstudents['registrationId']);?>/#Tab6"><img src='<?php echo $this->baseUrl();?>/images/free.png' border=0 width='20' height='20' title='<?php echo $this->translate("do you want to approve ?");?>' ></a></td>
	       <?php } 
	        } } 
	        ?>
			</tr>
			<?php 
			if (count($this->paginator)){
			?>
			<tr>
	        	<td colspan="8" align="right"><div class="pagination"><?php echo $this->paginationControl($this->lobjpaginator,'Sliding',
	                                    '/partials/my_pagination_control.phtml'); ?></div></td>
   			</tr>
   			<?php 
			}
   			?>
		</table>
	</fieldset>

