<style type="text/css">
.zend_form dt {
    width: 177px;
}
.zend_form dd {
    padding: 2px 187px;
}
</style>
<script type="text/javascript">
 
function edit_Organisasi(n) {
	 
	var x = document.getElementById("data_org").rows[n].cells;
	
	document.getElementById("title_bahasa_org").value=x[2].innerHTML;
	document.getElementById("title_org").value=x[3].innerHTML;
	document.getElementById("idOrganisasi").value=document.getElementById("idOrganisasilst["+n+"]").value;
	document.getElementById("yearstart").value= x[8].innerHTML;
	document.getElementById("yearstop").value= x[9].innerHTML;
	document.getElementById("level_org").value=document.getElementById("level_orglst["+n+"]").value;
	document.getElementById("role_org").value=document.getElementById("role_orglst["+n+"]").value;
	document.getElementById("field_org").value=document.getElementById("field_orglst["+n+"]").value;
	document.getElementById("category_org").value=document.getElementById("category_orglst["+n+"]").value;
	document.getElementById("IdSemester").value=document.getElementById("semester_orglst["+n+"]").value;
	document.getElementById("IdBuktiOrg").value=document.getElementById("bukti_orglst["+n+"]").value;
	
	//alert(document.getElementById("field").value);
}

function onclickDeleteOrg(n,redirect) {
	
	var r = confirm("Are you sure to delete it?");
	if (r == true) {
		var url="<?php echo $this->baseUrl();?>/default/skpm/delete-organisasi/idOrganisasi/"+n+redirect;
		window.location=url;
	}  
}
 
    
 
 
</script>


 
<div style="width:100%;">
<fieldset>
<form id="honors" method="post" action="<?php echo $this->baseUrl()?>/default/skpm/organisasi" >
<input type="hidden" name="idOrganisasi" id="idOrganisasi"> 
<input type="hidden" name="idStudentRegistration" id="idStudentRegistration" value="<?php echo $this->IdStudentRegistration;?>">
<input type="hidden" name="nim" id="nim" value="<?php echo $this->nim;?>">
<input type="hidden" name="studentname" id="studentname" value="<?php echo $this->studentname;?>">

<table  width="80%" cellpadding="5" cellspacing="3" border="0">
	<tr>	<td width="20%"><?php echo $this->translate("Name of Organization in Bahasa");?></td><td>:</td>
			<td> <textarea rows="4" cols="50" id="title_bahasa_org" name="title_bahasa_org">    
			</textarea></tr> 
	<tr>	<td width="20%"><?php echo $this->translate("Name Of Organization");?></td><td>:</td>
			<td> <textarea rows="4" cols="50" id="title_org" name="title_org">     
			</textarea></tr>
	<tr>	<td width="20%"><?php echo $this->translate("Category");?></td><td>:</td>
			<td>
		 
			<select id="category_org" name="category_org">
			    <option value="0"><?php echo $this->translate("Please Select");?></option>
			    <?php 
			    	foreach ($this->category_list as $level):
			    ?>
			    		<option value="<?php echo $level["key"];?>"<?php if($this->levelId == $level["key"]){ echo 'selected';}?>><?php echo $level["value"];?></option>
			    <?php 
			    	endforeach;
			    ?>
			</select>
		 
			</td></tr>
	<tr>	<td width="20%"><?php echo $this->translate("Field");?></td><td>:</td>
			<td> <select id="field_org" name="field_org">
			    <option value="0"><?php echo $this->translate("Please Select");?></option>
			    <?php 
			    	foreach ($this->field_list as $level):
			    ?>
			    		<option value="<?php echo $level["key"];?>"<?php if($this->levelId == $level["key"]){ echo 'selected';}?>><?php echo $level["value"];?></option>
			    <?php 
			    	endforeach;
			    ?>
			</select></td>	</tr>		
	
	<tr>	<td width="20%"><?php echo $this->translate("Level");?></td><td>:</td>
			<td>
		 
			<select id="level_org" name="level_org">
			    <option value="0"><?php echo $this->translate("Please Select");?></option>
			    <?php 
			    	foreach ($this->level_list as $level):
			    ?>
			    		<option value="<?php echo $level["key"];?>"<?php if($this->levelId == $level["key"]){ echo 'selected';}?>><?php echo $level["value"];?></option>
			    <?php 
			    	endforeach;
			    ?>
			</select>
		 
			</td></tr>
	<tr>	<td width="20%"><?php echo $this->translate("Occupacy");?></td><td>:</td>
			<td>
			 
			<select id="role_org" name="role_org">
			    <option value="0"><?php echo $this->translate("Please Select");?></option>
			    <?php 
			    	foreach ($this->role_list as $semester):
			    ?>
			    		<option value="<?php echo $semester["key"];?>" <?php if($this->fieldId == $semester["key"]){ echo 'selected';}?>><?php echo $semester["value"];?></option>
			    <?php 
			    	endforeach;
			    ?>
			</select>
		 
			</td></tr>
			<tr>	<td width="20%"><?php echo $this->translate("Year Start");?> </td><td>:</td><td>
			<select id="yearstart" name="yearstart">
				 <option value="0"><?php echo $this->translate("Please Select");?></option>
			    <?php 
			    	foreach ($this->year_list as $semester):
			    ?>
			    		<option value="<?php echo $semester;?>" <?php if($this->fieldId == $semester ){ echo 'selected';}?>><?php echo $semester ;?></option>
			    <?php 
			    	endforeach;
			    ?>
			</select>
			<?php echo $this->translate("Year Stop").' : ';?> 
			<select id="yearstop" name="yearstop" >
				  <option value="0"><?php echo $this->translate("Please Select");?></option>
			    <?php 
			    	foreach ($this->year_list as $semester):
			    ?>
			    		<option value="<?php echo $semester ;?>" <?php if($this->fieldId == $semester ){ echo 'selected';}?>><?php echo $semester ;?></option>
			    <?php 
			    	endforeach;
			    ?>
			</select>
			</td>
		<tr>	<td width="20%"><?php echo $this->translate("Semester");?></td><td>:</td>
			<td>
			 
			<select id="IdSemester" name="IdSemester" >
			     <?php 
			    	foreach ($this->semester_list as $semester):
			    ?>
			    		<option value="<?php echo $semester["key"];?>" <?php if($this->semesterid == $semester["key"]){ echo 'selected';}?>><?php echo $semester["value"];?></option>
			    <?php 
			    	endforeach;
			    ?>
			</select>
		 
			</td></tr>
	<tr>	<td width="20%"><?php echo $this->translate("Bukti Fisik");?></td><td>:</td>
			<td>
			 
			<select id="IdBuktiOrg" name="IdBukti" >
			     <?php 
			    	foreach ($this->bukti_list as $semester):
			    ?>
			    		<option value="<?php echo $semester["key"];?>" <?php if($this->buktiid == $semester["key"]){ echo 'selected';}?>><?php echo $semester["value"];?></option>
			    <?php 
			    	endforeach;
			    ?>
			</select>
		 
			</td></tr>
	<tr><td colspan="3" align="right"><input type="submit" name="submit" value="<?php echo $this->translate('Save')?>" ></td>
	
	</tr>
</table>

</form>
</fieldset>
<br>
 
 
<table class="table" id="data_org" width="100%" cellpadding="5" cellspacing="1" border="0">
	<tr>
		<th width="5%"><?php echo $this->translate("No");?></th>
		<th width="5%"><?php echo $this->translate("Status");?></th> 
		<th width="35%"><?php echo $this->translate("Name  in Bahasa");?></th>
		<th width="35%"><?php echo $this->translate("Name of Organization");?></th>
		<th width="10%"><?php echo $this->translate("Category");?></th>
		<th width="10%"><?php echo $this->translate("Field");?></th>			
		<th width="10%"><?php echo $this->translate("Level");?></th>
		<th width="10%"><?php echo $this->translate("Role");?></th>
		<th width="10%"><?php echo $this->translate("Year Started");?></th>
		<th width="10%"><?php echo $this->translate("Year Stoped");?></th>
					<th width="10%"><?php echo $this->translate("Semester");?></th>
		<th width="10%"><?php echo $this->translate("Certificate");?></th>

		<th width="10%"><?php echo $this->translate("Action");?></th>
	</tr>
	<?php  
	if (count($this->organisasis)>0) {
	foreach($this->organisasis as $index=>$value){ 
		$id=$value['idOrganisasi'];
	?>
	<tr <?php echo $i%2==0?"class='shade'":""; ?>>
		<input type="hidden" id="idOrganisasilst[<?php echo $index+1;?>]" value="<?php echo $value['idOrganisasi'];?>">
		<input type="hidden" id="level_orglst[<?php echo $index+1;?>]" value="<?php echo $value['levelid'];?>">
		<input type="hidden" id="field_orglst[<?php echo $index+1;?>]" value="<?php echo $value['fieldid'];?>">
		<input type="hidden" id="role_orglst[<?php echo $index+1;?>]" value="<?php echo $value['roleid'];?>">
		<input type="hidden" id="category_orglst[<?php echo $index+1;?>]" value="<?php echo $value['categoryid'];?>">
		<input type="hidden" id="semester_orglst[<?php echo $index+1;?>]" value="<?php echo $value['IdSemesterMain'];?>">
		<input type="hidden" id="bukti_orglst[<?php echo $index+1;?>]" value="<?php echo $value['BuktiFisik'];?>">
		
		<td><?php echo $index+1;?></td> 
		<td align="center">
		<?php if ($value['approved']=='2' ) {
					 
					?>
					<img src='<?php echo $this->baseUrl();?>/images/reject.png' border=0 width='20' height='20' title="<?php echo $this->translate('rejected by student'); ?>"> 
			  
				<?php } ?>
		<?php if ($value['approved_by']==$this->iduser && $value['approved']=='1') {
					 
					?>
					 
						<a href="<?php echo $this->url(array('module'=>'default','controller'=>'skpm', 'action'=>'organisasi-reject','idOrganisasi'=>$value['idOrganisasi'],'id'=>$this->IdStudentRegistration,'name'=>$this->studentname,'nim'=>$this->nim),'default',true)?>"><img src='<?php echo $this->baseUrl();?>/images/accept.png' border=0 width='20' height='20' title='<?php echo $this->translate("do you want to unapprove?");?>' ></a>
			<?php } else if ($value['approved']=='1') {?> 
			
					<img src='<?php echo $this->baseUrl();?>/images/prohibit.png' border=0 width='20' height='20' title="<?php echo $this->translate('Approved by other'); ?>"> 	
		<?php }
			if ($value['approved']=='0' ||$value['approved']=='') {
					 
					?>
					 	<img src='<?php echo $this->baseUrl();?>/images/free.png' border=0 width='20' height='20' title='<?php echo $this->translate("not approve yet?");?>' >
			<?php }?> 
		</td>

		<td><?php  echo $value['title_bahasa'];?> </td>
		<td><?php echo $value['title']; ?>
		<td><?php echo $value["categoryname"];?></td>
		<td><?php echo $value["field"];?></td>
		<td><?php echo $value["level"];?></td>
		<td><?php echo $value["role"];?></td>
		<td><?php echo $value["year_start"];?></td>
		<td><?php echo $value["year_stop"];?></td>
		<td><?php echo $value["SemesterMainName"];?></td>
		<?php 
		$pathupload=$value['path'];
		if($pathupload!=''){
			$dt = explode("triapp",$pathupload);
			//echo var_dump($dt);exit;
			$path = $dt[1];
			$path ="<a target='_blank' href=http://".APP_HOSTNAME.$path.">" ;
		
		?> <td align="center"><?php  echo $path;?><img src='<?php echo $this->baseUrl();?>/images/document.png' border=0 width='20' height='20' title="Download" ></a></td> <?php 
		} else {
			$direct=$this->url(array('module'=>'default','controller'=>'skpm', 'action'=>'skpm','id'=>$this->IdStudentRegistration,'nim'=>$this->nim,'name'=>$this->studentname),'default',true)."/#Tab5"; ?>
		<td align="center"><img src='<?php echo $this->baseUrl();?>/images/upload.png' border=0 width='20' height='20' title="Upload"  onclick="onclickUpload(<?php echo $value['idOrganisasi']?>,'Organisasi','<?php echo $direct;?>',<?php echo $this->IdStudentRegistration;?>,'103')" /></td>
		<?php }?>
		<td align="center">
		<?php if ($value['id_user']==$this->iduser && $value['approved']=='0') {?>
					<img src='<?php echo $this->baseUrl();?>/images/edit.png' border=0 width='20' height='20' title="Edit"  onclick="edit_Organisasi(<?php echo  $index+1;?>)" >
					<img src='<?php echo $this->baseUrl();?>/images/trash.png' border=0 width='20' height='20' title="Delete"  onclick="onclickDeleteOrg(<?php echo $value['idOrganisasi'];?>,'/id/<?php echo $this->IdStudentRegistration ?>/name/<?php echo $this->studentname ?>/nim/<?php echo $this->nim ?>')">
			<?php }?></td>
	
	</tr>
	<?php }
} ?>

</table>
  
 
