 
<table class="table" width="100%">
<tr><td width="20%"><?php  echo $this->translate("Student Name"); ?></td><td width="5%">:</td><td><?php echo $this->studentname;?></td>
<tr><td><?php  echo $this->translate("NIM"); ?></td><td>:</td><td><?php echo $this->nim;?></td>
<tr><td><?php  echo $this->translate("CGPA"); ?></td><td>:</td><td><?php echo $this->student_grade['sg_cgpa'];?></td>
<tr><td><?php  echo $this->translate("Total Credit Hours"); ?></td><td>:</td><td><?php echo $this->student_grade['sg_cum_credithour'];?></td>

</table>
 
  