<?php /* Set locale to Indonesia */
	     setlocale(LC_TIME, "id_ID"); ?>
		
<!-----------------------
	Name: Template Kartu Rencana Studi
	version: 1.0
	Author: Mardhiyati Ipin
-->

<html>
<head>
<style type="text/css">
body{
	font-family: "Trebuchet MS", Helvetica, sans-serif;
	font-size: 11px;
	padding:0;
	margin:0;
}
.table{
	width: 100%;
   
}

/* Table */
.table_header{
	font-family: "Trebuchet MS", Helvetica, sans-serif;	
    width: 100%;
    cellspacing: 0px;
    cellpadding: 5px;
    border:0px;
}
.table2{
	font-family: "Trebuchet MS", Helvetica, sans-serif;	
    width: 100%;
    cellspacing: 0px;
    cellpadding: 5px;
    border:1px solid #000;
}
.table_content{
	font-family: "Trebuchet MS", Helvetica, sans-serif;	
    width: 100%;
    cellspacing: 2px;
    cellpadding: 5px;
    border:1px solid #000;
}
.table_content th{
	background-color: #767676;
	color:white;
	line-height: 10px;
}
.table2 th{
	background-color: #767676;
	color:white;
	line-height: 10px;
}
.table2 tr{
	line-height: 5px;
}
.table2 td{
	/*border-bottom:1px dotted gray;*/
	border:1px solid #000;
	line-height: 16px;
}

.header_title  {
	font-size: 16px;
	font-weight: bold;
}

.header-top-notice{
	font-size: 0.8em;
	font-style: italic;
	text-decoration: underline;
	width: 100%";
	margin: 5px 0;
}

.header-right-info{
	width:100%;
	margin: 0;
	text-align: left;
	font-size: 1.3em;
	font-weight: bold;
}
.header-center-info h1{
	font-size: 1.3em;
}
.header-pes-no{
	border: 1px solid black;
	font-size: 1.1em;
	padding: 5px 5px;
	width: 100px;
}
div.box{
	border: 1px solid #111111;
}


td.border-top{
	border-top: 1px solid #111111;
}
td.border-top-bottom{
	border-top: 1px solid #111111;
	border-bottom: 1px solid #111111;
}
td.bold-text{
	font-weight: bold;
}
.style1 {
	font-size: 18px;
	font-weight: bold;
}
.style2 {
	font-size: 16px;
	font-weight: bold;
}
.style3 {
	font-size: 14px;
	font-weight: bold;
}
#footer {
  position: fixed;
  bottom: 0px;
  left: 0px;
  right: 0px;
  height: 30px;
  text-align: center;
  /* background-color: lightgray;
  border-top: 2px solid gray; */
}
</style>
<script>
function cetakpdf(){
	window.location="<?php echo $this->url(array('module'=>'finalassignment','controller'=>'proposal','action'=>'finalassignment-extend-pdf','proposedby'=>$this->proposal['IdStudentRegistration'],'idtaapplication'=>$this->proposal['IdTAApplication']), 'default', true);?>";
}
</script> 
<div class="message toolbar">
	<h2><?php echo $this->title; ?></h2>
	<div class="toolbar-button">
		<ul>
			<li>
			<a href="#" onclick="cetakpdf();">
				<span class='print'></span>
				Print Pdf
			</a>
			
		</li>
		</ul>
	</div>
</div> 
<br />
<fieldset><legend><?php echo $this->translate('Student Info');?></legend>
<table class="table">
<tr><td><?php echo $this->translate('Name');?></td><td>:</td><td><?php echo $this->student['appl_fname'].' '.$this->student['appl_mname'].' '.$this->student['appl_lname'];?></td>
<tr><td><?php echo $this->translate('NIM');?></td><td>:</td><td><?php echo $this->student['registrationId'];?></td>

<tr><td><?php echo $this->translate('Majoring');?></td><td>:</td><td><?php echo $this->student['majoring'];?></td>
 
	<tr>	<td width="25%"><?php echo $this->translate("Title in Bahasa");?></td><td width="5px">:</td>
			<td><?php echo $this->proposal['title_bahasa']; ?></td>  </tr> 
	<tr>	<td width="20%"><?php echo $this->translate("Title in English");?></td><td>:</td>
			<td> <?php echo $this->proposal['title']; ?></td></tr>
	<tr>	<td width="20%"><?php echo $this->translate("First Problem Statement");?></td><td>:</td>
			<td> <?php echo $this->proposal['problem1']; ?></td></tr>
	<tr>	<td width="20%"><?php echo $this->translate("Second Problem Statement");?></td><td>:</td>
			<td> <?php echo $this->proposal['problem2']; ?></td></tr>
	<tr>	<td width="20%"><?php echo $this->translate("Third Problem Statement");?></td><td>:</td>
			<td> <?php echo $this->proposal['problem3']; ?></td></tr>
	<tr>	<td width="20%"><?php echo $this->translate("Abstract");?></td><td>:</td>
			<td> <?php echo $this->proposal['abstrak']; ?></td></tr>
	 
</table>
 
</fieldset> 
<br>
<fieldset><legend><?php echo $this->translate('Extention Form');?></legend>

<form id="extend_form" method="post" action="/finalassignment/extend/index">
<input type="hidden" id="IdTAApplication" name="IdTAApplication" value="<?php echo $this->idtaapplication;?>">
<input type="hidden" id="IdStudentRegistration" name="IdStudentRegistration" value="<?php echo $this->proposedby;?>">
<input type="hidden" id="IdTAExtend" name="IdTAExtend" value="<?php echo $this->extend['IdTAExtend'];?>">
<input type="hidden" id="IdTAFlowMain" name="IdTAFlowMain" value="<?php echo $this->idflowmain;?>">
 
<table width="100%">
<tr>
			<td>
				<?php echo $this->translate("Extention Cause")?>
			</td>
			<td width="5px">:</td>
			<td>				
				<select name="ExtendCode" id="ExtendCode">
					<?php foreach ($this->extend_list as $items) {
						$select = "";
						if ($this->extend['ExtendCode']==$items['key'] ){
							$select = 'selected="selected"';
						}?>
					<option value="<?php echo $items['key'];?>" <?php echo $select; ?>> <?php echo $this->translate($items['value']);?> </option>
					 <?php }?>
				</select>
			</td>
		</tr>
		<tr>
			<td>
				<?php echo $this->translate("Remark")?>
			</td>
			<td width="5px">:</td>
			<td>
				<textarea cols="50" rows="5" name="remark" id="remark" ><?php if (isset( $this->extend)) echo $this->extend['remark'];?></textarea>
			</td>
		</tr>
  <tr><td colspan="3" align="center"><input type="submit" id="submit" name="submit"></td>
</table>



</form>
</fieldset>