<?if(isset($this->noticeMessage)){?>
<div class="message notice"><strong><? echo $this->noticeMessage;?></strong>.</div>
<?}?>
<?if(isset($this->noticeSuccess)){?>
<div class="message success"><strong><? echo $this->noticeSuccess;?></strong>.</div>
<?}?>
<?if(isset($this->noticeError)){?>
<div class="message error"><strong><? echo $this->noticeError;?></strong>.</div>
<?}?>

<div class="message toolbar">
	<h2><?php echo $this->title; ?></h2>
	<div class="toolbar-button">
		<ul>
			<li>
				<a href="<?php echo $this->url(array('module'=>'anr-setup','controller'=>'calendar', 'action'=>'edit','id'=>$this->id));?>">
					<span class='edit'></span>
					Edit
				</a>
			</li>
			<li>
				<a href="#" onClick="if(confirm('Confirm to delete?')){window.location='<?php echo $this->url(array('module'=>'anr-setup','controller'=>'calendar', 'action'=>'delete','id'=>$this->id));?>'}">
					<span class='delete'></span>
					Delete
				</a>
			</li>
			<li class="divider"></li>
			<li>
				<a href="<?php echo $this->url(array('module'=>'anr-setup','controller'=>'calendar', 'action'=>'index'),'default',true);?>">
					<span class='back'></span>
					Back
				</a>
			</li>
			<li>
				<a href="#" >
					<span class='info'></span>
					Info
				</a>
			</li>
		</ul>
	</div>
</div>
<br />

<table class="table2" width="500px" cellpadding="2" cellspacing="2">
	<tr>
		<th>Semester</th>
		<td><?php echo $this->data['semester_name']. " (".date("d-m-Y", strtotime($this->data['semester_start_date']))." - ".date("d-m-Y", strtotime($this->data['semester_end_date'])).")"?> </td>
	</tr>
	<tr>
		<th>Activity</th>
		<td><?php echo $this->data['activity_name']?></td>
	</tr>
	<tr>
		<th>Start Date</th>
		<td><?php echo date("d/m/Y", strtotime($this->data['start_date'])); ?></td>
	</tr>
	<tr>
		<th>End Date</th>
		<td><?php echo date("d/m/Y", strtotime($this->data['end_date']));?></td>
	</tr>
</table>