<script type="text/javascript">
	$(function() {
		$('#faculty_id').change(function() {
  			var fac_id = $('#faculty_id').val();

  			$.ajax({
    		  url: "<?php echo $this->url(array('module'=>'general-setup','controller'=>'department', 'action'=>'ajax-get-department'),'default',true);?>",
    		  data:"id="+fac_id,
    		  dataType:'json',
    		  context: document.body,
    		  success: function(data){
        		 $.each(data,function(key,value){
        			  alert(value.name);
        		  });
    		    
    		  }
    		});
		});
	});

</script>

<div class="message toolbar">
	<h2><?php echo $this->title; ?></h2>
	<div class="toolbar-button">
		<ul>
			<li>
				<a href="<?php echo $this->url(array('module'=>'anr-setup','controller'=>'course', 'action'=>'index'),'default',true);?>">
					<span class='back'></span>
					Back
				</a>
			</li>
			<li>
				<a href="#" >
					<span class='info'></span>
					Info
				</a>
			</li>
		</ul>
	</div>
</div>
<br />
<?php 
	$this->form->setAction($this->url());
	echo  $this->form;
?>
