
<script type="text/javascript">
	$(function() {
		// a workaround for a flaw in the demo system (http://dev.jqueryui.com/ticket/4375), ignore!
		$( "#dialog:ui-dialog" ).dialog( "destroy" );
	
		$( "#dialog-search" ).dialog({
			width: 400,
			autoOpen: false,
			modal: true,
			buttons: {
				"Search": function() { 
					$('#search_form').submit();
				}, 
				"Close": function() { 
					$(this).dialog("close"); 
				} 
			}
		});
		
	});

	function del(title, id){
		var id = $('input[name=course_id]:checked').val();

		if(!id){
			alert('Please select any course first');
		}else{
			if(confirm('Are you sure to delete '+title+'?')){
				window.location = "<?php echo $this->url(array('module'=>'anr-setup','controller'=>'course', 'action'=>'delete')); ?>/id/"+id;
			}
		}
	}
	
	function add(){
		window.location="<?php echo $this->url(array('module'=>'anr-setup','controller'=>'course', 'action'=>'add'));?>";
	}

	function edit(){
		var id = $('input[name=course_id]:checked').val();

		if(!id){
			alert('Please select any course first');
		}else{
			window.location="<?php echo $this->url(array('module'=>'anr-setup','controller'=>'course', 'action'=>'edit'),'default',true);?>/id/"+id;
		}
	}

</script>

<div class="message toolbar">
	<h2><?php echo $this->title; ?></h2>
	<div class="toolbar-button">
		<ul>
			<li>
				<a href="#" onclick="javascript:add()">
					<span class='add'></span>
					Add
				</a>
			</li>
			<li>
				<a href="#" onclick="javascript:edit()">
					<span class='edit'></span>
					Edit
				</a>
			</li>
			<li>
				<a href="#" onclick="javascript:del()">
					<span class='delete'></span>
					Delete
				</a>
			</li>
			<li class="divider"></li>
			<li>
				<a href="#" onClick="$('#dialog-search').dialog('open');" >
					<span class='search'></span>
					Search
				</a>
			</li>
			<li>
				<a href="#" >
					<span class='info'></span>
					Info
				</a>
			</li>
		</ul>
	</div>
</div>
<br />

	
<?php 
	echo $this->paginationControl($this->paginator,'Sliding','paginationTop.phtml');
?>
<table class="table" width="100%" cellpadding="5" cellspacing="2" border="0">
	<tr>
		<th width="25px">&nbsp;</th>
		<th width="90px">Course Code</th>
		<th width="90px">Course Code (LMS)</th>
		<th>Course Name</th>
		<th width="100px">Course Credit Hours</th>
		<th width="200px">Faculty</th>
		<th width="200px">Department</th>
		<th>Status</th>
	</tr>
	
	<?php 
	$i=0;
	foreach ($this->paginator as $entry): 
	
	if($entry['department_code']!=""){
		$department=$entry['department_name']." (".$entry['department_code'] .")";
		$faculty=$entry['faculty_name']." (". $entry['faculty_code'].")";
	}else{
		$department="";
		$faculty=$entry['faculty_name2']." (".$entry['faculty_code2'].")";
	}
	?>
	<tr <?php echo $i%2==0?"class='shade'":""; ?>>
		<td>
			<input type="radio" name="course_id" value="<?php echo $entry['id']; ?>">
		</td>
		<td><?php echo $entry['code']; ?></td>
		<td><?php echo $entry['lmsCode']; ?></td>
		<td><?php echo $entry['name']; ?></td>
		<td align="center"><?php echo $entry['credit_hour']; ?></td>
		<td><?php echo $faculty; ?></td>
		<td><?php echo $department; ?></td>
		<td align="center">
			<?php echo $entry['status']==1?"<span class='state publish'>&nbsp;</span>":"<span class='state unpublish'>&nbsp;</span>"; ?>
		</td>
	</tr>
	<?php 
	$i++;
	endforeach 
	?>

</table>

<?php 
	echo $this->paginationControl($this->paginator,'Sliding','paginationBottom.phtml');
?>
<div id="dialog-search" title="Search a Course">
	<form name="search_form" id="search_form" action="" method="post">
		<table class="table5">
			<tr>
				<th>Course Name</th>
				<td>:</td>
				<td>
					<input name="name" type="text" style="width:250px" />
				</td>
			</tr>
			<tr>
				<th>Course Code</th>
				<td>:</td>
				<td>
					<input name="code" type="text" style="width:250px" />
				</td>
			</tr>
			<!-- tr>
				<th>Faculty</th>
				<td>:</td>
				<td>
					<input type="text" style="width:250px" />
				</td>
			</tr>
			<tr>
				<th>Department</th>
				<td>:</td>
				<td>
					<input type="text" style="width:250px" />
				</td>
			</tr-->
		</table>
	</form>
</div>