<script>
    $(function() {
        
        $( "input[name='aph_start_date']" ).datepicker({
        	dateFormat: "dd-mm-yy",
            defaultDate: "+1w",
            changeMonth: true,
            numberOfMonths: 2,
            onSelect: function( selectedDate ) {
                $( "input[name='aph_end_date']" ).datepicker( "option", "minDate", selectedDate );
                $( "#aph_effective_date" ).datepicker( "option", "maxDate", selectedDate );
            }
        });
        
        $( "input[name='aph_end_date']" ).datepicker({
        	dateFormat: "dd-mm-yy",
            defaultDate: "+1w",
            changeMonth: true,
            numberOfMonths: 2,
            onSelect: function( selectedDate ) {
                $( "input[name='aph_start_date']" ).datepicker( "option", "maxDate", selectedDate );
            }
        });

        $( "#aph_effective_date" ).datepicker({
        	dateFormat: "dd-mm-yy",
        	changeMonth: true,
        	numberOfMonths: 2,
        });
    });
</script>

<div class="message toolbar">
	<h2><?php echo $this->title; ?></h2>
	<div class="toolbar-button">
		<ul>
			<li>
				<a href="<?php echo $this->url(array('module'=>'application','controller'=>'placement-test', 'action'=>'index'),'default',true);?>">
					<span class='back'></span>
					Back
				</a>
			</li>
			<li>
				<a href="#" >
					<span class='info'></span>
					Info
				</a>
			</li>
		</ul>
	</div>
</div>
<br />

<?php 
	$this->form->setAction($this->url());
	echo  $this->form;
?>