<script type="text/javascript">
$(function() {
	
});

function back(){
	window.location="<?php echo $this->url(array('module'=>'application','controller'=>'placement-test','action'=>'index'), 'default', true);?>";
}

function deleteData(id){
	$('#delete_id').val(id);
	$('#delete_form').submit();
}

function nextProcess(){
	window.location = "<?php echo $this->url(array('module'=>'application','controller'=>'placement-test','action'=>'wizard-step3'));?>";
}
</script>

<style type="text/css">
.zend_form input[type="text"].passing_mark {
	width: 30px;
}
</style>

<div class="message toolbar">
	<h2><?php echo $this->title; ?></h2>
	<div class="toolbar-button">
		<ul>
			<li class="divider"></li>	
			<li>							
				<a href="#" onClick="back()"><span class='back'></span>Back</a>				
			</li>
		</ul>
	</div>
</div>

<div align="center" style="background:#ebebeb; height:30px;">
	<ul class="steps">
	    <li class="prevDone">
			<span>1</span> <a href="<?php echo $this->url(array('module'=>'application','controller'=>'placement-test','action'=>'wizard-step1'));?>"><?php echo $this->translate('Component Setup')?></a>
		</li>
	    <li class="current">
			<span>2</span> <a href="<?php echo $this->url(array('module'=>'application','controller'=>'placement-test','action'=>'wizard-step2'));?>"><?php echo $this->translate('Program Setup')?></a>
		</li>
		<li class="next">
			<span>3</span> <a href="<?php echo $this->url(array('module'=>'application','controller'=>'placement-test','action'=>'wizard-step3'));?>"><?php echo $this->translate('Component Weightage')?></a> 
		</li>
		<li class="empty">
			<span>4</span> <a href="<?php echo $this->url(array('module'=>'application','controller'=>'placement-test','action'=>'wizard-step4'));?>"><?php echo $this->translate('Schedule')?></a>
		</li>
		<li class="empty">
			<span>5</span> <?php echo $this->translate('Submit')?>
		</li>
	</ul>
	<br class="clear" />
</div>

<br>
<h1><?php echo $this->translate("Placement Test Info"); ?></h1>
<div width="500px">
		<table class="table2" width="100%" cellpadding="3" cellspacing="1">
			<tr>
				<th width="150px"><? echo $this->translate("Placement Test Name"); ?></th>
				<td><?php echo $this->placement_test['aph_placement_name']; ?></td>
			</tr>
			<tr>
				<th width="150px"><? echo $this->translate("Code"); ?></th>
				<td><?php echo $this->placement_test['aph_placement_code']; ?></td>
			</tr>
			<tr>
				<th width="150px"><? echo $this->translate("Fees By Program"); ?></th>
				<td><?php echo $this->placement_test['aph_fees_program']==1?"Yes":"No"; ?></td>
			</tr>
			<tr>
				<th width="150px"><? echo $this->translate("Fees By Location"); ?></th>
				<td><?php echo $this->placement_test['aph_fees_location']==1?"Yes":"No"; ?></td>
			</tr>
			<tr>
				<th><? echo $this->translate("Start Date"); ?></th>
				<td><?php echo date("l, dS F Y", strtotime($this->placement_test['aph_start_date'])); ?></td>
			</tr>
			<tr>
				<th><? echo $this->translate("End Date"); ?></th>
				<td><?php echo date("l, dS F Y", strtotime($this->placement_test['aph_end_date'])); ?></td>
			</tr>
			<tr>
				<th><? echo $this->translate("Efective Date"); ?></th>
				<td><?php echo date("l, dS F Y", strtotime($this->placement_test['aph_effective_date'])); ?></td>
			</tr>
			<tr>
				<th><? echo $this->translate("Created by"); ?></th>
				<td><?php echo $this->placement_test['aph_create_by_name']; ?></td>
			</tr>
			<tr>
				<th><? echo $this->translate("Created Date"); ?></th>
				<td><?php echo date("d/m/Y g:ia", strtotime($this->placement_test['aph_create_date'])); ?></td>
			</tr>
		</table>	
</div>
<br />
<h1><?php echo $this->translate("Program"); ?></h1>
<div id="add_program" style="clear:both; border: 1px solid #111;">
	<form method="post">
		<input type="hidden" name="app_placement_code" value="<?php echo $this->placement_test['aph_placement_code']; ?>" />
		<input type="hidden" name="app_pass_mark" value="0" />
		<dl class="zend_form">
			<dt><?php echo $this->translate("Program"); ?></dt>
			<dd>
				<select name="app_program_code">
					<?php foreach ($this->programList as $program):?>
					<option value="<?php echo $program['ProgramCode']; ?>" ><?php echo $program['ArabicName']; ?>(<?php echo $program['ProgramName']; ?>)</option>
					<?php endforeach;?>
				</select>
			</dd>
			
			<dt><?php echo $this->translate("Passing Marks"); ?></dt>
			<dd>
				<input type="text" class="passing_mark" name="app_pass_mark" value="" maxlength="3" placeholder="0" />%
			</dd>
			
			<dt></dt>
			<dd>
				<input type="submit" name="submit" value="Add Program" />
			</dd>
		</dl>
	</form>
</div>
<table width="100%" class="table">
	<tr>
		<th rowspan="2"><?php echo $this->translate("Program Name"); ?></th>
		<th rowspan="2"><?php echo $this->translate("Program Name (Indonesia)"); ?></th>
		<th rowspan="2"><?php echo $this->translate("Program Code"); ?></th>
		<th><?php echo $this->translate("Passing Marks"); ?></th>
		<th rowspan="2">&nbsp;</th>
	</tr>
	<tr>
		<th>%</th>
	</tr>
	<?php if($this->placementtestProgramList){?>
	<?php foreach ($this->placementtestProgramList as $program):?>
	<tr>
		<td><?php echo $program['ProgramName'] ?></td>
		<td><?php echo $program['ProgramNameIndonesia'] ?></td>
		<td align="center"><?php echo $program['app_program_code'] ?></td>
		<td align="center"><?php echo $program['app_pass_mark'] ?></td>
		<td align="center">
			<a href="#" onclick="deleteData(<?php echo $program['app_id'] ?>)">Delete</a>
		</td>
	</tr>
	<?php endforeach;?>
	<?php }else{?>
	<tr>
		<td colspan="3" align="center"> <?php echo $this->translate("No Program Assigned"); ?></td>
	</tr>
	<?php }?>
</table>

<?php if($this->placementtestProgramList){?>
<div align="center" style="margin: 20px 0; padding: 5px; background: #EEEEEE; border: 1px solid #333333;">
	<input type="submit" value="<?php echo $this->translate("Proceed Next Process"); ?>" onclick="javascript:nextProcess()" />
</div>
<?php }?>

<form name="delete_form" id="delete_form" method="post">
	<input type="hidden" name="delete" value="1" />
	<input type="hidden" name="id" id="delete_id" value="" />
</form>



