<script type="text/javascript">
$(function() {
	
});

function back(){
	window.location="<?php echo $this->url(array('module'=>'application','controller'=>'placement-test','action'=>'index'), 'default', true);?>";
}
</script>

<style type="text/css">
.weightage{
	width:30px;
}
</style>


<div class="message toolbar">
	<h2><?php echo $this->title; ?></h2>
	<div class="toolbar-button">
		<ul>
			<li class="divider"></li>	
			<li>							
				<a href="#" onClick="back()"><span class='back'></span>Back</a>				
			</li>
		</ul>
	</div>
</div>

<div align="center" style="background:#ebebeb; height:30px;">
	<ul class="steps">
	    <li class="current">
			<span>1</span> <a href="<?php echo $this->url(array('module'=>'application','controller'=>'placement-test','action'=>'wizard-step1'));?>"><?php echo $this->translate('Component Setup')?></a>
		</li>
	    <li class="next">
			<span>2</span> <a href="<?php echo $this->url(array('module'=>'application','controller'=>'placement-test','action'=>'wizard-step2'));?>"><?php echo $this->translate('Program Setup')?></a>
		</li>
		<li class="empty">
			<span>3</span> <a href="<?php echo $this->url(array('module'=>'application','controller'=>'placement-test','action'=>'wizard-step3'));?>"><?php echo $this->translate('Component Weightage')?></a> 
		</li>
		<li class="empty">
			<span>4</span> <a href="<?php echo $this->url(array('module'=>'application','controller'=>'placement-test','action'=>'wizard-step4'));?>"><?php echo $this->translate('Schedule')?></a>
		</li>
		<li class="empty">
			<span>5</span> <?php echo $this->translate('Submit')?>
		</li>
	</ul>
	<br class="clear" />
</div>

<br>
<h1><?php echo $this->translate("Placement Test Info"); ?></h1>
<div width="500px">
		<table class="table2" width="100%" cellpadding="3" cellspacing="1">
			<tr>
				<th width="150px"><? echo $this->translate("Placement Test Name"); ?></th>
				<td><?php echo $this->placement_test['aph_placement_name']; ?></td>
			</tr>
			<tr>
				<th width="150px"><? echo $this->translate("Code"); ?></th>
				<td><?php echo $this->placement_test['aph_placement_code']; ?></td>
			</tr>
			<tr>
				<th width="150px"><? echo $this->translate("Fees By Program"); ?></th>
				<td><?php echo $this->placement_test['aph_fees_program']==1?"Yes":"No"; ?></td>
			</tr>
			<tr>
				<th width="150px"><? echo $this->translate("Fees By Location"); ?></th>
				<td><?php echo $this->placement_test['aph_fees_location']==1?"Yes":"No"; ?></td>
			</tr>
			<tr>
				<th><? echo $this->translate("Start Date"); ?></th>
				<td><?php echo date("l, dS F Y", strtotime($this->placement_test['aph_start_date'])); ?></td>
			</tr>
			<tr>
				<th><? echo $this->translate("End Date"); ?></th>
				<td><?php echo date("l, dS F Y", strtotime($this->placement_test['aph_end_date'])); ?></td>
			</tr>
			<tr>
				<th><? echo $this->translate("Efective Date"); ?></th>
				<td><?php echo date("l, dS F Y", strtotime($this->placement_test['aph_effective_date'])); ?></td>
			</tr>
			<tr>
				<th><? echo $this->translate("Created by"); ?></th>
				<td><?php echo $this->placement_test['aph_create_by_name']; ?></td>
			</tr>
			<tr>
				<th><? echo $this->translate("Created Date"); ?></th>
				<td><?php echo date("d/m/Y g:ia", strtotime($this->placement_test['aph_create_date'])); ?></td>
			</tr>
		</table>	
</div>
<br />
<h1><?php echo $this->translate("Component"); ?></h1>

<form method="post">
	<input type="hidden" name="apd_placement_code" value="<?php echo $this->placement_test['aph_placement_code']; ?>" />
	<table width="100%" class="table">
		<tr>
			<th>Component Name</th>
			<th>Component Name(Indonesia)</th>
			<th>Total Question</th>
			<th>Start Question</th>
			<th>End Question</th>
		</tr>
		<?php foreach ($this->componentList as $component):?>
		<tr>
			<td>
				<?php echo $component['ac_comp_name']; ?>
				<input type="hidden" name="apd_id[]" value="<?php echo $component['detail']['apd_id']; ?>" />
				<input type="hidden" name="apd_comp_code[]" value="<?php echo $component['ac_comp_code']; ?>" />
			</td>
			<td><?php echo $component['ac_comp_name_bahasa']; ?></td>
			<td align="center"><input type="text" class="weightage" maxlength="4" name="apd_total_question[]" value="<?php echo $component['detail']['apd_total_question']; ?>" /></td>
			<td align="center"><input type="text" class="weightage" maxlength="4" name="apd_questno_start[]" value="<?php echo $component['detail']['apd_questno_start']; ?>" /></td>
			<td align="center"><input type="text" class="weightage" maxlength="4" name="apd_questno_end[]" value="<?php echo $component['detail']['apd_questno_end']; ?>" /></td>
		</tr>
		<?php endforeach;?>
	</table>
	<small>*<?php echo $this->translate("Please enter atleast 1 question no for non theory component"); ?></small>
	<div align="center" style="margin: 20px 0; padding: 5px; background: #EEEEEE; border: 1px solid #333333;">
		<input type="submit" value="<?php echo $this->translate("Save & Next Process"); ?>" />
	</div>
</form>