
<?if(isset($this->noticeMessage)){?>
<div class="message notice"><strong><? echo $this->noticeMessage;?></strong>.</div>
<?}?>
<?if(isset($this->noticeSuccess)){?>
<div class="message success"><strong><? echo $this->noticeSuccess;?></strong>.</div>
<?}?>
<?if(isset($this->noticeError)){?>
<div class="message error"><strong><? echo $this->noticeError;?></strong>.</div>
<?}?>

<div class="message toolbar">
	<h2><?php echo $this->title; ?></h2>
	<div class="toolbar-button">
		<ul>
			<li>
				<a href="<?php echo $this->url(array('module'=>'admission-record','controller'=>'registration', 'action'=>'index'),'default',true);?>">
					<span class='back'></span>
					Back
				</a>
			</li>
			<li>
				<a href="#" >
					<span class='info'></span>
					Info
				</a>
			</li>
		</ul>
	</div>
</div>

<div align="center" style="background:#ebebeb; height:30px;">
<ul class="steps">
	<li class="prevDone">
		<span>1</span> <?php echo $this->translate("Student");?><?php echo $this->translate("Selection");?> 
	</li>
    <li class="current">
		<span>2</span>  <?php echo $this->translate("Semester");?><?php echo $this->translate("Selection");?> 
	</li>
    <li class="next">
		<span>3</span>  <?php echo $this->translate("Course");?><?php echo $this->translate("Add & Drop");?> 
	</li>
	<li class="empty">
		<span>3</span>  <?php echo $this->translate("Finish");?>
	</li>
</ul>
<br class="clear" />
</div>

<br />
<h2> <?php echo $this->translate("Student");?><?php echo $this->translate("Details");?> </h2>
<table>
	<tr>
		<th> <?php echo $this->translate("Name");?></th>
		<td>:</td>
		<td><?php echo $this->student['fullname']; ?></td>
	</tr>
	<tr>
		<th><?php echo $this->translate("Matric No");?> </th>
		<td>:</td>
		<td><?php echo $this->student['matric_no']; ?></td>
	</tr>
	<tr>
		<th><?php echo $this->translate("Program");?> </th>
		<td>:</td>
		<td><?php echo $this->program['main_name']; ?></td>
	</tr>
	<tr>
		<th><?php echo $this->translate("Semester");?> </th>
		<td>:</td>
		<td><?php echo $this->currentsemester["name"].'&nbsp;'.$this->currentsemester["year"];?></td>
	</tr>
</table>
<br />

<h2> <?php echo $this->translate("Semester");?>  <?php echo $this->translate("Details");?></h2>
<div style="width: 600px;">
<fieldset style="width:450px; margin:0 0">
	<legend><?php echo $this->translate("Semester");?>  <?php echo $this->translate("Options");?> </legend>
<form name="course_form" action="<?php echo $this->url(array('module'=>'admission-record','controller'=>'add-drop', 'action'=>'course'),'default',true);?>" method="post">
	<input type="hidden" name="student_id" value="<?php echo $this->student['id']?>" />
	<input type="hidden" name="program_id" value="<?php echo $this->program['id']?>" />
	<table width="100%">
		<tr>
			<td width="110px">
				<?php echo $this->translate("Program");?> 
			</td>
			<td width="5px">:</td>
			<td>
				<?php echo $this->program['main_name']?>
			</td>
		</tr>
		
		<tr>
			<td>
				<?php echo $this->translate("Semester");?> 
			</td>
			<td width="5px">:</td>
			<td>
			
			<input type="text" name="semester_id" value="<?php echo $this->currentsemester["id"];?>">
				
			</td>
		</tr>
		<tr>
			<td colspan="2">&nbsp;</td>
			<td><input type="submit" value="Next" /></td>
		</tr>
	</table>
</form>
</fieldset>
</div>
<br />
