<script type="text/javascript">
	function del(){
		var id = $('input[name=faculty_id]:checked').val();

		if(!id){
			alert('Please select any faculty first');
		}else{
			if(confirm('Are you sure to delete this Department ?')){
				window.location = "<?php echo $this->url(array('module'=>'general-setup','controller'=>'faculty', 'action'=>'delete')); ?>/id/"+id;
			}
		}
	}
	
	function add(){
		window.location="<?php echo $this->url(array('module'=>'general-setup','controller'=>'faculty', 'action'=>'add'));?>";
	}

	function edit(){
		var id = $('input[name=faculty_id]:checked').val();

		if(!id){
			alert('Please select any faculty first');
		}else{
			window.location="<?php echo $this->url(array('module'=>'general-setup','controller'=>'faculty', 'action'=>'edit'));?>/id/"+id;
		}
	}

</script>


<div class="message toolbar">
	<h2><?php echo $this->title; ?></h2>
	<div class="toolbar-button">
		<ul>
			<li>
				<a href="#" onclick="javascript:add()">
					<span class='add'></span>
					Add
				</a>
			</li>
			<li>
				<a href="#" onclick="javascript:edit()">
					<span class='edit'></span>
					Edit
				</a>
			</li>
			<li>
				<a href="#" onclick="javascript:del()">
					<span class='delete'></span>
					Delete
				</a>
			</li>
			<li class="divider"></li>
			<li>
				<a href="#" >
					<span class='info'></span>
					Info
				</a>
			</li>
		</ul>
	</div>
</div>
<br />

<?php 
	echo $this->paginationControl($this->paginator,'Sliding','paginationTop.phtml');
?>
<table class="table" width="100%" cellpadding="5" cellspacing="1" border="0">
	<tr>
		<th width="25px">&nbsp;</th>
		<th>Name</th>
		<th width="100px">Code</th>
		<th width="100px">Status</th>
	</tr>
	
	<?php 
	$i=0;
	foreach ($this->paginator as $entry): 
	?>
	<tr <?php echo $i%2==0?"class='shade'":""; ?>>
		<td width="25px">
			<input type="radio" name="faculty_id" value="<?php echo $entry['id']; ?>">
		</td>
		<td><?php echo $entry['name']; ?></td>
		<td align="center"><?php echo $entry['code']; ?></td>
		<td align="center"><?php echo $entry['status']==1?"Active":"Not Active"; ?></td>
	</tr>
	<?php 
	$i++;
	endforeach 
	?>

</table>

<?php 
	echo $this->paginationControl($this->paginator,'Sliding','paginationBottom.phtml');
?>