<script type="text/javascript">
function del(title, id){
	if(confirm('Are you sure to delete requirement for course type '+title+'?')){
		window.location = "<?php echo $this->url(array('module'=>'setup','controller'=>'program-requirement', 'action'=>'delete', 'program-id'=>$this->program_id)); ?>/id/"+id;
	}
}

function edit(id){
	window.location="<?php echo $this->url(array('module'=>'setup','controller'=>'program-requirement', 'action'=>'edit', 'program-id'=>$this->program_id));?>/id/"+id;
}
</script>

<?if(isset($this->noticeMessage)){?>
<div class="message notice"><strong><? echo $this->noticeMessage;?></strong>.</div>
<?}?>
<?if(isset($this->noticeSuccess)){?>
<div class="message success"><strong><? echo $this->noticeSuccess;?></strong>.</div>
<?}?>
<?if(isset($this->noticeError)){?>
<div class="message error"><strong><? echo $this->noticeError;?></strong>.</div>
<?}?>

<div class="message toolbar">
	<h2><?php echo $this->title; ?></h2>
	<div class="toolbar-button">
		<ul>
			<li>
				<a href="<?php echo $this->url(array('module'=>'anr-setup', 'controller' => 'academic-landscape', 'action' => 'view-detail', 'program-id'=>$this->program_id, 'id'=>$this->aid),'default',true); ?>">
					<span class='back'></span>
					Back
				</a>
			</li>
			<li>
				<a href="#" >
					<span class='info'></span>
					Info
				</a>
			</li>
		</ul>
	</div>
</div>
<br />

<?php
	echo  $this->form;
?>	