<script type="text/javascript">
	
	function save(){
		
		
	   var gtotal_require = document.getElementById('gtotal_require').value;
	   var gtotal_enter = document.getElementById('gtotal_enter').value;
	    
	   gtotal_enter = Math.round(gtotal_enter);
	   gtotal_require = Math.round(gtotal_require);
	  
	    if(gtotal_enter < gtotal_require){
	      alert(gtotal_enter);	
	    	message = confirm('You have entered below number of questions required. Do you still want to save?');
	    	
	    	if(message){
	    		document.addfrm.action="<?php echo $this->url(array('module'=>'question-bank','controller'=>'tos', 'action'=>'generate-tos'));?>";
				document.addfrm.submit();
	    	}
	    }
		
		
	}

	

</script>

<div class="message toolbar">
	<h2><?php echo $this->title; ?></h2>
	<div class="toolbar-button">
		<ul>
			<li>
				<a href="#" onclick="javascript:save()">
					<span class='save'></span>
					Save
				</a>
			</li>
			
			<li class="divider"></li>
			<li>
				<a href="#" >
					<span class='info'></span>
					Info
				</a>
			</li>
		</ul>
	</div>
</div>
<br />


<form name="addfrm" method="POST" action="">
<table class="table3" width="60%" border="0" cellpadding=" 5" cellspacing="1">
  <tr>
    <th>Course Name</th>
    <td width="5px">:</td>
    <td><?php echo $this->tos["cname"]?></td>
  </tr>
    <tr>
    <th>Set Name</th>
    <td width="5px">:</td>
    <td><?php echo $this->tos["tosname"]?></td>
  </tr> 
     <tr>
    <th>Total Questions</th>
    <td width="5px">:</td>
    <td><?php echo $this->tos["NosOfQues"]?></td>
  </tr> 
</table>

 <input type="hidden" name="idTos" size="5" value="<?php echo $this->tos["id"]?>">
 <input type="hidden" id="total_bank" size="5" value="<?php echo count($this->bank)?>">
 <input type="hidden" size="3" id="gtotal_require" value="<?php echo  $this->tos['NosOfQues']?>">
 <input type="hidden" size="3" id="gtotal_enter" value=""> 
 
 <?	$bankRow =1;
    foreach ($this->bank as $bank){ 
 	//get chapter for each bank
 	$chapterDB = new App_Model_Question_DbTable_Chapter();
 	$chapter = $chapterDB->getTopicbyPool($bank["bank_id"]);
 	
 ?>
 
  <input type="hidden" name="idSubMain[]" size="5" value="<?php echo $bank["id"]?>">
  <input type="hidden" name="pool_id[]" size="5" value="<?php echo $bank["bank_id"]?>">
  <input type="hidden" name="total_topic<?php echo $bankRow;?>" id="total_topic<?php echo $bankRow;?>" size="5" value="<?php echo count($chapter)?>">
 <h3><?php echo $bank["bname"]?></h3>
 
<table class="table3" width="90%" border="0" cellspacing="1" cellpadding="1">
  <tr> 
    <th rowspan="2">Pool</th>
    <th colspan="3">Difficulty Level</th>
    <th rowspan="2">Total</th>
  </tr>
  <tr> 
    <th>Easy</th>
    <th>Medium</th>
    <th>Difficult</th>
  </tr>
   
   <?   $topicRow=1; 
        foreach ($chapter as $c){
   	    $questionDB = new App_Model_Question_DbTable_Question();
   	 
   	?>
  <tr align="center"> 
    <td width="25%"><?php echo $c["name"]?><input type="hidden" size="5" name="idChapter[<?php echo $bank["id"]?>][]" value="<?php echo $c["id"]?>"></td>
    
    <? for($level=1; $level<=3; $level++){
    	$condition = array('pool_id'=>$bank['bank_id'],'topic_id'=>$c["id"],'difficulty_level'=>$level);
        $total_avail = $questionDB->getTotalQuestion($condition);
    ?>
    <td>    
     <input type="text" name="require[<?php echo $c["id"]?>][<?php echo $level;?>]" id="require[<?php echo $c["id"]?>][<?php echo $level;?>]" onblur="checkval('<?php echo $c["id"];?>','<?php echo $level?>','<?php echo $bankRow.$topicRow;?>')" size="3" value="">
     /
     <input type="text" name="available[<?php echo $c["id"]?>][<?php echo $level;?>]" id="available[<?php echo $c["id"]?>][<?php echo $level;?>]" size="3" value="<?php echo $total_avail;?>" style="background-color:#CCCCCC" readonly></td>
    <? } ?>

    <td><input type="text" size="3" name="total<?php echo $bankRow.$topicRow;?>" id="total<?php echo $bankRow.$topicRow;?>" value="" style="background-color:#E1FCD8" readonly></td>
  </tr>
  <? $topicRow++; } //end chapter ?>
  <tr align="center"> 
    <td colspan="4">Grand Total : <strong> <?php echo $bank['NosOfQues']?> questions</strong> </td>
    <td>
    <input type="text" size="3" name="gtotal" id="gtotal<?php echo $bankRow;?>" value="" style="background-color:#E1FCD8" readonly>    
       
   
    </td>
  </tr>
</table>
<br>
<script>
function checkval(topic,level,topicBR){
	    

var inputidname = 'require['+topic+']['+level+']';
var inputval = document.getElementById(inputidname).value;

var availableid = 'available['+topic+']['+level+']';
var availableval = document.getElementById(availableid).value;

availableid = Math.round(availableid);
availableval = Math.round(availableval);

if(inputval > availableval){	
	alert('Sorry, you have exceeded the available question.');
	document.getElementById(inputidname).focus;
	document.getElementById(inputidname).value=0;
}


//loop level
var total=0;
for(x=1; x<=3; x++){
	
	var inputidnamex = 'require['+topic+']['+x+']';
	curval = document.getElementById(inputidnamex).value;		
    total = Math.round(total) + Math.round(curval)
}


var totalname = 'total'+topicBR;
document.getElementById(totalname).value=total; //total each Topic Row


//get Grand Total: Sum of BankTopicRows
total_bank  = document.getElementById('total_bank').value; //ada berapa bank?

var gtotal=0;
var alltotal=0;

for(bank=1; bank<=total_bank; bank++){
	total_topic = document.getElementById('total_topic'+bank).value; //ada berapa topic?

	gtotal=0;
	for(m=1; m<=total_topic; m++){
		
		var topicRow = 'total'+bank+m; 		 
	    topicRowVal = document.getElementById(topicRow).value
	    gtotal = Math.round(gtotal) + Math.round(topicRowVal)
	   
	} 
	
	var bankName = 'gtotal'+bank;
	document.getElementById(bankName).value=gtotal;
	eachbanktotal = document.getElementById(bankName).value;	
	alltotal = Math.round(alltotal) + Math.round(eachbanktotal);
}

document.getElementById('gtotal_enter').value=alltotal;

}
</script>
  <? $bankRow++; }//end foreach ?>
</form>