<?php 
	//get locale
	$registry = Zend_Registry::getInstance();
	$locale = $registry->get('Zend_Locale');
	$this->locale = $locale->toString();
	
	if($locale == 'ar_YE'){
		$this->direction = "rtl";
		$this->float = "right";	
	}else{
		$this->direction = "ltr";
		$this->float = "left";
	}
	
	//applicant profile
	$auth = Zend_Auth::getInstance();
?>
<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->locale; ?>" dir="<?php echo $this->direction; ?>">
<head>
	<?php echo $this->headMeta(); ?>
	<?php echo $this->headTitle(); ?>
	<?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/layout.css'); ?>
	<?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/trisakti/simpletree.css'); ?>
	<?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/trisakti/topmenu.css'); ?>
	<?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/trisakti/style.css'); ?>
	<?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/trisakti/left-menu.css'); ?>
	
	<?php echo $this->headScript()->appendFile($this->baseUrl().'/ckeditor/ckeditor_basic.js');?>

	
	<?php
		$this->jQuery()->enable();
		$this->jQuery()->setVersion('1.7.2');
		$this->jQuery()->useCdn(false);
	 	$this->jQuery()->setLocalPath($this->baseUrl().'/js/jquery/jquery-1.5.1.min.js');
		
	 	
		$this->jQuery()->uiEnable();
		$this->jQuery()->setUiVersion('1.8.18');
		$this->jQuery()->useUiCdn(false);
		$this->jQuery()->addStylesheet($this->baseUrl().'/js/jquery/themes/smoothness/jquery-ui.css');
		$this->jQuery()->setUiLocalPath($this->baseUrl().'/js/jquery/jquery-ui-1.8.18.min.js');
		
		echo $this->jQuery();
		
		echo $this->headLink()->prependStylesheet($this->baseUrl().'/js/jquery/plugin/timepicker/timePicker.css');
		echo $this->headScript()->appendFile($this->baseUrl().'/js/jquery/plugin/timepicker/jquery.timepicker.js');
		
		
		echo $this->headScript()->appendFile($this->baseUrl().'/js/jquery/plugin/multiselect-1.12/jquery.multiselect.min.js');
		echo $this->headLink()->prependStylesheet($this->baseUrl().'/js/jquery/plugin/multiselect-1.12/jquery.multiselect.css');
	
	
	 	if($this->direction == 'rtl'){
	 		echo $this->headScript()->appendFile($this->baseUrl().'/js/jquery/plugin/potato.menu/jquery.ui.potato.menu.rtl.js');
	 		echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/trisakti/dashboard_rtl.css');
	 		echo $this->headLink()->prependStylesheet($this->baseUrl().'/js/jquery/plugin/potato.menu/jquery.ui.potato.menu.rtl.css');
	 		echo "<style>";
	 		echo "ul.potato-menu li.potato-menu-item {
	 				float:right;
				}";
	 		echo "#language{
	 				left:10px;
	 			}";
	 		
	 		echo "#appTitle{
	 				left: 15px;
					top: 25px;
	 			}";
	 		
	 		echo "#main-content{
						margin-right: 200px;
				}";
	 		
		 	echo "div.toolbar-button {
				float:left;
				text-align: left;
				}";
		 	
	 		echo "</style>";
	 	}else{
	 		echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/trisakti/dashboard_ltr.css');
	 		echo $this->headScript()->appendFile($this->baseUrl().'/js/jquery/plugin/potato.menu/jquery.ui.potato.menu.js');
	 		echo $this->headLink()->prependStylesheet($this->baseUrl().'/js/jquery/plugin/potato.menu/jquery.ui.potato.menu.css');
	 		
	 		echo "<style>";
	 		echo "ul.potato-menu li.potato-menu-item {
	 				float:left;
				}";
	 		echo "#language{
	 				right:10px;
	 			}";
	 		
	 		echo "#appTitle{
	 				right: 15px;
					top: 25px;
	 			}";
	 		echo "#main-content{
						margin-left: 200px;
				}";
	 		
	 		echo "div.toolbar-button {
				float:right;
				text-align: right;
				}";
	 		
	 		echo "</style>";
	 	}
	 
	 ?>
	 	
	<!--[if lt IE 7]>
	<style media="screen" type="text/css">
	#container {
		height:100%;
	}
	</style>
	<![endif]-->
	
	<script type="text/javascript">
	 $(document).ready(function() {
	        $('#mainMenu').ptMenu();
	        $('#mainMenu').show();
	        
	 });
	</script>
	
	<!-- sidebar menu -->
	<script type="text/javascript">
	function slide(navigation_id, pad_out, pad_in, time, multiplier)
	{
		// creates the target paths
		var list_elements = navigation_id + " li.sliding-element";
		var link_elements = list_elements + " a";
		// initiates the timer used for the sliding animation
		var timer = 0;
		// creates the slide animation for all list elements
		$(list_elements).each(function(i)
		{
			// margin left = - ([width of element] + [total vertical padding of element])
			$(this).css("margin-left","-180px");
			// updates timer
			timer = (timer*multiplier + time);
			$(this).animate({ marginLeft: "0" }, timer);
			$(this).animate({ marginLeft: "15px" }, timer);
			$(this).animate({ marginLeft: "0" }, timer);
		});
		// creates the hover-slide effect for all link elements
		$(link_elements).each(function(i)
		{
			/*$(this).hover(
			function()
			{
				$(this).animate({ paddingLeft: pad_out }, 150);
			},
			function()
			{
				$(this).animate({ paddingLeft: pad_in }, 150);
			});*/
		});
	}
	$(document).ready(function()
	{
		slide("#sliding-navigation", 25, 15, 0, .8);
	});
	</script>
	
	
</head>
<body>

<div id="container">
	<div id="header">
		<!-- Header start -->
		<div id="logo"><div id="name">&nbsp;</div></div>
		<div id="appTitle">
			<?php echo APPLICATION_ENTERPRISE; ?>
			<br />
			<i><?php echo APPLICATION_TITLE; ?></i>
		</div>
	</div>
	<div id="menu">
		<div id="language">
			<select style="width:100px;" onChange="window.location = '?lang=' + this.options[this.selectedIndex].value">
				<option value="en" <?php echo $this->locale=="en_US"?"selected='selected'":""; ?>>English</option>
				<option value="id" <?php echo $this->locale=="id_ID"?"selected='selected'":""; ?>>Bahasa Indonesia</option>
			<!--	<option value="ar" <?php echo $this->locale=="ar_YE"?"selected='selected'":""; ?>>Arabic</option>-->
			</select>
		</div>
		
		<div id="topmenu">
			<div class="underlinemenu">
				<?php echo $this->translate("Welcome")?>&nbsp; 
				<?php echo $auth->getIdentity()->appl_fname!=""?$auth->getIdentity()->appl_fname. " ":""; ?>
				<?php echo $auth->getIdentity()->appl_mname!=""?$auth->getIdentity()->appl_mname. " ":""; ?>
				<?php echo $auth->getIdentity()->appl_lname!=""?$auth->getIdentity()->appl_lname. " ":""; ?>
				<?php 
				if(isset($auth->getIdentity()->adminlogin)) {
					?>
					 <font color=red>(You login to this account Via Admin - <?php 
					echo $auth->getIdentity()->adminlogin;?>)</font>
					<?php 
				}
				?>
				<!--
				<ul>	  
					<li><a href="<?php echo $this->url(array('module'=>'default','controller'=>'applicant-portal','action'=>'index'),'default',true) ?>"><?php echo $this->translate("Home")?></a></li>
					<li><a href="<?php echo $this->url(array('module'=>'default','controller'=>'online-application','action'=>'logout'),'default',true) ?>"><?php echo $this->translate("Logout"); ?></a></li>	
				</ul>
				-->
			</div>
		</div>
		
		

		
		
	</div>
	<div id="live">
		<table class="table" width="100%" border="0" >
		<tr>
		 <?php if ($auth->getIdentity()->role=="student") {
		 	$dbStd=new App_Model_Record_DbTable_StudentRegistration();
		 	$regid=$auth->getIdentity()->registration_id;
		 	$smt=$dbStd->getSemesterStd($regid);
		 //	echo var_dump($smt);
		 	$semesterlist=$smt['sem'];
		 	$i=1;$semcount=$smt['semestermax'];
		 	$finis=1;
		 	foreach ($semesterlist as $value) {
				if ($i>$smt['semestercount'] && ($i<=$smt['semestermax']-2) ) $alert="yellow";
				else if ($i>$smt['semestermax']-2) $alert="red";
				else $alert="";
				//--------
				if ($semcount>0) {
				  if ($smt['semesterstart']=="1") {
			 			if ($dbStd->isIn($regid, $value.'1')) {
							?><td align="center" bgcolor="green"><font color="white"><?php echo  $value.'-1'?></font></td>
					 		<?php } else { $finis=0;?>
					 			<td align="center" bgcolor="<?php echo $alert;?>"><?php echo  $value.'-1'?></td>
					 	<?php }?>
					  <?php $i++; $semcount--;
					 		
			 		} else $smt['semesterstart']="1";
		 		}
		 		if ($i>$smt['semestercount'] && ($i<=$smt['semestermax']-2)) $alert="yellow";
		 		else if ($i>$smt['semestermax']-2) $alert="red";
		 		else $alert="";
		 		if ($semcount>0) {
			 		if ($dbStd->isIn($regid, $value.'2')) { ?>
			 			<td align="center" bgcolor="green"><font color="white"><?php echo $value.'-2'?></font></td>
			 		<?php }else {  $finis=0;?>
			 			<td align="center" bgcolor="<?php echo $alert;?>"><?php echo  $value.'-2'?></td>
			 		<?php }  
			 		
			 		$i++;$semcount--;
		 		}
		 		
		 	}
		 	if ($smt['semesterstart']=="2") {
				
			}
			if ($finis=="1") {
				 $bg="red";
				 $info="<h2> dan Sudah Habis</h2>";
			} else {
				$bg="darkblue";
				$info="";
			}
			?>
			</tr>
		 	<tr>
		 	<td colspan="<?php echo $i-1?>" align="center" bgcolor="<?php echo $bg?>"> <font color="white"> <?php echo "Maksimum masa studi anda ".$smt['semestermax'].' semester '.$info;?></font></td>
		 	</tr>
			
			<?php 
		 }?>
		 
		 </table>
	</div>
		<!-- Header end -->
	
	<div id="body">
		<!-- Begin Section Content-->
		<?php 
			$module = Zend_Controller_Front::getInstance()->getRequest()->getModuleName();
			
			$controller = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();
		
			$action = Zend_Controller_Front::getInstance()->getRequest()->getActionName();
			
			
			$file="";
			$submenu=null;
			
			if($auth->getIdentity()->role == 'student'){
				$file    = "sidebar/student.phtml";
			}elseif($auth->getIdentity()->role == 'alumni'){
				$file    = "sidebar/alumni.phtml";
			}elseif($auth->getIdentity()->role == 'parent'){
				$file    = "sidebar/parent.phtml";} 
			else if($auth->getIdentity()->role == 'tester'){
					$file    = "sidebar/tester.phtml";
			} else {
				$file    = "sidebar/applicant.phtml";	
			}		
			
			
			
			if($file!=''){
			?>
				<table width="100%" cellpadding="0" cellspacing="0" border="0">
					
					<tr>
					    <td rowspan="2" valign="top" width="16%"><?php echo $this->render($file); ?></td>
					    <td valign="top" width="84%">
					    	<?php
					    		if($submenu){
					    			echo $this->render($submenu);	
					    		}
					    	?>
					    </td>
					 </tr>
					 <tr>
					    <td valign="top"><?php echo $this->layout()->content; ?></td>
					 </tr>
					 
				</table>
			<?php
			}else{
				echo $this->layout()->content;	
			}
		?>
		<!-- End Section Content-->
		<div style="clear:both;">&nbsp;</div>
	</div>
	
	<div id="footer">
		<!-- Footer start -->
		<div style="width: 1024px; margin: 0 auto;">
			<div style="float:left; text-align: left; padding-top: 5px;">
				Trisakti University<br />
				Jalan Kyai Tapa No. 1 Grogol, Jakarta Barat, Indonesia<br />
				Phone: (62-21) 566 3232 | Fax: (62-21) 564 4270	
			</div>
			<div align="right" style="text-align: right; padding-top: 18px;" >
				Copyright &copy; <?php echo APPLICATION_ENTERPRISE; ?>. All rights reserved.
			</div>
		</div>
		<!-- Footer end -->
	</div>
</div>
</body>
</html>