<? echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->locale; ?>" dir="<?php echo $this->direction; ?>">
<head>
	<?php echo $this->headMeta(); ?>
	<?php echo $this->headTitle(); ?>
	<?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/layout.css'); ?>
	<?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/trisakti/simpletree.css'); ?>
	<?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/trisakti/topmenu.css'); ?>
	<?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/trisakti/style.css'); ?>
	<?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/trisakti/left-menu.css'); ?>
	
	<?php
		$this->jQuery()->enable();
		$this->jQuery()->setVersion('1.7.2');
		$this->jQuery()->useCdn(true);
	 	//$this->jQuery()->setLocalPath($this->baseUrl().'/js/jquery/jquery-1.4.1.min.js');
		
		$this->jQuery()->uiEnable();
		$this->jQuery()->setUiVersion('1.8.18');
		$this->jQuery()->useUiCdn();
		$this->jQuery()->addStylesheet($this->baseUrl().'/js/jquery/themes/smoothness/jquery-ui.css');
		//$this->jQuery()->setUiLocalPath($this->baseUrl().'/js/jquery/ui/jquery-ui.js');
		
		echo $this->jQuery();
		
		echo $this->headLink()->prependStylesheet($this->baseUrl().'/js/jquery/plugin/timepicker/timePicker.css');
		echo $this->headScript()->prependScript($this->baseUrl().'/js/jquery/plugin/timepicker/jquery.timepicker.js');
		
		echo $this->headScript()->prependScript($this->baseUrl().'/js/jquery/plugin/multiselect-1.12/jquery.multiselect.min.js');
		echo $this->headLink()->prependStylesheet($this->baseUrl().'/js/jquery/plugin/multiselect-1.12/jquery.multiselect.css');
	?>

	<?php

	//echo $this->headScript()->appendFile($this->baseUrl().'/js/jquery/ui/jquery-ui.js'); ?>
	
	<?php 
	
	
	 	if($this->direction == 'rtl'){
	 		echo $this->headScript()->prependScript($this->baseUrl().'/js/jquery/plugin/potato.menu/jquery.ui.potato.menu.rtl.js');
	 		echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/ibfim/dashboard_rtl.css');
	 		echo $this->headLink()->prependStylesheet($this->baseUrl().'/js/jquery/plugin/potato.menu/jquery.ui.potato.menu.rtl.css');
	 		echo "<style>";
	 		echo "ul.potato-menu li.potato-menu-item {
	 				float:right;
				}";
	 		echo "#language{
	 				left:10px;
	 			}";
	 		
	 		echo "#appTitle{
	 				left: 15px;
					top: 25px;
	 			}";
	 		
	 		echo "#main-content{
						margin-right: 200px;
				}";
	 		
		 	echo "div.toolbar-button {
				float:left;
				text-align: left;
				}";
		 	
	 		echo "</style>";
	 	}else{
	 		echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/ibfim/dashboard_ltr.css');
	 		echo $this->headScript()->prependScript( $this->baseUrl().'/js/jquery/plugin/potato.menu/jquery.ui.potato.menu.js');
	 		echo $this->headLink()->prependStylesheet($this->baseUrl().'/js/jquery/plugin/potato.menu/jquery.ui.potato.menu.css');
	 		
	 		echo "<style>";
	 		echo "ul.potato-menu li.potato-menu-item {
	 				float:left;
				}";
	 		echo "#language{
	 				right:10px;
	 			}";
	 		
	 		echo "#appTitle{
	 				right: 15px;
					top: 25px;
	 			}";

	 		echo "#main-content{
						margin-left: 200px;
				}";
	 		
	 		echo "div.toolbar-button {
				float:right;
				text-align: right;
				}";
	 		
	 		echo "</style>";
	 	}
	 
	 ?>
	 	
	<!--[if lt IE 7]>
	<style media="screen" type="text/css">
	#container {
		height:100%;
	}
	</style>
	<![endif]-->
	
	<script type="text/javascript">
	 $(document).ready(function() {
	        $('#mainMenu').ptMenu();
	        $('#mainMenu').show();
	        
	 });
	</script>
	
	 
	
	
</head>
<body>

<div id="container">
	<div id="header">
		<!-- Header start -->
		<div id="logo"><div id="name">&nbsp;</div></div>
		<div id="appTitle"><?php echo "TEST DARING"; ?></div>
	</div>
	 <!-- Header end -->
	
	<div id="body">
		<!-- Begin Section Content-->
		<?php 
			 
 		  
			echo $this->layout()->content;	
			 

		?>
		<!-- End Section Content-->
	</div>
	
	<div id="footer">
		<!-- Footer start -->
		Copyright &copy; <?php echo APPLICATION_ENTERPRISE; ?>
		<!-- Footer end -->
	</div>
</div>
</body>
</html>