<?php 
	//get locale
	$registry = Zend_Registry::getInstance();
	$locale = $registry->get('Zend_Locale');
	$this->locale = $locale->toString();
	
	if($locale == 'ar_YE'){
		$this->direction = "rtl";
		$this->float = "right";	
	}else{
		$this->direction = "ltr";
		$this->float = "left";
	}
?>
<? echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->locale; ?>" dir="<?php echo $this->direction; ?>">
<head>
	<?php echo $this->headMeta(); ?>
	<?php echo $this->headTitle(); ?>
	<?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/layout.css'); ?>
	<?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/trisakti/simpletree.css'); ?>
	<?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/trisakti/topmenu.css'); ?>
	<?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/trisakti/style.css'); ?>
	<?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/trisakti/left-menu.css'); ?>
	
	<?php echo $this->headScript()->appendFile($this->baseUrl().'/ckeditor/ckeditor_basic.js');?>

	
	<?php
		$this->jQuery()->enable();
		$this->jQuery()->setVersion('1.7.2');
		$this->jQuery()->useCdn(false);
	 	$this->jQuery()->setLocalPath($this->baseUrl().'/js/jquery/jquery-1.5.1.min.js');
		
		$this->jQuery()->uiEnable();
		$this->jQuery()->setUiVersion('1.8.18');
		$this->jQuery()->useUiCdn(false);
		$this->jQuery()->addStylesheet($this->baseUrl().'/js/jquery/themes/smoothness/jquery-ui.css');
		$this->jQuery()->setUiLocalPath($this->baseUrl().'/js/jquery/jquery-ui-1.8.18.min.js');
		$this->headScript()->appendFile($this->baseUrl().'/js/jquery/plugin/number/jquery.number.min.js');
		
		echo $this->jQuery();
		
		echo $this->headLink()->prependStylesheet($this->baseUrl().'/js/jquery/plugin/timepicker/timePicker.css');
		echo $this->headScript()->appendFile($this->baseUrl().'/js/jquery/plugin/timepicker/jquery.timepicker.js');
		
		
		echo $this->headScript()->appendFile($this->baseUrl().'/js/jquery/plugin/multiselect-1.12/jquery.multiselect.min.js');
		echo $this->headLink()->prependStylesheet($this->baseUrl().'/js/jquery/plugin/multiselect-1.12/jquery.multiselect.css');
	?>

	
	
	<?php 
	
	
	 	if($this->direction == 'rtl'){
	 		echo $this->headScript()->appendFile($this->baseUrl().'/js/jquery/plugin/potato.menu/jquery.ui.potato.menu.rtl.js');
	 		echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/trisakti/dashboard_rtl.css');
	 		echo $this->headLink()->prependStylesheet($this->baseUrl().'/js/jquery/plugin/potato.menu/jquery.ui.potato.menu.rtl.css');
	 		echo "<style>";
	 		echo "ul.potato-menu li.potato-menu-item {
	 				float:right;
				}";
	 		echo "#language{
	 				left:10px;
	 			}";
	 		
	 		echo "#appTitle{
	 				left: 15px;
					top: 25px;
	 			}";
	 		
	 		echo "#main-content{
						margin-right: 200px;
				}";
	 		
		 	echo "div.toolbar-button {
				float:left;
				text-align: left;
				}";
		 	
	 		echo "</style>";
	 	}else{
	 		echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/trisakti/dashboard_ltr.css');
	 		echo $this->headScript()->appendFile($this->baseUrl().'/js/jquery/plugin/potato.menu/jquery.ui.potato.menu.js');
	 		echo $this->headLink()->prependStylesheet($this->baseUrl().'/js/jquery/plugin/potato.menu/jquery.ui.potato.menu.css');
	 		
	 		echo "<style>";
	 		echo "ul.potato-menu li.potato-menu-item {
	 				float:left;
				}";
	 		echo "#language{
	 				right:10px;
	 			}";
	 		
	 		echo "#appTitle{
	 				right: 15px;
					top: 25px;
	 			}";

	 		echo "#main-content{
						margin-left: 200px;
				}";
	 		
	 		echo "div.toolbar-button {
				float:right;
				text-align: right;
				}";
	 		
	 		echo "</style>";
	 	}
	 
	 ?>
	 	
	<!--[if lt IE 7]>
	<style media="screen" type="text/css">
	#container {
		height:100%;
	}
	</style>
	<![endif]-->
	
	<script type="text/javascript">
	 $(document).ready(function() {
	        $('#mainMenu').ptMenu();
	        $('#mainMenu').show();
	        
	 });
	</script>
	
	<!-- sidebar menu -->
	<script type="text/javascript">
	function slide(navigation_id, pad_out, pad_in, time, multiplier)
	{
		// creates the target paths
		var list_elements = navigation_id + " li.sliding-element";
		var link_elements = list_elements + " a";

		// initiates the timer used for the sliding animation
		var timer = 0;

		// creates the slide animation for all list elements
		$(list_elements).each(function(i)
		{
			// margin left = - ([width of element] + [total vertical padding of element])
			$(this).css("margin-left","-180px");
			// updates timer
			timer = (timer*multiplier + time);
			$(this).animate({ marginLeft: "0" }, timer);
			$(this).animate({ marginLeft: "15px" }, timer);
			$(this).animate({ marginLeft: "0" }, timer);
		});

		// creates the hover-slide effect for all link elements
		$(link_elements).each(function(i)
		{
			/*$(this).hover(
			function()
			{
				$(this).animate({ paddingLeft: pad_out }, 150);
			},
			function()
			{
				$(this).animate({ paddingLeft: pad_in }, 150);
			});*/
		});
	}

	$(document).ready(function()
	{
		slide("#sliding-navigation", 25, 15, 0, .8);
	});
	</script>
	
	
</head>
<body>

<div id="container">
	<div id="header">
		<!-- Header start -->
		<div id="logo"><div id="name">&nbsp;</div></div>
		<div id="appTitle">
			<?php echo APPLICATION_ENTERPRISE; ?>
			<br />
			<i><?php echo APPLICATION_TITLE; ?></i>
		</div>
	</div>
	<div id="menu">
		<div id="language">
			<select style="width:100px;" onChange="window.location = '?lang=' + this.options[this.selectedIndex].value">
				<option value="en" <?php echo $this->locale=="en_US"?"selected='selected'":""; ?>>English</option>
				<option value="id" <?php echo $this->locale=="id_ID"?"selected='selected'":""; ?>>Bahasa Indonesia</option>
			<!--	<option value="ar" <?php echo $this->locale=="ar_YE"?"selected='selected'":""; ?>>Arabic</option>-->
			</select>
		</div>
		
		<div id="topmenu">
		<div class="underlinemenu">
			<ul>
				<!--  
				<li><a href="<?php echo $this->url(array('module'=>'general-setup','controller'=>'language','action'=>'index'),'default',true) ?>"><?php echo $this->translate("Set-Up")?></a></li>
				<li><a href="<?php echo $this->url(array('module'=>'application','controller'=>'index','action'=>'index'),'default',true) ?>"><?php echo $this->translate("Application")?></a></li>
				<li><a href="<?php echo $this->url(array('module'=>'schedule','controller'=>'index','action'=>'index'),'default',true) ?>"><?php echo $this->translate("Schedule")?></a></li>
				<li><a href="<?php echo $this->url(array('module'=>'admission-record','controller'=>'registration','action'=>'index'),'default',true) ?>"><?php echo $this->translate("Registration")?></a></li>
				<li><a href="<?php echo $this->url(array('module'=>'admission-record','controller'=>'student','action'=>'profile'),'default',true) ?>"><?php echo $this->translate("Records")?></a></li>
				<li><a href="<?php echo $this->url(array('module'=>'exam','controller'=>'asscomponent','action'=>'index'),'default',true) ?>"><?php echo $this->translate("Examination")?></a></li>				
				<li><a href="<?php echo $this->url(array('module'=>'question-bank','controller'=>'pool','action'=>'index'),'default',true) ?>"><?php echo $this->translate("Question Bank")?></a></li>
				<li><a href="/onlinetest/" target="_blank">Online Examination</a></li>
				<li><a href="<?php echo $this->url(array('module'=>'finance','controller'=>'bank','action'=>'index'),'default',true) ?>">Finance</a></li>
				<li><a href="<?php echo $this->url(array('module'=>'discipline','controller'=>'case','action'=>'student-case'),'default',true) ?>">Discipline</a></li>
				<li><a href="<?php echo $this->url(array('module'=>'default','controller'=>'authentication','action'=>'logout'),'default',true) ?>"><?php echo $this->translate("Logout"); ?></a></li>
				-->
			</ul>
		</div>
		</div>

		<div id="live">
		<?php //get student live 
			// $auth = Zend_Auth::getInstance();
			// if($auth->getIdentity()->role=='student'){
				//echo "student";
			// }
	 	?>
		</div>
		
	</div>
		<!-- Header end -->
	
	<div id="body">
		<!-- Begin Section Content-->
		<?php 
			$module = Zend_Controller_Front::getInstance()->getRequest()->getModuleName();
			
			$controller = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();
		
			$action = Zend_Controller_Front::getInstance()->getRequest()->getActionName();
			
			
			$file="";
			$submenu=null;
			
			if($module=='general-setup' || $module=='anr-setup'){
				$file="sidebar/setup.phtml";
				
				if (($controller == 'university') ||
					($controller == 'faculty') ||
					($controller == 'department') ||
					($controller == 'branch') ||
					($controller == 'office')) {
				 		
					$submenu = "submenu/organization.phtml";				
				}	
				elseif (($controller == 'country') ||
				 	($controller == 'state')) {
				 		
					$submenu = "submenu/country.phtml";	
								
				}elseif (($controller == 'award') ||
					($controller == 'main-program') ||
					($controller == 'program') ||
					($controller == 'program-requirement') ||
				 	($controller == 'academic-landscape')) {
				 		
					$submenu = "submenu/programme.phtml";				
				}	
				elseif (($controller == 'course') ||
					($controller == 'course-prerequisites') ||
				 	($controller == 'course-offered')) {
					$submenu = "submenu/course.phtml";				
				}
				else
				if (($controller == 'semester') ||
					($controller == 'activity') ||
				 	($controller == 'calendar')) {
					$submenu = "submenu/semester.phtml";				
				}else
				if ( ($controller == 'client') || ($controller == 'market')) {
					$submenu = "submenu/client.phtml";				
				}else 
				if ( ($controller == 'venue') ) {
					$file    = "sidebar/Schedule.phtml";
					$submenu = "submenu/application.phtml";	 	
				}else 
				if ( ($controller == 'takaful') || ($controller == 'email-template') ) {
					$file    = "sidebar/setup.phtml";
					$submenu = "submenu/application.phtml";	 	
				}
					
			}else
			/*if($module=='general-setup'){
				$file="sidebar/general-setup.phtml";
				
				if (($controller == 'university') ||
					($controller == 'faculty') ||
					($controller == 'department') ||
					($controller == 'branch') ||
					($controller == 'office') ||
				 	($controller == 'venue')) {
					$submenu = "submenu/organization.phtml";				
				}	
				elseif (($controller == 'country') ||
				 	($controller == 'state')) {
					$submenu = "submenu/country.phtml";				
				}	
			}else*/
			if($module=='system-setup'){
				//$file    = "sidebar/general-setup.phtml";	
				$file    = "sidebar/setup.phtml";
				
				if($controller=='module' || $controller=='role'){
					$submenu = "submenu/system-setup.phtml";
				}else
				if($controller=='user' || $controller=='audit'){
					$submenu = "submenu/users.phtml";
				}
				
				
				
			}else 
			if($module=='language-setup'){
				//$file    = "sidebar/general-setup.phtml";	
				$file    = "sidebar/setup.phtml";
				$submenu = "submenu/language.phtml";
			}else
			/*if($module=='anr-setup'){
				$file="sidebar/anr-setup.phtml";	
				
				if (($controller == 'award') ||
					($controller == 'market') ||
					($controller == 'main-program') ||
					($controller == 'program') ||
					($controller == 'program-requirement') ||
				 	($controller == 'academic-landscape')) {
					$submenu = "submenu/programme.phtml";				
				}	
				elseif (($controller == 'course') ||
					($controller == 'course-prerequisites') ||
				 	($controller == 'course-offered')) {
					$submenu = "submenu/course.phtml";				
				}
				elseif (($controller == 'semester') ||
					($controller == 'activity') ||
				 	($controller == 'calendar')) {
					$submenu = "submenu/semester.phtml";				
				}
				
			}else*/ 			
			if($module=='admission-record'){
				$file="sidebar/admission-record.phtml";
				
				if (($controller == 'registration') ||
					($controller == 'credit-transfer') ||
				 	($controller == 'add-drop')) {
					 $submenu = "submenu/registration.phtml";				
				}	
				if (($controller == 'student') ||
					($controller == 'change-program')) {
					$submenu = "submenu/record.phtml";
					$file    = "sidebar/record.phtml";				
				}
					
				
			}else			
			if($module=='finance'){
				if ($controller=='sponsor') {
					$file="sidebar/sponsor.phtml";
				}
				elseif ($controller=='payment'){
					$file="sidebar/payment.phtml";
				}
				elseif ($controller=='renewal'){
					$file="sidebar/renewal.phtml";
				}
				else {
					$file="sidebar/finance.phtml";
				}
				$submenu = "submenu/application.phtml";			
			}else			
			if($module=='question-bank'){
				$file="sidebar/questionbank.phtml";
				$submenu = "submenu/application.phtml";			
			}else
			
			if($module=='application'){
				
				if($controller=='migration'){	
					$file="sidebar/application.phtml";				
					$submenu = "submenu/migration.phtml";	
				}else
				if($controller=='entry-requirement' 
					|| $controller=='education-level'
					|| $controller=='qualification-item'){
					$file    = "sidebar/setup.phtml";	
					$submenu = "submenu/application-setup.phtml";
				}/*else if($controller=='selection-highschool'){	
					$file="sidebar/application.phtml";		
					if($action != 'index'){							
					$submenu = "submenu/selection-highschool.phtml";
					}	
				}*/else{
					$file="sidebar/application.phtml";
					$submenu = "submenu/application.phtml";	
				}
					
			}else 
			if($module=='exam'){
				if($controller=='examsitting'){
					$file    = "sidebar/exam.phtml";
					$submenu = "submenu/exam.phtml";	
				}elseif($controller=='result'){
					$file    = "sidebar/exam.phtml";
					$submenu = "submenu/result.phtml";	
				}elseif($controller=='markadjustment'){
					$file    = "sidebar/exam.phtml";
					$submenu = "submenu/exam.phtml";	
				}elseif($controller=='markadjsetup'){
					$file    = "sidebar/exam.phtml";
					$submenu = "submenu/exam.phtml";	
				}elseif($controller=='examuser'){
					$file    = "sidebar/exam.phtml";
					$submenu = "submenu/exam-setup.phtml";	
				}elseif($controller=='grade'){
					$file    = "sidebar/exam.phtml";
					$submenu = "submenu/grade.phtml";	
				}elseif($controller=='asscomponent' || $controller=='component' || $controller=='asscompitem'){
					$file    = "sidebar/exam.phtml";
					$submenu = "submenu/assessment-component.phtml";	
				}elseif($controller=='markentry'){
					$file    = "sidebar/exam.phtml";
					$submenu = "submenu/mark-entry.phtml";	
				}else{					
					$file="sidebar/exam.phtml";
				}
				//$submenu = "submenu/exam.phtml";		
				
			}else 
			if($module=='schedule'){
				$file    = "sidebar/Schedule.phtml";
				$submenu = "submenu/application.phtml";	
			}else
			if ($module=='setup'){
				if($controller=='result'){
					$file="sidebar/exam.phtml";
				}
			}else 
			if($module=='discipline'){
				$file    = "sidebar/discipline.phtml";
				$submenu = "submenu/application.phtml";	
			}
			
			
			if($file!=''){
			?>
				<table width="100%" cellpadding="0" cellspacing="0" border="0">
					
					<tr>
					    <td rowspan="2" valign="top" width="16%"><?php echo $this->render($file); ?></td>
					    <td valign="top" width="84%">
					    	<?php
					    		if($submenu){
					    			echo $this->render($submenu);	
					    		}
					    	?>
					    </td>
					 </tr>
					 <tr>
					    <td valign="top"><?php echo $this->layout()->content; ?></td>
					 </tr>
					 
				</table>
			<?php
			}else{
				echo $this->layout()->content;	
			}

		?>
		<!-- End Section Content-->
		<div style="clear:both;">&nbsp;</div>
	</div>
	
	<div id="footer">
		<!-- Footer start -->
		<div style="width: 1024px; margin: 0 auto;">
			<div style="float:left; text-align: left; padding-top: 5px;">
				Trisakti University<br />
				Jalan Kyai Tapa No. 1 Grogol, Jakarta Barat, Indonesia<br />
				Phone: (62-21) 566 3232 | Fax: (62-21) 564 4270	
			</div>
			<div align="right" style="text-align: right; padding-top: 18px;" >
				Copyright &copy; <?php echo APPLICATION_ENTERPRISE; ?>. All rights reserved.
			</div>
		</div>
		<!-- Footer end -->
	</div>
</div>
</body>
</html>