<div class="message toolbar">
	<h2><?php echo $this->title; ?></h2>
	<div class="toolbar-button">
		<ul>
			<li>
				<a href="<?php echo $this->url(array('module'=>'admission-record','controller'=>'registration', 'action'=>'index'),'default',true);?>">
					<span class='back'></span>
					Back
				</a>
			</li>
			<li>
				<a href="#" >
					<span class='info'></span>
					Info
				</a>
			</li>
		</ul>
	</div>
</div>

<div align="center" style="background:#ebebeb; height:30px;">
<ul class="steps">
	<li class="prevDone">
		<span>1</span> Student Selection
	</li>
    <li class="current">
		<span>2</span> Semester Selection
	</li>
    <li class="next">
		<span>3</span> Course Selection
	</li>
	<li class="empty">
		<span>3</span> Finish
	</li>
</ul>
<br class="clear" />
</div>
<br />
<?if(isset($this->noticeMessage)){?>
<div class="message notice"><strong><? echo $this->noticeMessage;?></strong>.</div><br />
<?}?>
<?if(isset($this->noticeSuccess)){?>
<div class="message success"><strong><? echo $this->noticeSuccess;?></strong>.</div><br />
<?}?>
<?if(isset($this->noticeError)){?>
<div class="message error"><strong><? echo $this->noticeError;?></strong>.</div><br />
<?}?>

<h2>Student Details</h2>
<table class="table5">
	<tr>
		<th><b>Name</b></th>
		<td>:</td>
		<td><?php echo $this->student['fullname']; ?></td>
	</tr>
	<tr>
		<th><b>Matric No</b></th>
		<td>:</td>
		<td><?php echo $this->student['matric_no']; ?></td>
	</tr>
	<tr>
		<th><b>Program</b></th>
		<td>:</td>
		<td><?php echo $this->program['main_name']; ?></td>
	</tr>
</table>
<br />

<h2>Semester Details</h2>
<div style="width: 600px;">
<fieldset style="width:450px; margin:0 0">
	<legend>Semester Options</legend>
<form name="course_form" action="<?php echo $this->url(array('module'=>'admission-record','controller'=>'add-drop', 'action'=>'course'),'default',true);?>" method="post">
	<input type="hidden" name="student_id" value="<?php echo $this->student['id']?>" />
	<input type="hidden" name="program_id" value="<?php echo $this->program['id']?>" />
	<table width="100%">
		<tr>
			<td width="110px">
				Program
			</td>
			<td width="5px">:</td>
			<td>
				<?php echo $this->program['main_name']?>
			</td>
		</tr>
		<tr>
			<td width="80px">
				Academic Landscape
			</td>
			<td width="5px">:</td>
			<td>
				<a href="#">Click here to view</a>
			</td>
		</tr>
		<tr>
			<td>
				Semester
			</td>
			<td width="5px">:</td>
			<td>
				<select name="semester_id" style="width:250px">
					<option value="0"> -- Select Semester --</option>
					<?php
						foreach ($this->semesterlist as $semester) {
							if($semester['id'] == $this->semester_id){
								$selected="selected='selected'";
							}else{
								$selected="";
							}
							echo "<option value='".$semester['id']."'" .$selected." >".$semester['name']."</option>";
						}
					?>
				</select>
			</td>
		</tr>
		<tr>
			<td colspan="2">&nbsp;</td>
			<td><input type="submit" value="Next" /></td>
		</tr>
	</table>
</form>
</fieldset>
</div>
<br />
