<script type="text/javascript">
	function del(){

		var id = $('input[name=id]:checked').val();
		
		if(confirm('Are you sure to delete?')){
			window.location = "<?php echo $this->url(array('module'=>'general-setup','controller'=>'highschool-subject', 'action'=>'delete'),'default',true); ?>/id/"+id;
		}
	}
	
	function add(){
		window.location="<?php echo $this->url(array('module'=>'general-setup','controller'=>'highschool-subject', 'action'=>'add'),'default',true);?>";
	}

	function edit(){
		var id = $('input[name=id]:checked').val();
		window.location="<?php echo $this->url(array('module'=>'general-setup','controller'=>'highschool-subject', 'action'=>'edit'),'default',true);?>/id/"+id;
	}

	function searchbox(){
		$('#div_search').show();
	}
</script>

<div class="message toolbar">
	<h2><?php echo $this->title; ?></h2>
	<div class="toolbar-button">
		<ul>
			<li>
				<a href="#" onclick="javascript:add()">
					<span class='add'></span>
					Add
				</a>
			</li>
			<li>
				<a href="#" onclick="javascript:edit()">
					<span class='edit'></span>
					Edit
				</a>
			</li>
			<li>
				<a href="#" onclick="javascript:del()">
					<span class='delete'></span>
					Delete
				</a>
			</li>
			<li class="divider"></li>
			<li>
				<a id="search" href="#" onclick="javascript:searchbox()">
					<span class='search'></span>
					Search
				</a>
			</li>
			<li>
				<a href="#" >
					<span class='info'></span>
					Info
				</a>
			</li>
		</ul>
	</div>
</div>
<br />

<div id="div_search" style="display:none;">
	<fieldset>
		<legend>Search</legend>
		<?php echo $this->searchForm; ?>
	</fieldset>
</div>

<div style="width:100%;">
<?php 
	echo $this->paginationControl($this->paginator,'Sliding','paginationTop.phtml');
?>
<table class="table" width="100%" cellpadding="5" cellspacing="1" border="0">
	<tr>
		<th width="2"></th>
		<th><?php echo $this->translate("Subject Name")?></th>
		<th><?php echo $this->translate("Subject Name")?>(Indonesia)</th>
		<th><?php echo $this->translate("Basic Core Subject")?></th>
	</tr>
	
	<?php 
	$i=0;
	foreach ($this->paginator as $entry): 
	?>
	<tr <?php echo $i%2==0?"class='shade'":""; ?>>
		<td> <input type="radio" name="id" value="<?php echo $entry['ss_id']; ?>"></td>
		<td><a href="<?php echo $this->url(array('module'=>'general-setup','controller'=>'highschool-subject', 'action'=>'detail','id'=>$entry['ss_id']),'default',true); ?>"><?php echo $entry['ss_subject']; ?></a></td>
		<td><a href="<?php echo $this->url(array('module'=>'general-setup','controller'=>'highschool-subject', 'action'=>'detail','id'=>$entry['ss_id']),'default',true); ?>"><?php echo $entry['ss_subject_bahasa']; ?></a></td>
		<td align="center"><?php echo $entry['ss_core_subject']==1?$this->translate("Yes"):$this->translate("No"); ?></td>
	</tr>
	<?php 
	$i++;
	endforeach 
	?>

</table>
</div>
<?php 
	echo $this->paginationControl($this->paginator,'Sliding','paginationBottom.phtml');
?>