<?php
if (isset($_REQUEST['submit']))
{
      // Live URL: https://api-3t.paypal.com/nvp
      // Test URL: https://api-3t.sandbox.paypal.com/nvp
      $url = 'https://api-3t.paypal.com/nvp';
 
      $amount = 10.00; // Obviously, we would sum up the contents of some cart to fill in this value.
      $credit_card_type = $_REQUEST['credit_card_type'];
      $credit_card_number = $_REQUEST['credit_card_number'];
      $expiration_month = $_REQUEST['expiration_month'];
      $expiration_year = $_REQUEST['expiration_year'];
      $cvv2 = $_REQUEST['cvv2'];
 
      $first_name = $_REQUEST['first_name'];
      $last_name = $_REQUEST['last_name'];
      $address1 = $_REQUEST['address1'];
      $address2 = $_REQUEST['address2'];
      $city = $_REQUEST['city'];
      $state = $_REQUEST['state'];
      $zip = $_REQUEST['zip'];
 
      $country = 'US'; // Assuming we are only accepting transactions within the United States.
      $currency_code = 'USD'; // Assuming we are using the United States Dollar
      $ip_address = $_SERVER['REMOTE_ADDR']; // Get the IP Address, assuming we are in a LAMP environment
 
      // Create an instance of our PayPal NVP client
      $client = new PayPal_Client($url);
 
      // Send our API request!
      $result = $client->doDirectPayment(
            $amount,
            $credit_card_type,
            $credit_card_number,
            $expiration_month,
            $expiration_year,
            $cvv2,
            $first_name,
            $last_name,
            $address1,
            $address2,
            $city,
            $state,
            $zip,
            $country,
            $currency_code,
            $ip_address);
 
      // Remember to store the transaction ID! You'll need it 
      // to lookup the transaction details. For now, let's just
      // display the results.
      echo $result->getBody();
}
?>
<form>
      <ul>
            <li><label>First Name:</label><input type="" name="" value="" /></li>
            <li><label>Last Name:</label><input type="" name="" value="" /></li>
            <li><label>Address, Line 1:</label><input type="" name="" value="" /></li>
            <li><label>Address, Line 2:</label><input type="" name="" value="" /></li>
            <li><label>City:</label><input type="" name="" value="" /></li>
            <li><label>State (2-Letter):</label><input type="" name="" value="" /></li>
            <li><label>Zip:</label><input type="" name="" value="" /></li>
      </ul>
      <ul>
            <li><label>Card Type</label><input type="" name="" value="" /></li>
            <li><label></label><input type="" name="" value="" /></li>
      </ul>
</form>