<?php 
	echo "<h1>". $this->title ."</h1>";
?>
<div style="width:900px; margin: 0 auto;">


	<div style="width: 100%;">
			<fieldset style="width:450px;">
				
			<form name="searchfrm" action="" method="post">
				<table width="100%">
					<tr>
						<td>
							Program 
						</td>
						<td width="5px">:</td>
						<td>			
							<select name="program_id" onChange="form.submit()">
							<option value="0">Please select</option>
							<?php 
							foreach($this->program as $p){
								if($this->program_id==$p[id])
								  $sel = "selected";
								else
								  $sel = "";
							 	echo "<option value='$p[id]' $sel>$p[main_name]</option>";
							 } ?>
							</select>
						</td>
					</tr>
					<tr>
						<td>
							Course
						</td>
						<td width="5px">:</td>
						<td>
						
							<select name="course_id">
							<option value="0">Please select</option>
							<?php 
							foreach($this->courses as $course){
								if($this->course_id==$course[id])
								  $sel = "selected";
								else
								  $sel = "";
							 	echo "<option value='$course[id]' $sel>$course[name]</option>";
							 } ?>
							</select>
						</td>
					</tr>
					<tr>
						<td colspan="2">&nbsp;</td>
						<td><input type="submit" value="search" /></td>
					</tr>
				</table>
			</form>
			</fieldset>
	</div>
</div>
