<script type="text/javascript">
	
	
	function save(){		
		document.addfrm.action="<?php echo $this->url(array('module'=>'question-bank','controller'=>'exam-set', 'action'=>'add-set'),'default',true);?>";
		document.addfrm.submit();
	}

	$(document).ready(function(){
	
	
	
	 $("#startdate").datepicker({
				"dateFormat":"yy-mm-dd",
				"changeMonth":"true",
				beforeShow: function(input, inst) { 
					if ($("#enddate").val()) { // Only update when has a value.
						 
							$( "#startdate" ).datepicker( "option", "maxDate", $("#enddate").datepicker("getDate") );
					}
				}
			
				
		});
		
		$("#enddate").datepicker({
				"dateFormat":"yy-mm-dd",
				"changeMonth":"true",
				beforeShow: function(input, inst) { 
					if ($("#startdate").val()) { // Only update when has a value.
							$( "#enddate" ).datepicker( "option", "minDate", $("#startdate").datepicker("getDate") );
					}
				}
				
		});
	
	});

</script>

<script type="text/javascript">

function addRow()
{ 
 	
  var tbl = document.getElementById('bank');
 
  var lastRow = tbl.rows.length;   
  var iteration = lastRow;
  var row = tbl.insertRow(lastRow);
  
   document.getElementById('iteration').value = iteration
  
  
   // select cell ppol
  var cellRightSel = row.insertCell(0);  
  var sel = document.createElement('select');
  sel.name = 'pool_id' + iteration;
  <? $d=0; foreach($this->pool as $p){?>
     sel.options[<?php echo $d?>] = new Option('<?php echo $p["name"]?>','<?php echo $p["id"]?>');
  <? $d++;} ?> 
  cellRightSel.appendChild(sel);
  
 
  // question no
  var total = row.insertCell(1);
  var cn = document.createElement('input');
  cn.type = 'text';
  cn.name = 'NosOfQues' + iteration;
  cn.id = 'NosOfQues'+ iteration;
  cn.size = 5;
  total.appendChild(cn);
   
  
}

function removeRow()
{	
	
  var curval=2;  
  newtotal=Math.abs(curval);  
  var tbl = document.getElementById('bank');
  var lastRow = tbl.rows.length;
  
  curval = document.getElementById('iteration').value;
  if (lastRow > newtotal) {
	  tbl.deleteRow(lastRow - 1);  
      document.getElementById('iteration').value = curval-1;
  }else{
      alert('Sorry you cannot remove this row. Please add at least one bank.');
  }
}





</script>

<div class="message toolbar">
	<h2><?php echo $this->title; ?></h2>
	<div class="toolbar-button">
		<ul>
		<li>
				<a href="#" onclick="javascript:save()">
					<span class='save'></span>
					Save
				</a>
			</li>
			<li class="divider"></li>
			<li>
				<a href="<?php echo $this->url(array('module'=>'question-bank','controller'=>'tos', 'action'=>'list-tos'),'default',true);?>" >
					<span class='back'></span>
					Back
				</a>
			</li>
			<li>
				<a href="#" >
					<span class='info'></span>
					Info
				</a>
			</li>
		</ul>
	</div>
</div>
<br>

<div style="width:900px;">
<form name="addfrm" method="POST" action="">
<table width="100%" border="0" cellpadding=" 5" cellspacing="1">
 <tr>
    <td>Course</td>
    <td>:</td>
    <td>
    <select name="courseid" id="courseid">
		<option> --Select Course-- </option>	
		<? foreach ($this->course as $c){?>	
		<option value="<?php echo $c["id"]?>"><?php echo $c["code"].'-'.$c["name"]?></option>		
		<? } ?>
	</select>
	
	</td>
  </tr>
  <tr>
    <td>Set Name</td>
    <td width="5px">:</td>
    <td><input type="text" name="setname" size="50" value=""></td>
  </tr>
 <tr>
    <td>Instruction</td>
    <td width="5px">:</td>
    <td><textarea name="instruction" cols="50" rows="10"></textarea></td>
  </tr>
  <tr>
    <td>Description</td>
    <td width="5px">:</td>
    <td><textarea name="description" cols="50" rows="10"></textarea></td>
  </tr>
 <tr>
    <td>Date</td>
    <td width="5px">:</td>
    <td>Start Date <input type="text" name="startdate" id="startdate" size="10" value=""> End Date <input type="text" name="enddate" id="enddate" size="10" value=""></td>
  </tr>
  
  <!-- <tr>
    <td>Select Bank/Pool</td>
    <td width="5px">:</td>
    <td> 
    <a href="javascript:void(0)" onclick="addRow()">Add Row</a>&nbsp;|&nbsp;
    <a href="javascript:void(0)" onclick="removeRow()">Remove Row</a><br>

    
          <table id="bank"  class="table3" width="50%" cellpadding="5" cellspacing="1" border="0">
        
         	<tr>
         		<th>Pool Name</th>
         		<th>No of Question</th>
         	</tr>
         	<tr >
         		<td> <select name="pool_id1" id="pool_id1">
						<option> --Select Pool-- </option>	
						<? $no=1; foreach ($this->pool as $p){?>	
						<option value="<?php echo $p["id"]?>"><?php echo $p["name"]?></option>		
						<? $no++;} ?>
					</select>
				</td>
         		<td><input type="text" name="NosOfQues1" id="NosOfQues1" size="5" value="" ></td>
         		
         	</tr>
         </table>        
         <input type="hidden" name="iteration" id="iteration" value="1">
         <input type="hidden" name="TotalNosOfQues" id="TotalNosOfQues" value="">
    </td>
  </tr>-->
  <tr>
    <td>Bank/Pool</td>
    <td width="5px">:</td>
    <td>
    
    <select name="pool_id[]" id="pool_id" multiple>		
		<? $no=1; foreach ($this->pool as $p){?>	
		<option value="<?php echo $p["id"]?>"><?php echo $p["name"]?></option>		
		<? $no++;} ?>
   </select>
   * You may select multiple bank/pool name.
    </td>
  </tr>
   <tr>
    <td>Time Limit</td>
    <td width="5px">:</td>
    <td><input type="text" name="TimeLimit" size="10" value=""></td>
  </tr>
   <tr>
    <td>Alert Time</td>
    <td width="5px">:</td>
    <td><input type="text" name="AlertTime" size="10" value=""></td>
  </tr>
   <tr>
    <td>Pass Mark</td>
    <td width="5px">:</td>
    <td><input type="text" name="passMark" size="10" value=""></td>
  </tr>
  
   <tr>
    <td>Status</td>
    <td>:</td>
    <td>
    <select name="status" id="status">
		<option> --Select Status-- </option>
		<option value="1" >Active</option>
		<option value="2" >Not Active</option>		
	</select>
	
	</td>
  </tr>
  </table>
  </form>
</div>

<script>
CKEDITOR.replace( 'description',
				{
					height: 100, 
					toolbar :
					[
					    { name: 'basicstyles', items : [ 'Bold','Italic','Underline','Strike','Subscript','Superscript','-','RemoveFormat' ] },
					    { name: 'paragraph',   items : [ 'NumberedList','BulletedList','-','Outdent','Indent','-','Blockquote','CreateDiv','-','JustifyLeft','JustifyCenter','JustifyRight','JustifyBlock','-','BidiLtr','BidiRtl' ] },
					  
					]
					
				});
				
				CKEDITOR.replace( 'instruction',
				{
					height: 100, 
					toolbar :
					[
					    { name: 'basicstyles', items : [ 'Bold','Italic','Underline','Strike','Subscript','Superscript','-','RemoveFormat' ] },
					    { name: 'paragraph',   items : [ 'NumberedList','BulletedList','-','Outdent','Indent','-','Blockquote','CreateDiv','-','JustifyLeft','JustifyCenter','JustifyRight','JustifyBlock','-','BidiLtr','BidiRtl' ] },
					  
					]
					
				});
				</script>