<script type="text/javascript">

   function searchbox(){
		$( "#dialog-search" ).dialog('open');
	}
	
   $(function() {
		// a workaround for a flaw in the demo system (http://dev.jqueryui.com/ticket/4375), ignore!
		$( "#dialog:ui-dialog" ).dialog( "destroy" );
	
		$( "#dialog-search" ).dialog({
			modal: true,
			autoOpen: false,
			width: 600,
			buttons: {
				"Search": function() { 
					$("#search_form").submit(); 
				}, 
				"Cancel": function() { 
					$(this).dialog("close"); 
				}
				
			}
		});
	});
	
	
	


</script>
<div class="message toolbar">
	<h2><?php echo $this->title; ?></h2>
	<div class="toolbar-button">
		<ul>
			
			<li class="divider"></li>
			<li>
				<a href="#" onclick="javascript:searchbox()">
					<span class='search'></span>
					Search
				</a>
			</li>
			<li>
				<a href="#" >
					<span class='info'></span>
					Info
				</a>
			</li>
		</ul>
	</div>
</div>
<br />

<?php 
	echo $this->paginationControl($this->paginator,'Sliding','paginationTop.phtml');
?>
<table class="table" width="100%" cellpadding="5" cellspacing="1" border="0">
	<tr>
		<th>Bil</th>		
		<th>Name</th>
		<th>ICNO</th>	
		<th>Registration ID</th>
		<th>Course</th>
		<th>Exam Date</th>
		<th>Exam Center</th>
		<th>Action</th>
	</tr>
	
	<?php 
	$i=0;
	foreach ($this->paginator as $entry): 
	?>
	<tr <?php echo $i%2==0?"class='shade'":""; ?>>		
	<td><?php echo $this->paginator->getAbsoluteItemNumber(0,$this->paginator->getCurrentPageNumber())+$i;?>
	)</td>
		<td><?php echo strtoupper($entry['ARD_NAME']); ?></td>
		<td><?php echo $entry['ARD_IC']; ?></td>		
		<td><?php echo $entry['regId']; ?></td>		
		<td><?php echo $entry['cname']; ?></td>	
		<td><?php echo $entry['exam_date']; ?></td>	
		<td><?php echo $entry['venue']; ?></td>	
		<td><a href="<?php echo $this->url(array('module'=>'question-bank','controller'=>'exam-set','action'=>'student-quest','regId'=>$entry['regId']),'default',true) ?>">View</a></td>	
	</tr>
	<?php 
	$i++;
	endforeach 
	?>

</table>

<?php 
	echo $this->paginationControl($this->paginator,'Sliding','paginationBottom.phtml');
?>



<div id="dialog-search" title="Search Bank">
<form name="search_form" id="search_form" action="" method="post">
	<table width="100%" class="table5">
	<tr>
			<td>
				Course Name
			</td>
			<td width="5px">:</td>
			<td>
				<select name="idCourse">
				<option value="">--All--</option>
				<?foreach ($this->course as $c){?>
				<option value="<?php echo $c["id"]?>"><?php echo $c["code"].'-'.$c["name"]?></option>
				<? } ?>
				</select>
			</td>
		</tr>
		
<tr>
			<td>
				Venue
			</td>
			<td width="5px">:</td>
			<td>
				<select name="idVenue">
				<option value="">--All--</option>
				<?foreach ($this->venue as $v){?>
				<option value="<?php echo $v["id"]?>"><?php echo $v["name"]?></option>
				<? } ?>
				</select>
			</td>
		</tr>
		<tr>
			<td>
				Name/IC Number
			</td>
			<td width="5px">:</td>
			<td><input type="text" size="50" name="keywords" value=""></td>
		</tr>
		
		
	</table>
</form>
</div>