<html>
 <script>
 function onclickUpload(n,doc,path) {
	 
		document.getElementById("items_id").value=n;
		document.getElementById("document_name").value=doc;
		document.getElementById("redirect_path").value=path;
		$('#dialog-upload-certificate').dialog('open');
	}

	$(function() {
		$( "#dialog-upload-certificate" ).dialog({
			autoOpen: false,
	    	resizable: false,
	      	height:140,
	      	modal: true,
	      	buttons: {
	        	"Upload certificate": function() {
	        		$('#form_certificate').submit();
	        	},
	        	Cancel: function() {
	          		$( this ).dialog( "close" );
	        	}
	      	}
	    });

		 
	});

$(function(){


	
	 
    // add multiple select / deselect functionality
    $("#c_checkall").click(function () {
          $('.chk_i').attr('checked', this.checked);
    });
 
    // if all checkbox are selected, check the selectall checkbox
    // and viceversa
    $(".chk_i").click(function(){
 
        if($(".chk_i").length == $(".chk_i:checked").length) {
            $("#c_checkall").attr("checked", "checked");
        } else {
            $("#c_checkall").removeAttr("checked");
        }
 
    });
    // add multiple select / deselect functionality
    $("#t_checkall").click(function () {
          $('.chk_t').attr('checked', this.checked);
    });
 
    // if all checkbox are selected, check the selectall checkbox
    // and viceversa
    $(".chk_t").click(function(){
 
        if($(".chk_t").length == $(".chk_t:checked").length) {
            $("#t_checkall").attr("checked", "checked");
        } else {
            $("#t_checkall").removeAttr("checked");
        }
 
    });
    // add multiple select / deselect functionality
    $("#skpi_checkall").click(function () {
          $('.chk_s').attr('checked', this.checked);
    });
 
    // if all checkbox are selected, check the selectall checkbox
    // and viceversa
    $(".chk_s").click(function(){
 
        if($(".chk_s").length == $(".chk_s:checked").length) {
            $("#skpi_checkall").attr("checked", "checked");
        } else {
            $("#skpi_checkall").removeAttr("checked");
        }
 
    });

    $('#status_toggler').change(function() {
        var all_val = $(this).val();
        
    	$('select[name="status[]"]').each(function(){
    	    $(this).val(all_val);
    	    
    	});
    	
	});
	
});
</script>
<body>

<div class="message toolbar">
	<h2><?php echo $this->title; ?></h2>
	<div class="toolbar-button">
		 
	<ul>
		<li>
				<a href="#" >
					<span class='info'></span>
					<?php echo $this->translate("info")?>
				</a>
			</li>
		</ul>
		
	</div>
</div>
<br /> 
<fieldset><legend><?php echo $this->translate('Apply Yudisium')?></legend>
<?php $std=$this->student;?>
<form name="form_apply" method="post" action="">

<table class="table">
<tr><th><?php echo "Nama" ?></th><td>:</td><td><?php echo $std['appl_fname'].' '.$std['appl_mname'].' '.$std['appl_lname'];?></td></tr>
<tr><th><?php echo "NIM" ?></th><td>:</td><td><?php echo $std['registrationId'];?></td></tr>
<tr><th><?php echo "Program Studi" ?></th><td>:</td><td><?php echo $std['ArabicName'];?></td></tr>
<tr><th><?php echo "Sks Lulus" ?></th><td>:</td><td><?php echo $std['sks'];?></td></tr>
<tr><th><?php echo "IPK Lulus" ?></th><td>:</td><td><?php echo $std['ipk'];?></td></tr>

</table>
<fieldset><legend><?php $ok="1";echo $this->translate('Prerequisite')?></legend>
<table class="table">
<tr><th><?php echo "Item Syarat"?></th><th><?php echo "Syarat"?></th><th><?php echo "Status"?></th><th><?php echo $this->translate("Upload")?></th>
<tr><td><?php echo "Bukti Bebas Pinjaman Perpustakaan"?></td><td>Tidak ada pinjaman</td><td><?php echo "";//$std['statuspustaka']?></td><td><!-- <input type="button" name="buttonpustaka" value="Upload Bukti Bebas Perpustakaan" onclick="onclickUpload(<?php echo $std['IdStudentRegistration']?>,'Perpustakaan','/default/student-portal/graduation-process');"> --></td>
<tr><td><?php echo "Memenuhi semua kewajiban keuangan"?></td><td align="center">0</td><td><?php echo "";//$std['statuskeungan']?></td><td></td>
<tr><td><?php echo "IPK minimal"?></td><td align="center"><?php echo $std['ipkmin']?></td><td><?php if ($std['ipkmin']<=$std['ipk']) {
							echo "Memenuhi"; 
						}else {
							echo "Belum memenuhi";
							$ok="0";
					}?></td><td></td>
<tr><td><?php echo "sks kumulatif minimal"?></td><td align="center"><?php echo $std['sksmin']?></td><td><?php if ($std['sksmin']<=$std['sks']) {
				echo "Memenuhi";  
				}else {
				echo "Belum memenuhi"; $ok="0";
}?></td><td></td>

</table>
<?php if ($ok=="1" && $std['apply']=="0") {?>
<input type="submit" name="submit_apply" value="apply yudicium">
<?php } else echo "<strong>Telah terdaftar sebagai peserta yudisium</strong>"?>
</form>
</fieldset>

<?php if ($std['apply']=="1") {?>
</fieldset>
<br>
<fieldset><legend><?php echo $this->translate("Persetujuan Cetakan")?></legend>
<fieldset><legend><?php echo " Petunjuk "?></legend>
<p>Setelah muncul link pada kolom Certificate/Ijazah, Transcript, SKPI, silahkan diunduh dokumennya dan diperiksa kebenaranya. Jika sudah benar silahkan lakukan persetujuan</p> 
<p><ol><li>Jika ada data akademik yang salah silahkan datang ke Subbag Pendidikan dan Pengajaran Fakultas saudara, dengan membawa bukti terkait</li>
<li> Untuk kesalahan nama dan tanggal lahir silahkan datang ke Subbag Pendidikan dan Pengajaran Fakultas saudara, dengan membawa copy ijasah terakhir dan akte kelahiran</li>
<li> Untuk kesalahan data di SKPI silahkan anda ke Subbag Litmaslum Fakultas saudara, dengan membawa bukti terkait
</li>
</ol></p>
</fieldset>
<br>

<div style="width:100%;">
<form name="printapproval" id="printapproval" method="post" >
<table class="table" width="100%" cellpadding="5" cellspacing="0" border="0">
<tr align="center" > 
<td><?php echo $this->translate('Student Id')?></td>
<td><?php echo $this->translate('Student Name')?></td>

<td><?php echo $this->translate('Place of Birth')?></td>
<td><?php echo $this->translate('Date of Birth')?></td>
<td><?php echo $this->translate('Certificate/Ijasah')?></td>
<td> <?php echo $this->translate("Certificate Approval"); ?>				
</td>
<td><?php echo $this->translate('Transcript')?></td>
<td><?php echo $this->translate("Transcript Approval"); ?>				
</td>
<td><?php echo $this->translate('SKPI')?></td>
<td><?php echo $this->translate("SKPI Approval"); ?>				
</td> 
</tr>
<?php  
$graduate=$std;
?>
<tr style="background-color:<?php echo $this->cycle(array("#F0F0F0","#FFFFFF"))->next()?>">
	 
	<td><?php echo $graduate['registrationId']?></td>
	<td><?php echo $graduate['appl_fname'].' '.$graduate['appl_mname'].' '.$graduate['appl_lname']?></a></td>
	
	<td><?php echo $graduate['appl_birth_place']?></td>
	<td><?php echo $graduate['appl_dob']?></td>
	<?php if ($graduate['ijazah']!=null) {?>
	<td> <a href="<?php echo "http://".ONNAPP_HOSTNAME.$graduate['ijazah'];?>" target="_BLANK" >Ijazah</a></td>
	<?php } 
	$statusall=0; 
	if ($graduate['ijazah']!=null) {
		$status='';
		if ($graduate['std_app_ijazah']=='1') $status='checked';
		if ($graduate['enable_print_ijazah']=="1") {
			$statusall++;?>
			<td><?php echo $this->translate('Ijazah Approved')?></td>
		<?php } else {?>
			<td align="center"><input class='chk_i' type="checkbox" name="p_ijasah" id="p_ijasah" <?php echo $status; ?> value='<?php echo $graduate['IdStudentRegistration'];?>'></td>
			</td>
	<?php }?>
	<?php 
	} else {?>
		<td>&nbsp;</td><td>&nbsp;</td>
	<?php }
	
	if ($graduate['transcript']!=null) {?>
	<td> 
	<a href="<?php echo "http://".ONNAPP_HOSTNAME.$graduate['transcript'];?>" target="_BLANK" >Transcript</a></td>
	<?php   
		$status='';
		if ($graduate['std_app_transcript']=='1') $status='checked';
		if ($graduate['enable_print_transcript']=="1") {
			$statusall++;?>
			<td><?php echo $this->translate('Transcript Approved')?></td>
		<?php } else {?>
	 		<td align="center"><input class='chk_t' type="checkbox" name='p_transcript' id='p_transcript' <?php echo $status; ?> value='<?php echo $graduate['IdStudentRegistration'];?>'></td>
			</td> 
	<?php }
	} else {?><td>&nbsp;</td><td>&nbsp;</td><?php } 
	if ($graduate['skpi']!=null) {?>
	<td> 
	<a href="<?php echo "http://".ONNAPP_HOSTNAME.$graduate['skpi'];?>" target="_BLANK" >SKPI</a></td>
	<?php 
		$status='';
		if ($graduate['std_app_skpi']=='1') $status='checked';
		if ($graduate['enable_print_skpi']=="1") {
				$statusall++;?>
			<td><?php echo $this->translate('SKPI Approved')?></td>
	<?php } else {?>
	 	<td align="center"><input class='chk_s' type="checkbox" name='p_skpi' id='p_skpi' <?php echo $status; ?> value='<?php echo $graduate['IdStudentRegistration'];?>'></td>
		</td> 
	<?php } 
	} else {?><td>&nbsp;</td><td>&nbsp;</td><?php } ?>
	 
	
</tr>
 
<?php if ($statusall<3) {?>
<tr><td colspan="11" align="center" bgcolor="LightGrey"><input type="submit" value="Approve It" name="submit_approval"></td></tr><?php } ?>
<?php } else echo "Anda belum berhak mendapatkan Ijazah/Transkrip Akademik/SKPI";
?>
</table>
</fieldset>
<br>
<?php  

if (isset($std['dean_approved']) && $std['dean_approved']) {?>

<fieldset><legend><?php echo $this->translate('Apply Convocation')?></legend>
<form name="formwisuda" method="post" >
<table class="table">
<tr><th><?php echo "Tgl Wisuda" ?></th><td>:</td><td><?php echo $std['dt_wisuda'];?></td></tr>
<tr><th><?php echo "Jam Wisuda" ?></th><td>:</td><td><?php echo $std['time_wisuda'];?></td></tr>
<tr><th><?php echo "Biaya Wisuda" ?></th><td>:</td><td><?php echo $std['price'];?></td></tr> 
<tr><th><?php echo "Status Biaya Wisuda" ?></th><td>:</td><td><?php echo $std['stsbiaya'];?></td></tr>
<?php if ($std['convoapp']!="1") {?>
<tr><th></th><td>:</td><td><input type="submit" name="wisuda" value="Apply Wisuda"> </td></tr> 
<?php } else {?><tr><th>Status</th><td>:</td><td><?php 
	echo $this->translate($std['msg']); }?> </td></tr>
</table>
</form>


<?php }?>
</form>
</fieldset>
<fieldset><legend><?php echo $this->translate('Document Readiness')?></legend>
 
<table class="table">
<tr><th><?php echo "Ijazah/Sertificate" ?></th><td>:</td><td><?php echo $std['ijazah_status'];?></td></tr>
<tr><th><?php echo "Transcript" ?></th><td>:</td><td><?php echo $std['transcript_status'];?></td></tr>
<tr><th><?php echo "SKPI" ?></th><td>:</td><td><?php echo $std['skpi_status'];?></td></tr> 
 
</table>
 
 
</fieldset>
</body>


<div id="dialog-upload-certificate" title="<?php echo $this->translate("Upload Student's Certificate");?>">
  	<form name="form_certificate" id="form_certificate" method="post" action="/default/student-portal/upload-certificate" enctype="multipart/form-data">
  		<input type="file" name="file" />
  		<input type="hidden" name="document_name" id="document_name">
  		<input type="hidden" id="items_id" name="items_id" />
  		
  	</form>
</div>
</html>