<html>
 <script>

$(function(){


	
	 
    // add multiple select / deselect functionality
    $("#c_checkall").click(function () {
          $('.chk_i').attr('checked', this.checked);
    });
 
    // if all checkbox are selected, check the selectall checkbox
    // and viceversa
    $(".chk_i").click(function(){
 
        if($(".chk_i").length == $(".chk_i:checked").length) {
            $("#c_checkall").attr("checked", "checked");
        } else {
            $("#c_checkall").removeAttr("checked");
        }
 
    });
    // add multiple select / deselect functionality
    $("#t_checkall").click(function () {
          $('.chk_t').attr('checked', this.checked);
    });
 
    // if all checkbox are selected, check the selectall checkbox
    // and viceversa
    $(".chk_t").click(function(){
 
        if($(".chk_t").length == $(".chk_t:checked").length) {
            $("#t_checkall").attr("checked", "checked");
        } else {
            $("#t_checkall").removeAttr("checked");
        }
 
    });
    // add multiple select / deselect functionality
    $("#skpi_checkall").click(function () {
          $('.chk_s').attr('checked', this.checked);
    });
 
    // if all checkbox are selected, check the selectall checkbox
    // and viceversa
    $(".chk_s").click(function(){
 
        if($(".chk_s").length == $(".chk_s:checked").length) {
            $("#skpi_checkall").attr("checked", "checked");
        } else {
            $("#skpi_checkall").removeAttr("checked");
        }
 
    });

    $('#status_toggler').change(function() {
        var all_val = $(this).val();
        
    	$('select[name="status[]"]').each(function(){
    	    $(this).val(all_val);
    	    
    	});
    	
	});
	
});
</script>
<body>

<div class="message toolbar">
	<h2><?php echo $this->title; ?></h2>
	<div class="toolbar-button">
		 
	<ul>
		<li>
				<a href="#" >
					<span class='info'></span>
					<?php echo $this->translate("info")?>
				</a>
			</li>
		</ul>
		
	</div>
</div>
<br /> 
<fieldset><legend><?php echo $this->translate("Persetujuan Cetakan")?></legend>
<div style="width:100%;">
<form name="printapproval" id="printapproval" method="post" >
<table class="table" width="100%" cellpadding="5" cellspacing="0" border="0">
<tr align="center" >
<td><?php echo $this->translate('No')?></td>
<td><?php echo $this->translate('Student Id')?></td>
<td><?php echo $this->translate('Student Name')?></td>

<td><?php echo $this->translate('Place of Birth')?></td>
<td><?php echo $this->translate('Date of Birth')?></td>
<td><?php echo $this->translate('Certificate/Ijasah')?></td>
<td> <?php echo $this->translate("Certificate Approval"); ?>				
</td>
<td><?php echo $this->translate('Transcript')?></td>
<td><?php echo $this->translate("Transcript Approval"); ?>				
</td>
<td><?php echo $this->translate('SKPI')?></td>
<td><?php echo $this->translate("SKPI Approval"); ?>				
</td> 
</tr>
<?php  
if (isset($this->graduates)) {
	foreach ($this->graduates as $key=> $graduate) {

?>
<tr style="background-color:<?php echo $this->cycle(array("#F0F0F0","#FFFFFF"))->next()?>">
	<td><?php echo $key+1;?></td>
	<td><?php echo $graduate['registrationId']?></td>
	<td><?php echo $graduate['appl_fname'].' '.$graduate['appl_mname'].' '.$graduate['appl_lname'].' '?></a></td>
	
	<td><?php echo $graduate['appl_birth_place']?></td>
	<td><?php echo $graduate['appl_dob']?></td>
	<?php if ($graduate['ijazah']!=null) {?>
	<td> <a href="<?php echo ONNAPP_HOSTNAME.$graduate['ijazah'];?>" target="_BLANK" >Ijazah</a></td>
	<?php }  
	if ($graduate['ijazah']!=null) {
		$status='';
		if ($graduate['std_app_ijazah']=='1') $status='checked';
		if ($graduate['dean_approval_skr']>0) {?>
			<td><?php echo $this->translate('Ijazah Approved')?></td>
		<?php } else {?>
			<td align="center"><input class='chk_i' type="checkbox" name="p_ijasah" id="p_ijasah" <?php echo $status; ?> value='<?php echo $graduate['idStudentRegistration'];?>'></td>
			</td>
	<?php }?>
	<?php 
	} else {?>
		<td>&nbsp;</td><td>&nbsp;</td>
	<?php }
	
	if ($graduate['transcript']!=null) {?>
	<td> 
	<a href="<?php echo "http://".ONNAPP_HOSTNAME.$graduate['transcript'];?>" target="_BLANK" >Transcript</a></td>
	<?php   
		$status='';
		if ($graduate['std_app_transcript']=='1') $status='checked';
		if ($graduate['dean_approval_skr']>0) {?>
			<td><?php echo $this->translate('Transcript Approved')?></td>
		<?php } else {?>
	 		<td align="center"><input class='chk_t' type="checkbox" name='p_transcript' id='p_transcript' <?php echo $status; ?> value='<?php echo $graduate['idStudentRegistration'];?>'></td>
			</td> 
	<?php }
	} else {?><td>&nbsp;</td><td>&nbsp;</td><?php } 
	if ($graduate['skpi']!=null) {?>
	<td> 
	<a href="<?php echo ONNAPP_HOSTNAME.$graduate['skpi'];?>" target="_BLANK" >Transcript</a></td>
	<?php 
		$status='';
		if ($graduate['std_app_skpi']=='1') $status='checked';
		if ($graduate['dean_approval_skr']>0) {?>
			<td><?php echo $this->translate('SKPI Approved')?></td>
	<?php } else {?>
	 	<td align="center"><input class='chk_s' type="checkbox" name='p_skpi' id='p_skpi' <?php echo $status; ?> value='<?php echo $graduate['idStudentRegistration'];?>'></td>
		</td> 
	<?php } 
	} else {?><td>&nbsp;</td><td>&nbsp;</td><?php } ?>
	 
	
</tr>

<?php 
} 
?>

<tr><td colspan="11" align="center" bgcolor="LightGrey"><input type="submit" value="Approve It" name="submit"></td></tr>
<?php } else echo "Anda belum berhak mendapatkan Ijazah/Transkrip Akademik/SKPI";
?>
</table>


</body>
</form>
</html>