<script type="text/javascript">
	
	function add(){
		window.location="<?php echo $this->url(array('module'=>'company','controller'=>'application', 'action'=>'add-batch-step1'));?>";
	}

</script>

<?if(isset($this->noticeMessage)){?>
<div class="message notice"><strong><? echo $this->noticeMessage;?></strong>.</div>
<?}?>
<?if(isset($this->noticeSuccess)){?>
<div class="message success"><strong><? echo $this->noticeSuccess;?></strong>.</div>
<?}?>
<?if(isset($this->noticeError)){?>
<div class="message error"><strong><? echo $this->noticeError;?></strong>.</div>
<?}?>

<div class="message toolbar">
	<h2><?php echo $this->title; ?></h2>
	<div class="toolbar-button">
		<ul>
			<li class="divider"></li>
			<li>
				<a href="#" >
					<span class='info'></span>
					Info
				</a>
			</li>
		</ul>
	</div>
</div>
<br />
<?php 
	//echo $this->paginationControl($this->paginator,'Sliding','paginationTop.phtml');
?>
<table class="table" width="100%" cellpadding="5" cellspacing="2">
	<tr>
		<th width="27%">Candidate Name</th>
		<th width="21%">Course</th>
		<th width="21%">Cost</th>
		<th width="21%">Payment Status</th>
		<th width="10%">Date Created</th>
	</tr>
	<?php
		if(isset($this->paginator)){

		$i=0;
		foreach ($this->paginator as $user): 
	?>
		<tr <?php echo $i%2==0?"class='shade'":""; ?>>
			<td>
				<input type="radio" name="student_id" value="<?php echo $user['ID']; ?>">
			</td>
			<td>
				<a href="<?php echo $this->url(array('module'=>'company','controller'=>'record', 'action'=>'view', 'id'=>$user['ID']),'default',true);?>"><?php echo $user['ARD_NAME']; ?></a>
			</td>
			<td><?php echo $user['ARD_IC']; ?></td>
			<td><?php echo $user['username']; ?></td>
			<td><?php echo $user['ARD_EMAIL']; ?></td>
			<td><?php echo $user['company_short_name']; ?></td>
			<td align="center"><?php echo date('d/m/Y  g:ia', strtotime($user['ARD_DATE_APP'])); ?></td>
		</tr>		
	<?php 
		$i++;
		endforeach;
	 
		}
	?>
</table>
<?php 
	//echo $this->paginationControl($this->paginator,'Sliding','paginationBottom.phtml');
?>
