<div class="message toolbar">
	<h2><?php echo $this->title; ?></h2>
	<div class="toolbar-button">
		<ul>
			<li>
				<a href="<?php echo $this->url(array('module'=>'application','controller'=>'manual', 'action'=>'list'),'default',true);?>">
					<span class='back'></span>
					Back
				</a>
			</li>
			<li>
				<a href="#" >
					<span class='info'></span>
					Info
				</a>
			</li>
		</ul>
	</div>
</div>
<br />


<table width="100%" cellpadding="5" class="table2" cellspacing="1">
  <tr bgcolor="#ffffff">
    <td width="20%">FULLNAME</td>
    <td width="80%"><?php echo $this->applicant['ARD_NAME'];?></td>
  </tr>
  <tr bgcolor="#ffffff">
    <td>IC NO</td>
    <td><?php echo $this->applicant['ARD_IC'];?></td>
  </tr>
  <tr bgcolor="#ffffff">
    <td>CITIZENSHIP</td>
    <td><?php echo $this->applicant['ARD_CITIZEN'];?></td>
  </tr>
  <tr bgcolor="#ffffff">
    <td>GENDER</td>
    <td><?php echo $this->applicant['ARD_SEX'];?></td>
  </tr>
  <tr bgcolor="#ffffff">
    <td>RACE</td>
    <td><?php echo $this->applicant['ARD_NAME'];?></td>
  </tr>
  <tr bgcolor="#ffffff">
    <td>CONTACT NUMBER</td>
    <td><?php echo $this->applicant['ARD_PHONE'];?></td>
  </tr>
  <tr bgcolor="#ffffff">
    <td>ADDRESS</td>
    <td><?php echo $this->applicant['ARD_ADDRESS'];?> <BR><?php echo $this->applicant['ARD_ADDRESS2'];?></td>
  </tr>
  <tr bgcolor="#ffffff">
    <td>POSTCODE</td>
    <td><?php echo $this->applicant['ARD_POSTCODE'];?></td>
  </tr>
  <tr bgcolor="#ffffff">
    <td>STATE</td>
    <td><?php echo $this->applicant['ARD_STATE'];?></td>
  </tr>
  <tr bgcolor="#ffffff">
    <td>EMAIL</td>
    <td><?php echo $this->applicant['ARD_EMAIL'];?></td>
  </tr>
  <tr bgcolor="#ffffff">
    <td>OFFER?</td>
    <td>&nbsp;</td>
  </tr>
  <tr bgcolor="#ffffff" valign="top">
    <td>PROGRAM OFFERED</td>
    <td>
    <?php
    foreach ($this->applied as $app){
    	echo "<input type='radio'>&nbsp;";
    	echo strtoupper($app['main_name'])."<br>";
    }
    ?></td>
  </tr>
</table>


