<style type="text/css">
#sliptbl
{
width:100%;
border-collapse:collapse;
}
#sliptbl td, #sliptbl th 
{
font-size:1em;
border:1px solid #98bf21;
padding:3px 7px 2px 7px;
}
#sliptbl th 
{
font-size:1.1em;
text-align:left;
padding-top:5px;
padding-bottom:4px;
background-color:#A7C942;
color:#ffffff;
}

.barcode {font-family: ccode39}

</style>


<p>
<table id="printbl" align="right"><tr><td >
<input type="button" value="PRINT" onclick="goprint();"></input></td></tr></table>
</p>

<table width="100%" border="0" cellspacing="0" cellpadding="5">
<!--<tr><td align=left>
<img src="<?php //echo $this->baseURL();?>/images/ustlogo.png " alt="USTY LOGO"/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<img src="<?php //echo $this->baseURL();?>/images/ustyname.gif " alt="USTY NAME"/>
</td></tr
<tr><td align=right><span class="barcode"><?php echo $this->exam_slip_no;?></span> </td></tr>>-->
 
  <tr> 
    <td><div align="center">    
    	<strong>GRADE VERIFICATION REQUEST FORM</strong></div></td>
  </tr>
</table>
<br>
<br>
<table class="table" width="80%" cellpadding="5" cellspacing="0" border="0" align="center">
	<tr>
		<th>Grade Symbol</th>
		<th>Point Grade</th>
		<th>Grade Status</th>
		<th>Min Mark</th>
		<th>Max Mark</th>
		
	</tr>
	
	<?php 
	$i=0;
	foreach ($this->grade_list as $entry): 
	?>
	<tr <?php echo $i%2==0?"class='shade'":""; ?> align="center">
		<td><?php echo $entry['symbol']; ?></td>
		<td><?php echo $entry['point']; ?></td>
		<td><?php echo $entry['status']; ?></td>
		<td><?php echo $entry['min_mark']; ?></td>
		<td><?php echo $entry['max_mark']; ?></td>
		
	</tr>
	<?php 
	$i++;
	endforeach 
	?>

</table>
<br></br>
<table border=0 width="80%" height="100" align="center">
<tr><td width=15%>Print On</td><td  width=30%>: <?php echo date("d M Y h:i:s");?></td><td  width=15%>Verify By,</td><td  width=30%>&nbsp;</td></tr>
<tr><td>Print By</td><td>: <?php echo $this->username?></td><td>Name</td><td>:</td></tr>
<tr><td>Request Number</td><td>: <?php echo $this->request_number;?></td><td>Designation</td><td>:</td></tr>
<tr><td>&nbsp;</td><td>&nbsp;</td><td>Date</td><td>:</td></tr>
</table>
<script>

function goprint(){
	document.getElementById('printbl').style.display = 'none';
	window.print();
}
</script>