<script>
function verify(){
	if(document.verifyform.request_number.value==''){
		alert('Please enter request number.');
		document.verifyform.request_number.focus();
		return false;
	}
	
	reqno = document.verifyform.request_number.value;	
	grade_group_id = document.verifyform.id.value;	
	
	if(confirm('Are you sure you want to verify this grade. Once the grade has been verified, changes will not be allowed.')){	
		window.close();	
		window.location = "<?php echo $this->url(array('module'=>'exam','controller'=>'grade', 'action'=>'verify'))?>/request_no/" + reqno + "/grade_group_id/"+grade_group_id
		window.opener.location.reload(true);
	}
}
</script>
<form name="verifyform" method="POST" action="">
<table cellpadding=5>
<input type="hidden" name="id" value="<?php echo $this->grade_group_id;?>"></input>
	<tr><td colspan=2>Please enter Verification Request Code</td></tr>
	<tr><td>Request Code:</td><td><input type"text" name="request_number" size=20 value=""></input></td></tr>
	<tr><td>&nbsp;</td><td><input type="button" value="Verified" onclick="verify();"></input>
						  <input type="button" value="Cancel" onclick="window.close();"></input></td></tr>
</table>
</form>