<div class="message toolbar">
	<h2><?php echo $this->title; ?></h2>
	<div class="toolbar-button">
		<ul>
			
			<li>
				<a href="#" >
					<span class='info'></span>
					Info
				</a>
			</li>
		</ul>
	</div>
</div>
<br />

<div style="width:100%;">
<h2><?php echo $this->translate("Application Details")?></h2>
<table class="table3" width="100%" cellpadding="5" cellspacing="1" border="0">
		<tr>
		    <th width="30%"><?php echo $this->translate("Name")?></th>
			<td><?php echo $this->applicant["appl_fname"].' '.$this->applicant["appl_mname"].' '.$this->applicant["appl_lname"]; ?></td>			
		</tr>
		<tr>
		    <th><?php echo $this->translate("Applicant ID")?></th>
			<td><?php echo $this->applicant["at_pes_id"]; ?></td>			
		</tr>
		<tr>
		    <th><?php echo $this->translate("Admission Type")?></th>
			<td><?php 			
				if( $this->applicant['at_appl_type']==1 ){
					echo $this->translate("USM");}
				else{
					echo $this->translate("PSSB");
				}?></td>			
		</tr>
		<tr>
		    <th><?php echo $this->translate("Programme Offered")?></th>
			<td>	
				<?php 
					echo '('.$this->program["program_code"].') '.$this->program["program_name_indonesia"];
				?>
			</td>			
		</tr>
		<tr>
		    <th><?php echo $this->translate("Date Applied")?></th>
			<td><?php echo $this->applicant['at_create_date']!=null?date('d-m-Y', strtotime( $this->applicant['at_submit_date']) ) ."<br />". date('H:i a', strtotime( $this->applicant['at_submit_date']) ) : "-"; ?></td>			
		</tr>
		<tr>
		    <th><?php echo $this->translate("Payment Status")?></th>
			<td><?php   setlocale(LC_MONETARY, 'id_ID');
						if($this->payment != 0){
    						echo $this->translate("Paid").' ('.money_format('%i', $this->payment).')';
    					}else{
    						echo $this->translate("Not Paid");
    					}
			   ?></td>			
		</tr>
</table>


<h2><?php echo $this->translate("Documents Uploaded")?></h2>
<table class="table3" width="100%" cellpadding="5" cellspacing="1" border="0">
<tr>
	<th width="50%"><?php echo $this->translate("Documents Name");?></th>
	<th><?php echo $this->translate("View");?></th>
	
<?php if($this->applicant["at_appl_type"]==1){?>
<tr>
	<td width="50%"><?php echo $this->translate("Kartu Asli Peserta Ujian Saringan Masuk Universitas Trisakti");?></td>
	<td><?php if(isset($this->url_kartu)) { ?><a href="<?php echo $this->url_kartu;?>" target="_blank"><?php echo $this->translate("Download")?></a><?php } ?></td>
	
</tr>
<?php } ?>

<tr>
	<td width="50%"><?php echo $this->translate("Slip Asli tanda pembayaran yang telah dilakukan");?></td>
	<td><?php if(isset($this->url_payment_slip)) { ?><a href="<?php echo $this->url_payment_slip;?>" target="_blank"><?php echo $this->translate("Download")?></a><?php } ?></td>
</tr>	
<tr>
	<td><?php echo $this->translate("Tanda Pengenal Asli (SIM/KTP)");?></td>
	<td><?php if(isset($this->url_identity_card)) { ?><a href="<?php echo $this->url_identity_card;?>" target="_blank"><?php echo $this->translate("Download")?></a><?php } ?></td>
</tr>	
<tr>
	<td><?php echo $this->translate("Surat Pernyataan Kesediaan Memenuhi Kewajiban Administrasi Keuangan, Tatatertib, sanksi-sanksi Mahasiswa Baru");?></td>
	<td><?php if(isset($this->url_surat_pernyataan)) { ?><a href="<?php echo $this->url_surat_pernyataan;?>" target="_blank"><?php echo $this->translate("Download")?></a><?php } ?></td>
</tr>
</table>


<h2><?php echo $this->translate("Quit Application Form")?></h2>
<?php echo $this->form;?>
</div>
