<<script type="text/javascript">
<!--
//-->
 
$(function() {
$("#appt_date").datepicker({
	"dateFormat":"yy-mm-dd",
	"changeMonth":"true"		
	
});
});

</script>

<div class="message toolbar">
    <h2><?php echo $this->translate('Request Counseling'); ?></h2>
    <div class="toolbar-button">
        <ul>
            <li>
                <a href="/counseling/" >
                    <span class='back'></span>
                    <?php echo $this->translate('Back');?>
                </a>
            </li>
        </ul>
    </div>
</div>
<br />

<form action="" method="post">
    <table class="table" width="100%">
     <tr>
            <td><?php echo $this->translate('Semester'); ?></td>
            <td>:</td>
            <td>
                	 	   
			    <select id="IdSemester" name="IdSemester" >
						<option value=""><?php echo $this->translate("Please Select"); ?></option>
					<?php 
					 foreach($this->semesterlist as $mysem){
							if($this->idSemester == $mysem["key"]){
								$selected = "selected";
							}else{
								$selected='';
							}
						?>
						<option value="<?php echo $mysem["key"];?>" <?php echo $selected;?>><?php echo $mysem["value"];?></option>
					<?php  } ?>
				</select></td>
	     
        </tr>
        <tr>
            <td><?php echo $this->translate('Summary'); ?></td>
            <td>:</td>
            <td>
                <input name="issue[summary]" style="width:100%;"/>
            </td>
        </tr>
        <tr>
            <td><?php echo $this->translate('Problem Type'); ?></td>
            <td>:</td>
            <td>
                <select name="issue[problem_id]">
                    <option value=""><?php echo $this->translate('Select Issue Type'); ?></option>
                    <?php foreach($this->problem_types as $type ) {  ?>
                        <option value="<?php echo $type['IdCounselingCategory']; ?>"><?php echo $type['name']; ?></option>
                    <?php } ?>
                </select>
            </td>
        </tr>
        <tr>
            <td style="vertical-align: top;"><?php echo $this->translate('Description'); ?></td>
            <td style="vertical-align: top;">:</td>
            <td>
                <textarea id="description" name="issue[description]" cols="30" rows="10"  style="width:100%;"></textarea>
            </td>
        </tr>
        <tr>
            <td style="vertical-align: top;"><?php echo $this->translate('Appointment Date'); ?></td>
            <td style="vertical-align: top;">:</td>
            <td>
                <?php echo $this->formdate->appt_date;?>
            </td>
        </tr>
        <tr>
            <td style="vertical-align: top;"><?php echo $this->translate('Subject To'); ?></td>
            <td style="vertical-align: top;">:</td>
            <td>
                <?php echo $this->formdate->IdSubject;?>
            </td>
        </tr>
        <tr>
            <td colspan="3"><input type="submit" value="<?php echo $this->translate('Submit'); ?>"></td>
        </tr>
    </table>

</form>
