<div class="message toolbar">
    <h2><?php echo $this->translate('View'); ?></h2>
    <div class="toolbar-button">
        <ul>
            <li>
                <a href="/counseling/" >
                    <span class='back'></span>
                    <?php echo $this->translate('Back');?>
                </a>
            </li>
        </ul>
    </div>
</div>
<br />
<table class="table" width="100%">
    <tr>
        <td width="15%"><?php echo $this->translate('Summary'); ?></td>
        <td width="2%">:</td>
        <td>
            <?php echo $this->issue->summary; ?>
        </td>
    </tr>
    <tr>
        <td style="vertical-align: text-top;" width="10%"><?php echo $this->translate('Description'); ?></td>
        <td>:</td>
        <td>
            <?php echo $this->issue->description; ?>
        </td>
    </tr>
    <tr>
        <td style="vertical-align: text-top;" width="10%"><?php echo $this->translate('Appointment'); ?></td>
        <td>:</td>
        <td>
            <?php echo $this->issue->appt_date; ?>
        </td>
    </tr>
    <tr>
        <td style="vertical-align: text-top;" width="10%"><?php echo $this->translate('Subject To'); ?></td>
        <td>:</td>
        <td>
            <?php echo $this->issue->IdSubject; ?>
        </td>
    </tr>
    <tr>
        <td style="vertical-align: text-top;" width="10%"><?php echo $this->translate('Reply'); ?></td>
        <td>:</td>
        <td>
            <?php echo $this->issue->reply; ?>
        </td>
    </tr>
</table>
