 
<script>
	$(function(){
		
		$('#check_all').change(function(){
			if( $(this).prop('checked') ){
				$('.check').prop('checked',true);
			}else{
				$('.check').prop('checked',false);
			}
		});
		
	});
</script>
<style>
.next_bar{
	width: 100%;
	background: #EEE;
	margin: 10px 0;
	padding: 2px 0;
	text-align: center;
}
select{
	width: 250px;
}
</style>


<div class="message toolbar">
	<h2><?php echo $this->title; ?></h2>
	<div class="toolbar-button">
		<ul>
			<li>
				
			</li>
		</ul>
	</div>
</div>
<?php if(isset($this->noticeMessage)){?>
<div class="message notice"><strong><?php echo $this->noticeMessage;?></strong>.</div>
<br />
<?php }?>
<?php if(isset($this->noticeSuccess)){?>
<div class="message success"><strong><?php echo $this->noticeSuccess;?></strong>.</div>
<br />
<?php }?>
<?php if(isset($this->noticeError)){?>
<div class="message error"><strong><?php echo $this->noticeError;?></strong>.</div>
<br />
<?php }?>

<!-- STEP 1 -->
<?php 
if($this->step == 1){
?>
<!-- Breadcrum -->
<div class="breadcrum">
	<ul class="tri-steps">
		<li class="current"><div class="text"><a href="<?php echo $this->url(array('module'=>'finalassignment','controller'=>'proposal','action'=>'application', 'step'=>1),'default',true);?>"><?php echo $this->translate("College"); ?></a></div></li>
		<li class="next"><div class="text"><a href="<?php echo $this->url(array('module'=>'finalassignment','controller'=>'proposal','action'=>'application', 'step'=>2),'default',true);?>"><?php echo $this->translate("Program"); ?></a></div></li>
		<li class="next"><div class="text"><a href="<?php echo $this->url(array('module'=>'finalassignment','controller'=>'proposal','action'=>'application', 'step'=>3),'default',true);?>"><?php echo $this->translate("Branch"); ?></a></div></li>	
		<li class="next"><div class="text"><a href="<?php echo $this->url(array('module'=>'finalassignment','controller'=>'proposal','action'=>'application', 'step'=>4),'default',true);?>"><?php echo $this->translate("Majoring"); ?></a></div></li>
		<li class="next"><div class="text"><a href="<?php echo $this->url(array('module'=>'finalassignment','controller'=>'proposal','action'=>'application', 'step'=>5),'default',true);?>"><?php echo $this->translate("Proposal"); ?></a></div></li> 
		<li class="next"><div class="text"><a href="<?php echo $this->url(array('module'=>'finalassignment','controller'=>'proposal','action'=>'application', 'step'=>6),'default',true);?>"><?php echo $this->translate("Prerequisite"); ?></a></div></li> 
		<li class="last"><div class="text"><a href="<?php echo $this->url(array('module'=>'finalassignment','controller'=>'proposal','action'=>'application', 'step'=>7),'default',true);?>"><?php echo $this->translate("Confirmation"); ?></a></div></li>
	</ul>
	<div class="clear"></div>
</div>
<br />
<!-- End Breadcrum -->
<form id="form_1" method="post" action="/finalassignment/proposal/application/step/1">
<table class="table" id="result" width="100%">
<tr><td width="20%"><?php echo $this->translate('Faculty')?></td>
	<td ><select name="IdCollege">
				<?php 
				foreach ($this->facultylist as $list):
					$select = "";
					if( isset($this->faculty) && $this->faculty==$list['IdCollege'] ){
						$select = 'selected="selected"';
					}
				?>
					<option value="<?php echo $list['IdCollege'];?>" <?php echo $select; ?>><?php echo $list['ArabicName'];?></option>
				<?php 
				endforeach;
				?>
			</select></td>
		</tr>	
</table>
<div class="next_bar">
	<input type="submit" value="<?php echo $this->translate("Next");?>" />
</div>
</form>
<!-- End Breadcrum -->
<?php 
}else
?>


<!-- STEP 2 -->
<?php
if($this->step == 2){
?>
<!-- Breadcrum -->
<div class="breadcrum">
	<ul class="tri-steps">
		<li class="previous"><div class="text"><a href="<?php echo $this->url(array('module'=>'finalassignment','controller'=>'proposal','action'=>'application', 'step'=>1),'default',true);?>"><?php echo $this->translate("College"); ?></a></div></li>
		<li class="current"><div class="text"><a href="<?php echo $this->url(array('module'=>'finalassignment','controller'=>'proposal','action'=>'application', 'step'=>2),'default',true);?>"><?php echo $this->translate("Program"); ?></a></div></li>
		<li class="next"><div class="text"><a href="<?php echo $this->url(array('module'=>'finalassignment','controller'=>'proposal','action'=>'application', 'step'=>3),'default',true);?>"><?php echo $this->translate("Branch"); ?></a></div></li>	
		<li class="next"><div class="text"><a href="<?php echo $this->url(array('module'=>'finalassignment','controller'=>'proposal','action'=>'application', 'step'=>4),'default',true);?>"><?php echo $this->translate("Majoring"); ?></a></div></li>
		<li class="next"><div class="text"><a href="<?php echo $this->url(array('module'=>'finalassignment','controller'=>'proposal','action'=>'application', 'step'=>5),'default',true);?>"><?php echo $this->translate("Proposal"); ?></a></div></li> 
		<li class="next"><div class="text"><a href="<?php echo $this->url(array('module'=>'finalassignment','controller'=>'proposal','action'=>'application', 'step'=>6),'default',true);?>"><?php echo $this->translate("Prerequisite"); ?></a></div></li> 
		<li class="last"><div class="text"><a href="<?php echo $this->url(array('module'=>'finalassignment','controller'=>'proposal','action'=>'application', 'step'=>7),'default',true);?>"><?php echo $this->translate("Confirmation"); ?></a></div></li>
	</ul>
	<div class="clear"></div>
</div>
<br />
<form id="form_2" method="post" action="/finalassignment/proposal/application/step/2">
<table class="table" id="result" width="100%">
<tr><td  width="20%"><?php echo $this->translate('Program Study')?></td>
	<td ><select name="IdProgram">
			<option value="All"><?php echo $this->translate("All");?></option>
				<?php 
				foreach ($this->programlist as $list):
					$select = "";
					if( isset($this->program) && $this->program==$list['key'] ){
						$select = 'selected="selected"';
					}
				?>
					<option value="<?php echo $list['key'];?>" <?php echo $select; ?>><?php echo  $list['value'];?></option>
				<?php 
				endforeach;
				?>
			</select></td>
		</tr>	
</table>
<div class="next_bar">
	<input type="submit" value="<?php echo $this->translate("Next");?>" />
</div>
</form>

<?php 
}else
?>


<!-- STEP 3 -->
<?php
if($this->step == 3){
?>
<!-- Breadcrum -->
<div class="breadcrum">
	<ul class="tri-steps">
		<li class="previous"><div class="text"><a href="<?php echo $this->url(array('module'=>'finalassignment','controller'=>'proposal','action'=>'application', 'step'=>1),'default',true);?>"><?php echo $this->translate("College"); ?></a></div></li>
		<li class="previous"><div class="text"><a href="<?php echo $this->url(array('module'=>'finalassignment','controller'=>'proposal','action'=>'application', 'step'=>2),'default',true);?>"><?php echo $this->translate("Program"); ?></a></div></li>
		<li class="current"><div class="text"><a href="<?php echo $this->url(array('module'=>'finalassignment','controller'=>'proposal','action'=>'application', 'step'=>3),'default',true);?>"><?php echo $this->translate("Branch"); ?></a></div></li>
		<li class="next"><div class="text"><a href="<?php echo $this->url(array('module'=>'finalassignment','controller'=>'proposal','action'=>'application', 'step'=>4),'default',true);?>"><?php echo $this->translate("Majoring"); ?></a></div></li>	
		<li class="next"><div class="text"><a href="<?php echo $this->url(array('module'=>'finalassignment','controller'=>'proposal','action'=>'application', 'step'=>5),'default',true);?>"><?php echo $this->translate("Proposal"); ?></a></div></li> 
		<li class="next"><div class="text"><a href="<?php echo $this->url(array('module'=>'finalassignment','controller'=>'proposal','action'=>'application', 'step'=>6),'default',true);?>"><?php echo $this->translate("Prerequisite"); ?></a></div></li> 
		<li class="last"><div class="text"><a href="<?php echo $this->url(array('module'=>'finalassignment','controller'=>'proposal','action'=>'application', 'step'=>7),'default',true);?>"><?php echo $this->translate("Confirmation"); ?></a></div></li>
	</ul>
	<div class="clear"></div>
</div>
<br />
<form id="form_3" method="post" action="/finalassignment/proposal/application/step/3">
<table class="table" id="result" width="100%">
<tr><td  width="20%"><?php echo $this->translate('Branch')?></td>
	<td><select name="IdBranch">
				<option value="All"><?php echo $this->translate("All");?></option>
				<?php 
				foreach ($this->branchlist as $list):
					$select = "";
					if( isset($this->branch) && $this->branch==$list['key'] ){
						$select = 'selected="selected"';
					}
				?>
					<option value="<?php echo $list['key'];?>" <?php echo $select; ?>><?php echo  $list['value'];?></option>
				<?php 
				endforeach;
				?>
			</select></td>
		</tr>	
</table>
<div class="next_bar">
	<input type="submit" value="<?php echo $this->translate("Next");?>" />
</div>
</form>


<?php 
}else
?>

<!-- STEP 4 -->
<?php
if($this->step == 4){
?>
<!-- Breadcrum -->
<div class="breadcrum">
	<ul class="tri-steps">
		<li class="previous"><div class="text"><a href="<?php echo $this->url(array('module'=>'finalassignment','controller'=>'proposal','action'=>'application', 'step'=>1),'default',true);?>"><?php echo $this->translate("College"); ?></a></div></li>
		<li class="previous"><div class="text"><a href="<?php echo $this->url(array('module'=>'finalassignment','controller'=>'proposal','action'=>'application', 'step'=>2),'default',true);?>"><?php echo $this->translate("Program"); ?></a></div></li>
		<li class="previous"><div class="text"><a href="<?php echo $this->url(array('module'=>'finalassignment','controller'=>'proposal','action'=>'application', 'step'=>3),'default',true);?>"><?php echo $this->translate("Branch"); ?></a></div></li>	
		<li class="current"><div class="text"><a href="<?php echo $this->url(array('module'=>'finalassignment','controller'=>'proposal','action'=>'application', 'step'=>4),'default',true);?>"><?php echo $this->translate("Majoring"); ?></a></div></li>
		<li class="next"><div class="text"><a href="<?php echo $this->url(array('module'=>'finalassignment','controller'=>'proposal','action'=>'application', 'step'=>5),'default',true);?>"><?php echo $this->translate("Proposal"); ?></a></div></li> 
		<li class="next"><div class="text"><a href="<?php echo $this->url(array('module'=>'finalassignment','controller'=>'proposal','action'=>'application', 'step'=>6),'default',true);?>"><?php echo $this->translate("Prerequisite"); ?></a></div></li> 
		<li class="last"><div class="text"><a href="<?php echo $this->url(array('module'=>'finalassignment','controller'=>'proposal','action'=>'application', 'step'=>7),'default',true);?>"><?php echo $this->translate("Confirmation"); ?></a></div></li>
	</ul>
	<div class="clear"></div>
</div>
<br />
<form id="form_4" method="post" action="/finalassignment/proposal/application/step/4">
<table class="table" id="result" width="100%">
<tr><td  width="20%"><?php echo $this->translate('Majoring')?></td>
	<td><select name="IdMajor">
				<option value="All"><?php echo $this->translate("All");?></option>
				<?php 
				foreach ($this->majorlist as $list):
					$select = "";
					if( isset($this->majorlist) && $this->major==$list['key'] ){
						$select = 'selected="selected"';
					}
				?>
					<option value="<?php echo $list['key'];?>" <?php echo $select; ?>><?php echo $list['value'];?></option>
				<?php 
				endforeach;
				?>
			</select></td>
		</tr>	
</table>
<div class="next_bar">
	<input type="submit" value="<?php echo $this->translate("Next");?>" />
</div>
</form>


<?php 
}else
?>


<!-- STEP 5 -->
<?php
if($this->step == 5){
?>
<!-- Breadcrum -->
<div class="breadcrum">
	<ul class="tri-steps">
		<li class="previous"><div class="text"><a href="<?php echo $this->url(array('module'=>'finalassignment','controller'=>'proposal','action'=>'application', 'step'=>1),'default',true);?>"><?php echo $this->translate("College"); ?></a></div></li>
		<li class="previous"><div class="text"><a href="<?php echo $this->url(array('module'=>'finalassignment','controller'=>'proposal','action'=>'application', 'step'=>2),'default',true);?>"><?php echo $this->translate("Program"); ?></a></div></li>
		<li class="previous"><div class="text"><a href="<?php echo $this->url(array('module'=>'finalassignment','controller'=>'proposal','action'=>'application', 'step'=>3),'default',true);?>"><?php echo $this->translate("Branch"); ?></a></div></li>	
		<li class="previous"><div class="text"><a href="<?php echo $this->url(array('module'=>'finalassignment','controller'=>'proposal','action'=>'application', 'step'=>4),'default',true);?>"><?php echo $this->translate("Majoring"); ?></a></div></li>
		<li class="current"><div class="text"><a href="<?php echo $this->url(array('module'=>'finalassignment','controller'=>'proposal','action'=>'application', 'step'=>5),'default',true);?>"><?php echo $this->translate("Proposal"); ?></a></div></li> 
		<li class="next"><div class="text"><a href="<?php echo $this->url(array('module'=>'finalassignment','controller'=>'proposal','action'=>'application', 'step'=>6),'default',true);?>"><?php echo $this->translate("Prerequisite"); ?></a></div></li> 
		<li class="last"><div class="text"><a href="<?php echo $this->url(array('module'=>'finalassignment','controller'=>'proposal','action'=>'application', 'step'=>7),'default',true);?>"><?php echo $this->translate("Confirmation"); ?></a></div></li>
	</ul>
	<div class="clear"></div>
</div>
<br />
<form id="form_5" method="post" action="/finalassignment/proposal/application/step/5">
<input type="hidden" name="idProposal" id="idProposal" value=<?php echo $this->idProposal;?>>
<input type="hidden" name="IdPengaju" id="IdPengaju" value="<?php echo $this->IdPengaju;?>">
<input type="hidden" name="STATUS_PENGAJU" id="STATUS_PENGAJU" value="<?php echo $this->proposedAs;?>">
<?php if ($this->proposal) {
	$titlebahasa=$this->proposal['title_bahasa']; 
	$title=$this->proposal['title'];
	$problem1=$this->proposal['problem1'];
	$problem2=$this->proposal['problem2'];
	$problem3=$this->proposal['problem3'];
	if ($this->proposal['abstrak']!=null)
		$abstrak=$this->proposal['abstrak'];
	else {
		$abstrak='';
		$pabstrak='Please fill abstract';
	}
	$ptitlebahasa='-';
	$ptitle='-';
	$pproblem1='-';
	$pproblem2='-';
	$pproblem3='-';
	$pabstrak='-';
} else {
	$titlebahasa='';
	$title='';
	$problem1='';
	$problem2='';
	$problem3='';
	$abstrak='';
	$ptitlebahasa='Please fill in title in Bahasa';
	$ptitle='Please fill in title in English';
	$pproblem1='Please fill in first problem statement';
	$pproblem2='Please fill in second problem statement if any';
	$pproblem3='Please fill in third problem statement if any';
	$pabstrak='Please fill abstract';
}?>

<table  width="80%" cellpadding="5" cellspacing="2" border="0">
	<tr>	<td width="20%"><?php echo $this->translate("Title in Bahasa");?></td><td>:</td>
			<td> <textarea rows="3" cols="80" id="title_bahasa" name="title_bahasa" placeholder="<?php echo $ptitlebahasa; ?>"><?php echo $this->translate($titlebahasa);?>   
			</textarea></tr> 
	<tr>	<td width="20%"><?php echo $this->translate("Title in English");?></td><td>:</td>
			<td> <textarea rows="3" cols="80" id="title" name="title" placeholder="<?php echo $ptitle; ?>"><?php echo $this->translate($title);?>
			</textarea></tr>
	<tr>	<td width="20%"><?php echo $this->translate("First Problem Statement");?></td><td>:</td>
			<td> <textarea rows="5" cols="80" id="problem1" name="problem1" placeholder="<?php echo $pproblem1; ?>"><?php echo $this->translate($problem1);?>   
			</textarea></tr>
	<tr>	<td width="20%"><?php echo $this->translate("Second Problem Statement");?></td><td>:</td>
			<td> <textarea rows="5" cols="80" id="problem2" name="problem2" placeholder="<?php echo $pproblem2; ?>"><?php echo $this->translate($problem2);?>
			</textarea></tr>
	<tr>	<td width="20%"><?php echo $this->translate("Third Problem Statement");?></td><td>:</td>
			<td> <textarea rows="5" cols="80" id="problem3" name="problem3" placeholder="<?php echo $pproblem3; ?>"><?php echo $this->translate($problem3);?>
			</textarea></tr>
	<tr>	<td width="20%"><?php echo $this->translate("Abstract");?></td><td>:</td>
			<td> <textarea placeholder="<?php echo $pabstrak; ?>" rows="10" cols="80" id=""abstrak"" name="abstrak" ><?php echo $this->translate($abstrak);?>   
			</textarea></tr>
	 
</table>

<div class="next_bar">
	<input type="submit" value="<?php echo $this->translate("Next");?>" />
</div>
</form>

<!-- STEP 6 -->
<?php } else
if($this->step == 6){
?>
<!-- Breadcrum -->
<div class="breadcrum">
	<ul class="tri-steps">
		<li class="previous"><div class="text"><a href="<?php echo $this->url(array('module'=>'finalassignment','controller'=>'proposal','action'=>'application', 'step'=>1),'default',true);?>"><?php echo $this->translate("College"); ?></a></div></li>
		<li class="previous"><div class="text"><a href="<?php echo $this->url(array('module'=>'finalassignment','controller'=>'proposal','action'=>'application', 'step'=>2),'default',true);?>"><?php echo $this->translate("Program"); ?></a></div></li>
		<li class="previous"><div class="text"><a href="<?php echo $this->url(array('module'=>'finalassignment','controller'=>'proposal','action'=>'application', 'step'=>3),'default',true);?>"><?php echo $this->translate("Branch"); ?></a></div></li>	
		<li class="previous"><div class="text"><a href="<?php echo $this->url(array('module'=>'finalassignment','controller'=>'proposal','action'=>'application', 'step'=>4),'default',true);?>"><?php echo $this->translate("Majoring"); ?></a></div></li>
		<li class="previous"><div class="text"><a href="<?php echo $this->url(array('module'=>'finalassignment','controller'=>'proposal','action'=>'application', 'step'=>5),'default',true);?>"><?php echo $this->translate("Proposal"); ?></a></div></li> 
		<li class="current"><div class="text"><a href="<?php echo $this->url(array('module'=>'finalassignment','controller'=>'proposal','action'=>'application', 'step'=>6),'default',true);?>"><?php echo $this->translate("Prerequisite"); ?></a></div></li> 
		<li class="last"><div class="text"><a href="<?php echo $this->url(array('module'=>'finalassignment','controller'=>'proposal','action'=>'application', 'step'=>7),'default',true);?>"><?php echo $this->translate("Confirmation"); ?></a></div></li>
	</ul>
	<div class="clear"></div>
</div>
<br />
<form id="form_6" method="post" action="/finalassignment/proposal/application/step/6">
<fieldset><legend><?php echo $this->translate('Choose Range CGPA as a prerequisite')?></legend>
	<table class="table" id="result" width="100%">
	<tr><td width="20%"><?php echo $this->translate('CGPA Minimum');?></td><td width="5%">:</td><td><input type="text" id="cgpa_min" name="cgpa_min" size=5 value="<?php echo $this->cgpa_min;?>"></td>
	<tr><td><?php echo $this->translate('CGPA Maksimum');?></td><td>:</td><td><input type="text" id="cgpa_max" name="cgpa_max" size=5 value="<?php echo $this->cgpa_max;?>"></td>
	</table>
</fieldset>
<fieldset><legend><?php echo $this->translate('Choose Subjects related to topics as prerequisite');?></legend>
<table class="table" id="result" width="100%">
 
<tr><th><?php echo $this->translate('Subject Name');?></th>
	<th><?php echo $this->translate('Subject Code');?></th>
	
	<th><?php echo $this->translate('Credithours');?></th>
	<th><?php echo $this->translate('Grade Minimum');?></th>
	<th><?php echo $this->translate('Take');?></th>
</tr>
<?php  
	foreach ($this->subject_list as $index=>$items) {
		 
		if (isset($this->subject[$items['IdSubject']])) {
			 
			$grade=$this->subject[$items['IdSubject']]['grade_name'];
			
			$status="checked";
		}
		else {
			$status="";
			$grade="";
		}
	
	?>
  
<tr><td><?php echo $items['BahasaIndonesia'];?></td>
	<input type="hidden" id="SubName[<?php echo $index ?>]" name="SubName[<?php echo $index ?>]" value="<?php echo $items['BahasaIndonesia'];?>" >
	<td align="center"><?php echo $items['SubCode'];?></td>
	<input type="hidden" id="SubCode[<?php echo $index ?>]" name="SubCode[<?php echo $index ?>]" value="<?php echo $items['SubCode'];?>" >
	<td align="center"><?php echo $items['CreditHours'];?></td>
	<td align="center"><input type="text" id="grade[<?php echo $index ?>]" name="grade[<?php echo $index ?>]" size=3 value="<?php echo $grade;?>"></td>
	<td align="center"><input type="checkbox" id="subject[<?php echo $index?>]" name="subject[<?php echo $index?>]" value="<?php echo $items['IdSubject'];?>" <?php echo $status;?>></td>
</tr>
<?php }?>
</table>
</fieldset>
<div class="next_bar">
	<input type="submit" value="<?php echo $this->translate("Next");?>" />
</div>
</form>
 
<!-- STEP 7 -->
<?php } else
if($this->step == 7){
?>
<!-- Breadcrum -->
<div class="breadcrum">
	<ul class="tri-steps">
		<li class="previous"><div class="text"><a href="<?php echo $this->url(array('module'=>'finalassignment','controller'=>'proposal','action'=>'application', 'step'=>1),'default',true);?>"><?php echo $this->translate("College"); ?></a></div></li>
		<li class="previous"><div class="text"><a href="<?php echo $this->url(array('module'=>'finalassignment','controller'=>'proposal','action'=>'application', 'step'=>2),'default',true);?>"><?php echo $this->translate("Program"); ?></a></div></li>
		<li class="previous"><div class="text"><a href="<?php echo $this->url(array('module'=>'finalassignment','controller'=>'proposal','action'=>'application', 'step'=>3),'default',true);?>"><?php echo $this->translate("Branch"); ?></a></div></li>
		<li class="previous"><div class="text"><a href="<?php echo $this->url(array('module'=>'finalassignment','controller'=>'proposal','action'=>'application', 'step'=>4),'default',true);?>"><?php echo $this->translate("Majoring"); ?></a></div></li>	
		<li class="previous"><div class="text"><a href="<?php echo $this->url(array('module'=>'finalassignment','controller'=>'proposal','action'=>'application', 'step'=>5),'default',true);?>"><?php echo $this->translate("Proposal"); ?></a></div></li> 
		<li class="previous"><div class="text"><a href="<?php echo $this->url(array('module'=>'finalassignment','controller'=>'proposal','action'=>'application', 'step'=>6),'default',true);?>"><?php echo $this->translate("Prerequisite"); ?></a></div></li> 
		<li class="last"><div class="text"><a href="<?php echo $this->url(array('module'=>'finalassignment','controller'=>'proposal','action'=>'application', 'step'=>7),'default',true);?>"><?php echo $this->translate("Confirmation"); ?></a></div></li>
	</ul>
	<div class="clear"></div>
</div>
<br />
<form id="form_7" method="post" action="/finalassignment/proposal/application/step/7">
<fieldset><legend><?php echo $this->translate('Proposal')?></legend>
 <input type="hidden" name="idProposal" id="idProposal" value=<?php echo $this->idProposal;?>>
<input type="hidden" name="IdPengaju" id="IdPengaju" value="<?php echo $this->IdPengaju;?>">
<input type="hidden" name="STATUS_PENGAJU" id="STATUS_PENGAJU" value="<?php echo $this->proposedAs;?>">
<?php if (count($this->proposal)>0) {
	$titlebahasa=$this->proposal['title_bahasa'];
	$title=$this->proposal['title'];
	$problem1=$this->proposal['problem1'];
	$problem2=$this->proposal['problem2'];
	$problem3=$this->proposal['problem3'];
	$abstrak=$this->proposal['abstrak'];
	$cgpa_min=$this->proposal['cgpa_min'];
	$cgpa_max=$this->proposal['cgpa_max'];
} ?>
<table  width="80%" cellpadding="5" cellspacing="2" border="0">
	<tr>	<td width="20%"><?php echo $this->translate("Title in Bahasa");?></td><td>:</td>
			<td> <?php echo $this->translate($titlebahasa);?>   
			</tr> 
	<tr>	<td width="20%"><?php echo $this->translate("Title in English");?></td><td>:</td>
			<td>   <?php echo $this->translate($title);?>
			</tr>
	<tr>	<td width="20%"><?php echo $this->translate("First Problem Statement");?></td><td>:</td>
			<td>  <?php echo $this->translate($problem1);?>   
			</tr>
	<tr>	<td width="20%"><?php echo $this->translate("Second Problem Statement");?></td><td>:</td>
			<td>     <?php echo $this->translate($problem2);?>
			 </tr>
	<tr>	<td width="20%"><?php echo $this->translate("Third Problem Statement");?></td><td>:</td>
			<td>    <?php echo $this->translate($problem3);?>
			</tr>
	<tr>	<td width="20%"><?php echo $this->translate("Abstract");?></td><td>:</td>
			<td>   <?php echo $this->translate($abstrak);?>   
			 </tr>
 	<tr>	<td width="20%"><?php echo $this->translate("CGPA Prerequisite");?></td><td>:</td>
			 <td>   <?php echo "CGPA Minimum= ".$this->translate($cgpa_min)." - CGPA Maximum= ".  $this->translate($cgpa_max);?>  
			 </tr>
	 <tr>	<td width="20%"><?php echo $this->translate("Subject Prerequisite");?></td><td>:</td>
			<td> 
			<table class="table" with="100%">
			<tr><th><?php echo $this->translate('Subject Code'); ?></th>
				<th><?php echo $this->translate('Subject Name'); ?></th>
				<th><?php echo $this->translate('Minimum Grade'); ?></th>
			</tr>
			<?php foreach ($this->subject as $item) {?>
				<tr><td align="center"><?php echo $item['SubCode']; ?></td>
				<td><?php echo $item['SubjectName']; ?></td>
				<td align="center"><?php echo $item['grade_name']; ?></td>
			</tr>
			<?php }?>
			</table> 
			 </tr>
</table>
 
<div class="next_bar">
	<input type="submit" value="<?php echo $this->translate("Save");?>" />
</div>
</fieldset>
</form>

<?php 
} ?>