<script>
dojo.addOnLoad(function(){
	dijit.byId('field3').focus();
	dijit.byId('field5').set('value','');
	dijit.byId('field5').set('placeHolder','Select');		
	});
</script>

	<fieldset>
	 <legend><?php echo $this->translate("Staff").' '.$this->translate("Master").' '.$this->translate("Search");?></legend>
                    <form action="<?php echo $this->baseUrl();?>/finalassignment/proposal/index-staff/search/1" method="POST">
                            <table width="100%">
                            	<tr>
                                    <td ><?php echo $this->translate("Full").' '.$this->translate("Name");?></td>
                                    <td colspan="3"><?php echo $this->lobjform->field4;?></td>
                                </tr>
                                <tr>
                                    <td ><?php echo $this->translate("First").' '.$this->translate("Name");?></td>
                                    <td ><?php echo $this->lobjform->field2;?></td>
                                    <td ><?php echo $this->translate("Last").' '.$this->translate("Name");?></td>
                                    <td ><?php echo $this->lobjform->field3;?></td>
                                </tr>
                                <tr>
                                	<td ><?php echo $this->translate("Designation");?></td>
                                    <td ><?php echo $this->lobjform->field5;?></td>
                                    <td ><?php echo $this->translate("Email");?></td>
                                    <td ><?php echo $this->lobjform->field6;?></td>
                                </tr>
                                <tr>
                                    <td ><?php echo $this->translate("Active");?></td>
                                    <td ><?php echo $this->lobjform->field7;?></td>
                                </tr>
                                <tr>
                                <td align = "center" colspan = "4">

											<?php echo $this->lobjform->Search;?>
											<input type='button' class="NormalBtn" dojotype="dijit.form.Button" label = "<?php echo $this->translate('Add')?>" value='click' onclick="window.location.href='<?php echo $this->url(array('module'=>'generalsetup','controller'=>'staffmaster', 'action'=>'newstaffmaster'),'default',true);?>';" />
											<?php echo $this->lobjform->Clear;?>
								</td>
							    </tr>
                        </table>
                    </form>	
    </fieldset> 
    <br/>
	<fieldset>
		<table class="table" width="100%" cellpadding="5" cellspacing="1">
	    	<tr>
	        	<th><?php echo $this->translate("Staff").' '.$this->translate("Name");?></th>
	       	    <th><?php echo $this->translate("Email");?></th>
	    	</tr>
	        <?php if (count($this->paginator)): ?>
	        <?php foreach ($this->paginator as $lobjstaff ): ?>
	  		<tr style="background-color:<?php echo $this->cycle(array("#F0F0F0","#FFFFFF"))->next()?>">
	        	<td><a href="<?php echo $this->baseUrl();?>/finalassignment/proposal/staff-proposal-list/id/<?php echo $this->escape($lobjstaff['IdStaff']);?>" ><?php print_r($this->escape($lobjstaff['FullName']));?></a></td>
	        	<td><?php echo $this->escape($lobjstaff['Email']);?></div></td>
	            <?php endforeach; ?>
	            <?php endif; ?> 
			</tr>
			<tr>
	        	<td colspan="8" align="right"><div class="pagination"><?php echo $this->paginationControl($this->lobjpaginator,'Sliding',
	                                    '/partials/my_pagination_control.phtml'); ?></div></td>
   			</tr>
		</table>
	</fieldset>