 
<script>
	$(function(){
		
		$('#check_all').change(function(){
			if( $(this).prop('checked') ){
				$('.check').prop('checked',true);
			}else{
				$('.check').prop('checked',false);
			}
		});
		
	});


	function cetak(){
		window.location="<?php echo $this->url(array('module'=>'finalassignment','controller'=>'proposal','action'=>'student-application-view','proposedby'=>$this->proposal['IdStudentRegistration'],'idtaapplication'=>$this->proposal['IdTAApplication']), 'default', true);?>";
	}
	function cetakpdf(){
		window.location="<?php echo $this->url(array('module'=>'finalassignment','controller'=>'proposal','action'=>'student-application-pdf','proposedby'=>$this->proposal['IdStudentRegistration'],'idtaapplication'=>$this->proposal['IdTAApplication']), 'default', true);?>";
	}
</script>



<div class="message toolbar">
	<h2><?php echo $this->title; ?></h2>
	<div class="toolbar-button">
		<ul>
			 <li>
			<a href="#" onclick="cetak();">
				<span class='print'></span>
				Print Screen
			</a>
			
		</li>
		 <li>
			<a href="#" onclick="cetakpdf();">
				<span class='print'></span>
				Print Pdf
			</a>
			
		</li>
		</ul>
	</div>
</div>
<?php if(isset($this->noticeMessage)){?>
<div class="message notice"><strong><?php echo $this->noticeMessage;?></strong>.</div>
<br />
<?php }?>
<?php if(isset($this->noticeSuccess)){?>
<div class="message success"><strong><?php echo $this->noticeSuccess;?></strong>.</div>
<br />
<?php }?>
<?php if(isset($this->noticeError)){?>
<div class="message error"><strong><?php echo $this->noticeError;?></strong>.</div>

<br /> 
<?php }?>
<br />
<fieldset><legend ><?php echo $this->translate('Student Info');?></legend>
<table>
<tr><td><?php echo $this->translate('NIM');?></td><td>:</td><td><?php echo $this->student['registrationId'];?></td>
<tr><td><?php echo $this->translate('Name');?></td><td>:</td><td><?php echo $this->student['appl_fname'].' '.$this->student['appl_mname'].' '.$this->student['appl_lname'];?></td>
<tr><td><?php echo $this->translate('Majoring');?></td><td>:</td><td><?php echo $this->student['majoring'];?></td>
<tr><td><?php echo $this->translate('Credit Hours Transcript/All');?></td><td>:</td><td><?php echo $this->student['credithours'].'/'.$this->student['credithoursall'];?></td>
<tr><td><?php echo $this->translate('CGPA Transcript/All');?></td><td>:</td><td><?php echo $this->student['cgpa'].'/'.$this->student['cgpaall'];?></td>
<tr><td><?php echo $this->translate('Prerequisite');?></td><td>:</td>
		<td><table class="table" width="100%">
		<tr>
			<th><?php echo $this->translate('Prerequisite Type');?></th>
			<th><?php echo $this->translate('Subject Name');?></th>
			<th><?php echo $this->translate('Minimum Value');?></th>
			<th><?php echo $this->translate('Grade');?></th>
			<th><?php echo $this->translate('Status');?></th>
		</tr>
		<?php if (count($this->prerequisites) >0 ) {
				if ($this->prerequisites[0]['completed']!='1') {
			    if ($this->prerequisites[0]['completed']=='0') {
				 	$status='Ok';
					foreach ($this->prerequisites as $item) {
					if ($item['Ok']=='X') $status="X";
					if ($item['PrerequisiteType']=='2') {
						$type='Credit Hours';
						$item['SubjectName']='-';
						$item['Grade']='-';
					}
					else if ($item['PrerequisiteType']=='3') $type='Co-Prerequisite';
					else  $type='Subject';
		?>
			<tr><td><?php echo $type;?></td>
			<td><?php echo $item['SubjectName'];?></td>
			<td align="center"><?php echo $item['PrerequisiteGrade'];?> </td>
			<td align="center"><?php echo $item['Grade'];?> </td>
			<td align="center"><?php echo $item['Ok'];?> </td>
			</tr>
		<?php 	} 	
		 
			 	
				if ($status=='X') {
					$disable="disabled";?>
				<tr ><td bgcolor="red" colspan="5"><strong><?php echo $this->translate('Prerequisite is not fullfilled, so prohibit to take this application')?></strong></td> 
			<?php 
			}
		}  else { foreach ($this->prerequisites as $item) { 
					if ($item['Ok']=='X') $status="X";
					if ($item['PrerequisiteType']=='2') {
						$type='Credit Hours';
						$item['SubjectName']='-';
						$item['Grade']='-';
					}
					else if ($item['PrerequisiteType']=='3') $type='Co-Prerequisite';
					else  $type='Subject';
			?>
			<tr><td><?php echo $type;?></td>
			<td><?php echo $item['SubjectName'];?></td>
			<td align="center"><?php echo $item['PrerequisiteGrade'];?> </td>
			<td align="center"><?php echo $item['Grade'];?> </td>
			<td align="center"><?php echo $item['Ok'];?> </td>
			</tr>
		 <?php }
			}
		} else { ?>
		
			<tr><td colspan="5"><?php echo $this->prerequisites[0]['Ok'];?></td>
			</tr>

		<?php 
		} ?>
		<?php 
	} else {?>
		<tr><td colspan="5"><?php echo $this->translate("No Prerequisite");?></tr>
		<?php } ?>
		</table></td>
</tr>
</table>

</fieldset>
<br />
<?php if ($this->prerequisites[0]['completed']=='1') {
if ($this->approved=="0") {?>
<fieldset><legend><?php echo $this->translate('Summary of Proposal');?></legend>
<form id="form" method="post" action="/finalassignment/proposal/student-application">
<input type="hidden" id="IdFlowMain" name="IdFlowMain" value="<?php  echo $this->idflowmain;?>">

<input type="hidden" name="IdProgram" id="IdProgram" value="<?php echo $this->student['IdProgram'];?>">
<input type="hidden" name="IdMajor" id="IdMajor" value="<?php echo $this->student['IdProgramMajoring'];?>">
<input type="hidden" name="IdBranch" id="IdBranch" value="<?php echo $this->student['IdBranch'];?>">
<input type="hidden" name="STATUS_PENGAJU" id="STATUS_PENGAJU" value="Student">
<?php 
if ($this->proposal) {
	 
	$idpengaju=$this->proposal['IdPengaju'];
	$idta=$this->proposal['IdTA'];
	$titlebahasa=$this->proposal['title_bahasa']; 
	$title=$this->proposal['title'];
	$problem1=$this->proposal['problem1'];
	$problem2=$this->proposal['problem2'];
	$problem3=$this->proposal['problem3'];
	$abstrak=$this->proposal['abstrak'];
	$ptitlebahasa='-';
	$ptitle='-';
	$pproblem1='-';
	$pproblem2='-';
	$pproblem3='-';
	$pabstrak='-';
	if ($this->proposal['STS_ACC']=='') $status=$this->translate("Not Approved Yet");
	else $status=$this->translate("Approved");
} else {
	 
	$idpengaju=$this->pengaju;
	$idta=null;
	$titlebahasa='';
	$title='';
	$problem1='';
	$problem2='';
	$problem3='';
	$abstrak='';
	$ptitlebahasa='Please fill in title in Bahasa';
	$ptitle='Please fill in title in English';
	$pproblem1='Please fill in first problem statement';
	$pproblem2='Please fill in second problem statement if any';
	$pproblem3='Please fill in third problem statement if any';
	$pabstrak='Please fill abstract';
	$status=$this->translate("No Status");
}?>
<input type="hidden" name="IdPengaju" id="IdPengaju" value="<?php echo $idpengaju;?>">
<input type="hidden" name="idProposal" id="idProposal" value="<?php echo $idta ;?>">
<input type="hidden" name="IdTAApplication" id="IdTAApplication" value="<?php echo $this->proposal['IdTAApplication'];?>">
<table class="table_content" >
	<tr>	<td width="25%"><?php echo $this->translate("Title in Bahasa");?></td><td>:</td>
			<td> <textarea rows="3" cols="70" id="title_bahasa" name="title_bahasa" align="left"><?php echo $titlebahasa;?>   
			</textarea></tr> 
	<tr>	<td width="20%"><?php echo $this->translate("Title in English");?></td><td>:</td>
			<td> <textarea rows="3" cols="70" id="title" name="title" align="left"><?php echo $title;?>
			</textarea></tr>
	<tr>	<td width="20%"><?php echo $this->translate("First Problem Statement");?></td><td>:</td>
			<td> <textarea rows="5" cols="70" id="problem1" name="problem1" align="left"><?php echo $problem1;?>   
			</textarea></tr>
	<tr>	<td width="20%"><?php echo $this->translate("Second Problem Statement");?></td><td>:</td>
			<td> <textarea rows="5" cols="70" id="problem2" name="problem2" align="left"><?php echo $problem2;?>
			</textarea></tr>
	<tr>	<td width="20%"><?php echo $this->translate("Third Problem Statement");?></td><td>:</td>
			<td> <textarea rows="5" cols="70" id="problem3" name="problem3" align="left"><?php echo $problem3;?>
			</textarea></tr>
	<tr>	<td width="20%"><?php echo $this->translate("Abstract");?></td><td>:</td>
			<td> <textarea rows="10" cols="70" id=""abstrak"" name="abstrak" align="left"><?php echo $abstrak;?>   
			</textarea></tr>
	
</table>
<h2><?php echo $this->translate('Related Subjects');?></h2>
<table class="table" width="100%" cellpadding="5" cellspacing="0" border="0">
<tr><th><?php echo $this->translate('Subject Code')?></th>
<th><?php echo $this->translate('Subject Name')?></th>
<th><?php echo $this->translate('Credit Hours')?></th>
<th><?php echo $this->translate('Grade')?></th>
<th><?php echo $this->translate('Take')?></th>
</tr>
<?php $index=0;
	foreach ($this->transkrip as $cat) {
	//  echo var_dump($cat);exit;
		
		foreach ($cat['subjects'] as $item) {
			$index++;
			$status="";
			foreach ($this->subject_list as $subject) { 
				if ($subject['IdSubject']==$item['IdSubject']) {
					$status="1";
				}
		 	}
		 	
			if ($status=="1") $status='checked';?>
			<tr><td><?php echo $item['ShortName'];?></td>
			<td><?php echo $item['NamaSubjek'];?></td>
			<td><?php echo $item['CreditHours'];?></td>
			<td><?php echo $item['grade_name'];?></td>
			<input type="hidden" id="grade[<?php echo $index?>]" name="grade[<?php echo $index?>]" value="<?php echo $item['grade_name'];?>">
			<td align="center"><input type="checkbox" id="subject[<?php echo $index?>]" name="subject[<?php echo $index?>]" value="<?php echo $item['IdSubject'];?>" <?php echo $status;?>></td>
			</tr>
	
<?php }
}?>
<tr><td colspan="5" align="center"  bgcolor="tosca" ><input type="submit" name="submit" value="<?php echo $this->translate('Save');?>" <?php echo $disable;?>></td>
</tr>
</table>

</form>
<?php } else {?>
<fieldset><legend><?php echo $this->translate('Proposal Info')?></legend>
	<table class="table_content" width="100%" cellpadding="5" cellspacing="0" border="0">
	<tr>	<td width="25%"><?php echo $this->translate("Title in Bahasa");?></td><td>:</td>
			<td><?php echo $this->proposal['title_bahasa']; ?></td>  </tr> 
	<tr>	<td width="20%"><?php echo $this->translate("Title in English");?></td><td>:</td>
			<td> <?php echo $this->proposal['title']; ?></td></tr>
	<tr>	<td width="20%"><?php echo $this->translate("First Problem Statement");?></td><td>:</td>
			<td> <?php echo $this->proposal['problem1']; ?></td></tr>
	<tr>	<td width="20%"><?php echo $this->translate("Second Problem Statement");?></td><td>:</td>
			<td> <?php echo $this->proposal['problem2']; ?></td></tr>
	<tr>	<td width="20%"><?php echo $this->translate("Third Problem Statement");?></td><td>:</td>
			<td> <?php echo $this->proposal['problem3']; ?></td></tr>
	<tr>	<td width="20%"><?php echo $this->translate("Abstract");?></td><td>:</td>
			<td> <?php echo $this->proposal['abstrak']; ?></td></tr>
	 
</table>
<br>
<?php echo $this->translate('Subject Related');?>
<table class="table_content" width="100%">
		<tr>
			<th><?php echo $this->translate('Subject Code');?></th>
			<th><?php echo $this->translate('Subject Name');?></th>
			<th><?php echo $this->translate('Credit Hours');?></th>
			<th><?php echo $this->translate('Minimum Grade');?></th> 
			<th><?php echo $this->translate('Grade');?></th> 
		</tr>
		<?php if (count($this->subject_list) >0 ) {
				foreach ($this->subject_list as $item) {
					 
		?>
			<tr><td><?php echo $item['ShortName'];?></td>
			<td><?php echo $item['SubjectName'];?></td>
			<td align="center"><?php echo $item['CreditHours'];?> </td>
			<td align="center"><?php echo $item['Grade_min'];?> </td>
			<td align="center"><?php echo $item['Grade_name'];?> </td> 
			</tr>
		<?php 	}
		
				
			if ($this->subject_list=='0') {
				$disable="disabled";?>
				<tr colspan="3"><td bgcolor="red"><strong><?php echo $this->translate('Prohibit to take this application')?></strong></td> 
			<?php 
			}
		}  else { ?>
			<tr><td><?php echo $this->translate("No subject related to");?></tr>
		<?php } ?>
		
		</table>  
<?php }?>
</fieldset>
<br />

<fieldset><legend><?php echo $this->translate('Status of Process');?></legend>
<table class="table" width="100%" cellpadding="5" cellspacing="0" border="0">
<tr>
	<th><?php echo $this->translate('Name of Process');?></th>
	<th><?php echo $this->translate('Authority of');?></th>
	<th><?php echo $this->translate('PIC');?></th>
	<th><?php echo $this->translate('Status of Process');?></th>
	<th><?php echo $this->translate('Date of entry');?></th>
	<th><?php echo $this->translate('Latest Date of Approval');?></th>
	<th><?php echo $this->translate('Date of Approval');?></th>
	<th><?php echo $this->translate('Documents');?></th>
</tr>
<?php  if ($this->process_status) {
	foreach ($this->process_status as $status) {
		if ($status['ApprovalStatus']==0) 
			$statusApp="Waiting for Approval";
		else if ($status['ApprovalStatus']==1) 
			$statusApp="Approved";
		else if ($status['ApprovalStatus']==2) 
			$statusApp="Pending";
		else  if ($status['ApprovalStatus']==3) 
			$statusApp="Rejected";
		?>
	<tr>
	<td><?php echo $status['ProcessName'];?></td>
	<td><?php echo $status['StaffAs'];?></td>
	<td><?php echo $status['FullName'];?></td>
	<td><?php echo $this->translate($statusApp);?></td>
	<td><?php echo $status['dt_entry'];?></td>
	<td><?php echo $status['dt_latest'];?></td>
	<td><?php echo $status['dt_Approved'];?></td>
	<?php if (isset($status['doc_url']) && $status['doc_url']!='') {?>
		<td><?php echo 'download document';?></td>
	<?php } else  {?>
		<td><?php echo $this->translate('no document');?></td>
	<?php }?>
</tr>
<?php }
} else echo '<tr><td> No Status of Process </td></tr>'?>
 
 
</table>
</fieldset>

<?php }?>