<script>
  
</script>
  
<div class="message toolbar">
	<h2><?php echo $this->title; ?></h2>
	<div class="toolbar-button">
		 
		<ul>
			 
		</ul>
	 </div>
</div>
<br />

<fieldset>
	<legend>Student Information</legend>
	<table>
		<tr>
			<td><?php echo $this->translate('Name');?></td>
			<td>:</td>
			<td>
				<?php echo $this->profile['appl_fname']!=null?$this->profile['appl_fname']." ":""; ?>
				<?php echo $this->profile['appl_mname']!=null?$this->profile['appl_mname']." ":""; ?>
				<?php echo $this->profile['appl_lname']!=null?$this->profile['appl_lname']." ":""; ?>
			</td>
		</tr>
		<tr>
			<td><?php echo $this->translate('Email');?></td>
			<td>:</td>
			<td><?php echo $this->profile['appl_email']?></td>
		</tr>
		<tr>
			<td><?php echo $this->translate('NIM');?></td>
			<td>:</td>
			<td><?php echo $this->registration['registrationId']?></td>
		</tr>
		 
		<tr>
			<td><?php echo $this->translate('Program');?></td>
			<td>:</td>
			<td><?php echo $this->registration['ProgramName']?></td>
		</tr>
		<tr>
			<td><?php echo $this->translate('Intake');?></td>
			<td>:</td>
			<td><?php echo $this->registration['IntakeDesc']?></td>
		</tr>
		
	</table>
</fieldset>
<?php foreach ($this->activity as $act) {
	$bundledetail=$act['bundledetail'];
	
?>
<fieldset><legend><?php echo $this->translate('Invoice Detail')?></legend>
	<form name="formDetail" method="post">
	<input type="hidden" name="IdApplication" value="<?php echo $this->registration['IdApplication'] ?>">
	<input type="hidden" name="IdStudentRegistration" value="<?php echo $this->registration['IdStudentRegistration'] ?>">
	<input type="hidden" name="transaction_id" value="<?php echo $this->registration['transaction_id'] ?>">
	<input type="hidden" name="idinvoice" value="<?php echo $act['idinvoice']; ?>">
	<input type="hidden" name="idsemester" value="<?php echo $act['IdSemesterMaster'] ?>">
	<input type="hidden" name="idacadyear" value="<?php echo $act['idacadyear'] ?>">
	<input type="hidden" name="description" value="<?php echo $act['bundle']['bundlename'].' '.$act['SemesterMainName'] ?>">
	<input type="hidden" name="IdCollege" value="<?php echo $this->program['IdCollege']?>">
	<input type="hidden" name="ProgramCode" value="<?php echo $this->program['ProgramCode']?>">
	<input type="hidden" name="fs_id" value="<?php echo $this->fee_structure['fs_id'] ?>">
	<input type="hidden" name="id" value="<?php echo $act['id'] ?>">
	<input type="hidden" name="idactivity" value="<?php echo $act['idActivity'] ?>">

	
	<table class="table">
		<tr>
			<td><?php echo $this->translate('Payment Name');?></td>
			<td>:</td>
			<td>
				 <?php echo $act['bundle']['bundlename']?>
			</td>
		</tr>
		<tr>
			<td><?php echo $this->translate('Semester');?></td>
			<td>:</td>
			<td><?php echo $act['SemesterMainName']?></td>
		</tr>
		<tr>
			<td><?php echo $this->translate('Level');?></td>
			<td>:</td>
			<td><?php echo $act['level']?></td>
		</tr>
	</table>
	<br><br>
	<?php if ($bundledetail!=array()) {?>
	<input type="hidden" name="payment">
	<table class="table">
		<tr>
			<th><?php echo $this->translate('No');?></th>
			<th><?php echo $this->translate('Component Name');?></th>
			<th><?php echo $this->translate('Amount');?></th>
			<th><?php echo $this->translate('Discount');?></th>
			<th><?php echo $this->translate('Net Amount');?></th> 
			
		</tr>
		<?php $i=1;$total=0;
			foreach ($bundledetail as $item) {
				$fee=$item['fee'];
				$total=$total+$fee['amount'];
				if ($i%2==0) $cls="shade";else $cls="";
			?>
			<input type="hidden" name="item[<?php echo $item['fi_id']?>]" value="<?php echo $fee['amount'];?>">
		<tr <?php echo $cls;?>>
			<td><?php echo $i;?></td>
			<td><?php echo $item['fi_name_bahasa'];?></td>
			<td align="right"><?php 
					$subtotal=$fee['amount'];
					echo $fee['amount'];?>
			</td> 
			<td>
			<?php 
				$totaldisc=0;
				if (isset($item['discount'])) {
				?><ul><?php 
					
					foreach ($item['discount'] as $discount) {
						$msg='';
						if ($discount['percentage']>0) {
							$discamount=$fee['amount']*$discount['percentage']/100;
							$msg= '('.$discount['percentage'].' %)';
						}else $discamount=$discount['amount'];
				?>
					<li><input type="hidden" name="discount[<?php echo $discount['id_dm'] ?>][<?php echo $item['fi_id']?>]" value="<?php echo $discamount;?>">
		
					<?php echo $discount['type'].' = '.$discamount.' '.$msg?></li>	
			<?php 		$totaldisc=$totaldisc+$discamount;
						//$total=$total-$discamount;
					} ?>
			</ul><?php 
				} else echo $totaldisc;?></td>
			<td align="right"><?php if (($subtotal-$totaldisc)>0) echo $subtotal-$totaldisc; else echo "0";?></td>
		</tr>
		<?php $i++;
			}?>
		<input type="hidden" name="totalamount" value="<?php echo $total?>">
		<input type="hidden" name="discountamount" value="<?php if (($total-$totaldisc)>0) echo $totaldisc; else echo $total?>">
		<tr>
			<th colspan="4"><?php echo $this->translate('Total');?></th>
			<th align="right"><?php if (($total-$totaldisc)>0) echo $total-$totaldisc; else echo "0";?></th>
		</tr>
		<?php 
		//echo var_dump($this->invoice);
		if (count($act['invoice'])>0) {
			$invoice=$act['invoice'];
			?>
			<tr>
			<th colspan="4" align="right"><?php echo $this->translate('Virtual Account');?></th>
			<th><?php echo $invoice['va'];?></th>
			
		</tr>
		<tr>
			<th colspan="4" align="right"><?php echo $this->translate('Expired Date');?></th>
			<th><?php  if ($invoice['va_expired_dt']!='') echo date('d-m-Y H:s:i',strtotime($invoice['va_expired_dt']));?></th>
			
		</tr>
		<tr>
			<th colspan="4" align="right"><?php echo $this->translate('Payment Status');?></th>
			<th><?php  if ($invoice['status_va']!='') echo $invoice['status_va']; else echo "Belum Dibayar";?></th>
			
		</tr>
			<?php 
		}?>
	</table>
	<br>
	<?php if ((count($act['invoice'])==0 || $act['invoice']['va']=='') && count($act['invoicerest'])==0) { ?>
	<input type="checkbox" name="agree" > Saya memahami jumlah total dan rincian pembayaran ini, dan akan melakukan pembayaran sesuai dengan ketentuan yang berlaku
	<br>
	<input type="submit" name="submit" value="Buat Virtual Account Pembayaran">
	<?php } 
	}
	if (count($act['invoicerest']) >0) {
		$invoicerest=$act['invoicerest'];?>
	<br><h2>Kekurangan/Kelebihan Pembayaran</h2><br>
	<input type="hidden" name="restpayment">
	<table class="table">
		<tr>
			<th><?php echo $this->translate('No');?></th>
			<th><?php echo $this->translate('Component Name');?></th>
			<th><?php echo $this->translate('Amount');?></th> 
			<th><?php echo $this->translate('Remark');?></th> 
			
		</tr>
		<?php $i=1;$total=0;$totalneg=0;
			foreach ($invoicerest as $fiid=>$item) {
				//$fee=$item['fee'];
	 		?>
			<?php if ($item['amount']>0) {?>
				<input type="hidden" name="itemrestpos[<?php echo $fiid?>]" value="<?php echo $item['amount'];?>">
			<?php $total=$total+$item['amount']; } else {?>
				<input type="hidden" name="itemrestneg[<?php echo $fiid?>]" value="<?php echo $item['amount'];?>">
			<?php $totalneg=$totalneg+$item['amount'];}?>
		<tr>
			<td><?php echo $i;?></td>
			<td><?php echo $item['fi_name_bahasa'];?></td>
			<td><?php echo $item['amount'];?></td> 
			<td><?php if ($item['amount']>0) {
						echo $this->translate('Kekurangan Pembayaran');
					 
			} else {
				echo $this->translate('Kelebihan Pembayaran');
			}
			?></td> 
			
		</tr>
		<?php $i++;
			}?>
		<input type="hidden" name="totalamountpos" value="<?php echo $total?>">
		<input type="hidden" name="totalamountneg" value="<?php echo $totalneg?>">
		<?php if ($total>0) {?><tr>
			<th colspan="2"><?php echo $this->translate('Total Additonal');?></th>
			<th><?php echo $total;?></th>
		</tr>
		<?php }
		if ($totalneg<0) {?>
		<tr>
			<th colspan="2"><?php echo $this->translate('Total Addvance');?></th>
			<th><?php echo $totalneg;?></th>
		</tr>
		<?php }?>
		 
	</table>
	<br> 
	<input type="checkbox" name="agree" > Saya memahami jumlah total dan rincian pembayaran ini, dan akan melakukan pembayaran sesuai dengan ketentuan yang berlaku
	<br>
		<?php  if (($total + $totalneg )>0) {?>
			<input type="submit" name="submit" value="Buat Virtual Account Pembayaran">
	
		<?php } else {?>
			<input type="submit" name="submit" value="Pindahkan Ke Tabungan">
	
		<?php }?>
	 <?php }?>
</form>
</fieldset> 
 <?php }?>
