<script type="text/javascript">
	function del(){
		var id = $('input[name=venue_id]:checked').val();

		if(!id){
			alert('Please select any venue first');
		}else{
			if(confirm('Are you sure to delete this venue ?')){
				window.location = "<?php echo $this->url(array('module'=>'general-setup','controller'=>'venue', 'action'=>'delete-branch'),'default',true); ?>/id/"+id;
			}
		}
	}
	
	function add(){
		window.location="<?php echo $this->url(array('module'=>'general-setup','controller'=>'venue', 'action'=>'add-branch', 'id'=>$this->id),'default',true);?>";
	}

	function edit(){
		var id = $('input[name=venue_id]:checked').val();

		if(!id){
			alert('Please select any venue first');
		}else{
			window.location="<?php echo $this->url(array('module'=>'general-setup','controller'=>'venue', 'action'=>'edit-branch'),'default',true);?>/id/"+id;
		}
	}

</script>

<div class="message toolbar">
	<h2><?php echo $this->title; ?></h2>
	<div class="toolbar-button">
		<ul>
			<li>
				<a href="#" onclick="javascript:add();">
					<span class='add'></span>
					Add
				</a>
			</li>
			<li>
				<a href="#" onclick="javascript:edit()">
					<span class='edit'></span>
					Edit
				</a>
			</li>
			<li>
				<a href="#" onclick="javascript:del()">
					<span class='delete'></span>
					Delete
				</a>
			</li>
			<li class="divider"></li>
			<li>
				<a href="<?php echo $this->url(array('module'=>'general-setup','controller'=>'venue', 'action'=>'index'),'default',true);?>" >
					<span class='back'></span>
					Back
				</a>
			</li>
			<li>
				<a href="#" >
					<span class='info'></span>
					Info
				</a>
			</li>
		</ul>
	</div>
</div>
<br />
	
<table class="table2" width="400px" cellpadding="5" cellspacing="2">
	<tr>
		<th width="100px">Branch Name</th>
		<td><?php echo $this->branch['name'];?></td>
	</tr>
	<tr>
		<th>Branch Code</th>
		<td><?php echo $this->branch['code'];?></td>
	</tr>
</table>	
<br />

<?php 
	echo $this->paginationControl($this->paginator,'Sliding','paginationTop.phtml');
?>
<table class="table" width="100%" cellpadding="5" cellspacing="0" border="0">
	<tr>
		<th width="25px">&nbsp;</th>
		<th>Venue</th>
		<th width="150px">Type</th>
		<th width="50px">Capacity</th>
	</tr>
	
	<?php 
	$i=0;
	foreach ($this->paginator as $entry): 
	?>
	<tr <?php echo $i%2==0?"class='shade'":""; ?>>
		<td>
			<input type="radio" name="venue_id" value="<?php echo $entry['id']; ?>">
		</td>
		<td><?php echo $entry['name']; ?></td>
		<td><?php echo $entry['venue_type_name']; ?></td>
		<td align="center"><?php echo $entry['capacity']; ?></td>
	</tr>
	<?php 
	$i++;
	endforeach 
	?>

</table>

<?php 

	echo $this->paginationControl($this->paginator,'Sliding','paginationBottom.phtml');
?>