<style type="text/css">
	table td ul{
		padding: 0 0 0 10px;
		margin: 0;	
	}
}
</style>

<table class="table6" width="500px" cellspacing="0" cellpadding="5" border="0">
	<tr>
		<td width="120px">Exam Center</td>
		<td width="5px">:</td>
		<td><?php echo $this->schedule['exam_center_name']; ?></td>
	</tr>
	<tr>
		<td valign="top">Course</td>
		<td valign="top">:</td>
		<td>
			<ul>
			<?php 
				foreach ($this->course as $course){
					echo "<li>".$course['course_name']."</li>";
				}
			?>
			</ul>
		</td>
	</tr>
	<tr>
		<td>Date</td>
		<td>:</td>
		<td><?php echo date('D jS F Y',strtotime($this->schedule['exam_date'])); ?></td>
	</tr>
	<tr>
		<td>Time</td>
		<td>:</td>
		<td><?php echo date('g:ia', strtotime($this->schedule['exam_time_start']) ); ?> - <?php echo date('g:ia', strtotime($this->schedule['exam_time_end']) ); ?></td>
	</tr>
	<tr>
		<td valign="top">Venue</td>
		<td valign="top">:</td>
		<td>
			<ul>
			<?php 
				foreach ($this->venue as $venue){
					echo "<li>".$venue['venue_name']." capacity:".$venue['venue_capacity']."</li>";
				}
			?>
			</ul>
		</td>
	</tr>
</table>
	