<?php
/*
 *  @author Suliana
 *  @created May 16, 2011
 */
?>


<div align="center" style="background:#fff; height:30px;">
	<ul class="stepsmenu">
		<li class="first"><a href="<?php echo $this->url(array('module'=>'application','controller'=>'education-level','action'=>'index'),'default',true) ?>"><?php echo $this->translate("Education Level"); ?></a></li>
		<li class="second"><a href="<?php echo $this->url(array('module'=>'application','controller'=>'qualification-item','action'=>'index'),'default',true) ?>"><?php echo $this->translate("Qualification Item"); ?></a></li>
	    <li class="third"><a href="<?php echo $this->url(array('module'=>'application','controller'=>'entry-requirement','action'=>'index'),'default',true) ?>"><?php echo $this->translate("Entry Requirement"); ?></a></li>
	</ul>
</div>