<div align="center" style="background:#fff; height:30px;">
	<ul class="stepsmenu">
		<li class="first"><a href="<?php echo $this->url(array('module'=>'exam','controller'=>'component','action'=>'index'),'default',true) ?>"><?php echo $this->translate("Setup Component"); ?></a></li>
		<li class="second"><a href="<?php echo $this->url(array('module'=>'exam','controller'=>'asscomponent','action'=>'index'),'default',true) ?>"><?php echo $this->translate("Mark Distribution"); ?></a></li>
	 	</ul>
</div>