<?php
/*
 *  @author Suliana
 *  @created May 16, 2011
 */
?>


<div align="center" style="background:#fff; height:30px;">
	<ul class="stepsmenu">
		<li class="first"><a href="<?php echo $this->url(array('module'=>'general-setup','controller'=>'client','action'=>'type'),'default',true) ?>"><?php echo $this->translate("Client Type"); ?></a></li>
		<li class="second"><a href="<?php echo $this->url(array('module'=>'anr-setup','controller'=>'market','action'=>'index'),'default',true) ?>"><?php echo $this->translate("Learning Mode"); ?></a></li>
	</ul>
</div>