<?php
/*
 *  @author Suliana
 *  @created May 16, 2011
 */
?>


<div align="center" style="background:#fff; height:30px;">
	<ul class="stepsmenu">
		<li class="first"><a href="<?php echo $this->url(array('module'=>'system-setup','controller'=>'module','action'=>'index'),'default',true) ?>"><?php echo $this->translate("Module Configuration"); ?></a></li>
	    <li class="second"><a href="<?php echo $this->url(array('module'=>'system-setup','controller'=>'role','action'=>'index'),'default',true) ?>"><?php echo $this->translate("Roles & Permissions"); ?></a></li>
	</ul>
</div>