<?php
/*
 *  @author Suliana
 *  @created May 16, 2011
 */
?>


<div align="center" style="background:#fff; height:30px;">
	<ul class="stepsmenu">
		<li class="first"><a href="<?php echo $this->url(array('module'=>'general-setup','controller'=>'country','action'=>'index'),'default',true) ?>"><?php echo $this->translate("Country"); ?></a></li>
	    <li class="second"><a href="<?php echo $this->url(array('module'=>'general-setup','controller'=>'state','action'=>'index'),'default',true) ?>"> <?php echo $this->translate("Governorate / State"); ?></a></li>
	</ul>
</div>