<?php
/*
 *  @author Suliana
 *  @created May 16, 2011
 */
?>


<div align="center" style="background:#fff; height:30px;">
	<ul class="stepsmenu">
		<li class="first"><a href="<?php echo $this->url(array('module'=>'language-setup','controller'=>'index', 'action'=>'index'),'default',true); ?>"><?php echo $this->translate("Language"); ?></a></li>		
		<li class="second"><a href="<?php echo $this->url(array('module'=>'application','controller'=>'salutation', 'action'=>'index'),'default',true);?>"><?php echo $this->translate("Salutation"); ?></a></li>	
		
	</ul>
</div>