<div align="center" style="background:#fff; height:30px;">
	<ul class="stepsmenu">
		<li class="first"><a href="<?php echo $this->url(array('module'=>'exam','controller'=>'markentry','action'=>'index'),'default',true) ?>"><?php echo $this->translate("Mark Entry"); ?></a></li>
		<li class="second"><a href="<?php echo $this->url(array('module'=>'exam','controller'=>'markentry','action'=>'print-search'),'default',true) ?>"><?php echo $this->translate("Print"); ?></a></li>
	 	</ul>
</div>