
<!--<div align="center" style="background:#fff; height:30px;">
	<ul class="stepsmenu">
		<li class="first"><a href="<?php echo $this->url(array('module'=>'application','controller'=>'migration', 'action'=>'index'),'default',true); ?>"><?php echo $this->translate("Student"); ?></a></li>
		<li class="second"><a href="<?php echo $this->url(array('module'=>'application','controller'=>'migration', 'action'=>'batch-index'),'default',true); ?>"><?php echo $this->translate("Batch Upload"); ?></a></li>		
	</ul>	
</div>-->