<?php
/*
 *  @author Suliana
 *  @created May 16, 2011
 */
?>


<!--<div align="center" style="background:#fff; height:30px;">
	<ul class="stepsmenu">
		<li class="first"><a href="<?php echo $this->url(array('module'=>'admission-record','controller'=>'registration','action'=>'index'),'default',true) ?>"><?php echo $this->translate("Auto-registration"); ?></a></li>
		<li class="first"><a href="<?php echo $this->url(array('module'=>'admission-record','controller'=>'registration','action'=>'index'),'default',true) ?>"><?php echo $this->translate("Student Registration"); ?></a></li>
		<li class="second"><a href="<?php echo $this->url(array('module'=>'admission-record','controller'=>'add-drop','action'=>'index'),'default',true) ?>"><?php echo $this->translate("Add/Drop"); ?></a></li>
	</ul>
</div>-->