<div align="center" style="background:#fff; height:30px;">
	<ul class="stepsmenu">
	    <!--<li class="first"><a href="<?php echo $this->url(array('module'=>'application','controller'=>'selection-highschool','action'=>'list-applicant','program_code'=>$this->program_code,'faculty_id'=>$this->faculty_id),'default',true) ?>"><?php echo $this->translate("Individual Approval"); ?></a></li>
		--><li class="first"><a href="<?php echo $this->url(array('module'=>'application','controller'=>'selection-highschool','action'=>'batch-dean-rating','program_code'=>$this->program_code,'faculty_id'=>$this->faculty_id),'default',true) ?>"><?php echo $this->translate("Batch Dean Rating"); ?></a></li>
		<li class="second"><a href="<?php echo $this->url(array('module'=>'application','controller'=>'selection-highschool','action'=>'batch-rector-rating','program_code'=>$this->program_code,'faculty_id'=>$this->faculty_id),'default',true) ?>"><?php echo $this->translate("Batch Rector Rating"); ?></a></li>
		<li class="third"><a href="<?php echo $this->url(array('module'=>'application','controller'=>'selection-highschool','action'=>'batch-approval','program_code'=>$this->program_code,'faculty_id'=>$this->faculty_id),'default',true) ?>"><?php echo $this->translate("Batch Approval"); ?></a></li>
	   </ul>
</div>