<div align="center" style="background:#fff; height:30px;">
	<ul class="stepsmenu">
		<li class="first"><a href="<?php echo $this->url(array('module'=>'system-setup','controller'=>'module','action'=>'index'),'default',true) ?>"><?php echo $this->translate("Module Configuration"); ?></a></li>	
		<li class="second"><a href="<?php echo $this->url(array('module'=>'system-setup','controller'=>'role','action'=>'index'),'default',true) ?>"><?php echo $this->translate("Roles & Permissions"); ?></a></li>	
		<!--<li class="third"><a href="<?php echo $this->url(array('module'=>'system-setup','controller'=>'user','action'=>'index'),'default',true) ?>"><?php echo $this->translate("Users"); ?></li>	
		<li class="fourth"><a href="<?php echo $this->url(array('module'=>'system-setup','controller'=>'audit','action'=>'index'),'default',true) ?>"><?php echo $this->translate("Audit Trail"); ?></a></li>		-->
	</ul>	
</div>