<?php
/*
 *  @author Suliana
 *  @created May 16, 2011
 */
?>


<div align="center" style="background:#fff; height:30px;">
	<ul class="stepsmenu">
		<li class="first"><a href="<?php echo $this->url(array('module'=>'system-setup','controller'=>'user','action'=>'index'),'default',true) ?>"><?php echo $this->translate("Users"); ?></a></li>
	    <li class="second"><a href="<?php echo $this->url(array('module'=>'system-setup','controller'=>'audit','action'=>'index'),'default',true) ?>"><?php echo $this->translate("Audit Trail"); ?></a></li>
	</ul>
</div>