<script>
$(document).ready(function(){

	 $( "#appl_dob" ).datepicker({
	     	dateFormat: "dd-mm-yy",
	     	changeMonth: true,
	     	numberOfMonths: 2,
	     });
     
   
});



function getLocation(element){
	//appl_province
	var select_date =  $("#aps_test_date").val()
	var placement_code =  "USM2020";
	var datetime= $("#aps_test_date option:selected").text();
	var date=datetime.substring(0,11);
	var time=datetime.substring(12,20);
	
	var selected_val = "<?php echo $this->aps_id;?>";
	 
	$.ajax({ 
		type: "POST",
		url: "<?php echo $this->url(array('module'=>'default','controller'=>'online-application','action'=>'ajax-get-location'),'default',true);?>/select_date/"+date+"/select_time/"+time+'/placement_code/'+placement_code, 
		data: "",
		dataType: 'json',
		beforeSend: function() {
			showLoading('aps_id','aps_id-element','loading');
		},
		complete: function() {
			hideLoading('loading','aps_id');
		}
	}).done(function ( data ) {
			$('#aps_id').empty().append('<option value=""> <?php echo $this->translate('please_select'); ?> </option>');
			 
			var location = $('#aps_id');
			var append_html = "";
			
			for (var index = 0; index < data.length; index++) {
				append_html += '<option value="'+data[index].aps_location_id+'"> '+data[index].location_name+' </option>';
			}	
			 
			location.append(append_html);
		});	 
}

 

function showLoading(target,target_div,loading_id){
	$('#'+target).hide();
	$('#'+target_div).append("<div id='"+loading_id+"'><img src='/images/ajax-loader-bar.gif' /></div>");
}

function hideLoading(loading_id,target){
	$('#'+loading_id).remove();
	$('#'+target).show();
}


 
	

$(window).load(function() {
	if( $('#aps_test_date').val() != '' ){
		getLocation();
		
	}
});

</script>

 

<div class="message toolbar">
	<h2><?php echo $this->title; ?></h2>
	<div class="toolbar-button">
		
	</div>
</div>

<?php if(isset($this->noticeMessage)){?>
<div class="message notice"><strong><?php echo $this->noticeMessage;?></strong>.</div>
<?php }?>
<?php if(isset($this->noticeSuccess)){?>
<div class="message success"><strong><?php echo $this->noticeSuccess;?></strong>.</div>
<?php }?>
<?php if(isset($this->noticeError)){?>
<div class="message error"><strong><?php echo $this->noticeError;?></strong>.</div>
<?php }?>

 <form name="tpaform" method="post" >
 
 	<table>
		<tr>
			<td width="80px"><?php echo $this->translate("Date of Exam");?></td>
			<td>:</td>
			<td><select name="aps_test_date" id="aps_test_date" onChange="getLocation(this)">
			<?php foreach ($this->testdate as $value) {
				?><option value="<?php echo $value['aps_id']?>"><?php echo date('d-m-Y',strtotime($value['aps_test_date']))?></option><?php 
			}?>
			
			</select></td>
		 
		<tr>
			<td><?php echo $this->translate("Total Fee");?></td>
			<td>:</td>
			<td><?php echo "Rp 200.000,-";?></td>
		</tr>
		
		<tr><td colspan="3"><input type="submit" name="submit"></td></tr>
	
	</table>
 	<fieldset><?php echo "Catatan:"?>
 		<p>Klik tombol submit untuk membuat nomor pembayaran, selanjutnya silahkan lihat nomor pembayaran di menu status keuangan</p>
 	</fieldset>
 
 
 </form>
  





