<style>
.required:after{
	content: " *";
	color: red;
}
</style>
<script>
$(document).ready(function(){

	 $( "#appl_dob" ).datepicker({
	     	dateFormat: "dd-mm-yy",
	     	changeMonth: true,
	     	numberOfMonths: 2,
	     });
   
});

$(function() {
	// a workaround for a flaw in the demo system (http://dev.jqueryui.com/ticket/4375), ignore!
	$( "#dialog:ui-dialog" ).dialog( "destroy" );

	$( "#dialog-approval" ).dialog({
		modal: true,
		autoOpen: false,
		width: 600,
		buttons: {
			"Save": function() { 
					confirm=$("#ConfirmationCode").val();
					idstudent=$("#IdStudentRegistration").val();
					$("#confirm").val(confirm);
					$("#hp").val($("#diaghp").val());
					 
					if ($("#valid").val()=="1") {
						 	$("#biodata_form").submit(); 
					 }
					 
					 
				 }
			, 
			"Cancel": function() { 
				$(this).dialog("close"); 
			}
			
		}
	});
	
	
});

$(window).load(function() {
	if( $('#appl_marital_status').val() == 4 || $('#appl_marital_status').val() == 38 || $('#appl_marital_status').val() == 39){
		$('#appl_no_of_child').removeAttr('disabled');
	}else{
		$('#appl_no_of_child').attr('disabled','disabled');
		$('#appl_no_of_child').val("");
	}

	 
});
</script>

<script type="text/javascript">
	function changeOrigin(element,targetElement,targetElement2){
		var country_id = 96;
		
		$.ajax({
			url: "<?php echo $this->url(array('module'=>'default','controller'=>'ajax-utility', 'action'=>'get-state'),'default',true);?>",
			data: {'country_id':country_id},
			type: 'POST',
			dataType: 'json'	
		}).done(function ( data ) {
			
			$(targetElement).empty().append('<option value=""> <?php echo $this->translate("please_select"); ?> </option>');
			$(targetElement2).empty().append('<option value=""> <?php echo $this->translate("please_select"); ?> </option>');
		
			
			$.each(data, function(index) {
				$(targetElement).append('<option value="'+data[index].idState+'"> '+data[index].StateName+' </option>');
				$(targetElement2).append('<option value="'+data[index].idState+'"> '+data[index].StateName+' </option>');
			});
			
			
		});
		
		if( $(element).val() != 96 ){
			$('#country_origin').removeAttr('disabled');
			$('#admission').hide();
			$('#divparent').hide();		
		}else{
			$('#country_origin').attr('disabled','disabled');
			$('#country_origin').val("");	
			$('#admission').show();	
			$('#divparent').show();		
		}

	}

	function showdiv(element){
		if( $(element).val() ==2 ){
		 	$('#placement').show();
		}else{
			$('#placement').hide();
		}
	}

	function enableChildren(element){
		
		if( $(element).val() == 4 || $(element).val() == 38 || $(element).val() == 39 ){
			$('#appl_no_of_child').removeAttr('disabled');
		}else{
			$('#appl_no_of_child').attr('disabled','disabled');
			$('#appl_no_of_child').val('0');
		}
	}

	function filladdress(element){

		if($(element).is(':checked')){

			$('#mappl_address_rt').val($('#appl_address_rt').val());
			$('#mappl_address_rw').val($('#appl_address_rw').val());
			$('#mappl_address1').val($('#appl_address1').val());
			$('#mappl_address2').val($('#appl_address2').val());
			$('#mappl_province').val($('#appl_province').val());
			$('#mappl_state').val($('#appl_state').val());
			$('#mappl_city').val($('#appl_city').val());
			$('#mappl_kelurahan').val($('#appl_kelurahan').val());
			$('#mappl_kecamatan').val($('#appl_kecamatan').val());
			$('#mappl_postcode').val($('#appl_postcode').val());
			
		}else{
			

			$('#mappl_address_rt').val(' ');
			$('#mappl_address_rw').val(' ');
			$('#mappl_address1').val(' ');
			$('#mappl_address2').val(' ');
			$('#mappl_province').val(' ');
			$('#mappl_state').val(' ');
			$('#mappl_city').val(' ');
			$('#mappl_kelurahan').val(' ');
			$('#mappl_kecamatan').val(' ');
			$('#mappl_postcode').val(' ');
		}
		
		
		
	}
	

	function changeState(element,targetElement){
		var country_id = $(element).val();
		
		$.ajax({
			url: "<?php echo $this->url(array('module'=>'default','controller'=>'ajax-utility', 'action'=>'get-state'),'default',true);?>",
			data: {'country_id':$(element).val()},
			type: 'POST',
			dataType: 'json',	
			beforeSend: function() {
				showLoading(targetElement,'loading');
			},
			complete: function() {
				hideLoading(targetElement,'loading');
			}	
		}).done(function ( data ) {
			
			$(targetElement).empty().append('<option value=""> <?php echo $this->translate("please_select"); ?> </option>');
		
			$.each(data, function(index) {
				$(targetElement).append('<option value="'+data[index].idState+'"> '+data[index].StateName+' </option>');
			});
		});
	}
	
	function changeCity(element, targetElement){
		$.ajax({
			url: "<?php echo $this->url(array('module'=>'default','controller'=>'ajax-utility', 'action'=>'get-city'),'default',true);?>",
			data: {'state_id':$(element).val()},
			type: 'POST',
			dataType: 'json',
			beforeSend: function() {
				showLoading(targetElement,'loading');
			},
			complete: function() {
				hideLoading(targetElement,'loading');
			}	
		}).done(function ( data ) {
			
			$(targetElement).empty().append('<option value=""> <?php echo $this->translate("please_select"); ?> </option>');
		
			$.each(data, function(index) {
				$(targetElement).append('<option value="'+data[index].idCity+'"> '+data[index].CityName+' </option>');
			});
		});
	}

	function showLoading(target,loading_id){
		$(target).hide();
		$(target).parent().append("<div id='"+loading_id+"'><img src='/images/ajax-loader-bar.gif' /></div>");
	}

	function hideLoading(target,loading_id){
		$('#'+loading_id).remove();
		$(target).show();
	}

	function onClick(){
		//send confirmation number
		var hp=$("#diaghp").val();
		 
		$("#IdStudentRegistration").val(<?php echo $this->stdid?>);
		idstudent=$("#IdStudentRegistration").val();
		$.ajax({
			url: "<?php echo $this->url(array('module'=>'default','controller'=>'course-registration', 'action'=>'ajax-send-sms'),'default',true);?>",
			data: {'hp':hp,'idstudent':idstudent,'iduser':<?php echo $this->appl_id;?>},
			type: 'POST',
			dataType: 'json' 
		}).done(function ( data ) {
			 
			 if (data=='Success Send') {
				 document.getElementById("demo").innerHTML = "Kode Konfirmasi telah dikirim ke";
			 } else {
				 document.getElementById("demo").innerHTML = "Tolong periksa Nomor HP anda karena kode Konfirmasi gagal dikirim ke";
				 
			 }
			
			 //data pesan
		});
		 
		 $( "#dialog-approval" ).dialog('open');
		
	}

	function checkconfirm() {

		confirm=$("#ConfirmationCode").val();
		idstudent=$("#IdStudentRegistration").val();
		document.getElementById("confirmmsg").innerHTML='';
		$.ajax({
			url: "<?php echo $this->url(array('module'=>'default','controller'=>'course-registration', 'action'=>'ajax-check-confirm'),'default',true);?>",
			data: {'idstudent':idstudent,'confirm':confirm},
			type: 'POST',
			dataType: 'json' 
		}).done(function ( data ) {
			 
			if (data=="Valid") { 
				document.getElementById("confirmmsg").innerHTML = "Kode Konfirmasi Ok";
				$("#valid").val("1");
				confirm=$("#ConfirmationCode").val();
				idstudent=$("#IdStudentRegistration").val();
				$("#confirm").val(confirm);
				$("#hp").val($("#diaghp").val());
				$("#biodata_form").submit();
		} else {
			   
				document.getElementById("confirmmsg").innerHTML = "Kode Konfirmasi Salah "+data+"X";
				document.getElementById("valid").value="0";
				if (data > "4") $("#dialog-approval").dialog("close"); 
		} 
		});
	}
</script>
<style type="text/css">
select, input[type='text']{
	width:250px;
}
select#appl_dob-day{
	width:50px;
}
select#appl_dob-month{
	width:100px;
}
select#appl_dob-year{
	width:80px;
}
input#appl_no_of_child{
	width: 20px;
}
</style>

<?php if(isset($this->noticeMessage)){?>
<div class="message notice"><strong><?php echo $this->noticeMessage;?></strong>.</div>
<?php }?>
<?php if(isset($this->noticeSuccess)){?>
<div class="message success"><strong><?php echo $this->noticeSuccess;?></strong>.</div>
<?php }?>
<?php if(isset($this->noticeError)){?>
<div class="message error"><strong><?php echo $this->noticeError;?></strong>.</div>
<?php }?>

<div class="message toolbar">
	<h2><?php echo $this->title; ?></h2>
	<div class="toolbar-button">
		
	</div>
</div>

<?php echo $this->form; ?>


<div id="dialog-approval" title="Approval by Confirmation Code sent to Mobile Phone">
 
<table name="approval_tbl" id="approval_tbl" class="table">
</table>
<br>
<br>
<table width="100%">
<?php $hp=$this->data['appl_phone_hp'];
	  if (substr($this->student['appl_phone_hp'],0,1)=="8") $hp='62'.$this->data['appl_phone_hp'];
	  if (substr($this->student['appl_phone_hp'],0,1)=="0") $hp='62'.substr($this->data['appl_phone_hp'],1);
  ?>
<type input="hidden" id="IdStudentRegistration" name="IdStudentRegistration" value="<?php echo $this->stdid;?>">
 <input type="hidden" id="diaghp" name="diaghp" value="<?php echo $hp?>">
<tr><td colspan="3"><span id="demo"></span><?php echo ' '.substr($hp,0,strlen($hp)-4)."xxxx". ' Jika nomor Handphone salah silahkan hubungi Admin Fakultas'?></td></tr>
<tr><td width="40%"><?php echo $this->translate('Masukan Kode Konfirmasi (4 kali gagal kode dibatalkan)')?></td><td width="5px">:</td>
<td><input type="text" size="6" name="ConfirmationCode" id="ConfirmationCode" onchange="checkconfirm()"><font color="red"><span id="confirmmsg"></span></font></td></tr>
</table>
</div>