<script>
$(document).ready(function(){

	 $( "#appl_dob" ).datepicker({
	     	dateFormat: "dd-mm-yy",
	     	changeMonth: true,
	     	numberOfMonths: 2,
	     });
     
   
});

function getDate(element){
	//appl_province
	var placement_code =  $("input[name='aph_placement_code']:checked").val()
	
	
	 
	$.ajax({ 
		type: "POST",
		url: "<?php echo $this->url(array('module'=>'default','controller'=>'online-application','action'=>'ajax-get-date'),'default',true);?>/placement_code/"+placement_code+"/transactionid/<?php echo $this->transaction_id; ?>/applid/<?php echo $this->appl_id; ?>/changedate/1", 
		data: "placement_code=" + placement_code,
		dataType: 'json',
		beforeSend: function() {
			showLoading('aps_test_date','aps_test_date-element','loading');
		},
		complete: function() {
			hideLoading('loading','aps_test_date');
		}
	}).done(function ( data ) {
			$('#aps_test_date').empty().append('<option value=""> <?php echo $this->translate('please_select'); ?> </option>');
			 
			var testdate = $('#aps_test_date');
			var append_html = "";
			
			for (var index = 0; index < data.length; index++) {
				append_html += '<option value="'+data[index].aps_id+'"> '+data[index].aps_test_date+' '+data[index].aps_start_time+' </option>';
			}	

			testdate.append(append_html);
		});	 
}

function getLocation(element){
	 
	var datetime= $("#aps_test_date option:selected").text();
	var date=datetime.substring(0,11);
	var time=datetime.substring(12,20);
	var select_aps = $("#aph_placement_code").val();
	
	var selected_val = "<?php echo $this->aps_id;?>";
	
	//alert("/online-application/ajax-get-location/select_date/"+date+"/select_aps/"+select_aps);
	$.ajax({ 
		type: "POST",
		url: "<?php echo $this->url(array('module'=>'default','controller'=>'online-application','action'=>'ajax-get-location'),'default',true);?>/select_date/"+date+"/select_time/"+time+"/select_aps/"+select_aps, 
		data: "select_date=" + date,
		dataType: 'json',
		beforeSend: function() {
			showLoading('aps_id','aps_id-element','loading');
		},
		complete: function() {
			hideLoading('loading','aps_id');
		}
	}).done(function ( data ) {
			$('#aps_id').empty().append('<option value=""> <?php echo $this->translate('please_select'); ?> </option>');
			 
			var location = $('#aps_id');
			var append_html = "";
			//alert(data.length);
			for (var index = 0; index < data.length; index++) {
				append_html += '<option value="'+data[index].aps_id+'"> '+data[index].location_name+' </option>';
			}	

			location.append(append_html);
		});	 
}

function showLoading(target,target_div,loading_id){
	$('#'+target).hide();
	$('#'+target_div).append("<div id='"+loading_id+"'><img src='/images/ajax-loader-bar.gif' /></div>");
}

function hideLoading(loading_id,target){
	$('#'+loading_id).remove();
	$('#'+target).show();
}


function getFees(element){
	
	var aps_id   =  $(element).val()	
	var appl_id    =  $("#appl_id").val()
	var transaction_id    =  $("#transaction_id").val()
    var app_ptest_code    =  $("#app_ptest_code").val()
    var aph_fees_program  =  $("#aph_fees_program").val()   
    var aph_fees_location =  $("#aph_fees_location").val()
     
   			
	
}	
	

$(window).load(function() {
	if( $('#aps_test_date').val() != '' ){
		getLocation();
		
	}
});

</script>


<div class="message toolbar">
	<h2><?php echo $this->title; ?></h2>
	<div class="toolbar-button">
		
	</div>
</div>

<?if(isset($this->noticeMessage)){?>
<div class="message notice"><strong><? echo $this->noticeMessage;?></strong>.</div>
<?}?>
<?if(isset($this->noticeSuccess)){?>
<div class="message success"><strong><? echo $this->noticeSuccess;?></strong>.</div>
<?}?>
<?if(isset($this->noticeError)){?>
<div class="message error"><strong><? echo $this->noticeError;?></strong>.</div>
<?}?>

<?php if( isset($this->data) ){?>
<fieldset>
	<table>
		<tr>
			<th colspan=3><?php echo $this->translate("Jadwal Sekarang");?></td>
			
		</tr>
		<tr>
			<td width="80px"><?php echo $this->translate("Date");?></td>
			<td>:</td>
			<td><?php echo $this->data['aps_test_date'];?></td>
		</tr>
		<tr>
			<td><?php echo $this->translate("Location");?></td>
			<td>:</td>
			<td><?php echo $this->data['al_location_name'];?></td>
		</tr>
		<tr>
			<td><?php echo $this->translate("Total Fee");?></td>
			<td>:</td>
			<td><?php echo $this->data['apt_fee_amt'];?></td>
		</tr>
	</table>
	</fieldset>

<?php }?>

<?php echo $this->form; ?>





