<div class="message toolbar">
	<h2><?php echo $this->title; ?></h2>
	<div class="toolbar-button">
		<ul>
			<li>
				<a href="<?php echo $this->url(array('module'=>'exam','controller'=>'defer', 'action'=>'index'),'default',true);?>">
					<span class='back'></span>
					Back
				</a>
			</li>
			<li>
				<a href="#" >
					<span class='info'></span>
					Info
				</a>
			</li>
		</ul>
	</div>
</div>


<div align="center" style="background:#ebebeb; height:30px;">
<ul class="steps">
	<li class="empty">
		<span>1</span> Student Selection
	</li>
    <li class="previous">
		<span>2</span> Exam Defer 
	</li>
	<li class="current">
		<span>3</span> Preview
	</li>

</ul>
<br class="clear" />
</div>


<br />
<h4>Student Details</h4>
<table width="100%">
	<tr>
		<td width="110px">NAME</td>
		<td width="5px">:</td>
		<td><?php echo $this->student['fullname']; ?></td>
		<td>PROGRAM</td>
		<td>:</td>
		<td><?php echo $this->program['main_name']?></td>
	</tr>
	<tr>
		<td>MATRIC NUM</td>
		<td>:</td>
		<td><?php echo $this->student['matric_no']; ?></td>
		<td>ACADEMIC STATUS</td>
		<td>:</td>
		<td><input type="hidden" name="academic_status" id="academic_status" value="1">GOOD</td>
	</tr>
	<tr>
		<td>BRANCH</td>
		<td>:</td>
		<td><?php echo $this->student['branch_name']?></td>
		<td>INTAKE</td>
		<td>:</td>
		<td><?php echo $this->student['intake_name']?></td>
	</tr>
	<tr>
		<td>SEMESTER</td>
		<td>:</td>
		<td colspan="3"><?php echo $this->semester["name"].'&nbsp;'.$this->semester["year"];?>
		</td>
	</tr>
</table>


<div>
	<h2>Exam Defer Status</h2>
	
	<table width="100%" border="0" class="table3" cellpadding="5" cellspacing="1">
	<tr>
		<th>No</th>
		<th>Course Name</th>
		<th>Course Code</th>
		<th>Reason</th>
		<th>Defer Date</th>
		<th>Defer Status</th>
		<th>Approved By</th>
		<th>Approved Date</th>
	</tr>
	<?php 
	$i=1;
	foreach ($this->list_application as $application):{
	?>
	
	<tr <?php echo $i%2==0?"class='shade'":""; ?>>
	    <td align="center"><?php echo $i;?>.</td>	
		<td align="left">  <?php echo $application['course_name']; ?></td>
		<td align="center"><?php echo $application['course_code']; ?></td>
		<td align="center"><?php echo $application['defer_reason'];?></td>
		<td align="center"><?php echo $application['defer_date'];?></td>
		<td align="center">
		<?php 
			if($application['defer_status']==2) $status = "Approved";
			if($application['defer_status']==1) $status = "Not Approved";
			if($application['defer_status']==0) $status = "Not Updated";				
			echo $status;
			?>
		</td>
		<td align="center">
		<?php
		if($application['defer_status']!=0){
			$oUser = new SystemSetup_Model_DbTable_User();
	    	$user = $oUser->getData($application['approvedby']); 
	    	echo $user["fullname"];
		}else{echo '-';}
		?>
		</td>
		<td align="center"><?php if($application['defer_status']!=0){ echo $application['approveddt']; } else echo '-';?></td>
	</tr>
	<?php 
			$i++;
		}
	endforeach 
	?>
	
</table>