<script type="text/javascript">
	
	
	function add(){
		window.location="<?php echo $this->url(array('module'=>'exam','controller'=>'component', 'action'=>'addform'),'default',true);?>";
	}

	function edit(){
		var id = $('input[name=id]:checked').val();

		if(!id){
			alert('Please select any component first');
		}else{
			window.location="<?php echo $this->url(array('module'=>'exam','controller'=>'component', 'action'=>'editform'),'default',true);?>/id/"+id;
		}
	}
	
	function del(){
		var id = $('input[name=id]:checked').val();

		if(!id){
			alert('Please select any component first');
		}else{
			if(confirm('Are you sure to delete this entire component?')){
				window.location = "<?php echo $this->url(array('module'=>'exam','controller'=>'component', 'action'=>'delete'),'default',true); ?>/id/"+id;
			}
		}
	}

</script>
<div class="message toolbar">
	<h2><?php echo $this->title; ?></h2>
	<div class="toolbar-button">
		<ul>
			<li>
				<a href="#" onclick="javascript:add()">
					<span class='add'></span>
					Add
				</a>
			</li>
			<li>
				<a href="#" onclick="javascript:edit()">
					<span class='edit'></span>
					Edit
				</a>
			</li>
			<li>
				<a href="#" onclick="javascript:del()">
					<span class='delete'></span>
					Delete
				</a>
			</li>
			<li class="divider"></li>
			<li>
				<a href="#" >
					<span class='info'></span>
					Info
				</a>
			</li>
		</ul>
	</div>
</div>
<br />

<div style="width:500px;">
<?php 
	echo $this->paginationControl($this->paginator,'Sliding','paginationTop.phtml');
?>
<table class="table" width="100%" cellpadding="5" cellspacing="2" border="0">
	<tr>
		<th width="25px">&nbsp;</th>
		<th>Component Name</th>
		<th>Component Item Name</th>
	</tr>
	
	<?foreach ($this->paginator as $component) { 
		$oComponent = new App_Model_Exam_DbTable_Component();
		$component_item = $oComponent->getInfo($component["id"]);
		
	?> 
		<tr valign="top">
			<td width="25px">&nbsp;<input type='radio' name='id' value='<?php echo $component["id"];?>'></td>
			<td><?php echo $component["component_name"];?></td>		
			<td><ul><? foreach ($component_item as $ci){
				     echo "<li>$ci[component_name]</li>";
				   }
				?></li></ul>
			</td>

		</tr>	
	<? } ?>
</table>
<?php 
	echo $this->paginationControl($this->paginator,'Sliding','paginationBottom.phtml');
?>
</div>