<script type="text/javascript">
	function showConfirm(){
		var id = $('input[name=courseTransfer[]]:checked').val();

		if(!id){
			alert('Please select course to credit transfer');
		}else{
			if(confirm('Are you sure to submit this credit transfer application?')){
				//window.location = "<?php echo $this->url(array('module'=>'admission-record','controller'=>'credit-transfer', 'action'=>'view-transfer'),'default',true); ?>";
				document.transfer_form.action ="<?php echo $this->url(array('module'=>'admission-record','controller'=>'credit-transfer', 'action'=>'view-transfer'),'default',true); ?>";
				document.transfer_form.submit();
	
			}
		}
	}
</script>	
	
<?if(isset($this->noticeSuccess)){?>
<div class="message success"><strong><? echo $this->noticeSuccess;?></strong>.</div>
<?}?>
<?if(isset($this->noticeError)){?>
<div class="message error"><strong><? echo $this->noticeError;?></strong>.</div>
<?}?>

<br>
<div class="message toolbar">
	<h2><?php echo $this->title; ?></h2>
	<div class="toolbar-button">
		<ul>
			<li>
				<a href="<?php echo $this->url(array('module'=>'admission-record','controller'=>'credit-transfer', 'action'=>'index'),'default',true);?>">
					<span class='back'></span>
					Back
				</a>
			</li>
			<li>
				<a href="#" >
					<span class='info'></span>
					Info
				</a>
			</li>
		</ul>
	</div>
</div>

<div align="center" style="background:#ebebeb; height:30px;">
<ul class="steps">
	<li class="prevDone">
		<span>1</span> Student Selection
	</li>
    <li class="current">
		<span>2</span> Credit Transfer
	</li>
	<li class="next">
		<span>3</span> Completed
	</li>
	
</ul>
<br class="clear" />
</div>

<br />
<h4>Student Details</h4>
<table>
	<tr>
		<td width="110px">Name</td>
		<td width="5px">:</td>
		<td><?php echo $this->student['fullname']; ?></td>
	</tr>
	<tr>
		<td>Matric No</td>
		<td>:</td>
		<td><?php echo $this->student['matric_no']; ?></td>
	</tr>
	<tr>
		<td width="110px">
			Program
		</td>
		<td width="5px">:</td>
		<td>
			<?php echo $this->program['main_name']?>
		</td>
	</tr>
	
	<tr>
		<td width="110px">
			Semester
		</td>
		<td width="5px">:</td>
		<td><?php echo strtoupper($this->semesterName["name"]);?> &nbsp;<?php echo $this->semesterName["year"]?>
		</td>
	</tr>
</table>
<br />


</form>	


<form name="transfer_form" action="" method="post">

	<input type="hidden" name="student_id" value="<?php echo $this->student['id']?>" />
	<input type="hidden" name="semester_id" value="<?php echo $this->semester_id?>" />
	
<h4>Academic Landscape</h4>	
      <table width="100%" border="0" cellspacing="1" cellpadding="5" class="table3">
            <tr align="center">
              <th colspan="2">Course Code</th>
              <th>Course Name</th>
              <th>Course Type</th>
              <th width="50">Semester / Level</th>
              <th width="30">Credit Hours</th>
              <th width="30">Status</th>
              <th width="50">Tick (/)</th>
            </tr>
            
            <?
            $i=1;
            foreach ($this->landscape as $landscape){
			?>
            <tr>
              <td width="2%"><?=$i;?>)</td>
              <td><?=$landscape["course_code"];?></td>
              <td><?=$landscape["course_name"];?></td>
               <td><?=$landscape["course_type_name"];?></td>
               <td align="center"><?=$landscape["level"];?></td>
               <td align="center"><?=$landscape["credit_hour"];?></td>
              <?php
              $courseID = $landscape["course_id"];
              
              $transferDB = new App_Model_Record_DbTable_CreditTransfer();
			  $transfer = $transferDB->getRow($this->student_id,$courseID);
			  if ($transfer) {
			  	$checked = "disabled";
			  	
			  	if ($transfer["status"] == 0) {
			  		$status = 'Applied';
			  	}elseif ($transfer["status"] == 1){
			  		$status = 'Approved';
			  	}else {
			  		$status = 'Disapproved';
			  	}
			  	
			  }else{
			  	$checked = "";
			  	$status = '-';
			  }
              ?>
              
              <td align="center"><?=$status?></td>
              <td align="center">
             
              
              <input type="checkbox" name="courseTransfer[]" id="courseTransfer[]" value="<?=$landscape["course_id"];?>" <?php echo $checked?>></td>
            </tr>
            <? 
            $i++;
            } ?>
          
      </table>

<div width="200px" align="right">
					<br />
					<input type="button" value="Apply Credit Transfer"  onclick="javascript:showConfirm();">
				</div>

<br /><br /><br />
</form>





</div>


