<?if(isset($this->noticeSuccess)){?>
<div class="message success"><strong><? echo $this->noticeSuccess;?></strong>.</div>
<?}?>
<?if(isset($this->noticeError)){?>
<div class="message error"><strong><? echo $this->noticeError;?></strong>.</div>
<?}?>

<br>
<div class="message toolbar">
	<h2><?php echo $this->title; ?></h2>
	<div class="toolbar-button">
		<ul>
			<li>
				<a href="<?php echo $this->url(array('module'=>'admission-record','controller'=>'credit-transfer', 'action'=>'index'),'default',true);?>">
					<span class='back'></span>
					Back
				</a>
			</li>
			<li>
				<a href="#" >
					<span class='info'></span>
					Info
				</a>
			</li>
		</ul>
	</div>
</div>

<div align="center" style="background:#ebebeb; height:30px;">
<ul class="steps">
	<li class="prevDone">
		<span>1</span> Student Selection
	</li>
    <li class="prevDone">
		<span>2</span> Credit Transfer
	</li>
	<li class="current">
		<span>3</span> Completed
	</li>
	
</ul>
<br class="clear" />
</div>

<br />
<h2>Student Details</h2>
<table>
	<tr>
		<td width="110px">Name</td>
		<td width="5px">:</td>
		<td><?php echo $this->student['fullname']; ?></td>
	</tr>
	<tr>
		<td>Matric No</td>
		<td>:</td>
		<td><?php echo $this->student['matric_no']; ?></td>
	</tr>
	<tr>
		<td width="110px">
			Program
		</td>
		<td width="5px">:</td>
		<td>
			<?php echo $this->program['main_name']?>
		</td>
	</tr>
	
	<tr>
		<td width="110px">
			Semester
		</td>
		<td width="5px">:</td>
		<td><?php echo strtoupper($this->semesterName["name"]);?> &nbsp;<?php echo $this->semesterName["year"]?>
		</td>
	</tr>
</table>

</form>	

<h4>Course Credit Transfer</h4>
<table width="100%" border="0" cellspacing="1" cellpadding="5" class="table3">
    <tr bgcolor="#f2f2f2" align="center">
      <th colspan="2">Course Code</th>
      <th>Course Name</th>
      <th width="30">Credit Hours</th>
      <th width="30">Status</th>
    </tr>
    
    <?
    $i=1;
    foreach ($this->creditTransfer as $transfer){
	?>
    <tr bgcolor="#ffffff">
      <td width="2%"><?=$i;?>)</td>
      <td><?=$transfer["course_code"];?></td>
      <td><?=$transfer["course_name"];?></td>
      <td align="center"><?=$transfer["course_credit_hour"];?></td>
      <td align="center"><?php echo $transfer['status']==1?"<span class='state publish'>&nbsp;</span>":"<span class='state unpublish'>&nbsp;</span>"; ?></td>
    </tr>
    <? 
    $i++;
    } ?>
  
</table>

</div>


