	
	

		
			
			<div class="breadcrum">
				<ul class="tri-steps">
					<li class="empty"><div class="text"><a href="<?php echo $this->url(array('module'=>'default','controller'=>'online-application','action'=>'biodata'),'default',true);?>"><?php echo $this->translate("biodata"); ?></a></div></li>
					<li class="empty"><div class="text"><a href="<?php echo $this->url(array('module'=>'default','controller'=>'online-application','action'=>'contactinfo'),'default',true);?>"><?php echo $this->translate("contact_info"); ?></a></div></li>
					
					<?php if($this->transaction["entry_type"]!=2){ //case agent(manual entry- which is already have no peserta/choose admission type)?>
					<li class="empty"><div class="text"><a href="<?php echo $this->url(array('module'=>'default','controller'=>'online-application','action'=>'admission'),'default',true);?>"><?php echo $this->translate("Admission Type"); ?></a></div></li>
					<?php } //end admission?>
					
					
					<?php if($this->transaction['at_appl_type']=='1'){?>
						<li class="empty"><div class="text"><a href="<?php echo $this->url(array('module'=>'default','controller'=>'online-application','action'=>'placement-test'),'default',true);?>"><?php echo $this->translate("test_schedule"); ?></a></div></li>
						<li class="empty"><div class="text"><a href="<?php echo $this->url(array('module'=>'default','controller'=>'online-application','action'=>'programme'),'default',true);?>"><?php echo $this->translate("programme"); ?></a></div></li>
						<li class="prevDone"><div class="text"><a href="<?php echo $this->url(array('module'=>'default','controller'=>'online-application','action'=>'uploaddocument'),'default',true);?>"><?php echo $this->translate("upload_document"); ?></a></div></li>
					<?php }else{?>
						<li class="empty"><div class="text"><a href="<?php echo $this->url(array('module'=>'default','controller'=>'online-application','action'=>'programme'),'default',true);?>"><?php echo $this->translate("programme"); ?></a></div></li>
						<li class="prevDone"><div class="text"><a href="<?php echo $this->url(array('module'=>'default','controller'=>'online-application','action'=>'uploaddocument'),'default',true);?>"><?php echo $this->translate("upload_document"); ?></a></div></li>
					<?php }?>
					<li class="lastCurrent"><div class="text"><a href="<?php echo $this->url(array('module'=>'default','controller'=>'online-application','action'=>'confirmation'),'default',true);?>"><?php echo $this->translate("confirmation"); ?></a></div></li>	
				</ul>
				<div class="clear"></div>
			</div>
			
			
			<div class="message toolbar">
				<h2><?php echo $this->title; ?></h2>
				<div class="toolbar-button">
					
				</div>
			</div>
			<table class="table">
				<tr><th><?php echo "Nama"?></th><td><?php echo $this->profile['appl_fname'].' '.$this->profile['appl_mname'].' '.$this->profile['appl_fname']?></td></tr>
				<tr><th><?php echo "Alamat"?></th><td><?php echo $this->profile['appl_address1']?></td></tr>
				<tr><th><?php echo "Tempat/Tgl Lahir"?></th><td><?php echo $this->profile['appl_birth_place'].'/'.date('Y-m-d', strtotime($this->profile['appl_dob']))?></td></tr>
				
				<tr><th><?php echo "Disiplin"?></th><td><?php echo $this->profile['discipline']?></td></tr>
				<tr><th><?php echo "Pendidikan"?></th><td><?php echo $this->profile['education']?></td></tr>
				<tr><th><?php echo "Pilihan"?></th>
					<td><ol><?php foreach ($this->program as $prog) {
						echo '<li>'.$prog['faculty'].'-'.$prog['program_name_indonesia'].' kelas:'.$prog['kelas'];
						}?></ol></td>
				</tr>
				 <tr><th><?php echo "Tanggal Ujian"?></th><td><?php echo $this->profile['discipline']?></td></tr>
				
			</table>
			<form name='myform' method="post" action="<?php echo $this->url(array('module'=>'default','controller'=>'online-application','action'=>'confirmation'),'default',true);?>">
			<br>
			<br>
			<br>
			<br>
			<br>
			<table align="center" class="table3" width="50%">
				<tr><td align="center">				
					<p><font size="3"><?php echo $this->translate("pre_confirmation_notice")?></font></p>
					<p><input type="Submit" name="submit"  value="<?php echo $this->translate("submit"); ?>" ></p>
				</td></tr>
				
			</table>
			</form>
			
	

