<style>
div.toolbar-button {
    float: right;
    text-align: right;
}
.zend_form select#appl_dob-day{
	width:50px;
}
.zend_form select#appl_dob-month{
	width:100px;
}
.zend_form select#appl_dob-year{
	width:80px;
}
</style>

<div class="message toolbar">
	<h2><?php echo $this->title; ?></h2>
	<div class="toolbar-button">
		<ul>
			<li>
				<a href="#" onclick="window.location = '<?php echo $this->url(array('module'=>'default','controller'=>'online-application'),'default',true);?>'">
					<span class='back'></span>
					<?php echo $this->translate("back"); ?>
				</a>
			</li>
		</ul>
	</div>
</div>

<?if(isset($this->noticeMessage)){?>
<div class="message notice"><strong><? echo $this->noticeMessage;?></strong>.</div>
<?}?>
<?if(isset($this->noticeSuccess)){?>
<div class="message success"><strong><? echo $this->noticeSuccess;?></strong>.</div>
<?}?>
<?if(isset($this->noticeError)){?>
<div class="message error"><strong><? echo $this->noticeError;?></strong>.</div>
<?}?>

<p>
<?php echo $this->msg; ?>
</p>

<?php echo $this->form; ?>