

<?php

$registry = Zend_Registry::getInstance();
$locale = $registry->get('Zend_Locale');
$this->locale = $locale->toString();
?>
 
<?php 
	echo $this->headScript()->appendFile($this->baseUrl().'/js/jquery/plugin/colorbox/jquery.colorbox-min.js');
	echo $this->headLink()->prependStylesheet($this->baseUrl().'/js/jquery/plugin/colorbox/colorbox.css');
?>
<script type="text/javascript">
	function viewDocReq(){
		var pId = $('#programme').val();

		if(pId!=0){
			$.colorbox({
				href:"<?php echo $this->url(array('module'=>'default','controller'=>'online-application', 'action'=>'view-document-requirement'),'default',true);?>/pid/"+pId,
				width: "70%",
				height: "70%"
			});
		}else{
			alert('<?php echo $this->translate("Please select programme"); ?>');
		}
	}
</script>

<style type="text/css">
	ol{
		padding: 0;
		margin: 0 0 0 18px;	
	}
	
	ol li{
		padding: 2px 0;
	}
	
	
* {box-sizing: border-box;}
body {font-family: Verdana, sans-serif;}
.mySlides {display: none;}
img {vertical-align: middle;}

/* Slideshow container */
.slideshow-container {
  max-width: 1000px;
  position: relative;
  margin: auto;
}

/* Caption text */
.text {
  color: #f2f2f2;
  font-size: 15px;
  padding: 8px 12px;
  position: absolute;
  bottom: 8px;
  width: 100%;
  text-align: center;
}

/* Number text (1/3 etc) */
.numbertext {
  color: #f2f2f2;
  font-size: 12px;
  padding: 8px 12px;
  position: absolute;
  top: 0;
}

/* The dots/bullets/indicators */
.dot {
  height: 15px;
  width: 15px;
  margin: 0 2px;
  background-color: #bbb;
  border-radius: 50%;
  display: inline-block;
  transition: background-color 0.6s ease;
}

.active {
  background-color: #717171;
}

/* Fading animation */
.fade {
  -webkit-animation-name: fade;
  -webkit-animation-duration: 1.5s;
  animation-name: fade;
  animation-duration: 1.5s;
}

@-webkit-keyframes fade {
  from {opacity: .4} 
  to {opacity: 1}
}

@keyframes fade {
  from {opacity: .4} 
  to {opacity: 1}
}

/* On smaller screens, decrease text size */
@media only screen and (max-width: 300px) {
  .text {font-size: 11px}
}
</style>

<script>

var slideIndex = 0;
showSlides();

function showSlides() {
	  var i;
	  var slides = document.getElementsByClassName("mySlides");
	  var dots = document.getElementsByClassName("dot");
	  for (i = 0; i < slides.length; i++) {
	    slides[i].style.display = "none";  
	  }
	  slideIndex++;
	  if (slideIndex > slides.length) {slideIndex = 1}    
	  for (i = 0; i < dots.length; i++) {
	    dots[i].className = dots[i].className.replace(" active", "");
	  }
	  slides[slideIndex-1].style.display = "block";  
	  dots[slideIndex-1].className += " active";
	  setTimeout(showSlides, 2000); // Change image every 2 seconds
}


</script>
 
<div style="float:left; width:100%;">
	<div class="message toolbar">
		<h2><?php echo $this->title; ?></h2>
		<div class="toolbar-button">
			<ul>
				<li>
					<a href="http://www.infopmb.trisakti.ac.id" target="_blank" >
						<span class='link'></span>
						<font size="4"><?php echo $this->translate("Info Detail PMB")?> </font>
					</a>
				</li>
			</ul>
		</div>
	</div>
	
	<?php if(isset($this->noticeMessage)){?>
	<div class="message notice"><strong><?php echo $this->noticeMessage;?></strong>.</div>
	<?php }?>
	<?php if(isset($this->noticeSuccess)){?>
	<div class="message success"><strong><?php echo $this->noticeSuccess;?></strong>.</div>
	<?php }?>
	<?php if(isset($this->noticeError)){?>
	<div class="message error"><strong><?php echo $this->noticeError;?></strong>.</div>
	<?php }?>
	<br>
	<table><tr><td width="50%" valign="top">
	<h2>
	<?php echo "Login bagi yang sudah mempunyai Akun"?></h2>
	<br>
	<?php echo $this->form; ?></td>
	
	 <td>
	 	
	 	<?php foreach ($this->schedule as $placement) {
	 		$periodes=$placement['periode'];
	 		
	 	?>
	 	JADWAL USM <?php echo  $placement['aph_placement_name']?><br>
	 	Awal Semester : <?php echo  $placement['IntakeDefaultLanguage'].' Kuliah Mulai :'.date('d-m-Y',strtotime($placement['class_start']))?><br>
	 	<table class="table">
	 		<tr><th>Periode</th><th>Tanggal USM</th><th>Jam Mulai</th></tr>
	 		<?php foreach ($periodes as $period) {?>
	 			<tr><td><?php echo date('M',strtotime($period['aps_test_date']))?></td>
	 			<td><?php echo date('d-m-Y',strtotime($period['aps_test_date']))?></td>
	 			<td><?php echo date('H:s:i',strtotime($period['aps_start_time']))?></td></tr>
	 		<?php }?>
	 	</table>
	 	<br><br>
	 	<?php }?>
	 	
	 </td> </tr>
	</table>
	
	 
	<table>
		<tr><td><font size="2pt"><strong><?php echo $this->translate("create_new_account")?>&nbsp;[<a href="<?php echo $this->url(array('module'=>'default','controller'=>'online-application','action'=>'register'),'default',true);?>"><?php echo $this->translate("click_here");?></a>].</strong></font></td></tr>
		<tr><td>
	    <font size="2pt"><p>Jika ada kesulitan silahkan hubungi:- <br> <br>

		Email : barensif@trisakti.ac.id <br>
		WA 	  : 0821-1000-2227 <br>
		TELP  :021-5663232 ext 8178 (Jam kerja : 8:00 s/d 16:00)<br>
		</p></font>
	   
	   </td></tr>
	
	</table>
	<br />
	<br />
	<div>
		<div style="width:400px">
			*<?php echo $this->translate("browser_recomendation");?>
			<a href="//affiliates.mozilla.org/link/banner/31579" target="_BLANK"><img src="//affiliates.mozilla.org/media/uploads/banners/910443de740d4343fa874c37fc536bd89998c937.png" alt="Download: Fast, Fun, Awesome" /></a>
		</div>
	</div>
</div>

<?php if ($this->locale=="en_US") { 
	$anntitle=$this->rsanntitle["sl_english"];
	$annmesg=$this->rsannmesg["sl_english"];
} else if ($this->locale=="id_ID") { 
	$anntitle=$this->rsanntitle["sl_bahasa"];
	$annmesg=$this->rsannmesg["sl_bahasa"];
}
?>

 
 