<div class="breadcrum">
	<ul class="tri-steps">
		<!-- 
		<li class="empty" ><div class="text"><a href="#"><?php echo $this->translate("apply"); ?></a></div></li>
		<li class="empty" ><div class="text"><a href="#"><?php echo $this->translate("login"); ?></a></div></li>
		 -->
		<li class="empty"><div class="text"><a href="#"><?php echo $this->translate("biodata"); ?></a></div></li>
		<li class="empty"><div class="text"><a href="#"><?php echo $this->translate("contact_info"); ?></a></div></li>
		<li class="empty"><div class="text"><a href="#"><?php echo $this->translate("programme"); ?></a></div></li>
		
		<?php if($this->applicant['appl_admission_type']=='2'){?>
			<li class="empty"><div class="text"><a href="#"><?php echo $this->translate("upload_document"); ?></a></div></li>
			<li class="prevDone"><div class="text"><a href="#"><?php echo $this->translate("test_schedule"); ?></a></div></li>
		<?php }else{?>
			<li class="prevDone"><div class="text"><a href="#"><?php echo $this->translate("upload_document"); ?></a></div></li>
		<?php }?>
		<li class="lastCurrent"><div class="text"><a href="#"><?php echo $this->translate("confirmation"); ?></a></div></li>	
	</ul>
	<div class="clear"></div>
</div>
			
			
<?php if($this->notice){ ?>

<div style="margin-top: 20px; padding: 0 .7em;" class="ui-state-highlight ui-corner-all">
<p><span style="float: left; margin-right: .3em;" class="ui-icon ui-icon-info"></span>
<?php echo $this->notice; ?></p>
</div>

<?php } ?>

<?if(isset($this->noticeMessage)){?>
<div class="message notice"><strong><? echo $this->noticeMessage;?></strong>.</div>
<?}?>
<?if(isset($this->noticeSuccess)){?>
<div class="message success"><strong><? echo $this->noticeSuccess;?></strong>.</div>
<?}?>
<?if(isset($this->noticeError)){?>
<div class="message error"><strong><? echo $this->noticeError;?></strong>.</div>
<?}?>