<style type="text/css">

.zend_form input[type="text"].mark {
    width: 30px;
}

#ui-datepicker-div
{
    display: none;
}
</style>

<script>
$(document).ready(function()
{   
	if($('#ap_prog_code').val()==""){
		$('#ap_prog_code').empty();
	}
	if($('#ap_prog_code_2').val()==""){
		$('#ap_prog_code_2').empty();
	}

	if($('#ap_prog_code_3').val()==""){
		$('#ap_prog_code_3').empty();
	}
	if($('#ap_prog_code_4').val()==""){
		$('#ap_prog_code_4').empty();
	}
	
    $("#from").datepicker({
        dateFormat: 'MM yy',
        changeMonth: true,
        changeYear: true,
        showButtonPanel: true,
		maxDate: '+0m +0w +1y',
        onClose: function(dateText, inst) {
            var month = $("#ui-datepicker-div .ui-datepicker-month :selected").val();
            var year = $("#ui-datepicker-div .ui-datepicker-year :selected").val();
            $("#from").val($.datepicker.formatDate('MM yy', new Date(year, month, 1)));

            $( "#to" ).datepicker( "option", "minDate", new Date(year, month, 1));
        }
    });

    $("#from").focus(function () {
        $(".ui-datepicker-calendar").hide();
        $("#ui-datepicker-div").position({
            my: "center top",
            at: "center bottom",
            of: $(this)
        });
    });

    $("#to").datepicker({
        dateFormat: 'MM yy',
        changeMonth: true,
        changeYear: true,
        showButtonPanel: true,
        maxDate: '+0m +0w +1y',
        onClose: function(dateText, inst) {
            var month = $("#ui-datepicker-div .ui-datepicker-month :selected").val();
            var year = $("#ui-datepicker-div .ui-datepicker-year :selected").val();
            $("#to").val($.datepicker.formatDate('MM yy', new Date(year, month, 1)));

            //$( "#from" ).datepicker( "option", "maxDate", new Date(year+1, month+1) );
        }
    });

    $("#to").focus(function () {
        $(".ui-datepicker-calendar").hide();
        $("#ui-datepicker-div").position({
            my: "center top",
            at: "center bottom",
            of: $(this)
        });
    });

    //init
    <?php
    if( isset($this->educationData['ae_discipline_code']) ){
    	?>
    	initSubject('<?php echo $this->educationData['ae_discipline_code']; ?>');
    	<?php	
    }
    ?>
    
});
function changeCountry(element){
	var country_id = $('#country').val();
	
	$.ajax({
		url: "<?php echo $this->url(array('module'=>'default','controller'=>'online-application', 'action'=>'ajax-get-state'),'default',true);?>",
		data: {'country_id':country_id},
		type: 'POST',
		dataType: 'json',
		beforeSend: function() {
			showLoading('state','state-element','loading');
		},
		complete: function() {
			hideLoading('loading','state');
		} 	
	}).done(function ( data ) {
		
		$('#state').empty().append('<option value=""> <?php echo $this->translate('please_select'); ?> </option>');
		
		 
		var state = $('#state');
		var append_html = "";
		
		for (var index = 0; index < data.length; index++) {
			append_html += '<option value="'+data[index].idState+'"> '+data[index].StateName+' </option>';
		}	

		state.append(append_html);

	});
}

		
function changeSchool(element){
	var type_id = $('#type').val();
	var state_id = $('#state').val();
	var city_id = $('#city').val();
	
	$.ajax({
		url: "<?php echo $this->url(array('module'=>'default','controller'=>'online-application', 'action'=>'ajax-get-school'),'default',true);?>",
		data: {'school_state_id':state_id,'school_city_id':city_id, 'keyvalue':1},
		type: 'POST',
		dataType: 'json',
		beforeSend: function() {
			showLoading('ae_institution','ae_institution-element','loading');
		},
		complete: function() {
			hideLoading('loading','ae_institution');
		} 	
	}).done(function ( data ) {
		
		$('#ae_institution').empty().append('<option value=""> <?php echo $this->translate('please select'); ?> </option>');
		
		
		var institution = $('#ae_institution');
		var append_html = "";
		//if (data.length==0) {
			//append_html = '<option value="0"> Data Sekolah anda tidak diundang (coba jalur PSSB/USM) </option>'; 	
		//}
		for (var index = 0; index < data.length; index++) {
			append_html += '<option value="'+data[index].sm_id+'"> '+data[index].sm_name+' </option>';
		}	

		institution.append(append_html);

	});
}

 
function changeState(element){
	var type_id = $('#type').val();
	var state_id = $('#state').val(); 
	$.ajax({
		url: "<?php echo $this->url(array('module'=>'default','controller'=>'online-application', 'action'=>'ajax-get-citys'),'default',true);?>",
		data: {'school_state_id':state_id, 'keyvalue':1},
		type: 'POST',
		dataType: 'json',
		beforeSend: function() {
			showLoading('city','city-element','loading');
		},
		complete: function() {
			hideLoading('loading','city');
		} 	
	}).done(function ( data ) {
		
		$('#city').empty().append('<option value=""> <?php echo $this->translate('please_select'); ?> </option>');
		
		 
		var city = $('#city');
		var append_html = "";
		
		for (var index = 0; index < data.length; index++) {
			append_html += '<option value="'+data[index].idCity+'"> '+data[index].CityName+' </option>';
		}	

		city.append(append_html);

	});
}

function showLoading(target,target_div,loading_id){
	$('#'+target).hide();
	$('#'+target_div).append("<div id='"+loading_id+"'><img src='/images/ajax-loader-bar.gif' /></div>");
}

function hideLoading(loading_id,target){
	$('#'+loading_id).remove();
	$('#'+target).show();
}
function getGroupNamePssb(element){
	
	var program_id = $('#ap_prog_code').val();
	 
	$.ajax({
		url: "<?php echo $this->url(array('module'=>'default','controller'=>'online-application', 'action'=>'ajax-get-branch'),'default',true);?>",
		data: {'program_id':program_id,'type':'pssb'},
		type: 'POST',
		dataType: 'json',
		beforeSend: function() {
			showLoading('grouppssb','grouppssb-element','loading');
		},
		complete: function() {
			hideLoading('loading','grouppssb');
			 
		} 	
	}).done(function ( data ) {
		
		$('#grouppssb').empty().append('<option value=""> <?php echo $this->translate('please_select'); ?> </option>');
		
		 
		var grouppssb = $('#grouppssb');
		var append_html = "";
		
		for (var index = 0; index < data.length; index++) {
			append_html += '<option value="'+data[index].IdProgramBranch+'"> '+data[index].GrpMhs+' </option>';
		}	

		grouppssb.append(append_html);
		 
	});
	
}

function getGroupNamePssb2(element){
	
	var program_id = $('#ap_prog_code_2').val();
	 
	$.ajax({
		url: "<?php echo $this->url(array('module'=>'default','controller'=>'online-application', 'action'=>'ajax-get-branch'),'default',true);?>",
		data: {'program_id':program_id,'type':'pssb'},
		type: 'POST',
		dataType: 'json',
		beforeSend: function() {
			showLoading('grouppssb2','grouppssb2-element','loading');
		},
		complete: function() {
			hideLoading('loading','grouppssb2');
		} 	
	}).done(function ( data ) {
		
		$('#grouppssb2').empty().append('<option value=""> <?php echo $this->translate('please_select'); ?> </option>');
		
		 
		var grouppssb = $('#grouppssb2');
		var append_html = "";
		
		for (var index = 0; index < data.length; index++) {
			append_html += '<option value="'+data[index].IdProgramBranch+'"> '+data[index].GrpMhs+' </option>';
		}	

		grouppssb.append(append_html);
		
	});
	//changeProgram3();
}

function getGroupNamePssb3(element){
	
	var program_id = $('#ap_prog_code_3').val();
	 
	$.ajax({
		url: "<?php echo $this->url(array('module'=>'default','controller'=>'online-application', 'action'=>'ajax-get-branch'),'default',true);?>",
		data: {'program_id':program_id,'type':'pssb'},
		type: 'POST',
		dataType: 'json',
		beforeSend: function() {
			showLoading('grouppssb3','grouppssb3-element','loading');
		},
		complete: function() {
			hideLoading('loading','grouppssb3');
		} 	
	}).done(function ( data ) {
		
		$('#grouppssb3').empty().append('<option value=""> <?php echo $this->translate('please_select'); ?> </option>');
		
		 
		var grouppssb = $('#grouppssb3');
		var append_html = "";
		
		for (var index = 0; index < data.length; index++) {
			append_html += '<option value="'+data[index].IdProgramBranch+'"> '+data[index].GrpMhs+' </option>';
		}	

		grouppssb.append(append_html);
		
	});
	//changeProgram4();
	
}

function getGroupNamePssb4(element){
	
	var program_id = $('#ap_prog_code_4').val();
	 
	$.ajax({
		url: "<?php echo $this->url(array('module'=>'default','controller'=>'online-application', 'action'=>'ajax-get-branch'),'default',true);?>",
		data: {'program_id':program_id,'type':'pssb'},
		type: 'POST',
		dataType: 'json',
		beforeSend: function() {
			showLoading('grouppssb4','grouppssb4-element','loading');
		},
		complete: function() {
			hideLoading('loading','grouppssb4');
		} 	
	}).done(function ( data ) {
		
		$('#grouppssb4').empty().append('<option value=""> <?php echo $this->translate('please_select'); ?> </option>');
		
		 
		var grouppssb = $('#grouppssb4');
		var append_html = "";
		
		for (var index = 0; index < data.length; index++) {
			append_html += '<option value="'+data[index].IdProgramBranch+'"> '+data[index].GrpMhs+' </option>';
		}	

		grouppssb.append(append_html);

	});
}

function changeDiscipline(element){
	
	$.ajax({
		url: "<?php echo $this->url(array('module'=>'default','controller'=>'online-application', 'action'=>'ajax-get-discipline'),'default',true);?>",
		data: {'school_type_id':$(element).val()},
		type: 'POST',
		dataType: 'json',
		beforeSend: function() {
			showLoading('ae_discpline','ae_discpline-element','loading');
		},
		complete: function() {
			hideLoading('loading','ae_discpline');
		} 		
	}).done(function ( data ) {
		
		$('#ae_discpline').empty().append('<option value=""> <?php echo $this->translate('please_select'); ?> </option>');
	
		$.each(data, function(index) {
			$('#ae_discpline').append('<option value="'+data[index].smd_code+'"> '+data[index].smd_desc+' </option>');
		});
	});
}

function validateSchool(element){

	type=$(element).val();
	$('#subject_list').show();

	$('#subject_list').empty();
	
	$('#subject_list').append(	
		$('<table id="subject" class="table" width="50%">')
			.append($('<thead>')
				.append($('<tr>')
	        		.append($('<th rowspan="1">').text("<?php echo $this->translate("Subjects"); ?>"))
	            	.append($('<th colspan="1">').text("<?php echo $this->translate("Mark"); ?>")) 
	        	)
	        	 
	        )
            .append($('<tbody>'))
	);

	$.ajax({
		url: "<?php echo $this->url(array('module'=>'default','controller'=>'online-application', 'action'=>'ajax-get-discipline-subject'),'default',true);?>",
		data: {'discipline_code':$(element).val(),'appltype':"7",'type':type,'placecode':<?php echo $this->placementcode; ?>},
		type: 'POST',
		dataType: 'json'	
	}).done(function ( data ) {
		$('#subject').find('tbody').html("");
		
		$.each(data, function(index) {
			var compulsary = "";

			if(data[index].ss_core_subject==1){
				compulsary = "*";
			}
				
			$('#subject').find('tbody')
				.append($('<tr>')
					.append($('<td>').html('<input type="hidden" name="aed_subject_id[]" value="'+data[index].ac_comp_code+'" />'+data[index].subjectname+compulsary))
	        		.append($('<td align="center">').html('<input type="text" class="mark"  maxlength="3" name="aed_mark[]" value="'+ (data[index].mark) +'" />')) 
	             )
		});
	});

	changeProgram($(element).val());
}

function initSubject(discipline_code){
	
	 programs[0]=$('#ap_prog_code').val();
	 programs[1]=$('#ap_prog_code2').val();
	 programs[2]=$('#ap_prog_code3').val();
	 programs[3]=$('#ap_prog_code4').val();

	$('#subject_list').append(	
		$('<table id="subject" class="table" width="50%">')
			.append($('<thead>')
				.append($('<tr>')
	        		.append($('<th rowspan="2">').text("<?php echo $this->translate("Subjects"); ?>"))
	            	.append($('<th colspan="2">').text("<?php echo $this->translate("Mark"); ?>")) 
	        	)
	        	 
	        )
            .append($('<tbody>'))
	);
	
	$.ajax({
		url: "<?php echo $this->url(array('module'=>'default','controller'=>'online-application', 'action'=>'ajax-get-discipline-subject'),'default',true);?>",
		data: {'discipline_code':discipline_code,'appltype':"7",'programs':programs,'placecode':<?php echo $this->placementcode; ?>},
		type: 'POST',
		dataType: 'json'	
	}).done(function ( data ) {
		$('#subject').find('tbody').html("");
		
		$.each(data, function(index) {
			var compulsary = "";

			if(data[index].ss_core_subject==1){
				compulsary = "*";
			}
				
			$('#subject').find('tbody')
				.append($('<tr>')
					.append($('<td>').html('<input type="hidden" name="aed_subject_id[]" value="'+data[index].sds_subject+'" />'+data[index].ss_subject+compulsary))
	        		.append($('<td align="center">').html('<input type="text" class="mark"  maxlength="3" name="aed_sem[]" value="'+ (data[index].aed_sem  ? data[index].aed_sem  : "") +'" />'))
	             )
		});

		calculate_average();
	});

	$('#subject_list').show();
}

 

function roundNumber(num, dec) {
	var result = Math.round(num*Math.pow(10,dec))/Math.pow(10,dec);
	return result;
}

function changeProgram(discipline){

	var prog4=$('#ap_prog_code4').val();
	var prog2=$('#ap_prog_code2').val();
	var prog3=$('#ap_prog_code3').val();
	
	$('#ap_prog_code').empty();
	var school=$('#ae_institution').val();
	var intake=$('#intake_id').val();
	var discipline=$('#ae_discpline').val();
	
	//alert("online-application/ajax-get-programme-invitation/discipline_code/"+discipline+"/intake_id/"+intake+"/school/"+school);
	
	if (discipline!="" && intake!="" ){
		$.ajax({
			url: "<?php echo $this->url(array('module'=>'default','controller'=>'online-application', 'action'=>'ajax-get-programme-utbk'),'default',true);?>",
			data: {'discipline_code':discipline,'intake_id':intake,'school':school,'prog2':prog2,'prog3':prog3,'prog4':prog4},
			type: 'POST',
			dataType: 'json',
			beforeSend: function() {
				showLoading('ap_prog_code','ap_prog_code-element','loading');
			},
			complete: function() {
				hideLoading('loading','ap_prog_code');
			} 
		}).done(function ( data ) {
			
			$('#ap_prog_code').empty().append('<option value=""> <?php echo $this->translate('please_select'); ?> </option>');
			
			<?php 
			$registry = Zend_Registry::getInstance();
			$locale = $registry->get('Zend_Locale');
			
			if ($locale=="en_US"){
			?>
				$.each(data, function(index) {
					$('#ap_prog_code').append('<option value="'+data[index].ProgramCode+'"> '+data[index].ProgramName+' ('+data[index].strata+') </option>');
				});
			<?php 	
			}else 
			if ($locale=="id_ID"){
			?>
				$.each(data, function(index) {
					$('#ap_prog_code').append('<option value="'+data[index].ProgramCode+'"> '+data[index].ArabicName+' ('+data[index].strata+')</option>');
				});
			<?php 
			}
			?>
			//changeProgram2();
			//initSubject(discipline);
		});
		
	}
	
}
function changeProgram2(){


	var prog1=$('#ap_prog_code').val();
	var prog4=$('#ap_prog_code_4').val();
	var prog3=$('#ap_prog_code_3').val();
	
	var discipline = $('#ae_discpline').val();
	var intake=$('#intake_id').val();
	var school=$("#ae_institution").val();
	if(discipline!="" && intake!=""){
		$.ajax({
			url: "<?php echo $this->url(array('module'=>'default','controller'=>'online-application', 'action'=>'ajax-get-programme-utbk'),'default',true);?>",
			data: {'discipline_code':discipline,'prog':prog1,'intake_id':intake,'school':school ,'prog3':prog3,'prog4':prog4},
			type: 'POST',
			dataType: 'json',
			beforeSend: function() {
				showLoading('ap_prog_code_2','ap_prog_code_2-element','loading');
			},
			complete: function() {
				hideLoading('loading','ap_prog_code_2');
			}  	
		}).done(function ( data ) {
			
			//$('#ap_prog_code').empty().append('<option value=""> <?php echo $this->translate('please_select'); ?> </option>');
			$('#ap_prog_code_2').empty().append('<option value=""> <?php echo $this->translate('please_select'); ?> </option>');
			 
			<?php 
			$registry = Zend_Registry::getInstance();
			$locale = $registry->get('Zend_Locale');
			
			if ($locale=="en_US"){
			?>
				$.each(data, function(index) {
					$('#ap_prog_code_2').append('<option value="'+data[index].ProgramCode+'"> '+data[index].ProgramName+' ('+data[index].strata+') </option>');
				});
			<?php 	
			}else 
			if ($locale=="id_ID"){
			?>
				$.each(data, function(index) {
					$('#ap_prog_code_2').append('<option value="'+data[index].ProgramCode+'"> '+data[index].ArabicName+' ('+data[index].strata+')</option>');
				});
			<?php 
			}
			?>
			//initSubject(discipline);
		});

		
	}
}

function changeProgram3(){

	var prog1=$('#ap_prog_code').val();
	var prog2=$('#ap_prog_code_2').val();
	var prog4=$('#ap_prog_code_4').val();

	
	var discipline = $('#ae_discpline').val();
	var intake=$('#intake_id').val();
	var school=$("#ae_institution").val();
	if(discipline!="" && intake!=""){
		$.ajax({
			url: "<?php echo $this->url(array('module'=>'default','controller'=>'online-application', 'action'=>'ajax-get-programme-utbk'),'default',true);?>",
			data: {'discipline_code':discipline,'prog':prog1,'prog2':prog2,'prog4':prog4,'intake_id':intake,'school':school},
			type: 'POST',
			dataType: 'json',
			beforeSend: function() {
				showLoading('ap_prog_code_3','ap_prog_code_3-element','loading');
			},
			complete: function() {
				hideLoading('loading','ap_prog_code_3');
			}  	
		}).done(function ( data ) {
			
			$('#ap_prog_code_3').empty().append('<option value=""> <?php echo $this->translate('please_select'); ?> </option>');
			  
			<?php 
			$registry = Zend_Registry::getInstance();
			$locale = $registry->get('Zend_Locale');
			
			if ($locale=="en_US"){
			?>
				$.each(data, function(index) {
					$('#ap_prog_code_3').append('<option value="'+data[index].ProgramCode+'"> '+data[index].ProgramName+' ('+data[index].strata+') </option>');
				});
			<?php 	
			}else 
			if ($locale=="id_ID"){
			?>
				$.each(data, function(index) {
					$('#ap_prog_code_3').append('<option value="'+data[index].ProgramCode+'"> '+data[index].ArabicName+' ('+data[index].strata+')</option>');
				});
			<?php 
			}
			?>
			//initSubject(discipline);
		});
		 
	}
}
function changeProgram4(){

	var prog1=$('#ap_prog_code').val();
	var prog2=$('#ap_prog_code_2').val();
	var prog3=$('#ap_prog_code_3').val();
	
	var discipline = $('#ae_discpline').val();
	var intake=$('#intake_id').val();
	var school=$("#ae_institution").val();
	if(discipline!="" && intake!=""){
		$.ajax({
			url: "<?php echo $this->url(array('module'=>'default','controller'=>'online-application', 'action'=>'ajax-get-programme-utbk'),'default',true);?>",
			data: {'discipline_code':discipline,'prog':prog1,'prog2':prog2,'prog3':prog3,'intake_id':intake,'school':school},
			type: 'POST',
			dataType: 'json',
			beforeSend: function() {
				showLoading('ap_prog_code_4','ap_prog_code_4-element','loading');
			},
			complete: function() {
				hideLoading('loading','ap_prog_code_4');
			}  	
		}).done(function ( data ) {
			 $('#ap_prog_code_4').empty().append('<option value=""> <?php echo $this->translate('please_select'); ?> </option>');
			 
			<?php 
			$registry = Zend_Registry::getInstance();
			$locale = $registry->get('Zend_Locale');
			
			if ($locale=="en_US"){
			?>
				$.each(data, function(index) {
					$('#ap_prog_code_4').append('<option value="'+data[index].ProgramCode+'"> '+data[index].ProgramName+' ('+data[index].strata+') </option>');
				});
			<?php 	
			}else 
			if ($locale=="id_ID"){
			?>
				$.each(data, function(index) {
					$('#ap_prog_code_4').append('<option value="'+data[index].ProgramCode+'"> '+data[index].ArabicName+' ('+data[index].strata+')</option>');
				});
			<?php 
			}
			?>
			//initSubject(discipline);
		});
		 
	}
}
</script>

<div class="breadcrum">
	<ul class="tri-steps">
		<li class="empty"><div class="text"><a href="<?php echo $this->url(array('module'=>'default','controller'=>'online-application','action'=>'biodata'),'default',true);?>"><?php echo $this->translate("biodata"); ?></a></div></li>
		
		<?php if($this->transaction["entry_type"]!=2){ //case agent(manual entry- which is already have no peserta/choose admission type)?>
		<li class="empty"><div class="text"><a href="<?php echo $this->url(array('module'=>'default','controller'=>'online-application','action'=>'contactinfo'),'default',true);?>"><?php echo $this->translate("contact_info"); ?></a></div></li>
		<li class="prevDone"><div class="text"><a href="<?php echo $this->url(array('module'=>'default','controller'=>'online-application','action'=>'admission'),'default',true);?>"><?php echo $this->translate("Admission Type"); ?></a></div></li>
		<?php }else{ //end admission?>
		<li class="prevDone"><div class="text"><a href="<?php echo $this->url(array('module'=>'default','controller'=>'online-application','action'=>'contactinfo'),'default',true);?>"><?php echo $this->translate("contact_info"); ?></a></div></li>
		<?php }//end else?>
		<li class="current"><div class="text"><a href="<?php echo $this->url(array('module'=>'default','controller'=>'online-application','action'=>'programme'),'default',true);?>"><?php echo $this->translate("programme"); ?></a></div></li>
		<li class="empty"><div class="text"><a href="<?php echo $this->url(array('module'=>'default','controller'=>'online-application','action'=>'uploaddocument'),'default',true);?>"><?php echo $this->translate("upload_document"); ?></a></div></li>
		<?php if($this->transaction['at_appl_type']=='1'){?>
		<li class="empty"><div class="text"><a href="<?php echo $this->url(array('module'=>'default','controller'=>'online-application','action'=>'uploaddocument'),'default',true);?>"><?php echo $this->translate("test_schedule"); ?></a></div></li>
		<?php }?>
		<li class="last"><div class="text"><a href="<?php echo $this->url(array('module'=>'default','controller'=>'online-application','action'=>'confirmation'),'default',true);?>"><?php echo $this->translate("confirmation"); ?></a></div></li>	
	</ul>
	<div class="clear"></div>
</div>
<?php if(isset($this->noticeMessage)){?>
<div class="message notice"><strong><?php echo $this->noticeMessage;?></strong>.</div>
<?php }?>
<?php if(isset($this->noticeSuccess)){?>
<div class="message success"><strong><?php echo $this->noticeSuccess;?></strong>.</div>
<?php }?>
<?php if(isset($this->noticeError)){?>
<div class="message error"><strong><?php echo $this->noticeError;?></strong>.</div>
<?php }?>


<div class="message toolbar">
	<h2><?php echo $this->title; ?></h2>
	<div class="toolbar-button">
		
	</div>
</div>

<?php if( isset($this->education_selected) && isset($this->education_selected) && $this->placementcode!=''){?>
<fieldset>
	<table>
		<tr>
			<td width="120px"><?php echo $this->translate("School Name");?></td>
			<td>:</td>
			<td><?php echo $this->education_selected['sm_name'];?> (<?php echo date('F Y', strtotime($this->education_selected['ae_year_from']));?> - <?php echo date('F Y', strtotime($this->education_selected['ae_year_end']));?>)</td>
		</tr>
		<tr>
			<td><?php echo $this->translate("Jurusan");?></td>
			<td>:</td>
			<td><?php echo $this->education_selected['smd_desc'];?></td>
		</tr>
		<tr>
			<td valign="top"><?php echo $this->translate("Prefered Programme");?></td>
			<td valign="top">:</td>
			<td>
				<ol>
					<?php 
						if(isset($this->programe_selected) && sizeof($this->programe_selected) > 0 ){
							foreach ($this->programe_selected as $programe){
								echo "<li>";
								echo $programe['program_name_indonesia'].' - '.$programe['kelas'];
								echo "</li>";	
							}
						}
					?>
				</ol>
			</td>
		</tr>
		 
	</table>
	<br />
	<input type="button" value="<?php echo $this->translate("Continue"); ?>" onclick="window.location = '<?php echo $this->url(array('module'=>'default','controller'=>'online-application','action'=>'uploaddocument'),'default',true);?>' " />
</fieldset>
<?php }?>


<?php if ($this->placementcode=='') echo $this->translate('This selection is not opened yet');
else echo $this->form; ?>
 