<script>
$(document).ready(function()
{   
    $("#from").datepicker({
        dateFormat: 'MM yy',
        changeMonth: true,
        changeYear: true,
        showButtonPanel: true,

        onClose: function(dateText, inst) {
            var month = $("#ui-datepicker-div .ui-datepicker-month :selected").val();
            var year = $("#ui-datepicker-div .ui-datepicker-year :selected").val();
            $("#from").val($.datepicker.formatDate('MM yy', new Date(year, month, 1)));

            //$( "#to" ).datepicker( "option", "minDate", new Date(year, month));
        }
    });

    $("#from").focus(function () {
        $(".ui-datepicker-calendar").hide();
        $("#ui-datepicker-div").position({
            my: "center top",
            at: "center bottom",
            of: $(this)
        });
    });

    $("#to").datepicker({
        dateFormat: 'MM yy',
        changeMonth: true,
        changeYear: true,
        showButtonPanel: true,
        
        onClose: function(dateText, inst) {
            var month = $("#ui-datepicker-div .ui-datepicker-month :selected").val();
            var year = $("#ui-datepicker-div .ui-datepicker-year :selected").val();
            $("#to").val($.datepicker.formatDate('MM yy', new Date(year, month, 1)));

            //$( "#from" ).datepicker( "option", "maxDate", new Date(year, month) );
        }
    });

    $("#to").focus(function () {
        $(".ui-datepicker-calendar").hide();
        $("#ui-datepicker-div").position({
            my: "center top",
            at: "center bottom",
            of: $(this)
        });
    });    
});


function changeSchool(element){
	var type_id = $('#type').val();
	var state_id = $('#state').val();
	var city_id = $('#city').val();
	$.ajax({
		url: "<?php echo $this->url(array('module'=>'default','controller'=>'online-application', 'action'=>'ajax-get-school'),'default',true);?>",
		data: {'school_state_id':state_id,'school_city_id':city_id, 'keyvalue':1},
		type: 'POST',
		dataType: 'json',
		beforeSend: function() {
			showLoading('ae_institution','ae_institution-element','loading');
		},
		complete: function() {
			hideLoading('loading','ae_institution');
		} 	
	}).done(function ( data ) {
		
		$('#ae_institution').empty().append('<option value=""> <?php echo $this->translate('please_select'); ?> </option>');
		
		 
		var institution = $('#ae_institution');
		var append_html = "";
		
		for (var index = 0; index < data.length; index++) {
			append_html += '<option value="'+data[index].sm_id+'"> '+data[index].sm_name+' </option>';
		}	

		institution.append(append_html);

	});
}
function changeSchoolPdpt(element){
	//var type_id = $('#type').val();
	//var state_id = $('#state').val();
	var city_id = $('#city').val();
	$.ajax({
		url: "<?php echo $this->url(array('module'=>'default','controller'=>'online-application', 'action'=>'ajax-get-school-pdpt'),'default',true);?>",
		data: {'school_city_id':city_id},
		type: 'POST',
		dataType: 'json',
		beforeSend: function() {
			showLoading('ae_pt','ae_pt-element','loading');
		},
		complete: function() {
			hideLoading('loading','ae_pt');
		} 	
	}).done(function ( data ) {
		
		$('#ae_pt').empty().append('<option value=""> <?php echo $this->translate('please_select'); ?> </option>');
		
		 
		var pt = $('#ae_pt');
		var append_html = "";
		
		for (var index = 0; index < data.length; index++) {
			append_html += '<option value="'+data[index].id_sp+'"> '+data[index].nm_sp+' </option>';
		}	
		//alert(append_html);
		pt.append(append_html);

	});
}

function changeState(element){
	var state_id = $('#state').val();
	
	$.ajax({
		url: "<?php echo $this->url(array('module'=>'default','controller'=>'online-application', 'action'=>'ajax-get-city'),'default',true);?>",
		data: {'state_id':state_id},
		type: 'POST',
		dataType: 'json',
		beforeSend: function() {
			showLoading('city','city-element','loading');
		},
		complete: function() {
			hideLoading('loading','city');
		} 	
	}).done(function ( data ) {
		
		$('#city').empty().append('<option value=""> <?php echo $this->translate('please_select'); ?> </option>');
		
		 
		var city = $('#city');
		var append_html = "";
		
		for (var index = 0; index < data.length; index++) {
			append_html += '<option value="'+data[index].idCity+'"> '+data[index].CityName+' </option>';
		}	

		city.append(append_html);

	});
}
function changeProdi(element){

	var idpt = $('#ae_pt').val();
	//alert("online-application/'ajax-get-prodi-pdpt/d_pt/"+idpt);
	$.ajax({
		url: "<?php echo $this->url(array('module'=>'default','controller'=>'online-application', 'action'=>'ajax-get-prodi-pdpt'),'default',true);?>",
		data: {'id_pt':idpt},
		type: 'POST',
		dataType: 'json',
		beforeSend: function() {
			showLoading('ae_institution','ae_institution-element','loading');
		},
		complete: function() {
			hideLoading('loading','ae_institution');
		} 	
	}).done(function ( data ) {
		
		$('#ae_institution').empty().append('<option value=""> <?php echo $this->translate('please_select'); ?> </option>');
		
		 
		var ae_institution = $('#ae_institution');
		var append_html = "";
		
		for (var index = 0; index < data.length; index++) {
			append_html += '<option value="'+data[index].key+'"> '+data[index].value+' ('+data[index].nm_jenjang+ ') </option>';
		}	

		ae_institution.append(append_html);

	});
}

function changeStatePdpt(element){
	var country_id = $('#country').val();
	
	$.ajax({
		url: "<?php echo $this->url(array('module'=>'default','controller'=>'online-application', 'action'=>'ajax-get-state-pdpt'),'default',true);?>",
		data: {'country_id':country_id},
		type: 'POST',
		dataType: 'json',
		beforeSend: function() {
			showLoading('state','state-element','loading');
		},
		complete: function() {
			hideLoading('loading','state');
		} 	
	}).done(function ( data ) {
		
		$('#state').empty().append('<option value=""> <?php echo $this->translate('please_select'); ?> </option>');
		
		 
		var city = $('#state');
		var append_html = "";
		
		for (var index = 0; index < data.length; index++) {
			append_html += '<option value="'+data[index].id_wil+'"> '+data[index].nm_wilayah+' </option>';
		}	

		city.append(append_html);

	});
}

function changeCityPdpt(element){
	var state_id = $('#state').val();
	
	$.ajax({
		url: "<?php echo $this->url(array('module'=>'default','controller'=>'online-application', 'action'=>'ajax-get-city-pdpt'),'default',true);?>",
		data: {'state_id':state_id},
		type: 'POST',
		dataType: 'json',
		beforeSend: function() {
			showLoading('city','city-element','loading');
		},
		complete: function() {
			hideLoading('loading','city');
		} 	
	}).done(function ( data ) {
		
		$('#city').empty().append('<option value=""> <?php echo $this->translate('please_select'); ?> </option>');
		
		 
		var city = $('#city');
		var append_html = "";
		
		
		for (var index = 0; index < data.length; index++) {
			append_html += '<option value="'+data[index].id_wil+'"> '+data[index].nm_wilayah+' </option>';
		}	

		city.append(append_html);

	});
}

function getGroupName(element){
	
	var program_id = $('#app_id').val();
	 
	$.ajax({
		url: "<?php echo $this->url(array('module'=>'default','controller'=>'online-application', 'action'=>'ajax-get-branch'),'default',true);?>",
		data: {'program_id':program_id,'type':'usm'},
		type: 'POST',
		dataType: 'json',
		beforeSend: function() {
			showLoading('group1','group1-element','loading');
		},
		complete: function() {
			hideLoading('loading','group1');
		} 	
	}).done(function ( data ) {
		
		$('#group1').empty().append('<option value=""> <?php echo $this->translate('please_select'); ?> </option>');
		
		 
		var group1 = $('#group1');
		var append_html = "";
		
		for (var index = 0; index < data.length; index++) {
			append_html += '<option value="'+data[index].IdProgramBranch+'"> '+data[index].GrpMhs+' </option>';
		}	

		group1.append(append_html);

	});
}

function getGroupName2(element){
	var program_id = $('#app_id2').val();
	
	$.ajax({
		url: "<?php echo $this->url(array('module'=>'default','controller'=>'online-application', 'action'=>'ajax-get-branch'),'default',true);?>",
		data: {'program_id':program_id,'type':'usm'},
		type: 'POST',
		dataType: 'json',
		beforeSend: function() {
			showLoading('group2','group2-element','loading');
		},
		complete: function() {
			hideLoading('loading','group2');
		} 	
	}).done(function ( data ) {
		
		$('#group2').empty().append('<option value=""> <?php echo $this->translate('please_select'); ?> </option>');
		
		 
		var group2 = $('#group2');
		var append_html = "";
		
		for (var index = 0; index < data.length; index++) {
			append_html += '<option value="'+data[index].IdProgramBranch+'"> '+data[index].GrpMhs+' </option>';
		}	
 
		group2.append(append_html);

	});
}
 
function showLoading(target,target_div,loading_id){
	$('#'+target).hide();
	$('#'+target_div).append("<div id='"+loading_id+"'><img src='/images/ajax-loader-bar.gif' /></div>");
}

function hideLoading(loading_id,target){
	$('#'+loading_id).remove();
	$('#'+target).show();
}

function changeDiscipline(element){
	
	$.ajax({
		url: "<?php echo $this->url(array('module'=>'default','controller'=>'online-application', 'action'=>'ajax-get-discipline'),'default',true);?>",
		data: {'school_type_id':$(element).val()},
		type: 'POST',
		dataType: 'json',
		beforeSend: function() {
			showLoading('ae_discpline','ae_discpline-element','loading');
		},
		complete: function() {
			hideLoading('loading','ae_discpline');
		} 		
	}).done(function ( data ) {
		
		$('#ae_discpline').empty().append('<option value=""> <?php echo $this->translate('please_select'); ?> </option>');
	
		$.each(data, function(index) {
			$('#ae_discpline').append('<option value="'+data[index].smd_code+'"> '+data[index].smd_desc+' </option>');
		});
	});
}

function changeSchoolWithoutType(element){
	var state_id = $('#state').val();
	
	$.ajax({
		url: "<?php echo $this->url(array('module'=>'default','controller'=>'online-application', 'action'=>'ajax-get-school'),'default',true);?>",
		data: {'school_state_id':state_id},
		type: 'POST',
		dataType: 'json'	
	}).done(function ( data ) {
		
		$('#ae_institution').empty().append('<option value=""> <?php echo $this->translate('please_select'); ?> </option>');
	
		$.each(data, function(index) {
			$('#ae_institution').append('<option value="'+data[index].sm_id+'"> '+data[index].sm_name+' </option>');
		});
	});

}


function changeProgramme(element){
	$('#app_id').empty().append('<option value=""> <?php echo $this->translate('please_select'); ?> </option>');
	$('#app_id2').empty().append('<option value=""> <?php echo $this->translate('please_select'); ?> </option>');
	
	$.ajax({
		url: "<?php echo $this->url(array('module'=>'default','controller'=>'online-application', 'action'=>'ajax-get-programme-pt'),'default',true);?>",
		data: {'discipline_code':$("#ae_discpline").val(),'intake_id':$("#intake_id).val(),'ae_year_end':$("#ae_year_end").val() },
		type: 'POST',
		dataType: 'json'	
	}).done(function ( data ) {
		
		
		<?php
			//this is to display programme name based on current locale
			$registry = Zend_Registry::getInstance();
			$locale = $registry->get('Zend_Locale');
			if ($locale=="en_US"){
		?>
		$.each(data, function(index) {
			$('#app_id').append('<option value="'+data[index].app_id+'"> '+data[index].ProgramName+' ('+data[index].strata+') </option>');
		});

		$.each(data, function(index) {
			$('#app_id2').append('<option value="'+data[index].app_id+'"> '+data[index].ProgramName+' ('+data[index].strata+') </option>');
		});
		<?php 
			}else if ($locale=="id_ID"){
		?>
		$.each(data, function(index) {
			$('#app_id').append('<option value="'+data[index].app_id+'"> '+data[index].ArabicName+' ('+data[index].strata+') </option>');
		});

		$.each(data, function(index) {
			$('#app_id2').append('<option value="'+data[index].app_id+'"> '+data[index].ArabicName+' ('+data[index].strata+') </option>');
		});
		
		<?php }?>
		
	});
}
</script>

<div class="breadcrum">
	<ul class="tri-steps">
		<li class="empty"><div class="text"><a href="<?php echo $this->url(array('module'=>'default','controller'=>'online-application','action'=>'biodata'),'default',true);?>"><?php echo $this->translate("biodata"); ?></a></div></li>
		
		<?php if($this->transaction['at_appl_type']=='1'){?>
		<li class="empty"><div class="text"><a href="<?php echo $this->url(array('module'=>'default','controller'=>'online-application','action'=>'contactinfo'),'default',true);?>"><?php echo $this->translate("contact_info"); ?></a></div></li>
		
			<?php if($this->transaction["entry_type"]!=2){ //case agent(manual entry- which is already have no peserta/choose admission type)?>
			<li class="empty"><div class="text"><a href="<?php echo $this->url(array('module'=>'default','controller'=>'online-application','action'=>'admission'),'default',true);?>"><?php echo $this->translate("Admission Type"); ?></a></div></li>
			<?php }//end admission ?>
		<li class="prevDone"><div class="text"><a href="<?php echo $this->url(array('module'=>'default','controller'=>'online-application','action'=>'placement-test'),'default',true);?>"><?php echo $this->translate("test_schedule"); ?></a></div></li>
		
		<?php }else{?>
		
		<li class="empty"><div class="text"><a href="<?php echo $this->url(array('module'=>'default','controller'=>'online-application','action'=>'contactinfo'),'default',true);?>"><?php echo $this->translate("contact_info"); ?></a></div></li>
			
			<?php if($this->transaction["entry_type"]!=2){ //case agent(manual entry- which is already have no peserta/choose admission type)?>
			<li class="empty"><div class="text"><a href="<?php echo $this->url(array('module'=>'default','controller'=>'online-application','action'=>'admission'),'default',true);?>"><?php echo $this->translate("Admission Type"); ?></a></div></li>
			<?php }//end admission ?>
		<li class="prevDone"><div class="text"><a href="<?php echo $this->url(array('module'=>'default','controller'=>'online-application','action'=>'placement-test'),'default',true);?>"><?php echo $this->translate("test_schedule"); ?></a></div></li>
		<?php }?>
		
		<li class="current"><div class="text"><a href="<?php echo $this->url(array('module'=>'default','controller'=>'online-application','action'=>'programme'),'default',true);?>"><?php echo $this->translate("programme"); ?></a></div></li>
		<li class="empty"><div class="text"><a href="<?php echo $this->url(array('module'=>'default','controller'=>'online-application','action'=>'uploaddocument'),'default',true);?>"><?php echo $this->translate("upload_document"); ?></a></div></li>
		<li class="last"><div class="text"><a href="<?php echo $this->url(array('module'=>'default','controller'=>'online-application','action'=>'uploaddocument'),'default',true);?>"><?php echo $this->translate("confirmation"); ?></a></div></li>	
	</ul>
	<div class="clear"></div>
</div>

<?php if(isset($this->noticeMessage)){?>
<div class="message notice"><strong><?php  echo $this->noticeMessage;?></strong>.</div>
<?php }?>
<?php if(isset($this->noticeSuccess)){?>
<div class="message success"><strong><?php echo $this->noticeSuccess;?></strong>.</div>
<?php }?>
<?php if(isset($this->noticeError)){?>
<div class="message error"><strong><?php echo $this->noticeError;?></strong>.</div>
<?php }?>

<div class="message toolbar">
	<h2><?php echo $this->title; ?></h2>
	<div class="toolbar-button">
		
	</div>
</div>

<?php if( isset($this->education_selected) && isset($this->education_selected) ){?>
<fieldset>
	<table>
		<tr>
			<td width="120px"><?php echo $this->translate("School Name");?></td>
			<td>:</td>
			<td><?php echo $this->education_selected['sm_name'];?> (<?php echo date('F Y', strtotime($this->education_selected['ae_year_from']));?> - <?php echo date('F Y', strtotime($this->education_selected['ae_year_end']));?>)</td>
		</tr>
		<tr>
			<td><?php echo $this->translate("Jurusan");?></td>
			<td>:</td>
			<td><?php echo $this->education_selected['smd_desc'];?></td>
		</tr>
		<tr>
			<td valign="top"><?php echo $this->translate("Prefered Programme");?></td>
			<td valign="top">:</td>
			<td>
				<ol>
					<?php 
						if(isset($this->programe_selected) && sizeof($this->programe_selected) > 0 ){
							foreach ($this->programe_selected as $programe){
								echo "<li>";
								echo $programe['program_name_indonesia'].' - '.$programe['kelas'];
								echo "</li>";	
							}
						}
					?>
				</ol>
			</td>
		</tr>
	</table>
	<br />
	<input type="button" value="<?php echo $this->translate("Continue"); ?>" onclick="window.location = '<?php echo $this->url(array('module'=>'default','controller'=>'online-application','action'=>'uploaddocument'),'default',true);?>' " />
</fieldset>
<?php }?>

<?php echo $this->form; ?>