 
 
 
<div class="message toolbar">
	<h2><?php echo $this->title; ?></h2>
	<div class="toolbar-button">
		
	</div>
</div>

<?php if(isset($this->noticeMessage)){?>
<div class="message notice"><strong><?php echo $this->noticeMessage;?></strong>.</div>
<?php }?>
<?php if(isset($this->noticeSuccess)){?>
<div class="message success"><strong><?php echo $this->noticeSuccess;?></strong>.</div>
<?php }?>
<?php if(isset($this->noticeError)){?>
<div class="message error"><strong><?php echo $this->noticeError;?></strong>.</div>
<?php }?>
 
 <table class="table">
 <tr><th>Nama Pembayaran</th><td><?php echo 'Pendaftaran Ujian Saringan Masuk Usakti'?></td></tr>
 <tr><th>Nomor Pembayaran</th><td bgcolor="white"><?php if ($this->invoice['va']!='') echo $this->invoice['va']; else echo '<a href="/online-application/push-e-collection/trxid/'.$this->transactionid.'/invoice/'.$this->invoice['no_fomulir'].'/re/1">Buat Nomor Pembayaran</a>'?></td></tr>
 <tr><th>Besar Pembayaran</th><td bgcolor="white"><?php echo $this->invoice['bill_amount']?></td></tr>
 <tr><th>Batas Waktu Pembayaran</th><td bgcolor="white"><?php echo date('d-m-Y h:s:i',strtotime($this->invoice['va_expired_dt']))?></td></tr>
 <tr><th>Dapat Dibayar di ATM</th><td>BNI46, BRI, MANDIRI</td></tr>
 
 
 </table>
 Silahkan dilakukan pembayaran menggunakan nomor pembayaran. Setelah pembayaran dilakukan, kartu peserta ujian dapat dibuat dan diunduh