 
<script>
 function savevoucher(element) {

	 $("#voucherform").submit();
	 
 }


 </script>
 
<div class="message toolbar">
	<h2><?php echo $this->title; ?></h2>
	<div class="toolbar-button">
		
	</div>
</div>

<?php if(isset($this->noticeMessage)){?>
<div class="message notice"><strong><?php echo $this->noticeMessage;?></strong>.</div>
<?php }?>
<?php if(isset($this->noticeSuccess)){?>
<div class="message success"><strong><?php echo $this->noticeSuccess;?></strong>.</div>
<?php }?>
<?php if(isset($this->noticeError)){?>
<div class="message error"><strong><?php echo $this->noticeError;?></strong>.</div>
<?php }?>
 
 <table class="table">
 <tr><th>Nama Pembayaran</th><td><?php echo 'Pendaftaran Ujian Saringan Masuk Usakti'?></td></tr>
 <tr><th>Nomor Pembayaran</th><td bgcolor="white">
 	<?php if (isset($this->invoice['va'])) {
 						if ($this->invoice['va']!='') 
 							echo $this->invoice['va']; 
 						else 
 							echo '<a href="/online-application/push-e-collection/trxid/'.$this->transactionid.'/invoice/'.$this->invoice['id'].'/re/1">Buat Nomor Pembayaran</a>';
 		}
 	?></td></tr>
 <tr><th>Besar Pembayaran</th><td bgcolor="white"><?php echo $this->invoice['bill_amount']-$this->invoice['cn_amount']?></td></tr>
 <tr><th>Batas Waktu Pembayaran</th><td bgcolor="white"><?php if ($this->invoice['va_expired_dt']!="") echo date('d-m-Y H:s:i',strtotime($this->invoice['va_expired_dt']))?></td></tr>
 <tr><th>Dapat Dibayar di ATM</th><td>Virtual Account BNI46 sedangkan untuk bank lain dilakukan dengan cara transfer ke nomor VA tersebut</td></tr>
 
 
 </table>
 <br>
 Silahkan dilakukan pembayaran menggunakan nomor pembayaran. Setelah pembayaran dilakukan, kartu peserta ujian dapat dibuat dan diunduh
 <br><br>
 <fieldset><legend><?php echo $this->translate("Voucher (if any)");?></legend>
 <form name="voucherform" id="voucherform" method="post">
 	Masukan kode voucher yang anda miliki <input type="text" name="voucher" id="voucher" size="20" onblur="savevoucher(this)">
	<input type="hidden" name="id" value="<?php echo $this->invoice['id']?>">
	<input type="hidden" name="noform" value="<?php echo $this->invoice['no_fomulir']?>">
	<input type="hidden" name="transactionid" value="<?php echo $this->transactionid?>">
	<br>
	<font color="red"><?php echo $this->msg;?></font>
 </form>
 </fieldset>