<?php
echo $this->headLink ()->prependStylesheet ( $this->baseUrl () . '/css/layout.css' );
echo $this->headLink ()->prependStylesheet ( $this->baseUrl () . '/css/default/style.css' );
echo $this->headLink ()->prependStylesheet ( $this->baseUrl () . '/css/jquery-ui-1.8.5.custom.css' );
echo $this->headLink ()->prependStylesheet ( $this->baseUrl () . '/js/jquery-1.4.3.min.js' );
echo $this->headLink ()->prependStylesheet ( $this->baseUrl () . '/js/jquery.ui.core.js' );
echo $this->headLink ()->prependStylesheet ( $this->baseUrl () . '/js/jquery.ui.datepicker.j' );
?>

<form name="f1" method="POST">
<div style="width:900px; margin:0 auto;">
<div id="dark_grey">
<fieldset><legend>&nbsp;<?php echo $this->title; ?>&nbsp;&nbsp;</legend>
	<?php 
//		$this->form->setAction($this->url());
//		echo  $this->form;
	?>
	
	
	<link rel="stylesheet" href="../demos.css">
	
	
	<script>
	$(function() {
		$( "#datepicker" ).datepicker();
	});
	</script>
	
	<!--<input type="text" value="" name="as_dtstart" onFocus="this.blur()" readonly><a href="javascript:void(0)" onClick="if(self.gfPop)gfPop.fStartPop(document.f1.as_dtstart,document.f1.as_dtend);return false;" HIDEFOCUS><img class="PopcalTrigger" align="absmiddle" src="DateRange/calbtn.gif" width="34" height="22" border="0" alt=""></a>-->
	
<table width="100%"  border="0" cellpadding="5">
  <tr>
    <td>Faculty Name </td>
    <td>:</td>
    <td>
    <select name="ID_FAC" id="ID_FAC">
	<option value="0"> -- Please select -- </option>
    <?php
    $facDB = new Onapp_Model_DbTable_Credittransfer();
	$this->fac = $facDB->getInfo("faculty");
	foreach ($this->fac as $fac) {
		echo "<option value='".$fac['faculty_id']."'>".$fac['faculty_desc']."</option>";
	}
    ?>
    </select>
    </td>
  </tr>
  <tr>
    <td>Programme Name </td>
    <td>:</td>
    <td>
    <select name="ID_PROG" id="ID_PROG">
	<option value="0"> -- Please select -- </option>
    <?php 
	$courseDB = new Onapp_Model_DbTable_Course();
	$this->course = $courseDB->getData();
	
	foreach ($this->course as $course) {
		echo "<option value='".$course['sc005id']."'>".$course['sc005desc']."</option>";
	}
	
	?>
	</select>
	</td>
  </tr>
  <tr>
    <td>Semester</td>
    <td>:</td>
    <td>
    <select name="ID_SEMESTER" id="ID_SEMESTER">
	<option value="0"> -- Please select -- </option>
    <?php
    $semDB = new Onapp_Model_DbTable_Credittransfer();
	$this->sem = $semDB->getInfo("semester");
	foreach ($this->sem as $sem) {
		echo "<option value='".$sem['semesterID']."'>".$sem['semester']."</option>";
	}
    ?>
    </select></td>
  </tr>
  <tr>
    <td>List of Subject </td>
    <td>:</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
</table>

<table width="100%">
		<tr>
			<td align="center">
			<input type="submit" value="Save" onclick="form.action='<? echo $this->url(array('module'=>'onapp','controller'=>'placementtest','action'=>'add'),'default',true) ?>'"/></td>
<!--			<td><input type="submit" value="Reset" /></td>-->
		</tr>
	</table>
	
</fieldset>
</div>
</div>

</form>