<?php
/*
 *  @author Muhamad Alif
 *  @created Oct 27, 2010
 */
?>
<div id="vertmenu">
	<ul >  
		<li ><h1>Examination</h1></li>  
	 <li ><a href="<?php echo $this->url(array('module'=>'exam-center','controller'=>'examination','action'=>'start-exam'),'default',true) ?>"><?php echo $this->translate("Start Exam"); ?></a></li>
	 <li ><a href="<?php echo $this->url(array('module'=>'question-bank','controller'=>'chapter','action'=>'index'),'default',true) ?>"><?php echo $this->translate("Extra Exam Time"); ?></a></li>
	    
	</ul>
</div>

					    