
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "https://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>Chat - Customer Module</title>
<link type="text/css" rel="stylesheet" href="style.css" />
</head>
<style> 
  
form, p, span {
    margin:0;
    padding:0; }
  
input { font:12px arial; }
  
a {
    color:#0000FF;
    text-decoration:none; }
  
    a:hover { text-decoration:underline; }
  
#wrapper  {
    margin:0 auto;
    padding-bottom:25px;
    background:#EBF4FB;
    width:400px;
    border:1px solid #ACD8F0; }
   
#chatbox {
    text-align:left;
    margin:0 auto;
    margin-bottom:25px;
    padding:10px;
    background:#fff;
    height:200px;
    width:350px;
    border:1px solid #ACD8F0;
    overflow:auto; }
#form {
	margin:0 auto;
    margin-bottom:25px;
    padding:10px;
}
#usermsg {
    width:395px;
    border:1px solid #ACD8F0; }
  
#submit { width: 60px; }
  
.error { color: #ff0000; }
  
#menu { padding:12.5px 25px 12.5px 25px; }
  
.welcome { float:left; } 
  
.msgln { margin:0 0 2px 0; }
	
</style>
	
<script >
setInterval (loadLog, 5000);

function Save() {	
	var clientmsg = $("#usermsg").val();
	$("#usermsg").val('');
	$.ajax({
		url: '<?php echo $this->baseUrl();?>/chat/index/ajax-save-chat',
		type: 'POST',
		dataType: "json",
		data: {text: clientmsg,trxid:<?php echo $this->transactionid?>},
		error: function(){
				alert("Terjadi masalah saat mengambil data !");
			}, 
		}).done (function (data) {
			 loadLog();
			 
		});				
	 
};
 
function loadLog(){		
	var oldscrollHeight = $("#chatbox").attr("scrollHeight") - 20; //Scroll height before the request
	$.ajax({
		url: "/chat/index/get-chat/id/<?php echo $this->transactionid?>",
		cache: false,
		success: function(html){		
			$("#chatbox").html(html); //Insert chat log into the #chatbox div	
			
			//Auto-scroll			
			var newscrollHeight = $("#chatbox").attr("scrollHeight") - 20; //Scroll height after the request
			if(newscrollHeight > oldscrollHeight){
				$("#chatbox").animate({ scrollTop: newscrollHeight }, 'normal'); //Autoscroll to bottom of div
			}				
	  	},
	});
	 
}
 
</script>
 
<div id="wrapper">
    <div id="menu">
        <p class="welcome">Selamat Datang,  </p>
        <div style="clear:both"></div>
    </div>
     
    <div id="chatbox"></div>
    <div id="form">
    	 
    	<input name="usermsg" type="text" id="usermsg" size="63" />
    	<input name="submitmsg" type="button"  id="submitmsg" value="Send" onclick="Save()"/>
   </div>
</div>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.3/jquery.min.js"></script>
<script type="text/javascript">
// jQuery Document
$(document).ready(function(){
 
});
</script>
</body>
</html>