<style type="text/css">
.zend_form dt {
    width: 177px;
}
.zend_form dd {
    padding: 2px 187px;
}
</style>
<script type="text/javascript">
 
function edit_Internship(n) {
	 
	var x = document.getElementById("data_internship").rows[n].cells;
	
	document.getElementById("title_bahasa_internship").value=x[2].innerHTML;
	document.getElementById("title_internship").value=x[3].innerHTML;

	document.getElementById("datestart_internship").value= x[6].innerHTML;
	document.getElementById("datestop_internship").value= x[7].innerHTML;
	document.getElementById("position_internship").value=x[4].innerHTML;
	document.getElementById("position_internshipeng").value=x[5].innerHTML;
	document.getElementById("idInternship").value=document.getElementById("idInternshiptbl["+n+"]").value;
	 
}

function onclickDeleteInternship(n) {
	
	var r = confirm("Are you sure to delete it?");
	if (r == true) {
		var url="skpi/delete-internship/idInternship/"+n;
		window.open(url);
	}  
}
 
 
 
</script>


 
<div style="width:100%;">
<fieldset>
<form id="honors" method="post" action="<?php echo $this->baseUrl()?>/skpi/internship" >
<input type="hidden" name="idInternship" id="idInternship">
<table  width="80%" cellpadding="5" cellspacing="0" border="0">
	<tr>	<td width="20%"><?php echo $this->translate("Name of Professional Practice in Bahasa");?></td><td>:</td>
			<td> <textarea rows="4" cols="50" id="title_bahasa_internship" name="title_bahasa_internship">    
			</textarea></tr> 
	<tr>	<td width="20%"><?php echo $this->translate("Name Of  Professional Practice");?></td><td>:</td>
			<td> <textarea rows="4" cols="50" id="title_internship" name="title_internship">     
			</textarea></tr>
	
		<tr>	<td width="20%"><?php echo $this->translate("Posisi/Peran");?></td><td>:</td>
			 
			 <td>	<input type="text" id="position_internship" name="position_internship" size="50"></tr>		
	
	
			 
		 </td></tr>
		 <tr>	<td width="20%"><?php echo $this->translate("Position/Role");?></td><td>:</td>
			 
			 <td>	<input type="text" id="position_internshipeng" name="position_internshipeng" size="50"></tr>		
	
	
			 
		 </td></tr>
			<tr>	<td width="20%"><?php echo $this->translate("Date Start");?> </td><td>:</td><td>
			 <input type="date" id="datestart_internship" name="datestart_internship">
			<?php echo $this->translate("Date Stop").' : ';?> 
			 <input type="date" id="datestop_internship" name="datestop_internship">
			</td>
			 
		 
	<tr><td colspan="3" align="right"><input type="submit" name="submit" value="<?php echo $this->translate('Save')?>" ></td>
	
	</tr>
</table>

</form>
</fieldset>
<br>
 
 
<table class="table" id="data_internship" width="100%" cellpadding="5" cellspacing="1" border="0">
	<tr>
		<th width="5%"><?php echo $this->translate("No");?></th>
		<th width="5%"><?php echo $this->translate("Status");?></th> 
		<th width="35%"><?php echo $this->translate("Name of  Professional Practice in Bahasa");?></th>
		<th width="10%"><?php echo $this->translate("Name of  Professional Practice ");?></th>
		
		<th width="10%"><?php echo $this->translate("Position");?></th>	
			<th width="10%"><?php echo $this->translate("Position in English");?></th>			
		<th width="10%"><?php echo $this->translate("Started Date");?></th>
		<th width="10%"><?php echo $this->translate("Stoped Date");?></th> 
		<th width="10%"><?php echo $this->translate("Certificate");?></th>
		<th width="10%"><?php echo $this->translate("Action");?></th>
	</tr>
	<?php  
	if (count($this->internships)>0) {
	foreach($this->internships as $index=>$value){ 
		$id=$value['idInternship'];
	?>
	<tr <?php echo $i%2==0?"class='shade'":""; ?>>
		<input type="hidden" id="idInternshiptbl[<?php echo $index+1;?>]" value="<?php echo $value['idInternship'];?>">
		 
		<td><?php echo $index+1;?></td> 
		<td align="center">
		<?php if ($value['id_user']!=$this->IdStudentRegistration && $value['approved']=='2' ) {
					 
					?>
						<a href="<?php echo $this->url(array('module'=>'default','controller'=>'skpi', 'action'=>'internship-approved','idInternship'=>$value['idInternship']),'default',true)?>"><img src='<?php echo $this->baseUrl();?>/images/reject.png' border=0 width='20' height='20' title="do you want to acept" ></a>
			  
				<?php } ?>
		<?php if ($value['id_user']!=$this->IdStudentRegistration && $value['approved']=='1') {
					 
					?>
					 
						<a href="<?php echo $this->url(array('module'=>'default','controller'=>'skpi', 'action'=>'internship-reject','idInternship'=>$value['idInternship']),'default',true)?>"><img src='<?php echo $this->baseUrl();?>/images/accept.png' border=0 width='20' height='20' title="do you want to reject" ></a>
			<?php }?> 
						
		<?php if ($value['approved']=='0' ||$value['approved']=='') {
					 
					?>
					 
						 <img src='<?php echo $this->baseUrl();?>/images/prohibit.png' border=0 width='20' height='20' title="Not Approved yet" ></a>
			<?php }?>
		 
			 
		</td>
		

		<td><?php  echo $value['title_bahasa'];?> </td>
		<td><?php echo $value['title']; ?>
		<td><?php echo $value["position"];?></td>
		<td><?php echo $value["position_eng"];?></td>
		<td><?php echo $value["datestart"];?></td>
		<td><?php echo $value["datestop"];?></td> 
		 
		<?php 
		$pathupload=$value['path'];
		if($pathupload!=''){
			$dt = explode("triapp",$pathupload);
			//echo var_dump($dt);exit;
			$path = $dt[1];
			$path ="<a target='_blank' href=http://".APP_HOSTNAME.$path.">" ;
		
		?> <td align="center"><?php  echo $path;?><img src='<?php echo $this->baseUrl();?>/images/document.png' border=0 width='20' height='20' title="Download" ></a></td> <?php 
		} else {?>
		<td align="center"><img src='<?php echo $this->baseUrl();?>/images/upload.png' border=0 width='20' height='20' title="Upload"  onclick="onclickUpload(<?php echo $value['idInternship']?>,'Internship','/default/skpi/#Tab5')" /></td>
		<?php }?>
		<td align="center">
		<?php if ($value['id_user']==$this->IdStudentRegistration) {?>
		<img src='<?php echo $this->baseUrl();?>/images/edit.png' border=0 width='20' height='20' title="Edit"  onclick="edit_Internship(<?php echo  $index+1;?>)" >
		<img src='<?php echo $this->baseUrl();?>/images/trash.png' border=0 width='20' height='20' title="Delete"  onclick="onclickDeleteInternship(<?php echo $value['idInternship'];?>)">
			<?php }?></td>
	
	</tr>
	<?php }
} ?>

</table>
  
 
