 
<style type="text/css">
.zend_form dt {
    width: 177px;
}
.zend_form dd {
    padding: 2px 187px;
}
</style>
<script type="text/javascript">
 
function edit_Language(n) {
	 
	var x = document.getElementById("data_language").rows[n].cells;
	
	document.getElementById("Skore").value= x[5].innerHTML; 
	document.getElementById("date_of_taken").value= x[6].innerHTML; 
	
	document.getElementById("languageid").value=document.getElementById("Languageid["+n+"]").value;
	document.getElementById("language_standart").value=document.getElementById("Standartid["+n+"]").value;
	document.getElementById("idLanguage").value= document.getElementById("idLanguage["+n+"]").value;
}

function onclickDelete(n) {
	
	var r = confirm("Are you sure to delete it?");
	if (r == true) {
		var url="skpi/delete-language/idLanguage/"+n;
		window.open(url);
	}  
}

 
 
    
 
 
</script>



<?php echo $this->idHonors;?>
<div style="width:100%;">
<fieldset>
<form id="honors" method="post" action="<?php echo $this->baseUrl()?>/skpi/language" >
<input type="hidden" name="idLanguage" id="idLanguage">
<table  width="80%" cellpadding="5" cellspacing="0" border="0">
	 
	<tr>	<td width="20%"><?php echo $this->translate("Foreign Language");?></td>
			<td width="5%">:</td>
			<td>
			<select id="languageid" name="languageid">
			    <option value="0"><?php echo $this->translate("Please Select");?></option>
			    <?php 
			    	foreach ($this->language_list as $level):
			    ?>
			    		<option value="<?php echo $level["key"];?>"><?php echo $level["value"];?></option>
			    <?php 
			    	endforeach;
			    ?>
			</select>
			 </td>	
	</tr>		
	
	<tr>	<td width="20%"><?php echo $this->translate("Standart");?></td><td>:</td>
			<td>
		 
			<select id="language_standart" name="language_standart">
			    <option value="0"><?php echo $this->translate("Please Select");?></option>
			    <?php 
			    	foreach ($this->standart_list as $level):
			    ?>
			    		<option value="<?php echo $level["key"];?>"<?php if($this->levelId == $level["key"]){ echo 'selected';}?>><?php echo $level["value"];?></option>
			    <?php 
			    	endforeach;
			    ?>
			</select>
		 
			</td>
	</tr>
			<tr>	<td width="20%"><?php echo $this->translate("Score");?> </td><td>:</td><td>
				<input type="number" id="Skore" name="Skore">
			</td>
	<tr>	<td width="20%"><?php echo $this->translate("Taken Date");?></td><td>:</td>
			<td>
			 <input type="date" id="date_of_taken" name="date_of_taken">
		 
			</td></tr>
			
	<tr><td colspan="3" align="right"><input type="submit" name="submit" value="<?php echo $this->translate('Save')?>" ></td>
	
	</tr>
</table>

</form>
</fieldset>
<br>
 
 
<table class="table" id="data_language" width="100%" cellpadding="5" cellspacing="1" border="0">
	<tr>
		<th width="5%"><?php echo $this->translate("No");?></th>
		<th width="5%"><?php echo $this->translate("Status");?></th> 
				<th width="35%"><?php echo $this->translate("Bahasa");?></th>
		<th width="35%"><?php echo $this->translate("Foreign Language");?></th>
		<th width="10%"><?php echo $this->translate("Standart");?></th>
		<th width="10%"><?php echo $this->translate("Score");?></th>			
		<th width="10%"><?php echo $this->translate("Taken Date");?></th> 
		<th width="10%"><?php echo $this->translate("Certificate");?></th>
		<th width="10%"><?php echo $this->translate("Action");?></th>
	</tr>
	<?php  
	if (count($this->languages)>0) {
	foreach($this->languages as $index=>$value){ 
		$id=$value['idLanguage'];
	?>
	<tr <?php echo $i%2==0?"class='shade'":""; ?>>
		<input type="hidden" id="idLanguage[<?php echo $index+1;?>]" value="<?php echo $value['idLanguage'];?>">
		<input type="hidden" id="Languageid[<?php echo $index+1;?>]" value="<?php echo $value['Languageid'];?>">
		<input type="hidden" id="Standartid[<?php echo $index+1;?>]" value="<?php echo $value['Standartid'];?>">
		 
		<td><?php echo $index+1;?></td> 
		<td align="center">
		<?php if ($value['id_user']!=$this->IdStudentRegistration && $value['approved']=='2' ) {
					 
					?>
						<a href="<?php echo $this->url(array('module'=>'default','controller'=>'skpi', 'action'=>'language-approved','idLanguage'=>$value['idLanguage']),'default',true)?>"><img src='<?php echo $this->baseUrl();?>/images/reject.png' border=0 width='20' height='20' title="do you want to acept" ></a>
			  
				<?php } ?>
		<?php if ($value['id_user']!=$this->IdStudentRegistration && $value['approved']=='1') {
					 
					?>
					 
						<a href="<?php echo $this->url(array('module'=>'default','controller'=>'skpi', 'action'=>'language-reject','idLanguage'=>$value['idLanguage']),'default',true)?>"><img src='<?php echo $this->baseUrl();?>/images/accept.png' border=0 width='20' height='20' title="do you want to reject" ></a>
			<?php }?> 
						
		<?php if ($value['approved']=='0' ||$value['approved']=='') {
					 
					?>
					 
						 <img src='<?php echo $this->baseUrl();?>/images/prohibit.png' border=0 width='20' height='20' title="Not Approved yet" ></a>
			<?php }?>
		 
			 
		</td>
		

		<td><?php  echo $value['Bahasa'];?> </td>
		<td><?php echo $value['Language']; ?>
		<td><?php echo $value["Standart"];?></td>
		<td><?php echo $value["Skore"];?></td>
		<td><?php echo $value["date_of_taken"];?></td>
		<?php 
		$pathupload=$value['path'];
		if($pathupload!=''){
			$dt = explode("triapp",$pathupload);
			//echo var_dump($dt);exit;
			$path = $dt[1];
			$path ="<a target='_blank' href=http://".APP_HOSTNAME.$path.">" ;
		
		?> <td align="center"><?php  echo $path;?><img src='<?php echo $this->baseUrl();?>/images/document.png' border=0 width='20' height='20' title="Download" ></a></td> <?php 
		} else {?>
		<td align="center"><img src='<?php echo $this->baseUrl();?>/images/upload.png' border=0 width='20' height='20' title="Upload"  onclick="onclickUpload(<?php echo $value['idLanguage']?>,'Language','/default/skpi/#Tab3')" /></td>
		<?php }?>
		<td align="center">
		<?php if ($value['id_user']==$this->IdStudentRegistration) {?>
		<img src='<?php echo $this->baseUrl();?>/images/edit.png' border=0 width='20' height='20' title="Edit"  onclick="edit_Language(<?php echo  $index+1;?>)" >
		<img src='<?php echo $this->baseUrl();?>/images/trash.png' border=0 width='20' height='20' title="Delete"  onclick="onclickDelete(<?php echo $value['idLanguage'];?>)">
			<?php }?></td>
	
	</tr>
	<?php }
} ?>

</table>
  

   
