<script type="text/javascript">
	function del(){
		var id = $('input[name=type_id]:checked').val();

		if(!id){
			alert('Please select any takaful operator first');
		}else{
			if(confirm('Are you sure to delete this client type?')){
				window.location = "<?php echo $this->url(array('module'=>'general-setup','controller'=>'takaful', 'action'=>'delete-type')); ?>/id/"+id;
			}
		}
	}
	
	function add(){
		window.location="<?php echo $this->url(array('module'=>'general-setup','controller'=>'takaful', 'action'=>'add-type'));?>";
	}

	function edit(){
		var id = $('input[name=type_id]:checked').val();

		if(!id){
			alert('Please select any takaful operator first');
		}else{
			window.location="<?php echo $this->url(array('module'=>'general-setup','controller'=>'takaful', 'action'=>'edit-type'));?>/id/"+id;
		}
	}


	/*//To remove flash MSG*/
	setTimeout(function() {
		$( "#msg" ).hide( 'blind',null, 1000);
	}, 5000 );


</script>


<div class="message toolbar">
	<h2><?php echo $this->title; ?></h2>
	<div class="toolbar-button">
		<ul>
<!--			<li>
				<a href="#" onclick="javascript:add()">
					<span class='add'></span>
					Add
				</a>
			</li>
			<li>
				<a href="#" onclick="javascript:edit()">
					<span class='edit'></span>
					Edit
				</a>
			</li>
			<li>
				<a href="#" onclick="javascript:del()">
					<span class='delete'></span>
					Delete
				</a>
			</li>
			<li class="divider"></li>-->
			<li>
				<a href="#" >
					<span class='info'></span>
					Info
				</a>
			</li>
		</ul>
	</div>
</div>
<br />

<?if(isset($this->noticeMessage)){?>
<div id="msg" class="message notice"><strong><? echo $this->noticeMessage;?></strong>.</div>
<?}?>
<?if(isset($this->noticeSuccess)){?>
<div class="message success"><strong><? echo $this->noticeSuccess;?></strong>.</div>
<?}?>
<?if(isset($this->noticeError)){?>
<div class="message error"><strong><? echo $this->noticeError;?></strong>.</div>
<?}?>

<?php 
	echo $this->paginationControl($this->paginator,'Sliding','paginationTop.phtml');
	
?>
<table class="table4" width="100%" cellpadding="5" cellspacing="1" border="0">
	<tr>
		<th colspan='2' rowspan="2">CANDIDATE NAME</th>
		<th rowspan="2">ICNO</th>
		<th rowspan="2">COURSE NAME</th>
		<th colspan="3">PAYMENT </th>
		<th rowspan="2"> EXAMINATION DATE</th>
		<th rowspan="2"> APPLICATION DATE</th>
		<th rowspan="2">ACTION</th>
		
	</tr>
	<tr>
	  <th>MODE</th>
	  <th>INVOICE NO</th>
	  <th>STATUS</th>
  </tr>
	
	<?php 
	$i=0;
	$bil=0;

	foreach ($this->paginator as $entry): 
	
	$id = $entry['ID'];
	
	$registrationDB = new App_Model_Record_DbTable_Registrationdetails();
	$registrationData = $registrationDB->listStudent($id);
	
	$totArrayStud = count($registrationData);
	if($totArrayStud != 1){
		$rowspan = "rowspan = '$totArrayStud'";
	}else{
		$rowspan = "";
	}

	echo "<tr valign='top' bgcolor='#f2f2f2'><td $rowspan>";
	echo $this->paginator->getAbsoluteItemNumber(0,$this->paginator->getCurrentPageNumber())+$bil;
	echo ")</td>";
	echo "<td $rowspan>".strtoupper($entry['ARD_NAME'])."</td>";
	echo "<td $rowspan>$entry[ARD_IC]</td>";
	
		foreach ($registrationData as $data){
	
	?>
			<td bgcolor='#f2f2f2'><?php echo $data['course_name']; ?></td>
			<td bgcolor='#f2f2f2'><?php echo $data['paymentMode']; ?></td>
			<td bgcolor='#f2f2f2'><?php echo $data['receiptNo']; ?></td>
			<td bgcolor='#f2f2f2'><?php if($data['paymentStatus'] == 0)echo "<font color=red><b>PENDING</b></font>";elseif($data['paymentStatus'] == 1) echo "<font color=green>COMPLETED</font>"; ?></td>
			
			
			<td bgcolor='#f2f2f2'><?php 
			if($data['idSchedule'] == 0){
				echo "-";
			}else{
				echo date('d-M-Y',strtotime($data['exam_date'])); 
			}	?></td>
			<td bgcolor='#f2f2f2'><?php echo date('d-M-Y',strtotime($data['dateApplied'])); ?></td>
			<td bgcolor='#f2f2f2'><a href='<?php echo $this->url(array('module'=>'finance','controller'=>'individual', 'action'=>'payment-detail','idApp'=>$data['ID'],'id'=>$data['id'])); ?>'>Click</a> <?php echo $data['id'];?></td>
		</tr>
	<?php 
		}
	$i++;
	$bil++;
	endforeach 
	?>

</table>

<?php 
	echo $this->paginationControl($this->paginator,'Sliding','paginationBottom.phtml');
?>