<script type="text/javascript">
$(function() {
	$( "#search-dialog" ).dialog({ 
		autoOpen: false,
		width: 400,
		modal: true,
		buttons: { 
			"Search": function() {
				 
				$("#course_form").submit();
				$(this).dialog("close"); 
			},
			"Close": function() { 
				$(this).dialog("close"); 
			} 
		} 
	});
	
});

function searchbox(){
	$( "#search-dialog" ).dialog('open');
}

</script>

<div class="message toolbar">
	<h2><?php echo $this->title; ?></h2>
	<div class="toolbar-button">
		<ul>
			<li>
				<a id="search" href="#" onclick="javascript:searchbox()">
					<span class='search'></span>
					Search
				</a>
			</li>
			<li>
				<a href="#" >
					<span class='info'></span>
					Info
				</a>
			</li>
		</ul>
	</div>
</div>
<br />


<div style="width:100%;">
<?php 
	echo $this->paginationControl($this->paginator,'Sliding','paginationTop.phtml');
?>

<br>
<table class="table" width="100%" cellpadding="5" cellspacing="1" border="0">
	<tr>
		<th>Name</th>
		<th width="200px">Code</th>
		<th width="200px">LMS Code</th>
	</tr>
	
	<?php 
	$i=0;
	foreach ($this->paginator as $entry): 
	?>
	<tr <?php echo $i%2==0?"class='shade'":""; ?>>
		<td><a href="<?php echo $this->url(array('module'=>'finance','controller'=>'feestructure','action'=>'view','id'=>$entry['id']));?>"><?php echo $entry['name']; ?></a></td>           
		<td align="center"><?php echo $entry['code'];?></td>
		<td align="center"><?php echo $entry['lmsCode'];?></td>
	</tr>
	<?php
	$i++;
	endforeach 
	?>
</table>
</form>
</div>
<?php 
	echo $this->paginationControl($this->paginator,'Sliding','paginationBottom.phtml');
?>

<div id="search-dialog" title="Search Program">
	<form name="course_form" id="course_form" action="" method="post">
		<table class="table5" width="100%">
			<tr>
				<td width="100px">
					Program Name
				</td>
				<td width="5px">:</td>
				<td>
					<input type="text" name="name" value="<?php echo $this->search_name; ?>" style="width:250px" />
				</td>
			</tr>
			<tr>
				<td>
					Program Code
				</td>
				<td width="5px">:</td>
				<td>
					<input type="text" name="code" value="<?php echo $this->search_code; ?>" style="width:250px" />
				</td>
			</tr>
		</table>
	</form>
</div>