 
<script>
	 

	function edit_examiner(n) {
		// alert('ok');
		var x = document.getElementById("data").rows[n].cells;
		document.getElementById("Sequence").value=x[0].innerHTML;
		document.getElementById("Job").value=x[2].innerHTML;  
		document.getElementById("IdPosition").value=document.getElementById("IdPosition["+n+"]").value;
		document.getElementById("IdComposition").value=document.getElementById("IdComposition["+n+"]").value;
		 
		
	}
</script>



<div class="message toolbar">
	<h2><?php echo $this->title; ?></h2>
	<div class="toolbar-button">
		<ul>
			<li>
				
			</li>
		</ul>
	</div>
</div>
<?php if(isset($this->noticeMessage)){?>
<div class="message notice"><strong><?php echo $this->noticeMessage;?></strong>.</div>
<br />
<?php }?>
<?php if(isset($this->noticeSuccess)){?>
<div class="message success"><strong><?php echo $this->noticeSuccess;?></strong>.</div>
<br />
<?php }?>
<?php if(isset($this->noticeError)){?>
<div class="message error"><strong><?php echo $this->noticeError;?></strong>.</div>

<br /> 
<?php }?>
<br />
<fieldset><legend ><?php echo $this->translate('Document Requisite Scope');?></legend>
<table>
<tr><td><?php echo $this->translate('Program');?></td><td>:</td><td><?php echo $this->docflow['Program'] ;?></td>
<tr><td><?php echo $this->translate('Majoring');?></td><td>:</td><td><?php echo $this->docflow['Major'];?></td>
<tr><td><?php echo $this->translate('Branch');?></td><td>:</td><td><?php echo $this->docflow['Branch'] ;?></td>
<tr><td><?php echo $this->translate('Activity Name');?></td><td>:</td><td><?php echo $this->docflow['ActivityName'];?></td>
<tr><td><?php echo $this->translate('Stage Name');?></td><td>:</td><td><?php echo $this->docflow['ProcessName'];?></td>
<tr><td><?php echo $this->translate('Process Name');?></td><td>:</td><td><?php echo $this->docflow['Process_name'];?></td>
<tr><td><?php echo $this->translate('Sequence');?></td><td>:</td><td><?php echo $this->docflow['Sequence'];?></td>

 
</table>

</fieldset>
 
<br />
<fieldset>
<form id="form" method="post" action="/finalassignment/examination/examiner-composition">
<input type="hidden" name="IdComposition" id="IdComposition" >
<input type="hidden" name="IdTAFlow" id="IdTAFlow" value="<?php echo $this->idtaflow;?>">
<table class="table" width="100%" cellpadding="5" cellspacing="0" border="0">
	<tr><td width="20%"><?php echo $this->translate('Position');?></td><td>:</td>
	<td><select name="IdPosition" id="IdPosition">
			<option value=""  ><?php echo $this->translate('--Please Select--');?></option>
				<?php 
				foreach ($this->Compisitions as $list):
					$select = "";
					if( isset($this->idposition) && $this->idposition==$list['key'] ){
						$select = 'selected="selected"';
					}
				?>
					<option value="<?php echo $list['key'];?>" <?php echo $select; ?>><?php echo $list['value'];?></option>
				<?php 
				endforeach;
				?>
			</select></td>
		</tr>	
	<tr>	<td width="25%"><?php echo $this->translate("Sequence");?></td><td>:</td>
			<td> <input type="text"   size="5" id="Sequence" name="Sequence"  > <?php echo $this->translate('Note: Order of Otority ');?>
			 </tr> 
	<tr>	<td width="25%"><?php echo $this->translate("Job");?></td><td>:</td>
			<td><textarea rows="5" cols="70" name="Job" id="Job" ></textarea>
	 
	<tr><td colspan="4" align="center"  > <input type="submit" name="submit" value="<?php echo $this->translate('Save');?>" <?php echo $disable;?>></td>
	 
</table>

</form>
<br />
<?php echo $this->translate('List of Examiner Composition');?></h2>
<table width="100%" id="data" class="table">
	<tr>
		<th><?php echo $this->translate('Sequence');?></th>
		<th><?php echo $this->translate('Position');?></th>
		<th><?php echo $this->translate('Job');?></th>
		<th><?php echo $this->translate('Action');?></th> 
	</tr>
	<?php 
	if($this->ExamComp){
      foreach($this->ExamComp as $index => $batch){
	?><input type="hidden" id="IdPosition[<?php echo $index+1;?>]" value="<?php echo $batch['IdPosition'];?>">
	<input type="hidden" id="IdComposition[<?php echo $index+1;?>]" value="<?php echo $batch['IdComposition'];?>">
	 
	<tr <?php echo $index%2==0?"class='shade'":""?> >
		<td><?php echo $batch['Sequence'];?></td>
		<td><?php echo $batch['PositionName'];?></td>
		<td><?php echo $batch['Job'];?></td> 
		<td><img src='<?php echo $this->baseUrl();?>/images/edit.png' border=0 width='16' height='16' title="Edit"  onclick="edit_examiner(<?php echo $index+1;?>)" >
			<a href="<?php echo $this->url(array('module'=>'finalassignment','controller'=>'examination','action'=>'delete-examiner-composition','idcomposition'=>$batch['IdComposition'],'idTAFlow'=>$batch['IdFlow']),'default',true)?>"><img src='<?php echo $this->baseUrl();?>/images/trash.png' border=0 width='16' height='16' title="Delete" ></a>		 
	</tr>
	<?php 
	  }
	}
	?>
</table>
</fieldset>
