<?php
echo $this->headLink ()->prependStylesheet ( $this->baseUrl () . '/css/layout.css' );
echo $this->headLink ()->prependStylesheet ( $this->baseUrl () . '/css/default/style.css' );
echo $this->headLink ()->prependStylesheet ( $this->baseUrl () . '/css/jquery-ui-1.8.5.custom.css' );
echo $this->headLink ()->prependStylesheet ( $this->baseUrl () . '/js/jquery-1.4.3.min.js' );
echo $this->headLink ()->prependStylesheet ( $this->baseUrl () . '/js/jquery.ui.core.js' );
echo $this->headLink ()->prependStylesheet ( $this->baseUrl () . '/js/jquery.ui.datepicker.j' );
?>

<form name="f1" method="POST">
<div style="width:900px; margin:0 auto;">
<div id="dark_grey">
<fieldset><legend>&nbsp;<?php echo $this->title; ?>&nbsp;&nbsp;</legend>
<link rel="stylesheet" href="../demos.css">
	
	
	<script>
	$(function() {
		$( "#datepicker" ).datepicker();
	});
	</script>
	
	<table width="100%" cellpadding="5" cellspacing="1" bgcolor="#CCCCCC">
  <tr>
    <td bgcolor="#F2F2F2">Group Code </td>
    <td bgcolor="#FFFFFF">:</td>
    <td bgcolor="#FFFFFF"><input type="text" name="txtcode" id="txtcode" value="" style="width:70%"></td>
  </tr>
  <tr>
    <td bgcolor="#F2F2F2">Description</td>
    <td bgcolor="#FFFFFF">:</td>
    <td bgcolor="#FFFFFF"><input type="text" name="txtdesc" id="txtdesc" value="" style="width:70%"></td>
  </tr>
 </table>

<table width="100%">
		<tr>
			<td align="center">
			<input type="submit" value="Save" onclick="form.action='<? echo $this->url(array('module'=>'finance','controller'=>'promotion','action'=>'add'),'default',true) ?>'"/></td>
		</tr>
	</table>
	
</fieldset>
</div>
</div>

</form>