
<div class="message toolbar">
	<h2><?php echo $this->title; ?></h2>
	<div class="toolbar-button"></div>	
</div>

<table>
<tr>
<td>

<p>Untuk menyimpan Kartu Peserta Ujian, sila klik icon Download.</p>

<p>Pada saat hadir Ujian Saringan Masuk, harap membawa:<p>
<p>
<ul>
	<li>Surat Keterangan Bebas Buta Warna dari dokter Spesialis Negeri kecuali untuk Fakultas Hukum, 
		Fakultas Ekonomi (Ilmu Ekonomi, Manajemen, Akuntasi) dan Teknik Sipil.</li>
	<li>Kartu Identitas (KTP SIM Kartu Pelajar/Passport) asli.</li>
	<li>Pensil 2B dan penghapus</li>
	<li>Berpakaian rapi dan sopan dan wajib memakai sepatu.</li>
</ul>
</p>
</td>
</tr>

</table>
<div align="center">
<h3><?php echo $this->translate("placement_test_pass");?></h3>

<iframe src="http://docs.google.com/gview?url=http://<?php echo APP_HOSTNAME ?>/documents/<?php echo $this->appl_id;?>/13500100_validasi_bank.pdf&embedded=true" style="width:80%; height:1000px;" frameborder="0"></iframe>
	</div>