<?php
echo $this->headLink ()->prependStylesheet ( $this->baseUrl () . '/css/layout.css' );
echo $this->headLink ()->prependStylesheet ( $this->baseUrl () . '/css/default/style.css' );
echo $this->headLink ()->prependStylesheet ( $this->baseUrl () . '/css/jquery-ui-1.8.5.custom.css' );
echo $this->headLink ()->prependStylesheet ( $this->baseUrl () . '/js/jquery-1.4.3.min.js' );
echo $this->headLink ()->prependStylesheet ( $this->baseUrl () . '/js/jquery.ui.core.js' );
echo $this->headLink ()->prependStylesheet ( $this->baseUrl () . '/js/jquery.ui.datepicker.j' );
?><div style="width:900px; margin:0 auto;">
<div id="dark_grey">
<fieldset><legend>&nbsp;<?php echo $this->title; ?>&nbsp;&nbsp;</legend>
	<?php 
//		$this->form->setAction($this->url());
//		echo  $this->form;

echo $this->id;

if ($this->id != 0) {
	echo "update";
	
	$data = new Finance_Model_DbTable_Payment();
	$dt = $data->getData($this->id);
		echo $dt['plan_name'];
}
	?>
	
	
	<link rel="stylesheet" href="../demos.css">
	
	
	<script>
	$(function() {
		$( "#datepicker" ).datepicker();
	});
	</script>
	
	
	
<form name="f1" method="POST">	 
	<table width="100%" cellpadding="5" cellspacing="1" bgcolor="#CCCCCC">
  <tr>
    <td bgcolor="#F2F2F2">Payment Plan Name</td>
    <td bgcolor="#FFFFFF">:</td>
    <td bgcolor="#FFFFFF"><input type="text" name="fr_paymode" id="fr_paymode" size="80" value="<?=$dt['plan_name']?>"></td>
  </tr>
  <tr>
    <td bgcolor="#F2F2F2">Plan Description</td>
    <td bgcolor="#FFFFFF">:</td>
    <td bgcolor="#FFFFFF"><textarea cols="50"> <?=$dt['plan_method']?></textarea></td>
  </tr>
</table>

<table width="100%">
		<tr>
			<td align="center">
			<input type="submit" value="Save" onclick="form.action='<? echo $this->url(array('module'=>'finance','controller'=>'paymentmode','action'=>'add'),'default',true) ?>'"/></td>
<!--			<td><input type="submit" value="Reset" /></td>-->
		</tr>
	</table>
	</form>
</fieldset>
</div>
</div>