<html>
 <body>
 <div class="message toolbar">
	<h2><?php echo $this->title; ?></h2>
	<div class="toolbar-button">
		<ul>
		    <li>
				<a href="#" >
					<span class='info'></span>
					Info
				</a>
			</li>
		</ul>
	</div>
</div>
<br>
<form method="post" name="editmark">
<table>
<tr>
<input type="hidden" name="IdStudentMarksEntry" value="<?php echo $this->id;?>">
<input type="hidden" name="updUser" value="<?php echo $this->iduser;?>">
<input type="hidden" name="oldmark" value="<?php echo $this->student['TotalMarkObtained'];?>">
<input type="hidden" name="Percentage" value="<?php echo $this->student['Percentage'];?>">
<input type="hidden" name="idRemarkingHistory" value="<?php echo $this->remark['idRemarkingHistory'];?>">
<td><?php echo $this->translate("Subject")?></td><td>:</td><td><?php echo $this->student['ShortName'].' '.$this->student['BahasaIndonesia'];?></td></tr>
<tr><td><?php echo $this->translate("Student")?></td><td>:</td><td><?php echo $this->student['StudentName']?></td></tr>
<tr><td><?php echo $this->translate("Mark Component")?></td><td>:</td><td><?php echo $this->student['ComponentName'];?></td></tr>
<tr><td><?php echo $this->translate("Percentage")?></td><td>:</td><td><?php echo $this->student['Percentage']?></td></tr>
<tr><td><?php echo $this->translate("Mark")?></td><td>:</td><td><?php echo $this->student['TotalMarkObtained']?></td></tr>
<tr><td><?php echo $this->translate("New Mark")?></td><td>:</td><td><input type="text" name="remarking" value=<?php echo $this->remark['remarking'];?>></td></tr>
<tr><td><?php echo $this->translate("Reasoning for Remarking")?></td><td>:</td><td><textarea cols=50 rows=5 name="Note"><?php echo $this->remark['Note'];?></textarea></td>
</tr>
<tr><td></td><td></td><td><input type="submit" name="submit"></td></tr>
</table>
</form>
 </body>
</html>