<?php
/*
 *  @author Suliana
 *  @created May 16, 2011
 */
?>
<div id="vertmenu">
	<ul> 
		<li><h1>Registration set-up</h1></li>
		 <li><a href="<?php echo $this->url(array('module'=>'anr-setup','controller'=>'award','action'=>'index'),'default',true) ?>"><?php echo $this->translate("Programme"); ?></a></li>  
		 <li><a href="<?php echo $this->url(array('module'=>'anr-setup','controller'=>'course','action'=>'index'),'default',true) ?>"><?php echo $this->translate("Course"); ?></a></li>  
		 <li><a href="<?php echo $this->url(array('module'=>'anr-setup','controller'=>'semester','action'=>'semestername'),'default',true) ?>"><?php echo $this->translate("Semester"); ?></a></li>  
		 <li><a href="<?php echo $this->url(array('module'=>'application','controller'=>'placement-test','action'=>'index'),'default',true) ?>"><?php echo $this->translate("Pre-Application"); ?></a></li>  
	 
	  
	   <!-- <li><a href="<?php echo $this->url(array('module'=>'anr-setup','controller'=>'award','action'=>'index'),'default',true) ?>"><?php echo $this->translate("Award"); ?></a></li>   
	    <li><a href="<?php echo $this->url(array('module'=>'anr-setup','controller'=>'market','action'=>'index'),'default',true) ?>"><?php echo $this->translate("Learning Mode"); ?></a></li>  
	    <li><a href="<?php echo $this->url(array('module'=>'anr-setup','controller'=>'main-program','action'=>'index'),'default',true) ?>"><?php echo $this->translate("Main Program"); ?></a></li>  
	    <li><a href="<?php echo $this->url(array('module'=>'anr-setup','controller'=>'program','action'=>'index'),'default',true) ?>"><?php echo $this->translate("Program"); ?></a></li>
	    <li><a href="<?php echo $this->url(array('module'=>'anr-setup','controller'=>'program-requirement','action'=>'index'),'default',true) ?>"><?php echo $this->translate("Program Requirement"); ?></a></li>
	    <li><a href="<?php echo $this->url(array('module'=>'anr-setup','controller'=>'academic-landscape','action'=>'index'),'default',true) ?>"><?php echo $this->translate("Program Academic Landscape"); ?></a></li>   
	</ul> 
	<br />
	<ul>  
	    <li><h1>Semester Setup</h1></li>  
	    <li><a href="<?php echo $this->url(array('module'=>'anr-setup','controller'=>'semester','action'=>'index'),'default',true) ?>"><?php echo $this->translate("Semester"); ?></a></li>  
	    <li><a href="<?php echo $this->url(array('module'=>'anr-setup','controller'=>'activity','action'=>'index'),'default',true) ?>"><?php echo $this->translate("Activity"); ?></a></li>  
	    <li><a href="<?php echo $this->url(array('module'=>'anr-setup','controller'=>'calendar','action'=>'index'),'default',true) ?>"><?php echo $this->translate("Calendar"); ?></a></li>     
	</ul>
	<br />
	<ul>  
	    <li><h1>Course Setup</h1></li>  
	    <li><a href="<?php echo $this->url(array('module'=>'anr-setup','controller'=>'course','action'=>'index'),'default',true) ?>"><?php echo $this->translate("Course"); ?></a></li>
	    <li><a href="<?php echo $this->url(array('module'=>'anr-setup','controller'=>'course-prerequisites','action'=>'index'),'default',true) ?>"><?php echo $this->translate("Course Prerequisites"); ?></a></li>  
	    <li><a href="<?php echo $this->url(array('module'=>'anr-setup','controller'=>'course-offered','action'=>'index'),'default',true) ?>"><?php echo $this->translate("Course Offered"); ?></a></li>  -->   
	</ul>
</div>