<?php
/*
 *  @author Suliana
 *  @created May 16, 2011
 */
?>


<div id="vertmenu">

	<ul>  
		<li><h1><?php echo $this->translate("Announcement"); ?></h1></li>	    
	    <li><a href="<?php echo $this->url(array('module'=>'application','controller'=>'announcement','action'=>'index'),'default',true) ?>"><?php echo $this->translate("Announcement"); ?></a></li>
	</ul>
	<!-- MOVE TO SIS -->
	<!--
	<br>
	<ul>  
		<li><h1>Application</h1></li>  
	    <li><a href="<?php echo $this->url(array('module'=>'application','controller'=>'index','action'=>'index'),'default',true) ?>"><?php echo $this->translate("Application List"); ?></a></li>
	</ul>
	<br>
	<ul>  
		<li><h1>Placement Test</h1></li>
	    <li><a href="<?php echo $this->url(array('module'=>'application','controller'=>'placement-test-type','action'=>'index'),'default',true) ?>"><?php echo $this->translate("Type Set-up"); ?></a></li>
	    <li><a href="<?php echo $this->url(array('module'=>'application','controller'=>'placement-test-component','action'=>'index'),'default',true) ?>"><?php echo $this->translate("Component Set-up"); ?></a></li>
	    <li><a href="<?php echo $this->url(array('module'=>'application','controller'=>'placement-test-program-component','action'=>'index'),'default',true) ?>"><?php echo $this->translate("Program Component Set-up"); ?></a></li>
	    <li><a href="<?php echo $this->url(array('module'=>'application','controller'=>'placement-test-location','action'=>'index'),'default',true) ?>"><?php echo $this->translate("Location Set-up"); ?></a></li>
	    <li><a href="<?php echo $this->url(array('module'=>'application','controller'=>'placement-test','action'=>'index'),'default',true) ?>"><?php echo $this->translate("Placement Test"); ?></a></li>
	    
	   	    
	    <li><a href="<?php echo $this->url(array('module'=>'application','controller'=>'placement-test-schema','action'=>'index'),'default',true) ?>"><?php echo $this->translate("Answer Schema"); ?></a></li>
	    <li><a href="<?php echo $this->url(array('module'=>'application','controller'=>'placement-test-answer','action'=>'index'),'default',true) ?>"><?php echo $this->translate("Answer Sheet"); ?></a></li>
	    
	    
	    <li><a href="<?php echo $this->url(array('module'=>'application','controller'=>'placement-test-email','action'=>'index'),'default',true) ?>"><?php echo $this->translate("Email Template Set-up"); ?></a></li>  
	</ul>
	 
	<br>
	<ul>  
		<li><h1><?php echo $this->translate('high_school_certificate')?></h1></li>
		
		<li><a href="<?php echo $this->url(array('module'=>'application','controller'=>'selection-highschool','action'=>'list-applicant'),'default',true) ?>"><?php echo $this->translate("Individual Selection"); ?></a></li>
		<li><a href="<?php echo $this->url(array('module'=>'application','controller'=>'selection-highschool','action'=>'batch-dean-rating'),'default',true) ?>"><?php echo $this->translate("Batch Dean Rating"); ?></a></li>
		<li><a href="<?php echo $this->url(array('module'=>'application','controller'=>'selection-highschool','action'=>'batch-rector-rating'),'default',true) ?>"><?php echo $this->translate("Batch Rector Rating"); ?></a></li>
		<li><a href="<?php echo $this->url(array('module'=>'application','controller'=>'selection-highschool','action'=>'batch-approval'),'default',true) ?>"><?php echo $this->translate("Batch Approval"); ?></a></li>
		<li><a href="<?php echo $this->url(array('module'=>'application','controller'=>'selection-highschool','action'=>'selection-status'),'default',true) ?>"><?php echo $this->translate("Selection Status"); ?></a></li>
		<li><a href="<?php echo $this->url(array('module'=>'application','controller'=>'selection-highschool-report','action'=>'report-list'),'default',true) ?>"><?php echo $this->translate("High School Report"); ?></a></li>
	</ul>
	 -->
	 
</div>

					    