<div id="vertmenu">
	<ul>  
		<li><h1>Discipline</h1></li>
	    <li><a href="<?php echo $this->url(array('module'=>'discipline','controller'=>'case','action'=>'index'),'default',true) ?>"><?php echo $this->translate("Case Setup"); ?></a></li>
	    <li><a href="<?php echo $this->url(array('module'=>'discipline','controller'=>'penalty','action'=>'index'),'default',true) ?>"><?php echo $this->translate("Penalty Setup"); ?></a></li>
	    <li><a href="<?php echo $this->url(array('module'=>'discipline','controller'=>'case','action'=>'student-case'),'default',true) ?>"><?php echo $this->translate("Case"); ?></a></li>
	</ul>
</div>