<?php
/*
 *  @author Alif
 *  @created Apr 23, 2012
 */
?>
<div id="vertmenu">
	<ul>  
		<li><h1>Schedule</h1></li>
	    <li><a href="<?php echo $this->url(array('module'=>'schedule','controller'=>'index','action'=>'index'),'default',true) ?>"><?php echo $this->translate("Exam Schedule"); ?></a></li>
	    <li><a href="<?php echo $this->url(array('module'=>'general-setup','controller'=>'venue','action'=>'index'),'default',true) ?>"><?php echo $this->translate("Venue Set-Up"); ?></a></li>
	</ul>
</div>