<script type="text/javascript">
function delete_user(title,id){
	var id = $('input[name=lid]:checked').val();

	if(!id){
		alert('Please select any user');
	}else{
		if(confirm('Confirm to delete this user?')){
			window.location = "<?php echo $this->url(array('module'=>'exam','controller'=>'lecturer', 'action'=>'delete-lecturer'));?>/id/"+id
		}
	}
}

function edit_user(){
	var id = $('input[name=lid]:checked').val();

	if(!id){
		alert('Please select any user');
	}else{
		window.location="<?php echo $this->url(array('module'=>'exam','controller'=>'lecturer','action'=>'edit-lecturer'),'default',true) ?>/id/"+id;
	}
}
</script>


<div class="message toolbar">
	<h2><?php echo $this->title; ?></h2>
	<div class="toolbar-button">
		<ul>
			<li>
				<a href="<?php echo $this->url(array('module'=>'exam', 'controller' => 'lecturer', 'action' => 'add-lecturer')); ?>">
					<span class='add'></span>
					Add
				</a>
			</li>
			<li>
				<a href="#" onclick="javascript:edit_user()">
					<span class='edit'></span>
					Edit
				</a>
			</li>
			<li>
				<a href="#" onclick="javascript:delete_user()">
					<span class='delete'></span>
					Delete
				</a>
			</li>
			<li class="divider"></li>
			<li>
				<a href="#" onclick="javascript:search_user()">
					<span class='search'></span>
					Search
				</a>
			</li>
		</ul>
	</div>
</div>
<br />

<?if(isset($this->noticeMessage)){?>
<div class="message notice"><strong><? echo $this->noticeMessage;?></strong>.</div>
<?}?>
<?if(isset($this->noticeSuccess)){?>
<div class="message success"><strong><? echo $this->noticeSuccess;?></strong>.</div>
<?}?>
<?if(isset($this->noticeError)){?>
<div class="message error"><strong><? echo $this->noticeError;?></strong>.</div>
<?}?>


<?php 
	echo $this->paginationControl($this->paginator,'Sliding','paginationTop.phtml');
?>
<table class="table" width="100%" cellpadding="5" cellspacing="0" border="0">
	<tr>
		<th width="25px">&nbsp;</th>
		<th>Name</th>
		<th width="250px">Branch</th>
		<th width="250px">Email</th>
	</tr>
	
	<?php 
	$i=0;
	foreach ($this->paginator as $entry): 
	?>
	<tr <?php echo $i%2==0?"class='shade'":""; ?>>
		<td>
			<input type="radio" name="lid" value="<?php echo $entry['id']; ?>">
		</td>
		<td>
			<a href="<?php echo $this->url(array('module'=>'exam', 'controller' => 'lecturer', 'action' => 'view-lecturer', 'id'=>$entry['id'])); ?>">
				<?php echo $entry['name']; ?>
			</a>
		</td>
		<td align="center">
			<?php
				if($entry['branch_id']==0){
					echo "USTY HQ";
				}else{ 
					echo $entry['branch_name'];
				} 
			?>
		</td>
		<td align="center">
			<?php echo $entry['email']; ?>
		</td>
	</tr>
	<?php 
	$i++;
	endforeach 
	?>
	
	<?php 
	if( count($this->paginator) <1 ){
	?>
		<tr>
			<td colspan="4" align="center">
				<?php echo $this->translate("There are no lecturer data"); ?>
			</td>
		</tr>
	<?php 
	}
	?>

</table>
<?php 
	echo $this->paginationControl($this->paginator,'Sliding','paginationBottom.phtml');
?>
