<?php
echo $this->headLink ()->prependStylesheet ( $this->baseUrl () . '/css/layout.css' );
echo $this->headLink ()->prependStylesheet ( $this->baseUrl () . '/css/default/style.css' );
?>

<script type="text/javascript">
	$(function() {
		$("#entitlement").dialog({
			autoOpen: false,
			width: 670,
			height: 300,
			buttons: { 
				"Close": function() { $(this).dialog("close"); },
				"Save": function() {
					document.manual_entitlement.submit();
				} 
			}		
		});
	});

	function calculate_balance(leaveType){
		var cf = parseInt($("#cf_"+leaveType).val());
		var ent = parseInt($("#ent_"+leaveType).val());
		var tkn = parseInt($("#taken_"+leaveType).val());

		var bal = 0;

		if(cf!=NaN && ent!=NaN && tkn!=NaN){
			bal = (cf+ent)-tkn;
		}
		
		$("#balance_"+leaveType).html(bal);
	}
</script>


<SCRIPT language="javascript">

    function addRowToTable()
	{
	  var tbl = document.getElementById('tblSample');
	  var lastRow = tbl.rows.length;
	  // if there's no header row in the table, then iteration = lastRow + 1
	  var iteration = lastRow;
	  var row = tbl.insertRow(lastRow);
	  
	  // left cell
	  var cellLeft = row.insertCell(0);
	  var textNode = document.createTextNode(iteration);
	  cellLeft.appendChild(textNode);
	  
	  // right cell
	  
	  for(i=1;i<5;i++){
	 
	  var cellRight = row.insertCell(i);
	  var el = document.createElement("input");
	  el.type = 'text';
	  el.name = 'txtRow' + iteration+i;
	  el.size = 10;
	  cellRight.appendChild(el);
	  
//	  var cellRight = row.insertCell(2);
//	  var el = document.createElement("input");
//	  el.type = 'text';
//	  el.name = 'txtRow' + iteration;
//	  el.size = 10;
//	  cellRight.appendChild(el);
//	  
//	  var cellRight = row.insertCell(3);
//	  var el = document.createElement("input");
//	  el.type = 'text';
//	  el.name = 'txtRow' + iteration;
//	  el.size = 10;
//	  cellRight.appendChild(el);
//	  
//	  var cellRight = row.insertCell(4);
//	  var el = document.createElement("input");
//	  el.type = 'text';
//	  el.name = 'txtRow' + iteration;
//	  el.size = 10;
//	  cellRight.appendChild(el);
	  
	//alert(el.name);
	  
	  }  
	  
	  //el.onkeypress = keyPressTest;
	  //cellRight.appendChild(el);
	  
	  // select cell
//	  var cellRightSel = row.insertCell(2);
//	  var sel = document.createElement('select');
//	  sel.name = 'selRow' + iteration;
//	  sel.options[0] = new Option('text zero', 'value0');
//	  sel.options[1] = new Option('text one', 'value1');
//	  cellRightSel.appendChild(sel);
	}


</SCRIPT>


<?if(isset($this->noticeMessage)){?>
<div class="message notice"><strong><? echo $this->noticeMessage;?></strong>.</div>
<?}?>
<?if(isset($this->noticeSuccess)){?>
<div class="message success"><strong><? echo $this->noticeSuccess;?></strong>.</div>
<?}?>
<?if(isset($this->noticeError)){?>
<div class="message error"><strong><? echo $this->noticeError;?></strong>.</div>
<?}?>

<?php
	echo "<h1>". $this->title ."</h1>";
	//echo "<h1>". $this->id ."</h1>";
	
$applyDB = new Onapp_Model_DbTable_Apply();
$apply = $applyDB->getData($this->id);

?>


	<p><b>A. PERSONAL PARTICULARS</b></p>
	<table width="100%" border="0" cellpadding="5" align="center" bgcolor="#fff" cellspacing="1">
		<tr>
			<td width="20%" bgcolor="#f2f2f2"><?php echo $this->translate("Fullname"); ?></td>
			<td width="2%">:</td>
			<td><?php echo $apply["ARD_NAME"];?></td>
		</tr>
		<tr>
			<td bgcolor="#f2f2f2"><?php echo $this->translate("Personal ID"); ?></td>
			<td>:</td>
			<td><?php echo $apply["ARD_IC"];?></td>
		</tr>
		<tr>
			<td bgcolor="#f2f2f2"><?php echo $this->translate("Contact Number"); ?></td>
			<td>:</td>
			<td><?php echo $apply["ARD_HPHONE"];?></td>
		</tr>
		<tr>
			<td bgcolor="#f2f2f2"><?php echo $this->translate("Email"); ?></td>
			<td>:</td>
			<td><?php echo $apply["ARD_EMAIL"]; ?></td>
		</tr>
		<tr>
			<td bgcolor="#f2f2f2"><?php echo $this->translate("Programme Level"); ?></td>
			<td>:</td>
			<td>
			
			<?php echo $apply["ARD_PROGRAM"]; ?>
			<?php 
			$programDB = new Onapp_Model_DbTable_Program();
			$this->program = $programDB->getData($apply["ARD_PROGRAM"]);
			
			echo $this->program["sc001_name"]; ?>
			</td>
		</tr>
		
		<!--<tr>
			<td bgcolor="#f2f2f2"><?php echo $this->translate("Required Qualification"); ?></td>
			<td>:</td>
			<td><?php 
//			$quaDB = new Onapp_Model_DbTable_Qualification();
//			$this->qua = $quaDB->getData($_POST["sc003_qualification_id"]);
//			
//			echo $this->qua["sc003_name"]; ?></td>
		</tr>-->
	</table>
	
	
	<!-- $prog_qua = $_POST["prog_qua"];
	  	$n= count($prog_qua);
		$i= 0;
		
		while ($i < $n)
		{
			if ($pq["id"] == $prog_qua[$i]) {
				$select = "disabled";
				break;
			}
			else 
				$select = "";
			$i++;
		}-->
	

		
		
<BR>
	<p><b>B. ENTRY REQUIREMENTS</b></p>
	
	<form name="f2" method="POST" action="/onapp/index/add-req/id/<?php echo $this->id;?>">
	<p> Please select required entry requirement : 
	
	<input type="hidden" name="id_apply" value="<?=$this->id?>">
	<select name="sc001_program_id" onChange="">
			<option value="0"> -- Please select -- </option>
			<?php 
			$quaDB = new Onapp_Model_DbTable_Qualification();
			$this->qualification = $quaDB->getData();
			
				foreach ($this->qualification as $qua) {
					$select = "";
					if($this->formData['sc003_qualification_id'] == $qua['sc003_qualification_id']){
						$select = 'selected=selected';	
					}else{
						$select = "alt='false'";
					}
					echo "<option value='".$qua['sc003_qualification_id']."'>".$qua['sc003_name']."</option>";
				}
			?>
		</select>
		</p>
	
	<?php //echo $this->translate("Bachelor Degree"); ?> <input type="submit" value="Add More" onclick="addRowToTable();" />
	<table class="table4" width="100%" cellpadding="5" cellspacing="1" id="tblSample">
		<tr>
			<th>Bil</th>
			<th>Year Graduate</th>
			<th align="center">School/College/University</th>
			<th align="center">Programme</th>
			<th align="center">Grade</th>
		</tr>
		<tr>
			<td>1</td>
			<td><input type="text" name="txtRow11" size="5"></td>
			<td><input type="text" name="txtRow12" size="10"></td>
			<td><input type="text" name="txtRow13" size="10"></td>
			<td><input type="text" name="txtRow14" size="10"></td>
		</tr>
	</table>
	
	<table>
		<tr>
			<td><input type="submit" value="Save" /></td>
			<td><input type="submit" value="Reset" /></td>
		</tr>
	</table>
	
	</form>

<div style="width:100%; margin: 10px auto;">
	<table class="table3" width="830px" cellpadding="5">
		<tr>
			<td colspan="5"><?php echo $this->translate("Programme Offered"); ?></td>
		</tr>
		<tr>
			<td>Bil</td>
			<td align="center">Programme Name</td>
			<td align="center">Credit Hours</td>
			<td align="center"></td>
		</tr>
		
		<?php 
		
		$courseDB = new Onapp_Model_DbTable_Course();
		$this->program = $courseDB->getPaginateData($apply["ARD_PROGRAM"]);
		$bil = 1;
			foreach ($this->program as $program){
			?>
			<tr>
				<td><?php echo $bil; ?></td>
				<td><?php echo $program['sc005desc']; ?></td>
				<td align="center"><?php echo $program['sc005cdthours']?></td>
				<td align="center"><input name="radiobutton" type="radio" value="radiobutton"></td>
			</tr>
			<?php
			$bil++;
			} 
		?>
	</table>
	
	<table>
		<tr>
			<td><input type="submit" value="Next" onClick="$('#entitlement').dialog('open');" /></td>
			<td><a href="<?php echo $this->url(array('module'=>'leave','controller'=>'manual-entitlement','action'=>'print','id'=>$this->id),'default',true) ?>" target="blank"><input type="submit" value="Reset" /></a></td>
		</tr>
	</table>
</div>
