<script type="text/javascript">
	$(document).ready(function() {
		
		$("#date_received").datepicker({
				"dateFormat":"yy-mm-dd",
				"changeMonth":"true",
		});

	});

	

	/*//To remove flash MSG*/
	setTimeout(function() {
		$( "#msg" ).hide( 'blind',null, 1000);
	}, 5000 );


</script>

<div class="message toolbar">
	<h2><?php echo $this->title; ?></h2>
	<div class="toolbar-button">
		<ul>
			<li class="divider"></li>
			<li>
				<a href="<?php echo $this->url(array('module'=>'finance','controller'=>'individual', 'action'=>'index'),'default',true);?>" >
					<span class='back'></span>
					Back
				</a>
			</li>
			<li>
				<a href="#" >
					<span class='info'></span>
					Info
				</a>
			</li>
		</ul>
	</div>
</div>
<br />
<form name="f1" method="post" action="<?php echo $this->url(array('module'=>'finance','controller'=>'individual','action'=>'update'),'default',true) ?>">
<table width="80%" border="0" cellpadding="5">
<tr>
    <td width="30%">Candidate Name</td>
    <td width="1">:</td>
    <td width="70%"><?php echo $this->candidate['ARD_NAME'];?></td>
  </tr>
  <tr>
    <td>IC NO</td>
    <td>:</td>
    <td><?php echo $this->candidate['ARD_IC'];?></td>
  </tr>
  <tr>
    <td>Course</td>
    <td>:</td>
    <td><?php echo $this->candidate['course_name'];?></td>
  </tr>
  <tr>
    <td>Exam Center</td>
    <td>:</td>
    <td><?php echo $this->candidate['centername'];?></td>
  </tr>
  <tr>
    <td>Examination Date</td>
    <td>:</td>
    <td><?php echo $this->candidate['exam_date'];?></td>
  </tr>
  <tr>
    <td>Payment Mode</td>
    <td>:</td>
    <td><?php echo $this->candidate['paymentMode'];?></td>
  </tr>
  <tr>
    <td>Reference Number/Receipt Number</td>
    <td>:</td>
    <td><label for="textfield"></label>
    <input type="text" name="textfield" id="textfield"></td>
  </tr>
  <tr>
    <td>Date Received</td>
    <td>:</td>
    <td><label for="textfield"></label>
    <input type="text" name="date_received" id="date_received"></td>
  </tr>
  <tr>
    <td>Amount</td>
    <td>:</td>
    <td><label for="textfield"></label>
    <input type="text" name="textfield" id="textfield"></td>
  </tr>
</table>


<table>
		<tr>
			<td><input type="submit" value="Save" name="submit"></td>
			<td><input type="submit" value="Reset" /></td>
		</tr>
	</table>
	</form>
	

<?php 
//	$this->form->setAction($this->url());
	//echo  $this->form;
?>