<script type="text/javascript">


function addRowToTable()
{

  var tbl = document.getElementById('tblComponent');
  var lastRow = tbl.rows.length; 
  // if there's no header row in the table, then iteration = lastRow + 1
  var iteration = lastRow;
  var row = tbl.insertRow(lastRow);

 
  iteration = lastRow-1;

  document.getElementById('iteration').value = iteration

  // left cell
  var cellLeft = row.insertCell(0);
  var textNode = document.createTextNode(iteration);
  cellLeft.appendChild(textNode);
  
  // component_name
 /* var component_name = row.insertCell(1);
  var cn = document.createElement('input');
  cn.type = 'text';
  cn.name = 'component_name' + iteration;
  cn.id = 'component_name'+ iteration;
  cn.size = 20;*/
 
  // select cell component name
  var component_id = row.insertCell(1);
  var ci = document.createElement('select');
  ci.name = 'component_id' + iteration;
  ci.options[0] = new Option('-- Please Select --', '0');
     
  <? $i=1; foreach ($this->components as $component){ ?> 
  ci.options[<?php echo $i;?>] = new Option('<?php echo $component["component_name"]?>', '<?php echo $component["id"]?>');
  <? $i++; } ?>

  component_id.appendChild(ci);
  

  //component_weightage
  var component_weightage = row.insertCell(2);
  var cw = document.createElement('input');
  cw.type = 'text';
  cw.name = 'component_weightage' + iteration ;
  cw.id = 'component_weightage'+ iteration;
  cw.size = 20;

  cw.onblur = onblurRow;  
  component_weightage.appendChild(cw);


  //component_passing_mark
  var component_passing_mark = row.insertCell(3);
  var cpm = document.createElement('input');
  cpm.type = 'text';
  cpm.name = 'component_passing_mark' + iteration;
  cpm.id = 'component_passing_mark'+ iteration;
  cpm.size = 20;
  
  //cpm.onkeypress = keyPressTest;
  component_passing_mark.appendChild(cpm);

  //component_total_mark
  var component_total_mark = row.insertCell(4);
  var ctm = document.createElement('input');
  ctm.type = 'text';
  ctm.name = 'component_total_mark' + iteration;
  ctm.id = 'component_total_mark'+ iteration;
  ctm.size = 20;
  
 // ctm.onkeypress = keyPressTest;
  component_total_mark.appendChild(ctm);


  //checkbox cell
  /*var compulsory_to_pass = row.insertCell(5);
  var box = document.createElement('input');
  box.type = 'checkbox';
  box.name = 'compulsory_to_pass' + iteration;
  box.id = 'compulsory_to_pass' + iteration;
  compulsory_to_pass.appendChild(box);*/
  
  // select cell
  //var cellRightSel = row.insertCell(2);
  //var sel = document.createElement('select');
 // sel.name = 'selRow' + iteration;
 // sel.options[0] = new Option('text zero', 'value0');
  //sel.options[1] = new Option('text one', 'value1');
  //cellRightSel.appendChild(sel);
}
function keyPressTest(e, obj)
{
  var validateChkb = document.getElementById('chkValidateOnKeyPress');
  if (validateChkb.checked) {
    var displayObj = document.getElementById('spanOutput');
    var key;
    if(window.event) {
      key = window.event.keyCode; 
    }
    else if(e.which) {
      key = e.which;
    }
    var objId;
    if (obj != null) {
      objId = obj.id;
    } else {
      objId = this.id;
    }
    displayObj.innerHTML = objId + ' : ' + String.fromCharCode(key);
  }
}
function removeRowFromTable()
{
  var tbl = document.getElementById('tblComponent');
  var lastRow = tbl.rows.length;
  
  curval = document.getElementById('iteration').value;
  if (lastRow > 2) tbl.deleteRow(lastRow - 1);   
  document.getElementById('iteration').value = curval-1;
}
function openInNewWindow(frm)
{
  // open a blank window
  var aWindow = window.open('','TableAddRowNewWindow','scrollbars=yes,menubar=yes,resizable=yes,toolbar=no,width=400,height=400');
      
  // set the target to the blank window
  frm.target = 'TableAddRowNewWindow';
  
  // submit
  frm.submit();
}

function validateRow(frm)
{	
	    var tbl = document.getElementById('tblComponent');
	    
	    var lastRow = tbl.rows.length - 2;
	    
	    
	  
	    var i;
	    var total=0;		  
	    
	    for (i=1; i<=lastRow; i++) {
	      	  var aRow = document.getElementById('component_weightage' + i);
		   
		      if (aRow.value.length <= 0) {
		        alert('Row ' + i + ' is empty');
		        return false;
		      }

	         //get total weightage
			 rowVal = aRow.value;
			 total=total+Math.abs(rowVal);	
	    }  
	    
	    if(lastRow==0){
	    	alert('There is no assessment component entered.');
			return false;
	    }
	
		/*if(total !=100){
			alert('Please make sure the total weightage is '+total+'.');
			return false;
		}*/
		
		
					    
 	return true;
}

function onblurRow(){

    	//get total weightage
	    var tbl = document.getElementById('tblComponent');
	    var lastRow = tbl.rows.length - 2;
	  
	    var i;
	    var total=0;		  
	    
	    for (i=1; i<=lastRow; i++) {
	      	 var aRow = document.getElementById('component_weightage' + i);
		     //get total weightage
			 rowVal = aRow.value;
			 total=total+Math.abs(rowVal);

			 if(total > 100){
					alert('Total weightage is '+total+' .Please make sure...');					
					aRow.value=0;
					aRow.focus();
					return;
			}	
	    }  
	    
	document.getElementById('total_weightage').value = total;	
}

function show(val){

	if(val==1){
		document.getElementById('tbltype1').style.display = '';
		document.getElementById('tbltype2').style.display = 'none';
	}

	if(val==2){
		document.getElementById('tbltype1').style.display = 'none';
		document.getElementById('tbltype2').style.display = '';
	}
	
}


function save(){
	$returnVal = validateRow(document.form1);

	if($returnVal==true){
		document.form1.action="<?php echo $this->url(array('module'=>'exam','controller'=> 'asscomponent','action'=>'addform')); ?>";
		document.form1.submit();
	}
}

function back(){
	window.location="<?php echo $this->url(array('module'=>'exam','controller'=>'asscomponent','action'=>'index'), 'default', true);?>";
}



</script>




<div class="message toolbar">
	<h2><?php echo $this->title; ?></h2>
	<div class="toolbar-button">
		<ul>	
		   <li>
				<!--<input type="Submit" value="Submit" onsubmit="return validateRow(this.form);" />
				-->
				   <a href="#" onClick="save();">
					<span class='save'></span>
					Save
				</a>
			</li>
			<li class="divider"></li>		
			<li>
				 <a  href="#" onclick="addRowToTable();">
					<span class='add'></span>
					Add Row
				 </a>
			</li>
			<li>
				<a href="#" onClick="removeRowFromTable();">
					<span class='remove' align="center"></span>
					Remove Row
				</a>
			</li>
			
			<li>							
					<a href="#" onClick="back()">
						<span class='back'></span>Back</a>				
			</li>	
	
			</ul>
	</div>
</div>

<br>
<?if(isset($this->noticeMessage)){?>
<div class="message notice"><strong><? echo $this->noticeMessage;?></strong>.</div>
<br>
<?}?>
<form name="form1" action="" method="post">
	
	<table class="table3" width="600px" cellpadding="5" cellspacing="1" border="0">

					<tr>
						<th>
							Program 
						</th>					
						<td>:			
							<input type="hidden" name="program_id" value="<?php echo $this->program_id?>" size="50"></input>
							<?php echo $this->program_name;?>
						</td>
					</tr>
					<tr>
						<th>
							Course
						</th>
						
						<td>	:					
							<input  type="hidden" name="course_id" value="<?php echo $this->course_id?>" size=50></input>
							<?php echo $this->course_name;?>
						</td>
						</td>
					</tr>			
					
						<tr>
		<th>
			Mark Distribution Type
		</th>
		
		<td>
		<?php echo $this->mark_tname;?>
			
		</td>
	</tr>
					
				</table>

<br></br>
<span id="tbltype1" >

<br>
<h2>Add Assessment Component Instruction</h2>
<ul style="1">
	<li>To add row, click on "Add Row" button.</li>
	<li>To remove row, click on "Remove Row" button.</li>
	<li>Fill in the information required then click "Save" button to save.</li>
</ul>
<br>
<table id="tblComponent" class="table3" width="80%" cellpadding="5" cellspacing="1" >
  <tr>
    <th colspan="5">Assessment Component List.</th>
  </tr>
  <tr>
    <td>No</td>   
    <td>Component Name</td>
    <td>Weightage</td>
    <td>Pass Mark</td>
    <td>Total Mark</td>    
  </tr>
  <tr>
    <td>1</td>  
    <td>
  <!--  <input type="text" name="component_name1" id="component_name1" size="20"   />-->
    <select name="component_id1" id="component_id1">
    		<option value="0">-- <?php echo $this->translate("Please Select")?> --</option>
        <? foreach ($this->components as $component){?>
    		<option value="<?php echo $component["id"]?>"><?php echo $component["component_name"]?></option>
    	<? } ?>
    </select>
    </td>
    <td><input type="text" name="component_weightage1" id="component_weightage1"></input></td>
    <td><input type="text" name="component_passing_mark1" id="component_passing_mark1"></input></td>
    <td><input type="text" name="component_total_mark1" id="component_total_mark1"></input></td>    
  </tr>
</table>
<input type="hidden" name="iteration" id="iteration" value="1"></input>

<!--
	<p>Total Weightage : <input type="text" id="total_weightage" value="0" size=5 readonly="readonly"></input></p>
-->

</span>


<!-- other options:- -->
<span id="tbltype2" style="display:none" >
<table id="tblComponent2" class="table" width="50%" cellpadding="5" cellspacing="1" >
	<tr>
		<th>No</th>   
    	<th>Component Name</th>
    </tr>
    <tr align="center">
		<td >1</td>   
    	<td><input type="text" name="component_name" id="component_name" size="20" value="Final Mark" /></td>
    </tr>
</table>
<table width=50%>
<tr><td  align="right">
<input type="Submit" value="Submit"/>
</td></tr>
</table>
</span>



</form>