<script type="text/javascript">
    $(document).ready(function(){
        $("#changePassword").submit(function(){
            //e.preventDefault();
            $(".error").remove();
            current  = $("#current_password").val();
            new_pass = $("#new_password").val();
            retype_pass = $("#retype_password").val();
            
            if((current != '') && (new_pass != '') && (retype_pass != ''))
            {
                if(new_pass != retype_pass)
                {
                    $('<span class="error">Password Mismatch</span>').insertAfter("#retype_password");
                    return false
                }
                else
                {
                    return true
                }
                
            }
            else
            {
                if(current == '')
                {
                    $('<span class="error"><?php echo $this->translate('This field cannot be empty');?></span>').insertAfter("#current_password");
                }
                
                if(new_pass == '')
                {
                    $('<span class="error"><?php echo $this->translate('This field cannot be empty');?></span>').insertAfter("#new_password");
                }
                
                if(retype_pass === '')
                {
                    $('<span class="error"><?php echo $this->translate('This field cannot be empty');?></span>').insertAfter("#retype_password");
                }
                return false
            }
        });
        
    });
</script>

<style type="text/css">
select, input[type='text']{
	width:250px;
}

</style>
<?php if($this->msg == true):?>
<div class="message success">
	<h2><?php echo $this->translate('Your password has changed'); ?></h2>
	<div class="toolbar-button">
		
	</div>
</div>
<?php endif;?>
<div class="message toolbar">
	<h2><?php echo $this->title; ?></h2>
	<div class="toolbar-button">
		
	</div>
</div>
<div>
    <form method="POST" id="changePassword">
        <table>
            <tr>
                <td>Current Password</td>
                <td><input type="password" name="current_password" id="current_password" />
                    <?php if($this->incorrect == true):?>
                        <span class="error"><?php echo $this->translate('Incorrect Password!');?></span>
                    <?php endif;?>
                </td>
            </tr>
            <tr>
                <td><label>New Password</label></td>
                <td><input type="password" name="new_password" id="new_password"/></td>
            </tr>
            <tr>
                <td><label>Retype New Password</label></td>
                <td><input type="password" name="retype_password" id="retype_password" /></td>
            </tr>
            <tr>
                <td colspan="2"><input type="submit" value="Submit" /></td>
            </tr>
        </table>
     </form>
</div>