<script type="text/javascript">
	function del(title, id){
		if(confirm('Are you sure to delete '+title+'?')){
			window.location = "<?php echo $this->url(array('module'=>'onapp','controller'=>'qualificationitem', 'action'=>'delete')); ?>/id/"+id;
		}
	}
	
	function add(){
		window.location="<?php echo $this->url(array('module'=>'onapp','controller'=>'qualificationitem', 'action'=>'add'));?>";
	}

	function edit(id){
		window.location="<?php echo $this->url(array('module'=>'onapp','controller'=>'qualificationitem', 'action'=>'edit'));?>/id/"+id;
	}

</script>
<?php 
	echo "<h1>". $this->title ."</h1>";
?>

<div style="width:900px; margin: 0 auto;">
	<div class="span-7 buttons">
		<a class="positive addLink" href="#" onClick="add()">Add Programme</a>
	</div>
	<br />
<?php 
	echo $this->paginationControl($this->paginator,'Sliding','paginationTop.phtml');
?>
<table class="table" width="100%" cellpadding="5" cellspacing="0" border="0">
	<tr>
		<th width="5">Bil</th>
		<th>Programme Name</th>
		<th width="110px"><i>options</i></th>
	</tr>
	
	<?php 
	$i=1;
	foreach ($this->paginator as $entry): 
	?>
	<tr <?php echo $i%2==0?"class='shade'":""; ?>>
		<td><?php echo $i ?></td>
		<td><?php echo $entry['sc005desc']; ?></td>
		<td>
			<a class="editLink" href="#" onClick="edit(<?php echo $entry['ID']; ?>)">Edit</a>&nbsp;
			<a class="delLink2" href="#" onClick="del('<?php echo $entry['ID']; ?>',<?php echo $entry['ID']; ?>)">Delete</a>
		</td>
	</tr>
	<?php 
	$i++;
	endforeach 
	?>

</table>
</div>
<?php 
	//echo $this->paginationControl($this->paginator,'Sliding','paginationBottom.phtml');
?>
