

  


<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
.container {
  position: relative;
  width: 100%;
  max-width: 400px;
}

.container img {
  width: 100%;
  height: auto;
}

.container .btn {
  position: bottom;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  -ms-transform: translate(-50%, -50%);
  background-color: #555;
  color: white;
  font-size: 16px;
  padding: 12px 24px;
  border: none;
  cursor: pointer;
  border-radius: 5px;
  text-align: center;
}

.container .btn:hover {
  background-color: darkblue;
}
</style>
<script> 
function send(){
	$("#form").submit();
}
</script>
</head>
<body>
 
<form method="post" id="form">
<div class="container">
  <img src="/documents/pemira.jpeg" alt="Snow" style="width:100%">
  <button class="btn" onclick="send()">Vote</button>
</div>
</form>

</body>
</html>