<table cellpadding='5' cellspacing='5'>
	<tr>
		<td>Nomor</td>
		<td width='5px'>:</td>
		<td></td>
	</tr>
	<tr>
		<td>Lampiran</td>
		<td width="5px">:</td>
		<td>1 berkas</td>
	</tr>
	<tr valign='top'>
		<td>Perihal</td>
		<td width="5px">:</td>
		<td>Hasil Seleksi PSSB<br>Facultas <?php echo $this->faculty_name; ?></td>
	</tr>
	<tr valign='top'>
		<td>Kepada Yth</td>
		<td width="5px">:</td>
		<td>Sdr. Wakil Rektor Bidang Akademik<br>u.p Sdr.Ka.BAA<br><strong>UNIVERSITAS TRISAKTI</strong></td>
	</tr>
	<tr>
		<td>&nbsp;</td>
		<td width="5px">&nbsp;</td>
		<td>Dengan ini kami laporkan hasil seleksi lamaran PSSB,<br><br>
			<table>
				<tr>
					<td>- Facultas</td>
					<td>:</td>
					<td><?php echo $this->faculty_name; ?></td>
				</tr>
				<tr>
					<td>- Bulan</td>
					<td>:</td>
					<td><?php echo $this->bulan; ?></td>
				</tr>
				<tr>
					<td>- Periode</td>
					<td>:</td>
					<td><?php echo $this->periode; ?></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td>&nbsp;</td>
		<td width="5px">&nbsp;</td>
		<td>dengan hasil sebagai berikut:<br><br>
		
			<table>
				<tr>
				    <td width='5px'>-</td>
					<td>Lamaran yang <strong>DITERIMA</strong> berjumlah : <?php echo $this->total_offer;?> orang.</td>					
				</tr>
				<tr>
				    <td width='5px'>&nbsp;</td>
					<td>Dengan rincian sebagai berikut:</td>					
				</tr>	
				<tr>
				    <td width='5px'>&nbsp;</td>
					<td>
							<table cellspacing='5' cellpadding='5'>
							<?php //loop program based on faculty
							$i=1;
							$total_offer=0;
							foreach($this->program_list as $p){ 
								
								$appProgramDB = new App_Model_Application_DbTable_ApplicantProgram();
								$total_offer = $appProgramDB->getTotalStudent($p["ProgramCode"],$this->period_id,'OFFER');
								echo "<tr>
									  <td>$i.</td>
									  <td>Program Studi  ".ucwords($p['ArabicName'])."</td>
									  <td> : ".$total_offer." orang</td>
									  </tr>";
								
							$i++;}?>
							</table><br><br>
					</td>					
				</tr>	
				
					<tr>
				    <td width='5px'>-</td>
					<td>Lamaran yang <strong>DITOLAK</strong> berjumlah : <?php echo $this->total_offer;?> orang.</td>					
				</tr>
				<tr>
				    <td width='5px'>&nbsp;</td>
					<td>Dengan rincian sebagai berikut:</td>					
				</tr>	
				<tr>
				    <td width='5px'>&nbsp;</td>
					<td>
							<table cellspacing='5' cellpadding='5'>
							<?php //loop program based on faculty
							$i=1;
							foreach($this->program_list as $p){ 
								$appProgramDB = new App_Model_Application_DbTable_ApplicantProgram();
								$total_reject = $appProgramDB->getTotalStudent($p["ProgramCode"],$this->period_id,'REJECT');
								
								echo "<tr>
									  <td width='5px'>$i.</td>
									  <td>Program Studi  ". ucwords($p['ArabicName'])."</td>
									  <td> : ".$total_reject." orang</td>
									  </tr>";
								
							$i++;}?>
							</table>
					</td>					
				</tr>			
			</table>
			
		</td>
	</tr>
	<tr>
		<td>&nbsp;</td>
		<td width="5px">&nbsp;</td>
		<td>Mohon kiranya hasil seleksi PSSB sesuai tersebut diatas diterbitkan hasilnya <br>
			sesuai Surat Keputusan Wakil Rektor Bidang Akademik pada:<br>
			Bulan :<br>
			Minggu ke : 1/2/3/4 (pilih salah satu)<br>
			Rincian terlampir.<br><br>
			Demikian kami sampaikan.Terima kasih atas perhatian dan kerjasamanya.<br>
		</td>
	</tr>
	<tr>
		<td>&nbsp;</td>
		<td width='5px'>&nbsp;</td>
		<td align='right'>
		<br>
		<br>
		<br>
		<table ><tr><td align='center'>Dekan,<br><br><br>(......................)</td></tr></table>
		
		
		</td>
	</tr>
</table>