
<style type="text/css">
#sliptbl
{
width:100%;
border-collapse:collapse;
}
#sliptbl td, #sliptbl th 
{
font-size:1em;
border:1px solid #98bf21;
padding:3px 7px 2px 7px;
}
#sliptbl th 
{
font-size:1.1em;
text-align:left;
padding-top:5px;
padding-bottom:4px;
background-color:#A7C942;
color:#ffffff;
}

.barcode {font-family: ccode39}

</style>


<p>
<table id="printbl"><tr><td align="right">
<input type="button" value="PRINT" onclick="goprint();"></input></td></tr></table>
</p>

<table width="100%" border="0" cellspacing="0" cellpadding="5">
<tr><td align=left>
<img src="/images/ustlogo.png " alt="USTY LOGO"/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<img src="/images/ustyname.gif " alt="USTY NAME"/>
</td></tr>

 
  <tr> 
    <td><div align="center">
    
    		<strong>STUDENT MARK VERIFICATION REQUEST FORM</strong></div></td>
  </tr>
</table>

<br>
<br>
<br>
<?php if($this->student_list){?>
<table  width="100%" cellpadding="5" cellspacing="0">
	<tr><td width="10%">Program</td><td>:&nbsp;<?php echo $this->program_name?></td></tr>
	<tr><td>Course</td><td>:&nbsp;<?php echo $this->course_name?></td></tr>
	<tr><td>Semester</td><td>:&nbsp;<?php echo $this->semester_name?></td></tr>
</table>
<br></br>
<table class="table" width="100%" cellpadding="5" cellspacing="1" >

	<tr align="center">
	   <th>No.</th>		
		<th>Student Name</th>		
		<?php foreach($this->asscomponent_list as $component) { 		
			echo "<th>$component[component_name]</th>";
	     }?>	
	     <th>Total Mark</th>			
	</tr>
	
	<?php $i=0;
	foreach($this->student_list as $student){?>	
	<tr  align="center">
	    <td><?php echo $i+1;?></td>
	   <td width="30%">					
			<?php echo $student["fullname"];?>
		</td>
		    
			<?php	
			$final_course_mark=0;						   
			foreach($this->asscomponent_list as $component) {
				//get current mark
    	          $oMark = new App_Model_Exam_DbTable_Markentry();
    	          $mark  = $oMark->getMarkByComponent($student["scr_id"],$component["id"]); 
				
				echo "<td width=10%>$mark[component_student_mark]</td>";
				//kira total mark
				$total = ($mark["component_student_mark"]/$component["component_total_mark"])*$component["component_weightage"];
        	    $final_course_mark = $final_course_mark+$total; //total mark per course      
				
			}?>	
	         <td><?php echo $final_course_mark;?></td>		
	</tr>
	<?php  $i++;} ?>
	
</table>


<?php }//end if student list?>
<br>
</br>
<br></br>

<table border=0 width="100%" height="100">
<tr><td width=15%>Print On</td><td  width=30%>: <?php echo date("d M Y h:i:s");?></td><td  width=15%>Signature</td><td  width=30%>:</td></tr>
<tr><td>Print By</td><td>: <?php echo $this->username?></td><td>Verify By</td><td>:</td></tr>
<tr><td>Request Number</td><td>: <?php echo $this->request_number;?></td><td>Date</td><td>:</td></tr>
</table>
<script>

function goprint(){
	document.getElementById('printbl').style.display = 'none';
	window.print();
}
</script>