<style>
.button-group, .play-area {
  border: 1px solid grey;
  padding: 1em 1%;
  margin-bottom: 1em;
}

.button {
  padding: 0.5em;
  margin-right: 1em;
}

.play-area-sub {
  width: 47%;
  padding: 1em 1%;
  display: inline-block;
  text-align: center;
}

#capture {
  display: none;
}

#snapshot {
  display: inline-block;
  width: 320px;
  height: 240px;
}
</style>
 <script type="text/javascript">
  function startExam(idtrx) {
	  window.location.replace('/examapplicant/examination/start-exam/idtrx/'+idtrx);
  }

  $(window).bind("load", function() {
	   // code here
	   startStreaming();
});

</script>
<div class="message toolbar">
	<h2><?php echo $this->title; ?></h2>
	<div class="toolbar-button">
		<ul>		
			<li>
				 	<span class='info'>Info</span>
					
				 
			</li>
		</ul>
	</div>
</div>
<br>


<?php if(isset($this->noticeMessage)){?>
<div class="message notice"><strong><?php echo $this->noticeMessage;?></strong>.</div>
<?php }?>
<?php if(isset($this->noticeSuccess)){?>
<div class="message success"><strong><?php echo $this->noticeSuccess;?></strong>.</div>
<?php }?>
<?php if(isset($this->noticeError)){?>
<div class="message error"><strong><?php echo $this->noticeError;?></strong>.</div>
<?php }?>

<div>
	<fieldset>
		<legend><?php echo $this->translate("Detail Information About Your Exam");?></legend>
			<?php if ($this->test=="1") {?>
			<table class="table">
			<tr><td colspan="3" bgcolor="lightgreen" align="center">
				 <input class="btn" type="button" id="btnstart" value="<?php echo $this->translate('Start Exam');?>" onclick="startExam('<?php echo $this->transaction["at_trans_id"];?>')" disabled>
				</td></tr>
			 <tr><td><?php 
					if($this->photo!=null){
						//$imageHelper = new icampus_Function_General_Image();
						//$path = $imageHelper->getImagePath($this->photo['pathupload'],250,250);			
						$dt = explode("triapp",$this->photo['pathupload']);
						$path = $dt[1]; 
					?>
						<img class="photo" src="<?php echo $path; ?>"/>
					<?php }else{?>
						<img class="photo" src="/images/no-photo.jpg" width="194" height="250" />
					<?php }?>
					 <div class="play-area-sub">
				    <h3>The Capture</h3>
				    <canvas id="capture" width="200" height="240"></canvas>
				    <div id="snapshot"></div>
				  </div>
				</td>
			 <td>
			 <table class="table">
			 	<tr>
			 		<th><?php echo $this->translate('Name')?></th>
			 		<td><?php echo $this->transaction['appl_fname'].' '.$this->transaction['appl_mname'].' '.$this->transaction['appl_lname']?></td>
			 	<tr>
			 	<tr>
			 		<th><?php echo $this->translate('No. Formulir')?></th>
			 		<td><?php echo $this->transaction['at_pes_id']?></td>
			 	<tr>
			 	<tr>
			 		<th><?php echo $this->translate('Address')?></th>
			 		<td><?php echo $this->transaction['appl_address1']?></td>
			 	<tr>
			 	<tr>
			 		<th><?php echo $this->translate('Program Study')?></th>
			 		<td><?php  
			 			 
			 				echo 'Pilihan I 	:'.$this->program['program_code1'].' '.$this->program['program_name1'].'<br>';
			 				echo 'Pilihan II	:'.$this->program['program_code2'].' '.$this->program['program_name2'].'<br>';
						?></td>
			 	<tr>
			 </table>
			 <table>
			 		 
			 		<?php foreach ($this->examdetail as $exam) {
			 				$comps=$exam['compcode'];?>
			 			<tr><th><?php echo $exam['ptestname']?></th>
			 				<th><?php echo $exam['aps_test_date']?></th>
			 				<th><?php echo $exam['time_start'].'-'.$exam['time_stop']?></th>
			 			</tr>
			 			<tr><td colspan="3"><?php foreach ($comps as $comp ) echo $comp['ac_comp_name_bahasa'].' '?></td></tr>
			 		<?php }?>
			 	</table>
			 </td>
			 <td>
			 <div class="play-area">
				  <div class="play-area-sub">
				    <h3>Ambil Foto anda untuk autentikasi online</h3> <button id="btn-capture" type="button" class="button">Ambil Foto</button>
				    <video id="stream" width="320" height="240"></video>
				  </div>
				 
</div>
			 
			 </td>
			 </tr>
			 
			</table>
			<?php } else  echo "Pada hari ini tidak ada Ujian Saringan Masuk";?>		 
	</fieldset>
</div>  
 

<script>



//The buttons to start & stop stream and to capture the image
//var btnStart = document.getElementById( "btn-start" );
//var btnStop = document.getElementById( "btn-stop" );
var btnCapture = document.getElementById( "btn-capture" );

//The stream & capture
var stream = document.getElementById( "stream" );
var capture = document.getElementById( "capture" );
var snapshot = document.getElementById( "snapshot" );



//The video stream
var cameraStream = null;

//Attach listeners
//btnStart.addEventListener( "click", startStreaming );
//btnStop.addEventListener( "click", stopStreaming );

//Start Streaming
function startStreaming() {

	 
	
	var mediaSupport = 'mediaDevices' in navigator;

	if( mediaSupport && null == cameraStream ) {

		navigator.mediaDevices.getUserMedia( { video: true } )
		.then( function( mediaStream ) {

			cameraStream = mediaStream;

			stream.srcObject = mediaStream;

			stream.play();
			$("#btnstart").attr("disabled", false);
		})
		.catch( function( err ) {

			console.log( "Unable to access camera: " + err );
		});
	}
	else {

		alert( 'Your browser does not support media devices.' );

		return;
	} 
}

//Stop Streaming
function stopStreaming() {

	if( null != cameraStream ) {

		var track = cameraStream.getTracks()[ 0 ];

		track.stop();
		stream.load();

		cameraStream = null;
	}
}

btnCapture.addEventListener( "click", captureSnapshot );

function captureSnapshot() {

	if( null != cameraStream ) {

		var ctx = capture.getContext( '2d' );
		var img = new Image();

		ctx.drawImage( stream, 0, 0, capture.width, capture.height );

		img.src		= capture.toDataURL( "image/png" );
		img.width	= 200;
		img.height	= 240;

		snapshot.innerHTML = '';

		snapshot.appendChild( img );
	}
}
function sendData(){
	var request = new XMLHttpRequest();
	
	request.open( "POST", "/upload/url", true );
	
	var data	= new FormData();
	var dataURI	= snapshot.firstChild.getAttribute( "src" );
	var imageData   = dataURItoBlob( dataURI );
	
	data.append( "image", imageData, "myimage" );
	
	request.send( data );
}
</script>