<style>
.button-group, .play-area {
  border: 0px solid grey;
  padding: 1em 1%;
  margin-bottom: 1em; 
}
p    {color: white; font-size: 20px}

.button {
  padding: 0.5em;
  margin-right: 1em;
}

.play-area-sub {
  padding: 1em 1%;
  display: inline-block;
  text-align: center; 
}

#capture {
  	display: none;
	
		
}

#snapshot {
  display: inline-block;
  width: 200px;
  height: 150px;
}
</style>
 <script type="text/javascript">
  function startExam(idtrx) {
	  if ($("#photo").val()=="ok") {
	  	 //stopStreaming();
	 	 window.location.replace('/examapplicant/examination/start-exam/idtrx/'+idtrx);

	   } else alert('Tolong klik tombol Ambil Foto terlebih dahulu');
  }
  $(window).bind("load", function() {
	   // code here
	 // $("#btnstart").attr("disabled", true);
	  startTimer("<?php echo $this->datestart?>");
	  startStreaming();
});

  function savePhoto(){
		var canvas=document.getElementById("capture");
		var dataUrl=canvas.toDataURL(); 
		type=$("#type").val();
		$.ajax({
			  type: "POST",
			  url: "/examapplicant/examination/send-start-photo",
			  data: {'image': dataUrl,'trxid':$("#transaction_id").val(),'type':type}
			})
			.done(function(respond){
				  
				//$("#type").val(type*1+1);
				$("#photo").val('ok');
				})
			.fail(function(respond){console.log("fail");});
	}
	
  function startTimer(endtime){
		var countDownDate = new Date(endtime).getTime();
		
		//Update the count down every 1 second
		var x = setInterval(function() {
		
		//Get today's date and time
		var now = new Date().getTime();
		
		//Find the distance between now and the count down date
		var distance = countDownDate - now;
		
		//Time calculations for days, hours, minutes and seconds
		 
		var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
		var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
		var seconds = Math.floor((distance % (1000 * 60)) / 1000);
		
		//Output the result in an element with id="demo"
		document.getElementById("examtime").innerHTML =  hours + " : " + minutes + " : " + seconds;
		
		//If the count down is over, write some text 
		if (distance < 0) {
			clearInterval(x);
			$("#stop").val("1");
			document.getElementById("examtime").innerHTML = '<font><strong>Waktu ujian sudah dibuka, waktu ujian anda dimulai saat anda mengklik tombol MULAI di halaman berikutnya</strong></font>';
		}
		}, 1000);
}
	
</script>
 
<?php if(isset($this->noticeMessage)){?>
<div class="message notice"><strong><?php echo $this->noticeMessage;?></strong>.</div>
<?php }?>
<?php if(isset($this->noticeSuccess)){?>
<div class="message success"><strong><?php echo $this->noticeSuccess;?></strong>.</div>
<?php }?>
<?php if(isset($this->noticeError)){?>
<div class="message error"><strong><?php echo $this->noticeError;?></strong>.</div>
<?php }?>

<div>
	<input type="hidden" id="transaction_id" value="<?php echo $this->transaction_id?>">
	<input type="hidden" id="type" value="<?php echo 500+$this->testtype*1;?>">
	<input type="hidden" id="photo" value="">
	<fieldset>
		<legend><?php echo $this->translate("Detail Information About Your Exam");?></legend>
			<?php if ($this->test=="1") {?>
			<table width="100%">
			 	<tr><td bgcolor="Darkblue" align="center"  width="15%"><p id="examtime"></p></td></tr>
			 </table>
			 <br>
			<h2>Baca petunjuk ujian seleksi masuk Usakti dengan seksama</h2>
			 
			<ol>
				<li>Pastikan kamera komputer/hp anda dinyalakan untuk pengambilan foto anda </li>
				<li>Periksa Kuota Data anda karena kebutuhan data selama pelaksanaaan USM sekitar 50 MB pastikan kuato data internet anda memenuhi</li>
				<li>Periksa semua informasi di laman ini sampai anda jumpai tombol 'Mulai'</li>
				<li>Pada halaman ini akan ada informasi terkait (1) Indentitas anda dan Program Studi yang dipilih; (2) Materi Ujian dan waktu ujian; (3) Pengambilan foto anda</li>
			 	<li>Pada layar soal tidak ada tombol save karena setiap anda menjawab sistem secara otomatis menyimpan jawaban anda dan hasilnya ditampilkan di Daftar Jawaban</li>
			 	<li>Jika waktu ujian telah selesai maka layar secara otomatis akan tertutup</li>
			 	<li>Jika waktu ujian belum selesai dan anda menutup layar soal maka ujian dianggap sudah selesai</li>
				<li>Waktu Ujian dimulai pada saat anda telah selesai memerikan kecukupan jumlah soal dihalaman berikutnya dan menekan tombol 'Mulai'</li>
			</ol>
			<hr>
			
			 
			 <br>
			<fieldset><legend><?php echo 'Identitas dan Pilihan Program Studi'?></legend>
			<table width="70%"><tr><td width="20%">
			  <?php 
					if($this->photo!=null){
					 	$dt = explode("triapp",$this->photo['pathupload']);
						$path = $dt[1]; 
					?>
						<img class="photo" src="<?php echo $path; ?>"/>
					<?php }else{?>
						<img class="photo" src="/images/no-photo.jpg" width="194" height="250" />
					<?php }?>
				 
			 </td><td valign="top">
			<table class="table" width="100%">
			 	<tr>
			 		<th><?php echo $this->translate('Name')?></th>
			 		<td><?php echo $this->transaction['appl_fname'].' '.$this->transaction['appl_mname'].' '.$this->transaction['appl_lname']?></td>
			 	<tr>
			 	<tr>
			 		<th><?php echo $this->translate('No. Formulir')?></th>
			 		<td><?php echo $this->transaction['at_pes_id']?></td>
			 	<tr>
			 	<tr>
			 		<th><?php echo $this->translate('Address')?></th>
			 		<td><?php echo $this->transaction['appl_address1']?></td>
			 	<tr>
			 	<tr>
			 		<th><?php echo $this->translate('Program Study')?></th>
			 		<td><?php  
			 			 
			 				echo 'Pilihan I 	:'.$this->program['program_code1'].' '.$this->program['program_name1'].'<br>';
			 				echo 'Pilihan II	:'.$this->program['program_code2'].' '.$this->program['program_name2'].'<br>';
						?></td>
			 	<tr>
			 </table>
			 </td></tr>
			 </table>
			 </fieldset>
			 <br>
			 <fieldset><legend><?php echo 'Informasi Materi Ujian Seleksi'?></legend>
			 
			 <table class="table" width="70%">
			 		 
			 		<?php foreach ($this->examdetail as $exam) {
			 				$comps=$exam['compcode'];?>
			 			<tr>
			 			<td width="5px"><?php if ($exam['active']=="1") {?>
			 					<img src="/images/icon/green.png"  style="width:25px;height:25px;" title="<?php echo 'Open';?>"> </a>  
			 				<?php } else {?>
			 					<img src="/images/icon/red.png"  style="width:20px;height:20px;" title="<?php echo 'Close';?>"> </a>
			 				<?php }?></td>
			 			<th><?php echo $exam['ptestname']?></th>
			 				<th><?php echo date('d-m-Y',strtotime($exam['aps_test_date']))?></th>
			 				<th><?php echo $exam['time_start'].'-'.$exam['time_stop']?></th>
			 			</tr>
			 			<tr><td colspan="4"><?php foreach ($comps as $comp ) echo $comp['ac_comp_name_bahasa'].'<br> '?></td></tr>
			 		<?php }?>
			 </table>
			  
			 </fieldset>
			<table  >
			<tr>
			<td width="30%" align="left">
			 	<div class="play-area">
				  
				    Ambil Foto anda untuk bukti daring 
				    <button id="btn-capture" type="button" class="button">Ambil Foto</button>
				    <video id="stream" width="320" height="240"></video>
		 		</div>
	 		 </td>
			 <td width="20%" align="center">
			 
					 <div class="play-area-sub">
				    <canvas id="capture" width="160" height="120"></canvas>
				    <div id="snapshot"></div>
				  </div>
				</td>
			 
			 
			 </tr>
			<tr><td colspan="2">&nbsp;</tr>
			<tr><td colspan="2" bgcolor="lightgreen" align="center">
				 <input class="btn" type="button" id="btnstart" value="<?php echo $this->translate('Next');?>" onclick="startExam('<?php echo $this->transaction["at_trans_id"];?>')">
			</td></tr>
			</table>
			<?php } else  {
				echo "Pada hari ini tidak ada Ujian Saringan Masuk";
				echo "<br>";
				echo 'Jika ingin mencoba silahkan klik <a href="/examapplicant/examination/index-training">link ini</a>';
			 
			}?>	
			
				 
	</fieldset>
</div>  
 

<script>



//The buttons to start & stop stream and to capture the image
//var btnStart = document.getElementById( "btn-start" );
//var btnStop = document.getElementById( "btn-stop" );
var btnCapture = document.getElementById( "btn-capture" );

//The stream & capture
var stream = document.getElementById( "stream" );
var capture = document.getElementById( "capture" );
var snapshot = document.getElementById( "snapshot" );



//The video stream
var cameraStream = null;

//Attach listeners
//btnStart.addEventListener( "click", startStreaming );
//btnStop.addEventListener( "click", stopStreaming );

//Start Streaming
function startStreaming() {

	 
	
	var mediaSupport = 'mediaDevices' in navigator;

	if( mediaSupport && null == cameraStream ) {

		navigator.mediaDevices.getUserMedia( {video: { width: 1280, height: 720 }})
		.then( function( mediaStream ) {

			cameraStream = mediaStream;

			stream.srcObject = mediaStream;

			stream.play();
		})
		.catch( function( err ) {

			console.log( "Unable to access camera: " + err );
		});
		
	}
	else {

		alert( 'Your browser does not support media devices.' );

		return;
	} 
}

//Stop Streaming
function stopStreaming() {

	if( null != cameraStream ) {

		var track = cameraStream.getTracks()[ 0 ];

		track.stop();
		stream.load();

		cameraStream = null;
	}
}

btnCapture.addEventListener( "click", captureSnapshot );

function captureSnapshot() {

	if( null != cameraStream ) {

		var ctx = capture.getContext( '2d' );
		var img = new Image();

		ctx.drawImage( stream, 0, 0, capture.width, capture.height );

		img.src		= capture.toDataURL( "image/png" );
		img.width	= 160; 

		snapshot.innerHTML = '';

		snapshot.appendChild( img );
 		savePhoto();
		
	}
} 
</script>