<style>
.button-group, .play-area {
  border: 0px solid grey;
  padding: 0em 1%;
  margin-bottom: 0em; 
}
p    {color: white; font-size: 20px}

.button {
  padding: 0.5em;
  margin-right: 1em;
}

.play-area-sub {
  padding: 1em 1%;
  display: inline-block;
  text-align: center; 
}

#capture {
  	display: none;
	
		
}

#snapshot {
  display: inline-block;
  width: 200px;
  height: 150px;
}
</style>
 <script type="text/javascript">
 function close(){
	 $("#dialog-result").dialog('open');
 }
</script>
  

<div>
	<input type="hidden" id="transaction_id" value="<?php echo $this->transaction_id?>">
	 
	<fieldset><legend><?php echo $this->translate("Daftar Hasil Ujian Anda");?></legend>
			 
	<table class="table">
	
	<?php foreach ($this->component as $value) {
		
		?><tr><th rowspan="2"><?php echo $value['ac_comp_name_bahasa']?></th>
		 <?php foreach ($value['ans'] as $ans) {
		 			?><th><?php echo $ans['apad_ques_no']?></th><?php  
		 		}
		 ?></tr>
		 <tr>
		  <?php foreach ($value['ans'] as $ans) {
		 			?><td align="center"><?php echo $ans['apad_appl_ans']?></td><?php  
		 		}
		 ?>
		 </tr>
		 
		 <?php 
	}?>

	</table>
	<table  width="100%"> 
			<tr><td colspan="2" bgcolor="lightgreen" align="center">
				 <input class="btn" type="button" id="btnstart" value="<?php echo $this->translate('Finish');?>" onclick="keluar()">
				  <input class="btn" type="button" id="btnstart" value="<?php echo $this->translate('Close');?>" onclick="close()">
			</td></tr>
			</table> 
	</fieldset>
</div>  
 
 