<style>
p    {color: white; font-size: 16px}
.numberCircle {
    border-radius: 50%;
    width: 36px;
    height: 36px;
    padding: 8px;

    background: #fff;
    border: 2px solid #666;
    color: #666;
    text-align: center;

    font: 32px Arial, sans-serif;
}
</style>
<script src="https://cdnjs.cloudflare.com/ajax/libs/fabric.js/2.4.5/fabric.js"></script>
<script type="text/javascript">


$(function() {
	 
	$(".next").click(function(){
	var  order=$("#order").val()*1;
	if (order<=$("#n_of_quest").val() & $("#stop").val()!="1") {
		 	$.ajax({
					url: '<?php echo $this->baseUrl();?>/examapplicant/examination/ajax-get-question',
					type: 'POST',
					data: {'apa_id': $("#apa_id").val(),'order':order+1},
					dataType: 'json',
					error: function(){
							alert("Terjadi masalah saat menghapus data !");
						}, 
					}).done(function ( data ) {
		 					//$("#QuestionTxt").val(data.question);
		 					$("#ordertxt").text(data.apad_ques_no);
		 					$("#order").val(data.apad_ques_no);
		 					if (data.apad_appl_ans==" ") {
								var selValue = $("input[type='radio']:checked").val();
								 $('input:radio[name="answer"][value="'+selValue+'"]').attr('checked',false);
							}
							else $('input:radio[name="answer"][value="'+data.apad_appl_ans+'"]').attr('checked',true);
							
		 					$("#answered"+data.apad_ques_no).text(data.apad_appl_ans);
		 					$("#idQuestion").val(data.idQuestion);
		 					$("#apad_id").val(data.apad_id);
		 					var urllink=data.question_url;
		 					
		 					$("#Question").attr("src",urllink);
							if (data.question_parent_url!='') 
								$("#parent").attr("src",data.question_parent_url);
							else $("#parent").attr("src","");
		 			});
			}
	});

	$(".pre").click(function(){
		var order=$("#order").val()*1;
		if (order>1 & $("#stop").val()!="1") {
			 	$.ajax({
						url: '<?php echo $this->baseUrl();?>/examapplicant/examination/ajax-get-question',
						type: 'POST',
						data: {'apa_id': $("#apa_id").val(),'order':order-1},
						dataType: 'json',
						error: function(){
								alert("Terjadi masalah saat menghapus data !");
							}, 
						}).done(function ( data ) {
			 					//$("#QuestionTxt").val(data.question);
			 					$("#ordertxt").text(data.apad_ques_no);
			 					$("#order").val(data.apad_ques_no);
			 					$("#apad_id").val(data.apad_id);
			 					if (data.apad_appl_ans==" ") {
									var selValue = $("input[type='radio']:checked").val();
									 $('input:radio[name="answer"][value="'+selValue+'"]').attr('checked',false);
								}
								else $('input:radio[name="answer"][value="'+data.apad_appl_ans+'"]').attr('checked',true);
								
			 					$("#answered"+data.apad_ques_no).text(data.apad_appl_ans);
			 					$("#idQuestion").val(data.idQuestion);
			 					var urllink=data.question_url;
			 					$("#Question").attr("src",urllink);
								if (data.question_parent_url!='') 
									$("#parent").attr("src",data.question_parent_url);
								else $("#parent").attr("src","");
			 			});
				}
			});
		 
		
 
});

function getQuestion(order){
	if ( $("#stop").val()!="1") {
	$.ajax({
		url: '<?php echo $this->baseUrl();?>/examapplicant/examination/ajax-get-question',
		type: 'POST',
		data: {'apa_id': $("#apa_id").val(),'order':order},
		dataType: 'json',
		error: function(){
				alert("Terjadi masalah saat menghapus data !");
			}, 
		}).done(function ( data ) {
					//$("#QuestionTxt").val(data.question);
					$("#ordertxt").text(data.apad_ques_no);
					$("#order").val(data.apad_ques_no);
					$("#apad_id").val(data.apad_id);
					if (data.apad_appl_ans==" ") {
						var selValue = $("input[type='radio']:checked").val();
						 $('input:radio[name="answer"][value="'+selValue+'"]').attr('checked',false);
					}
					else $('input:radio[name="answer"][value="'+data.apad_appl_ans+'"]').attr('checked',true);
					//$("#answer").val(data.apad_appl_ans);
					$("#answered"+data.apad_ques_no).text(data.apad_appl_ans);
					$("#idQuestion").val(data.idQuestion);
					 
					var urllink=data.question_url;
					$("#Question").attr("src",urllink);
					if (data.question_parent_url!='') 
						$("#parent").attr("src",data.question_parent_url);
					else $("#parent").attr("src","");
			});
	}
}

 

function saveAnswer(answer){
	 if ($("#stop").val()!="1") {
			var idQuestion=$("#idQuestion").val();
			var order=$("#order").val();
			 
			$.ajax({
				  type: "POST",
				  url: "/examapplicant/examination/ajax-save-answer",
				  data: {'idQuestion':idQuestion,'apad_id':$("#apad_id").val(),'answer':answer,'order':order},
				  dataType: 'json'
				})
				.done(function(respond){
					 var element="#answered"+respond.apad_ques_no;
					 $(element).text(respond.apad_appl_ans);
					 
					})
				.fail(function(respond){console.log("fail");})
				.always(function(respond){console.log("always");
			});
	 }
}

function firstQuestion(Qurl,parenturl) {
	$("#Question").attr("src",Qurl);
 	//populateCanvas("Question",Qurl);
	if (parenturl!='') 
		$("#parent").attr("src",parenturl);
	else $("#parent").attr("src","");
	if ("<?php echo $this->question['apad_appl_ans'] ?>"==" ") {
		var selValue = $("input[type='radio']:checked").val();
		 $('input:radio[name="answer"][value="'+selValue+'"]').attr('checked',false);
	}
	else $('input:radio[name="answer"][value="<?php echo $this->question['apad_appl_ans'] ?>"]').attr('checked',true);
	
	//startTimer("<?php echo $this->question['stop_time']?>");
	startTimer("2020-03-30 13:00:00");
}

$(window).bind("load", function() {
	   // code here
	firstQuestion($('#question_url').val(),$('#question_parent_url').val());
});

function startTimer(endtime){
		var countDownDate = new Date(endtime).getTime();
		
		//Update the count down every 1 second
		var x = setInterval(function() {
		
		//Get today's date and time
		var now = new Date().getTime();
		
		//Find the distance between now and the count down date
		var distance = countDownDate - now;
		
		//Time calculations for days, hours, minutes and seconds
		 
		var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
		var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
		var seconds = Math.floor((distance % (1000 * 60)) / 1000);
		
		//Output the result in an element with id="demo"
		document.getElementById("examtime").innerHTML =  hours + " : " + minutes + " : " + seconds;
		
		//If the count down is over, write some text 
		if (distance < 0) {
			clearInterval(x);
			$("#stop").val("1");
			document.getElementById("examtime").innerHTML = '<font color="red"><strong>Waktu Ujian Habis</strong></font>';
		}
		}, 1000);
}
</script>
 
<body >
<?php if(isset($this->noticeMessage)){?>
<div class="message notice"><strong><?php echo $this->noticeMessage;?></strong>.</div>
<?php }?>
<?php if(isset($this->noticeSuccess)){?>
<div class="message success"><strong><?php echo $this->noticeSuccess;?></strong>.</div>
<?php }?>
<?php if(isset($this->noticeError)){?>
<div class="message error"><strong><?php echo $this->noticeError;?></strong>.</div>
<?php }?>
<input type="hidden" id="apa_id" name="apa_id" value="<?php echo $this->question['apad_apa_id']?>">
<input type="hidden" id="apad_id" name="apad_id" value="<?php echo $this->question['apad_id']?>">
<input type="hidden" id="idQuestion" value="<?php echo $this->question['idQuestion']?>">
<input type="hidden" id="order" value="1">
<input type="hidden" id="question_url" value="<?php echo $this->question['question_url']?>">
<input type="hidden" id="question_parent_url" value="<?php echo $this->question['question_parent_url']?>">
<input type="hidden" id="n_of_quest" value="<?php echo $this->n_of_quest?>">
<div>
	<fieldset>
		<legend><?php echo $this->translate("Answer Result");?></legend>
			<table class="table"  width="100%">
			<?php $nrow=2;
				for ($j=1;$j<=$nrow;$j++) {?>
			<tr><?php for ($i=($j-1)*$this->n_of_quest/$nrow+1;$i<=$j*$this->n_of_quest/$nrow;$i++) {?><td  width="2%" bgcolor="darkgrey" align="center"><font color="white"><a href="#" onclick="getQuestion('<?php echo $i?>')"><?php echo $i;?></a></font></td><?php }?></tr> 
			<tr><?php for ($i=($j-1)*$this->n_of_quest/$nrow+1;$i<=$j*$this->n_of_quest/$nrow;$i++) {?><td  width="2%" bgcolor="white" align="center"><div id="answered<?php echo $i;?>"><?php echo $this->answer[$i]?></div></td><?php }?></tr>
			<?php }?>
			</table>		 
	</fieldset>
</div> 
<div>
	<fieldset align="center">
		<legend><?php echo $this->translate("Exam Quetion");?></legend>
			
			<table border="0" width="100%">
			 
			 <tr>
			
			 <td colspan="2" align="center">
					 <img id="parent" src=""/>
			 	 
			 </td>
			 </tr>
			 <tr>
			 <td valign="top" align="center"><div id="ordertxt" style="font-size:14px" class="numberCircle"><strong> <?php echo $this->question['apad_ques_no']?> </strong></div></td>
			 <td align="center">
			 	 <img id="Question" src=""/>
			 </td>
			 </tr>
			 <tr bgcolor="lightblue">
				<td colspan="2" align="center">
				<table width="100%" border="0" class="table">
					<tr>
					<td   align="center" width="15%">
						 <a class="pre btn" id="pre" href="#">Soal Sebelum</a>
						 </td>
					<td bgcolor="darkblue" align="center"  width="15%"></td>
					
						  
						 <td align="center" bgcolor="white">
						 <input type="radio" name="answer" value="A" onclick="saveAnswer('A')"> A
						 <input type="radio" name="answer" value="B" onclick="saveAnswer('B')"> B
						 <input type="radio" name="answer" value="C" onclick="saveAnswer('C')"> C
						 <input type="radio" name="answer" value="D" onclick="saveAnswer('D')"> D
						 <input type="radio" name="answer" value="E" onclick="saveAnswer('E')"> E
					</td>
					<td bgcolor="darkblue" align="center"  width="15%"><p id="examtime"></p></td>
					<td align="center"  width="15%">	
					<a class="next btn" id="next" href="#">Soal Berikutnya</a>
			 		</td>
			 	</tr>
				</table>
				</td>
			 </tr>
			 
			</table>		 
	</fieldset>
</div> 
</body>
<input type="hidden" id="stop" value="">
 