<?php
echo $this->headLink ()->prependStylesheet ( $this->baseUrl () . '/css/layout.css' );
echo $this->headLink ()->prependStylesheet ( $this->baseUrl () . '/css/default/style.css' );
echo $this->headLink ()->prependStylesheet ( $this->baseUrl () . '/css/jquery-ui-1.8.5.custom.css' );
echo $this->headLink ()->prependStylesheet ( $this->baseUrl () . '/js/jquery-1.4.3.min.js' );
echo $this->headLink ()->prependStylesheet ( $this->baseUrl () . '/js/jquery.ui.core.js' );
echo $this->headLink ()->prependStylesheet ( $this->baseUrl () . '/js/jquery.ui.datepicker.j' );
?>

<form name="f1" method="post" action="<?php echo $this->url(array('module'=>'finance','controller'=>'addfee','action'=>'add'),'default',true) ?>">


<div style="width:900px; margin:0 auto;">
<div id="dark_grey">
<fieldset><legend>&nbsp;<?php echo $this->title; ?>&nbsp;&nbsp;</legend>
<link rel="stylesheet" href="../demos.css">

	
	<script>
	$(function() {
		$( "#datepicker" ).datepicker();
	});
	</script>

<?




?>	
	

	
	<table width="100%" cellpadding="5" cellspacing="1" bgcolor="#CCCCCC">
  <tr>
    <td bgcolor="#F2F2F2">1) Item </td>
    <td bgcolor="#FFFFFF">:</td>
    <td bgcolor="#FFFFFF">
  <input type="text" name="txtitem" id="txtitem" value="" style="width:70%">

	</td>
  </tr>
  <tr>
    <td bgcolor="#F2F2F2"> 2) Description </td>
    <td bgcolor="#FFFFFF">:</td>
    <td bgcolor="#FFFFFF">
   
    <input type="text" name="txtdesc" id="txtdesc" value="" style="width:70%">
    </td>
  </tr>
   <tr>
    <td bgcolor="#F2F2F2">3) Amount(RM)</td>
    <td bgcolor="#FFFFFF">:</td>
    <td bgcolor="#FFFFFF">
 
    <input type="text" name="txtamt" id="txtamt" value="" style="width:70%">
    </td>
  </tr>

  
 </table>
<br>
<table width="100%">
		<tr>
			<td valign="top" colspan="3" align="center"> <input type="submit" name="Submit" value="Add"> <input type="submit" name="Reset" value="Cancel"></td>
		</tr>
	</table>
	
</fieldset>
</div>
</div>

</form>