<script type="text/javascript">
	function del(){

		var id = $('input[name=id]:checked').val();
		
		if(confirm('Are you sure to delete?')){
			window.location = "<?php echo $this->url(array('module'=>'general-setup','controller'=>'highschool', 'action'=>'delete'),'default',true); ?>/id/"+id;
		}
	}
	
	function add(){
		window.location="<?php echo $this->url(array('module'=>'general-setup','controller'=>'highschool', 'action'=>'add'),'default',true);?>";
	}

	function edit(){
		var id = $('input[name=id]:checked').val();
		window.location="<?php echo $this->url(array('module'=>'general-setup','controller'=>'highschool', 'action'=>'edit'),'default',true);?>/id/"+id;
	}

	function searchbox(){
		$('#div_search').show();
	}

	function changeState(element,targetElement){
		var country_id = $(element).val();
		
		$.ajax({
			url: "<?php echo $this->url(array('module'=>'default','controller'=>'ajax-utility', 'action'=>'get-state'),'default',true);?>",
			data: {'country_id':$(element).val()},
			type: 'POST',
			dataType: 'json'	
		}).done(function ( data ) {
			
			$(targetElement).empty().append('<option value=""> <?php echo $this->translate("please_select"); ?> </option>');
		
			$.each(data, function(index) {
				$(targetElement).append('<option value="'+data[index].idState+'"> '+data[index].StateName+' </option>');
			});
		});
	}
	
	function changeCity(element, targetElement){
		$.ajax({
			url: "<?php echo $this->url(array('module'=>'default','controller'=>'ajax-utility', 'action'=>'get-city'),'default',true);?>",
			data: {'state_id':$(element).val()},
			type: 'POST',
			dataType: 'json'	
		}).done(function ( data ) {
			
			$(targetElement).empty().append('<option value=""> <?php echo $this->translate("please_select"); ?> </option>');
		
			$.each(data, function(index) {
				$(targetElement).append('<option value="'+data[index].idCity+'"> '+data[index].CityName+' </option>');
			});
		});
	}
</script>

<div class="message toolbar">
	<h2><?php echo $this->title; ?></h2>
	<div class="toolbar-button">
		<ul>
			<li>
				<a href="#" onclick="javascript:add()">
					<span class='add'></span>
					Add
				</a>
			</li>
			<li>
				<a href="#" onclick="javascript:edit()">
					<span class='edit'></span>
					Edit
				</a>
			</li>
			<li>
				<a href="#" onclick="javascript:del()">
					<span class='delete'></span>
					Delete
				</a>
			</li>
			<li class="divider"></li>
			<li>
				<a id="search" href="#" onclick="javascript:searchbox()">
					<span class='search'></span>
					Search
				</a>
			</li>
			<li>
				<a href="#" >
					<span class='info'></span>
					Info
				</a>
			</li>
		</ul>
	</div>
</div>
<br />

<div id="div_search" style="display:none;">
	<fieldset>
		<legend>Search</legend>
		<?php echo $this->searchForm; ?>
	</fieldset>
</div>

<div style="width:100%;">
<?php 
	echo $this->paginationControl($this->paginator,'Sliding','paginationTop.phtml');
?>
<table class="table" width="100%" cellpadding="5" cellspacing="1" border="0">
	<tr>
		<th width="2"></th>
		<th><?php echo $this->translate("School Name")?></th>
		<th><?php echo $this->translate("School Name")?>(Indonesia)</th>
		<th><?php echo $this->translate("Code")?></th>
		<th><?php echo $this->translate("Type")?></th>
		<th><?php echo $this->translate("Address")?></th>
	</tr>
	
	<?php 
	$i=0;
	foreach ($this->paginator as $entry): 
	?>
	<tr <?php echo $i%2==0?"class='shade'":""; ?>>
		<td> <input type="radio" name="id" value="<?php echo $entry['sm_id']; ?>"></td>
		<td><a href="<?php echo $this->url(array('module'=>'general-setup','controller'=>'highschool', 'action'=>'detail','id'=>$entry['sm_id']),'default',true); ?>"><?php echo $entry['sm_name']; ?></a></td>
		<td><a href="<?php echo $this->url(array('module'=>'general-setup','controller'=>'highschool', 'action'=>'detail','id'=>$entry['sm_id']),'default',true); ?>"><?php echo $entry['sm_name_bahasa']; ?></a></td>
		<td align="center"><?php echo $entry['sm_school_code']; ?></td>
		<td align="center"><?php echo $entry['st_name']; ?>(<?php echo $entry['st_code']; ?>)</td>
		<td align="left">
			<?php echo $entry['sm_address1']; ?>
			<?php echo $entry['sm_address2']!=null?"<br />".$entry['sm_address2']:""; ?>
			<?php echo $entry['sm_city']!=null?"<br />".$entry['CityName']:""; ?>
			<?php echo $entry['sm_state']!=null?"<br />".$entry['StateName']:""; ?>
			<?php echo $entry['sm_country']!=null?"<br />".$entry['CountryName']:""; ?>
		</td>
	</tr>
	<?php 
	$i++;
	endforeach 
	?>

</table>
</div>
<?php 
	echo $this->paginationControl($this->paginator,'Sliding','paginationBottom.phtml');
?>