<script>
function assign(){
	document.f2.action='<?php echo $this->url(array('module'=>'exam','controller'=>'examuser','action'=>'assign'))?>';
	document.f2.submit();
}
function unassign(){
	document.f2.action='<?php echo $this->url(array('module'=>'exam','controller'=>'examuser','action'=>'unassign'))?>';
	document.f2.submit();
}
</script>
<div class="message toolbar">
	<h2><?php echo $this->title; ?></h2>
	<div class="toolbar-button">
		<ul>
			<li>
				<a href="#" onclick="javascript:assign()">
					<span class='add'></span>
					Assign
				</a>
			</li>
			<li>
				<a href="#" onclick="javascript:unassign()">
					<span class='delete'></span>
					UnAssign
				</a>
			</li>
			
		</ul>
	</div>
</div>
<br></br>

<div style="width: 100%;">
<fieldset style="width:450px;">
<form name="f1" method="post" action="">
	<table class="" cellpadding=5 cellspacing=0 width=100%>
	    <tr><td colspan=2>Fill in username in the field provided. Click "Search" button to search.</td></tr>
		<tr><td>Keywords:</td><td><input type="text" name="keywords" size=30 value=""></input></td></tr>
		<tr><td>&nbsp;</td><td><input type="submit" name="submit" value="Search"></input></td></tr>
	</table>
</form>
</fieldset>
</div>	
<br></br>
<form name="f2" method="post" action="">
<?php if($this->list_user ){?>
<h2>User list.</h2>
Click on appropriate radio button. Click assign to assign user to program.
<table class="table" width="50%" cellpadding="5" cellspacing="2">
    <tr>   	
    	<th width="5%">&nbsp;</th>
    	<th>Name</th>
    </tr>
<?php $i=1; foreach ($this->list_user as $user){?>
	<tr <?php echo $i%2==0?"class='shade'":""; ?>>
		<td><input type="radio" name="id" value="<?php echo $user["id"]?>"></input></td>
		<td><?php echo $user["fullname"];?></td>
	</tr>
<?php $i++;} ?>
</table>
<?php } ?>
</form>