 
<script>

function onclickUpload(idtasupervision) {
	$("#dialogIdTASupervision").val(idtasupervision);
	$('#dialog-upload-evidence').dialog('open');
}
function onclickClear(){
	// alert('Kosongkan');
		document.getElementById("chapter_progress").value=''; 
		document.getElementById("stdnote").value= '';
		document.getElementById("supervisornote").value='';
		document.getElementById("progress").value=''; 
		document.getElementById("chapter").value='';
		document.getElementById("IdTASupervision").value='';
	 
}
$(function() {
	$( "#dialog-upload-evidence" ).dialog({
		autoOpen: false,
    	resizable: false,
      	height:140,
      	modal: true,
      	buttons: {
        	"Upload Evidence": function() {
        		//
        		$('#form_evidence').submit();
        	},
        	Cancel: function() {
          		$( this ).dialog( "close" );
        	}
      	}
    });

	$( ".datepicker" ).datepicker({
		maxDate: "0",
		"dateFormat" : 'yy-mm-dd',
		changeMonth: true,
	    changeYear: true 
	});
});

	$(function(){
		
		$('#check_all').change(function(){
			if( $(this).prop('checked') ){
				$('.check').prop('checked',true);
			}else{
				$('.check').prop('checked',false);
			}
		});
		
	});

	function edit_supervision(k,n) {
		 
		var x = document.getElementById("data"+k).rows[n].cells;
		//document.getElementById("chapter_progress").value=x[1].innerHTML; 
		document.getElementById("stdnote").value=x[2].innerHTML;
		document.getElementById("supervisornote").value=x[3].innerHTML;
		//document.getElementById("progress").value=x[4].innerHTML; 
		document.getElementById("chapter").value=document.getElementById("tblchapter["+k+"]["+n+"]").value;
		document.getElementById("supervisor").value=document.getElementById("tblsupervisor"+k).value;
		document.getElementById("IdTASupervision").value=document.getElementById("tblIdTASupervision["+k+"]["+n+"]").value;
		
		
	}
</script>



<div class="message toolbar">
	<h2><?php echo $this->title.' by '.$this->type; ?></h2>
	<div class="toolbar-button">
		<ul>
			<li>
				
			</li>
		</ul>
	</div>
</div>
<?php if(isset($this->noticeMessage)){?>
<div class="message notice"><strong><?php echo $this->noticeMessage;?></strong>.</div>
<br />
<?php }?>
<?php if(isset($this->noticeSuccess)){?>
<div class="message success"><strong><?php echo $this->noticeSuccess;?></strong>.</div>
<br />
<?php }?>
<?php if(isset($this->noticeError)){?>
<div class="message error"><strong><?php echo $this->noticeError;?></strong>.</div>

<br /> 
<?php }?>
<br />
<fieldset><legend ><?php echo $this->translate('Proposal Info');?></legend>
<table>
<tr><td><?php echo $this->translate('Title in Bahasa');?></td><td>:</td><td><?php echo $this->proposal['title_bahasa'];?></td>
<tr><td><?php echo $this->translate('Title');?></td><td>:</td><td><?php echo $this->proposal['title'];?></td>
<tr><td><?php echo $this->translate('Abstract');?></td><td>:</td><td><?php echo $this->proposal['abstrak'];?></td> 
 
</table>

</fieldset>
 
<br />
<fieldset><legend><?php
if ($this->type=='Student') echo $this->translate("Student Note");
else echo $this->translate("Supervisor Note");?></legend>
<form id="form" method="post" action="/finalassignment/supervision/supervision-index">
 <input type="hidden" name="IdTAApplication" id="IdTAApplication" value="<?php echo $this->IdTAApplication;?>">
 <input type="hidden" name="IdStaff" id="IdStaff" value="<?php echo $this->idstaff;?>">
 <input type="hidden" name="type" id="type" value="<?php echo $this->type;?>">
<input type="hidden" name="IdTASupervision" id="IdTASupervision" >
<table   width="100%" cellpadding="5" cellspacing="5" border="0">
	<?php if ($this->type=='Student') {?>
	<tr><td width="20%"><?php echo $this->translate('Supervisor')?></td><td>:</td>
	<td ><select name="supervisor" id="supervisor">
			<option value=""  ><?php echo $this->translate('--Please Select--');?></option>
				<?php 
				foreach ($this->supervision_list as $list):
					$select = "";
					if( isset($this->idsupervisor) && $this->idsupervisor==$list['IdStaff'] ){
						$select = 'selected="selected"';
					}
				?>
					<option value="<?php echo $list['IdStaff'];?>" <?php echo $select; ?>><?php echo $list['Fullname'];?></option>
				<?php 
				endforeach;
				?>
			</select> <?php if ($this->type!='Student') {?>
			<?php echo $this->translate('progress')?>
			<input type="text"  size="10" id="chapter_progress" name="chapter_progress"   > %
		<?php }?>
			</td>
			
		</tr>
	<?php }?>	
	<tr><td width="20%"><?php echo $this->translate('Chapter')?></td><td>:</td>
	<td ><select name="chapter" id="chapter">
			<option value=""  ><?php echo $this->translate('--Please Select--');?></option>
				<?php 
				foreach ($this->chapter_list as $list):
					$select = "";
					if( isset($this->idchapter) && $this->idchapter==$list['chapter'] ){
						$select = 'selected="selected"';
					}
				?>
					<option value="<?php echo $list['key'];?>" <?php echo $select; ?>><?php echo $list['value'];?></option>
				<?php 
				endforeach;
				?>
			</select> <?php if ($this->type!='Student') {?>
			<?php echo $this->translate('progress')?>
			<input type="text"  size="10" id="chapter_progress" name="chapter_progress"   > %
		<?php }?>
			</td>
			
		</tr>	
		<?php  
		if ($this->type=='Student') {?>
		<tr><td width="20%"><?php echo $this->translate("Student Note");?></td><td>:</td>
			<td> <textarea rows="5" cols="70" id="stdnote" name="stdnote"></textarea>
			 </tr>	
		<?php } else {?>
			<tr><td width="20%"><?php echo $this->translate("Student Note");?></td><td>:</td>
			<td> <textarea rows="5" cols="70" id="stdnote" name="stdnote" disabled></textarea>
			 </tr>	
		<?php }?>
		<?php if ($this->type=='Student') {?>
		<tr><td width="20%"><?php echo $this->translate("Supervisor Note");?></td><td>:</td>
			<td> <textarea rows="5" cols="70" id="supervisornote" name="supervisornote" disabled></textarea>
			 </tr>		 
		<?php } else {?>
		<tr><td width="20%"><?php echo $this->translate("Supervisor Note");?></td><td>:</td>
			<td> <textarea rows="5" cols="70" id="supervisornote" name="supervisornote"></textarea>
			 </tr>
		<?php }?>
		<?php if ($this->type!='Student') {?>
	<tr>	<td width="20%"><?php echo $this->translate("Whole Achievment");?></td><td>:</td>
			<td> <input type="text"  size="10" id="progress" name="progress"   >%
			 </tr>
	 <?php }?>
	<tr><td colspan="4" align="center"  > 
	 <input type="submit" name="submit" value="<?php echo $this->translate('Save');?>" <?php echo $disable;?>>
	 <input type="button" name="clear" value="<?php echo $this->translate('Clear');?>"  onclick="onclickClear();" ></td>
	 
</table>

</form>
</fieldset>
<br /><fieldset><legend>
<?php echo $this->translate('Supervision History');?></legend>
<?php if($this->supervision_list){
		foreach ($this->supervision_list as $key=>$staff) {
			 $idstaff=$staff['IdStaff'];
			 $supervision=$staff[$idstaff];
		 ?>
		 	 <input type="hidden" id="tblsupervisor<?php echo $key+1;?>" value="<?php echo $idstaff ?>">
			  <h2><?php echo 'Supervision By: '.$staff['Fullname'].' ('.$staff['StaffAs'].')';?></h2>
			  	<table width="100%" id="data<?php echo $key+1;?>" class="table">
					<tr>
						<th><?php echo $this->translate('Chapter');?></th>
						<th><?php echo $this->translate('Ch. progress %');?></th>
						<th><?php echo $this->translate('Student Note');?></th>
						 <th><?php echo $this->translate('Supervisor Note');?></th>
						<th><?php echo $this->translate('Achievement in %');?></th>
						<th><?php echo $this->translate('Date of Recorded');?></th>
						<th><?php echo $this->translate('Document');?></th>
						<th><?php echo $this->translate('Action');?></th> 
					</tr>
				<?php if (count($supervision)>0) {
			      	foreach($supervision as $index => $batch){
						?> 
						<input type="hidden" id="tblIdTASupervision[<?php echo $key+1;?>][<?php echo $index+1;?>]" value="<?php echo $batch['IdTASupervision'];?>">
						<input type="hidden" id="tblchapter[<?php echo $key+1;?>][<?php echo $index+1;?>]" value="<?php echo $batch['chapter'];?>">
						<tr <?php echo $index%2==0?"class='shade'":""?> >
							<td><?php echo $batch['ChapterName'];?></td>
							<td><?php echo $batch['chapter_progress'];?></td>
							<td><?php echo $batch['Student_Note'];?></td>
							<td><?php echo $batch['Supervisor_Note'];?></td>
							<td><?php echo $batch['Percent_progress'];?></td>
							<td><?php echo $batch['dt_entry'];?></td>
							<td><table border="0"><tr><td>
							<?php $pathupload= $batch['doc_url'];
							if($pathupload!=''){
								$dt = explode("triapp",$pathupload);
								//echo var_dump($dt);exit;
								$path = $dt[1];
								$path ="<a target='_blank' href=http://".APP_HOSTNAME.$path.">" ;
							
							  echo $path;?><img src='<?php echo $this->baseUrl();?>/images/document.png' border=0 width='20' height='20' title="Download" ></a></td>
							  
							  <img src='<?php echo $this->baseUrl();?>/images/upload.png' border=0 width='20' height='20' title="Re-Upload"  onclick="onclickUpload(<?php echo $batch['IdTASupervision'];?>)" /><?php 
							} else { ?></td><tr><td>
								<img src='<?php echo $this->baseUrl();?>/images/upload.png' border=0 width='20' height='20' title="Upload"  onclick="onclickUpload(<?php echo $batch['IdTASupervision'];?>)" />
							 
							<?php } ?></td><?php 
							?></tr></table></td>
							
							<td> <?php if ($batch['Supervisor_Note']=='') { ?>
							<img src='<?php echo $this->baseUrl();?>/images/edit.png' border=0 width='16' height='16' title="Edit"  onclick="edit_supervision(<?php echo $key+1;?>,<?php echo $index+1;?>)" >
							<?php  } 
								if ($batch['dt_update']=='0000-00-00 00:00:00' || $batch['dt_update']=='') {?>
								<a href="<?php echo $this->url(array('module'=>'finalassignment','controller'=>'supervision', 'action'=>'supervision-delete','IdTASupervision'=>$batch['IdTASupervision'],'IdTAApplication'=>$batch['IdTAApplication'],'idstaff'=>$batch['IdStaff'],'type'=>$this->type),'default',true)?>"><img src='<?php echo $this->baseUrl();?>/images/trash.png' border=0 width='16' height='16' title="Delete" ></a>		 
								<?php }?></td>
						</tr>
					<?php 
					}
				} ?></table> 
			  
		<?php 
	}
}?>
 
</fieldset>
<div id="dialog-upload-evidence" title="<?php echo $this->translate("Upload Evidence");?>">
  	<form name="form_evidence" id="form_evidence" method="post" action="/finalassignment/supervision/upload-evidence" enctype="multipart/form-data">
  		<input type="file" name="file" />
  		<input type="hidden" id="dialogIdTASupervision" name="dialogIdTASupervision" >
  		<input type="hidden" id="IdStaff" name="IdStaff" value="<?php echo $this->idstaff;?>">
  		<input type="hidden" id="IdTAApplication" name="IdTAApplication" value="<?php echo $this->IdTAApplication;?>">
  		
  	</form>
</div>