
<script type="text/javascript">
	function del(title, id){
		var id = $('input[name=department_id]:checked').val();

		if(!id){
			alert('Please select any department first');
		}else{
			if(confirm('Are you sure to delete this department ?')){
				window.location = "<?php echo $this->url(array('module'=>'general-setup','controller'=>'department', 'action'=>'delete')); ?>/id/"+id;
			}
		}
	}
	
	function add(){
		window.location="<?php echo $this->url(array('module'=>'general-setup','controller'=>'department', 'action'=>'add'));?>";
	}

	function edit(id){
		var id = $('input[name=department_id]:checked').val();

		if(!id){
			alert('Please select any department first');
		}else{
			window.location="<?php echo $this->url(array('module'=>'general-setup','controller'=>'department', 'action'=>'edit'));?>/id/"+id;
		}
	}

	$(function() {
		// a workaround for a flaw in the demo system (http://dev.jqueryui.com/ticket/4375), ignore!
		$( "#dialog:ui-dialog" ).dialog( "destroy" );
	
		$( "#view-dialog" ).dialog({
			autoOpen:false,
			modal: true,
			width: 400,
			buttons: { "Close": function() { $(this).dialog("close"); }}
		});
	});

	function view(id){
		$("#view-dialog").load("<?php echo $this->url(array('module'=>'general-setup','controller'=>'department', 'action'=>'view'));?>/id/"+id, [], function(){
			$( "#view-dialog" ).dialog('open');
        });
	}
</script>

<div class="message toolbar">
	<h2><?php echo $this->title; ?></h2>
	<div class="toolbar-button">
		<ul>
			<li>
				<a href="#" onclick="javascript:add()">
					<span class='add'></span>
					Add
				</a>
			</li>
			<li>
				<a href="#" onclick="javascript:edit()">
					<span class='edit'></span>
					Edit
				</a>
			</li>
			<li>
				<a href="#" onclick="javascript:del()">
					<span class='delete'></span>
					Delete
				</a>
			</li>
			<li class="divider"></li>
			<li>
				<a href="#" >
					<span class='info'></span>
					Info
				</a>
			</li>
		</ul>
	</div>
</div>
<br />

<?php 
	echo $this->paginationControl($this->paginator,'Sliding','paginationTop.phtml');
?>
<table class="table" width="100%" cellpadding="5" cellspacing="0" border="0">
	<tr>
		<th width="50%">Faculty</th>
		<th width="50%">Department</th>
	</tr>
	
	<?php 
	$i=0;
	foreach ($this->paginator as $entry): 
	?>
	<tr <?php echo $i%2==0?"class='shade'":""; ?>>
		<td>
			<?php echo $entry['faculty_name']; ?> - <?php echo $entry['faculty_code']; ?>
		</td>
		<td>
			<table class="table2" width="100%" cellpadding="0" cellspacing="0">
				<?php
				foreach ($entry['department'] as $department): 
				?>
					<tr> 
						<td width="25px">
							<input type="radio" name="department_id" value="<?php echo $department['id']; ?>">
						</td>
						<td><a href="#" onClick="javascript:view(<?php echo $department['id']; ?>);"><?php echo $department['name']; ?></a></td>
					</tr>
				<?php 
				endforeach 
				?>
			</table>
		</td>
	</tr>
	<?php 
	$i++;
	endforeach 
	?>

</table>

<?php 

	echo $this->paginationControl($this->paginator,'Sliding','paginationBottom.phtml');
?>
<div id="view-dialog" title="Department Details"></div>