<script>
function cetak(){
	window.location="<?php echo $this->url(array('module'=>'reports','controller'=>'student-course-registration','action'=>'course-register-recap-pdf','IdProgram'=>$this->program,'IdSemester'=>$this->semester), 'default', true);?>";
}
</script>
<div class="message toolbar">
	<h2><?php echo $this->title; ?></h2>
	<div class="toolbar-button">
		<ul>
			<li>
				<a href="#" >
					<span class='info'></span>
					<?php echo $this->translate("info")?>
				</a>
			</li>
			<li>
			<a href="#" onclick="cetak();">
				<span class='print'></span>
				Print Daftar
			</a>
			
		</li>
		</ul>
		
	</div>
</div>

<br>
 
<fieldset> <legend><?php echo $this->translate('Time Space Map')?></legend>
<table>
<tr><td>Semester</td><td>:</td><td><?php echo $this->semester; ?></td></tr>
<tr><td>Course Name</td><td>:</td><td><?php echo $this->group['subject_code'].' '.$this->group['subject_name']; ?></td></tr>
<tr><td>Group Name</td><td>:</td><td><?php echo $this->group['GroupName']; ?></td></tr>
<tr><td>Lecturer</td><td>:</td><td><?php echo $this->group['FullName']; ?></td></tr> 
</table>
<br>
<table class='table'>
<tr>
	<th><?php echo $this->translate('Day')?></th>
	<th><?php echo $this->translate('Star')?></th>
	<th><?php echo $this->translate('Stop')?></th>
	<th><?php echo $this->translate('Venue')?></th>
</tr>
<?php foreach ($this->schedule as $jad) {?>
<tr>
	<td><?php echo $jad['sc_day']?></td>
	<td><?php echo $jad['sc_start_time']?></td>
	<td><?php echo $jad['sc_end_time']?></td>
	<td><?php echo $jad['sc_venue']?></td>
</tr>
<?php }?>
</table>
<br>
<table class="table" width="100%" cellpadding="5" cellspacing="2" border="0">
	<tr>
		<th width="5%" ><?php echo $this->translate("No")?></th>
		<th width="15%" ><?php echo $this->translate("Day")?></th>
		<?php $jam=0;$menit=0;
			for ($i=0;$i<=81;$i++) {
				if ($menit==60) {$menit=0; $jam++;}
				$curjam=7+$jam;
				?>
		<th><?php echo $curjam.':'.$menit?></th>
		<?php 
			$menit=$menit+10;}?>
		</tr>
		
	<?php 
	 
	$count=1;
	unset($clas);
	$keyclas=0;
	$last=0;$tcol=0;
	$day=array('7'=>'Minggu','1'=>'Senin','2'=>'Selasa','3'=>'Rabu','4'=>'Kamis','5'=>'Jumat','6'=>'Sabtu');
	if(count($this->timespace)> 0 ){
		 
		for ($i=1;$i<8;$i++) {
			echo "<td>".$i."</td><td>".$day[$i]."</td>";
			if (array_key_exists($i, $this->timespace)) {
				$timespaces=$this->timespace[$i];
				$tcol=0;
				$last=42;
				foreach ($timespaces as $timetable) {
					
					$startcode= (int) date('H',strtotime($timetable['sc_start_time']));
					$startcode= $startcode*6 + (int) date('i',strtotime($timetable['sc_start_time']))/10;
					$endcode =  ((int) date('H',strtotime($timetable['sc_end_time'])))*6+ ((int) date('i',strtotime($timetable['sc_end_time']))/10);
					//echo $startcode.'/';
					//echo $endcode;
					//exit;
					if (($startcode-$last)>0) {
						$tcol=$tcol+$startcode-$last;
						?><td style="background-color:yellow" colspan=<?php echo $startcode-$last;?>></td>
						<?php 
					}
					if 	(($startcode-$last)<0) {
						$clas[$keyclas]=$timetable;
						$keyclas++;
						
					}
					else {
						$colspan=$endcode-$startcode;
						$last=$endcode+1;
						$tcol=$tcol+$colspan;
						?>
						<td colspan=<?php echo $colspan+1?> style="background-color:red"></td>
						<?php 
						}
					}
					if (43+81-$last>0) {
						?><td  style="background-color:yellow" colspan=<?php echo 44+80-$last; ?></td>
						<?php 
						}
						?>
					</tr>
				<?php }
				 
				if (43+81-$last>0) {
					?><td  style="background-color:yellow" colspan=<?php echo 44+80; ?></td>
				<?php 
				}
				?>
									</tr>
				
			<?php }
			 
		 
		 }
		
?>
</table>
</fieldset>