<script type="text/javascript">
$().ready(function() {
	$('#add').click(function() {
		return !$('#select1 option:selected').remove().appendTo('#select2');
	});
	$('#remove').click(function() {
		return !$('#select2 option:selected').remove().appendTo('#select1');
	});

	$('form').submit(function() {
		var course = "";
		
		$('#select2 option').each(function(i) {
			$(this).attr("selected", "selected");
			if(course==""){
				course += this.value;
			}else{
				course += "," + this.value;
			}
		});

		$('#course').attr("value", course);
	});
});
</script>

<?if(isset($this->noticeMessage)){?>
<div class="message notice"><strong><? echo $this->noticeMessage;?></strong>.</div>
<?}?>
<?if(isset($this->noticeSuccess)){?>
<div class="message success"><strong><? echo $this->noticeSuccess;?></strong>.</div>
<?}?>
<?if(isset($this->noticeError)){?>
<div class="message error"><strong><? echo $this->noticeError;?></strong>.</div>
<?}?>

<div class="message toolbar">
	<h2><?php echo $this->title; ?></h2>
	<div class="toolbar-button">
		<ul>
			<li>
				<a href="<?php echo $this->url(array('module'=>'admission-record','controller'=>'registration', 'action'=>'semester', 'stud_id'=>$this->student['id']),'default',true);?>">
					<span class='back'></span>
					Back
				</a>
			</li>
			<li>
				<a href="#" >
					<span class='info'></span>
					Info
				</a>
			</li>
		</ul>
	</div>
</div>

<div align="center" style="background:#ebebeb; height:30px;">
<ul class="steps">
	<li class="prevDone">
		<span>1</span> Student Selection
	</li>
    <li class="prevDone">
		<span>2</span> Semester Selection
	</li>
    <li class="current">
		<span>3</span> Course Selection
	</li>
	<li class="next">
		<span>3</span> Finish
	</li>
</ul>
<br class="clear" />
</div>

<br />
<h2>Student Details</h2>
<table>
	<tr>
		<td width="110px">Name</td>
		<td width="5px">:</td>
		<td><?php echo $this->student['fullname']; ?></td>
	</tr>
	<tr>
		<td>Matric No</td>
		<td>:</td>
		<td><?php echo $this->student['matric_no']; ?></td>
	</tr>
	<tr>
		<td>IC</td>
		<td>:</td>
		<td><?php echo $this->student['ic_no']; ?></td>
	</tr>
	<tr>
		<td>Program</td>
		<td>:</td>
		<td><?php echo $this->program['main_name']; ?></td>
	</tr>
	<tr>
		<td>Semester</td>
		<td>:</td>
		<td><?php echo $this->semester_id; ?></td>
	</tr>
</table>
<br />

<h2>Course Offered For this semester</h2>
<form name="registration_form" action="<?php echo $this->url(array('module'=>'admission-record','controller'=>'registration', 'action'=>'receipt'),'default',true);?>" method="post">
	<input type="hidden" name="student_id" value="<?php echo $this->student['id']?>" />
	<input type="hidden" name="semester_id" value="<?php echo $this->semester_id?>" />
	<input type="hidden" name="course" id="course" value="" />
	
	<table width="900px" border="0">
		<tr>
			<td>
				<h4>Courses List</h4>
				<select id="select1" name="courselist" size="20" style="width:400px;" multiple="multiple" >
					<?php foreach ($this->courseList as $course):?>
						<option value="<?php echo $course['course_id']; ?>"><?php echo $course['course_code']; ?> - <?php echo $course['course_name']; ?></option>
					<?php endforeach;?>
				</select>
			</td>
			<td align="middle" valign="middle">
				<input id="add" type="button" class="buttonLink" value="Add" />
				<input id="remove" type="button" class="buttonLink" value="Remove" />
			</td>
			<td>
				<h4>Course to register</h4>
				<select id="select2" name="select2" size="20" style="width:400px;" multiple="multiple" >
					<?php foreach ($this->courseprerequisites as $course):?>
						<option value="<?php echo $course['id']; ?>"><?php echo $course['code']; ?> - <?php echo $course['name']; ?></option>
					<?php endforeach;?>
				</select>
			</td>
		</tr>
		<tr>
			<td colspan="3" align="left">
				<div width="200px">
					<br />
					<input type="submit" value="Next" />
				</div>
			</td>
		</tr>
	</table>
</form>