<p><strong>Important Note:</strong></p>
<ol>
  <li>Auto-registration as the name suggested should be  a process by which admin can select what programme, what intake to be  automatically registered <br><br></li>
  <li>Student registration should be a process by each  admin will search for student via ic, name etc and then based on the info  provided select subject to be registered. Semester should be automatically  tagged to current &ndash; system shouldn&rsquo;t ask the admin to select sem. Upon  selection of the submission, admin should be asked to &ldquo;register&rdquo; instead of  next and system completes the registration. Too abrupt current flow<br><br></li>
  <li>Add Drop screen isn&rsquo;t too clear &ndash; must clearly  show what is Add and what is Drop. Student can only drop subject within the  Add/Drop period. After this period, any drop will be considered as &ldquo; subject  withdrawal&rdquo; will have impact on finance<br><br></li>
</ol>
