<script>
<!--
function printContent(id,studname){
str=document.getElementById(id).innerHTML
newwin=window.open('','printwin','left=100,top=50,width=600,height=600')
newwin.document.write('<html><head><style>#body,table,p{font-family:Trebuchet Ms,Verdana,Arial,Helvetica,sans-serif;font-size:11px;}h2{font-family: Arial,Helvetica,Georgia, Serif;font-size: 12px;font-weight: bold;display: block;}.table{font-family: Georgia, Serif;font-size: 11px;background-color: #E5E5E5;}.table th{background-color: #767676;color:white;line-height: 16px;}.table td{border:1px solid #FFFFFF;line-height: 16px;}.table .shade{background-color: #F8F7F3;}</style>');
newwin.document.write('<TITLE>Student Registration</TITLE>\n')

newwin.document.write('<script>\n')
newwin.document.write('function chkstate(){\n')
newwin.document.write('if(document.readyState=="complete"){\n')
newwin.document.write('window.close()\n')
newwin.document.write('}\n')
newwin.document.write('else{\n')
newwin.document.write('setTimeout("chkstate()",2000)\n')
newwin.document.write('}\n')
newwin.document.write('}\n')
newwin.document.write('function print_win(){\n')
newwin.document.write('window.print();\n')
newwin.document.write('chkstate();\n')
newwin.document.write('}\n')
newwin.document.write('<\/script>\n')

newwin.document.write('</HEAD>\n')
newwin.document.write('<BODY onload="print_win()">\n')
newwin.document.write('<p align=center><img src=/images/ustlogo.gif><img src=/images/ustyname.gif><br><br>')
newwin.document.write('<b>REGISTRATION SLIP</b></p><br>')
newwin.document.write(str)
newwin.document.write('<p>Student</p><br><br>...........................................<br>')
newwin.document.write('<p>')
newwin.document.write(studname)
newwin.document.write('</p>')
newwin.document.write('<br><br><p>Approved by</p><br><br><br>...........................................<br><p>Program Head</p>')
newwin.document.write('</BODY>\n')
newwin.document.write('</HTML>\n')
newwin.document.close()
}
//-->
</script>


<?if(isset($this->noticeMessage)){?>
<div class="message notice"><strong><? echo $this->noticeMessage;?></strong>.</div>
<?}?>
<?if(isset($this->noticeSuccess)){?>
<div class="message success"><strong><? echo $this->noticeSuccess;?></strong>.</div>
<?}?>
<?if(isset($this->noticeError)){?>
<div class="message error"><strong><? echo $this->noticeError;?></strong>.</div>
<?}?>
<br>
<div class="message toolbar">
	<h2><?php echo $this->title; ?></h2>
	<div class="toolbar-button">
		<ul>
			<li>
				<a href="#null" onclick="printContent('print_div2','<?php echo $this->student['fullname']; ?>')">
					<span class='print'></span>
					Print
				</a>
			</li>
			<li>
				<a href="#" >
					<span class='info'></span>
					Info
				</a>
			</li>
		</ul>
	</div>
</div>

<div align="center" style="background:#ebebeb; height:30px;">
<ul class="steps">
	<li class="prevDone">
		<span>1</span> Student Selection
	</li>
    <li class="prevDone">
		<span>2</span> Course Registration
	</li>
	<li class="current">
		<span>3</span> Completed
	</li>
</ul>
<br class="clear" />
</div>

<br />
<div id="print_div2" >

<h2>Student Details</h2>
<table>
	<tr>
		<td width="110px">Name</td>
		<td width="5px">:</td>
		<td><?php echo $this->student['fullname']; ?></td>
	</tr>
	<tr>
		<td>Matric No</td>
		<td>:</td>
		<td><?php echo $this->student['matric_no']; ?></td>
	</tr>
	<tr>
		<td>Program</td>
		<td>:</td>
		<td><?php echo $this->program['main_name']; ?></td>
	</tr>
	<tr>
		<td>Semester</td>
		<td>:</td>
		<td><?php echo $this->semester['name']; ?></td>
	</tr>
</table>
<br />

<h2>Course Registered</h2>
<table class="table" width="100%" cellpadding="5" cellspacing="2">
	<tr>
		<th></th>
		<th>Course Name</th>
		<th>Course Code</th>
		<th>Credit Hour</th>
		<th>Status</th>
	</tr>
	<?php 
	$i=0;
	$bil = 1;
	foreach ($this->courses as $course):
	?>
	<tr <?php echo $i%2==0?"class='shade'":""; ?>>
		<td align="left"><?php echo $bil; ?></td>
		<td align="left"><?php echo $course['course_name']; ?></td>
		<td align="center"><?php echo $course['course_code']; ?></td>
		<td align="center"><?php echo $course['course_credit_hour']; ?></td>
		<td align="center"><?php echo $course['status']; ?></td>
	</tr>
	<?php 
	$bil++;
	$i++;
	endforeach 
	?>
</table>

</div>
