<?if(isset($this->noticeSuccess)){?>
<div class="message success"><strong><? echo $this->noticeSuccess;?></strong>.</div>
<?}?>
<?if(isset($this->noticeError)){?>
<div class="message error"><strong><? echo $this->noticeError;?></strong>.</div>
<?}?>

<br>
<div class="message toolbar">
	<h2><?php echo $this->title; ?></h2>
	<div class="toolbar-button">
		<ul>
			<li>
				<a href="<?php echo $this->url(array('module'=>'admission-record','controller'=>'registration', 'action'=>'index'),'default',true);?>">
					<span class='back'></span>
					Back
				</a>
			</li>
			<li>
				<a href="#" >
					<span class='info'></span>
					Info
				</a>
			</li>
		</ul>
	</div>
</div>

<div align="center" style="background:#ebebeb; height:30px;">
<ul class="steps">
	<li class="prevDone">
		<span>1</span> Student Selection
	</li>
    <li class="current">
		<span>2</span> Course Registration
	</li>
	<li class="next">
		<span>3</span> Completed
	</li>
</ul>
<br class="clear" />
</div>

<br />
<h2>Student Details</h2>
<table>
	<tr>
		<td width="110px">Name</td>
		<td width="5px">:</td>
		<td><?php echo $this->student['fullname']; ?></td>
	</tr>
	<tr>
		<td>Matric No</td>
		<td>:</td>
		<td><?php echo $this->student['matric_no']; ?></td>
	</tr>
	<tr>
			<td width="110px">
				Program
			</td>
			<td width="5px">:</td>
			<td>
				<?php echo $this->program['main_name']?>
			</td>
		</tr>
	<tr>
			<td width="110px">
				Maximum Credit Hour
			</td>
			<td width="5px">:</td>
			<td>
				<?php echo $this->max_sem_credit?>
			</td>
		</tr>
</table>
<br />


	<h2>Semester Selection</h2>


<form name="semester_form" action="<?php echo $this->url(array('module'=>'admission-record','controller'=>'registration', 'action'=>'semester', 'stud_id'=>$this->student['id']),'default',true);?>" method="post">

	<input type="hidden" name="student_id" value="<?php echo $this->student['id']?>" />
	<input type="hidden" name="program_id" value="<?php echo $this->program['id']?>" />
	

	<table width="100%">
		
		
		<tr>
			<td colspan="3">
			Please select semester :-
			</td>
		</tr>
				
		<tr>
			<td width="110px">Semester</td>
			<td width="5px">:</td>
			<td>					
				<select name="semester_id" style="width:250px" onchange="this.form.submit()">
					<option value="0"> -- Select Semester --</option>
					<?php
						foreach ($this->semesterlist as $semester) {
							if($this->semester_id == $semester['id']){
								$selected="selected";
							}else{
								$selected="";
							}
							echo "<option value='".$semester['id']."'" .$selected." >".$semester['name']."</option>";
						}
					?>
				</select>
				
				<? if($this->currentsemester["id"] == $this->semester_id ) echo "Current Semester";?>
			</td>
		</tr>
	</table>

<br />
</form>	





<? if(isset($this->courses)) {?>
<h2>Course Registered</h2>

<?if(isset($this->noticeMessage)){?>
<div class="message notice"><strong><? echo $this->noticeMessage;?></strong>.</div>
<?}?>

<br>

<table class="table" width="100%" cellpadding="5" cellspacing="2">
	<tr>
		<th>Course Name</th>
		<th>Course Code</th>
		<th>Credit Hour</th>
		<th>Course Type</th>
	</tr>
	<?php 
	$i=0;
	$total = 0;
	foreach ($this->courses as $course):
		if($course['course_status_id']==1){
	?>
	<tr <?php echo $i%2==0?"class='shade'":""; ?>>
		<td align="left"><?php echo $course['course_name']; ?></td>
		<td align="center"><?php echo $course['course_code']; ?></td>
		<td align="center"><?php echo $course['course_credit_hour']; ?></td>
		<td align="center"><?php echo $course['course_type']; ?></td>
	</tr>
	<?php
	
		$credit_hour = $course['course_credit_hour'];
	
		}
		$total = $total+$credit_hour;
	$i++;
	endforeach 
	?>
	
	<tr>
		<td colspan="2" align="right"  bgcolor="#f2f2f2">Total Credit Hour</td>
		<td  bgcolor="#f2f2f2" align="center"><?php echo $total;?></td>
	</tr>
</table>
<? } else { ?>


<h2>Course Offered</h2>
<form name="registration_form" action="<?php echo $this->url(array('module'=>'admission-record','controller'=>'registration', 'action'=>'register'),'default',true);?>" method="post">

	<input type="hidden" name="student_id" value="<?php echo $this->student['id']?>" />
	<input type="hidden" name="semester_id" value="<?php echo $this->semester_id?>" />
	<input type="hidden" name="course" id="course" value="" />
	
	
<?php if ($this->courseList) { ?>
Please tick the appropriate box and click on "Register Course" button to register.
<br><br>
	
	
	<?
		//TO SEPERATE COURSE TYPE
		//1) CHECK FROM PROGRAM REQUIREMENT COURSE_TYPE
		foreach ($this->program_requirement as $proReq){
			echo "<div><strong>Course Type: ".$proReq['course_type_name']."</strong></div>";
	?>
	
							
						
							<table class="table" width="100%" cellpadding="5" cellspacing="2">
							
							<tr>								
								<th>Course Name</th>
								<th>Course Code</th>
								<th>Credit Hour</th>
								<th>Course Type</th>
								<th>Action</th>
							</tr>
							<?php 
							$i=0;
							$bil=1;
							foreach ($this->courseList as $course):
									if($course['course_type_id']==$proReq["course_type_id"]){
							?>
							
							
							<tr <?php echo $i%2==0?"class='shade'":""; ?>>
								
								<td align="left"><?php echo $course['course_name']; ?></td>
								<td align="center"><?php echo $course['course_code']; ?></td>
								<td align="center"><?php echo $course['course_credit_hour']; ?></td>
								<td align="center"><?php echo $course['course_type_id']; ?></td>
								<td align="center"> <input type="checkbox" name="course_select[]" id="course_select[]" value="<?php echo $course['course_id']?>" /></td>
							</tr>
							
							<?php 
									}//end if course type
							$bil++;
							$i++;
							endforeach 
							?>
													
								
						</table>
						<br>
						
						
		<? }//END PROGRAM REQUIREMENT ?>


<div width="200px">
<br />
<input type="submit" value="Register Course">
</div>
			
<? }else {
	echo "There are no course(s) offer for selected semester.";
}
?>
</form>

</div>


<? } ?>
