
<?if(isset($this->noticeMessage)){?>
<div class="message notice"><strong><? echo $this->noticeMessage;?></strong>.</div>
<?}?>
<?if(isset($this->noticeSuccess)){?>
<div class="message success"><strong><? echo $this->noticeSuccess;?></strong>.</div>
<?}?>
<?if(isset($this->noticeError)){?>
<div class="message error"><strong><? echo $this->noticeError;?></strong>.</div>
<?}?>

<div class="message toolbar">
	<h2><?php echo $this->title; ?></h2>
	<div class="toolbar-button">
		<ul>
			<li>
				<a href="<?php echo $this->url(array('module'=>'admission-record','controller'=>'registration', 'action'=>'index'),'default',true);?>">
					<span class='back'></span>
					Back
				</a>
			</li>
			<li>
				<a href="#" >
					<span class='info'></span>
					Info
				</a>
			</li>
		</ul>
	</div>
</div>

<div align="center" style="background:#ebebeb; height:30px;">
<ul class="steps">
	<li class="prevDone">
		<span>1</span> Student Selection
	</li>
    <li class="current">
		<span>2</span> Student Registration
	</li>
	<li class="next">
		<span>3</span> Finish
	</li>
</ul>
<br class="clear" />
</div>

<br />
<h2>Student Details</h2>
<table>
	<tr>
		<td width="110px">Name</td>
		<td width="5px">:</td>
		<td><?php echo $this->student['fullname']; ?></td>
	</tr>
	<tr>
		<td>Matric No</td>
		<td>:</td>
		<td><?php echo $this->student['matric_no']; ?></td>
	</tr>
	
</table>
<br />

<h2>Semester Detail</h2>


<!--<form name="course_form" action="<?php echo $this->url(array('module'=>'admission-record','controller'=>'registration', 'action'=>'course'),'default',true);?>" method="post">-->
<form name="searchfrm" action="" method="post">
	<input type="hidden" name="student_id" value="<?php echo $this->student['id']?>" />
	<input type="hidden" name="program_id" value="<?php echo $this->program['id']?>" />
	<table width="100%">
		<tr>
			<td width="110px">
				Program
			</td>
			<td width="5px">:</td>
			<td>
				<?php echo $this->program['main_name']?>
			</td>
		</tr>
		<tr>
			<td>
				Current Semester
			</td>
			<td width="5px">:</td>
			<td>
			<?php 
			foreach($this->currentsemester as $s){
				echo $s["name"];
			}
			?>
			<input type="hidden" name="semester_id" id="semester_id" value="<?php echo $s["id"]?>"></td>
		</tr>
		<tr>
			<td>
				Semester
			</td>
			<td width="5px">:</td>
			<td>
			
		
							
				<select name="semester_id" style="width:250px" onChange="form.submit()">
					<option value="0"> -- Select Semester --</option>
					<?php
						foreach ($this->semesterlist as $semester) {
							if($this->sem == $semester['id']){
								$selected="selected";
							}else{
								$selected="";
							}
							echo "<option value='".$semester['id']."'" .$selected." >".$semester['name']."</option>";
						}
					?>
				</select>
			</td>
		</tr>
		
	</table>
	<br />


</form>	



<h2>Course Offered</h2>
<form name="registration_form" action="<?php echo $this->url(array('module'=>'admission-record','controller'=>'registration', 'action'=>'receipt'),'default',true);?>" method="post">

	<input type="hidden" name="student_id" value="<?php echo $this->student['id']?>" />
	<input type="hidden" name="semester_id" value="<?php echo $this->semester_id?>" />
	<input type="hidden" name="course" id="course" value="" />
	
	<?php
	if ($this->courseList) {
		
	?>

	<table class="table" width="100%" cellpadding="5" cellspacing="2">
	<tr>
		<th></th>
		<th>Course Name</th>
		<th>Course Code</th>
		<th>Credit Hour</th>
		<th>Status</th>
	</tr>
	<?php 
	$i=0;
	$bil=1;
	foreach ($this->courseList as $course):
	?>
	<tr <?php echo $i%2==0?"class='shade'":""; ?>>
		<td align="left"><?php echo $bil; ?></td>
		<td align="left"><?php echo $course['course_name']; ?></td>
		<td align="center"><?php echo $course['course_code']; ?></td>
		<td align="center"><?php echo $course['course_credit_hour']; ?></td>
		<td align="center"> <input type="checkbox" name="course_select[]" id="course_select[]" value="<?php echo $course['course_id']?>" /></td>
	</tr>
	<?php 
	$bil++;
	$i++;
	endforeach 
	?>
	
	
		
</table>

<div width="200px">
					<br />
					<input type="submit" value="Register">
				</div>


</form>

<? }else {
	echo "N/A";
}


?>


</div>
<br />
