<?if(isset($this->noticeMessage)){?>
<div class="message notice"><strong><? echo $this->noticeMessage;?></strong>.</div>
<?}?>
<?if(isset($this->noticeSuccess)){?>
<div class="message success"><strong><? echo $this->noticeSuccess;?></strong>.</div>
<?}?>
<?if(isset($this->noticeError)){?>
<div class="message error"><strong><? echo $this->noticeError;?></strong>.</div>
<?}?>

<div class="message toolbar">
	<h2><?php echo $this->title; ?></h2>
	<div class="toolbar-button">
		<ul>
			<li>
				<a href="<?php echo $this->url(array('module'=>'admission-record','controller'=>'registration', 'action'=>'index'),'default',true);?>">
					<span class='back'></span>
					Back
				</a>
			</li>
			<li>
				<a href="#" >
					<span class='info'></span>
					Info
				</a>
			</li>
		</ul>
	</div>
</div>
<br />
<h2>Student Detail</h2>
<table>
	<tr>
		<th>Name</th>
		<td>:</td>
		<td></td>
	</tr>
</table>
<br />
<h2>Semester Detail</h2>
<div style="width: 600px;">
<fieldset style="width:450px; margin:0 0">
	<legend>Semester Options</legend>
<form name="course_form" action="" method="post">
	<table width="100%">
		<tr>
			<td width="110px">
				Program
			</td>
			<td width="5px">:</td>
			<td>
				<?php echo $this->program['main_name']?>
			</td>
		</tr>
		<tr>
			<td width="80px">
				Academic Landscape
			</td>
			<td width="5px">:</td>
			<td>
				<a href="#">Click here to view</a>
			</td>
		</tr>
		<tr>
			<td>
				Semester
			</td>
			<td width="5px">:</td>
			<td>
				<select name="semester_id" style="width:250px">
					<option value="0"> -- Select Semester --</option>
					<?php
						foreach ($this->semesterlist as $semester) {
							if($semester['id'] == $this->semester_id){
								$selected="selected='selected'";
							}else{
								$selected="";
							}
							echo "<option value='".$semester['id']."'" .$selected." >".$semester['name']."</option>";
						}
					?>
				</select>
			</td>
		</tr>
		<tr>
			<td colspan="2">&nbsp;</td>
			<td><input type="submit" value="Get Course Offered" /></td>
		</tr>
	</table>
</form>
</fieldset>
</div>
<br />
<h2>Course Offered</h2>
<br />
<br />
<div>
	<input type="submit" value="Register This Student" onClick="$('#registration-dialog').dialog('open')" />
	<input type="button" value="Back" onclick="javascript:window.location='<?php echo $this->url(array('module'=>'admission-record','controller'=>'registration', 'action'=>'index'),'default',true);?>'" />
</div>