

<div class="message toolbar">
	<h2><?php echo $this->title; ?></h2>
	<div class="toolbar-button">
		<ul>
			<li>
				<a href="/servqual/survey/new-target/id/<?php echo $this->idsurvey?>/add/1" >
					<span class='add'></span>
					<?php echo $this->translate("Add Target"); ?>
				</a>
			</li>
		</ul>
	</div>
</div>
<br />

<?php if(isset($this->noticeMessage)){?>
<div class="message notice"><strong><?php echo $this->noticeMessage;?></strong>.</div>
<br />
<?php }?>
<?php if(isset($this->noticeSuccess)){?>
<div class="message success"><strong><?php echo $this->noticeSuccess;?></strong>.</div>
<br />
<?php }?>
<?php if(isset($this->noticeError)){?>
<div class="message error"><strong><?php echo $this->noticeError;?></strong>.</div>
<br />
<?php }?>

<h2><?php echo $this->translate('Target');?></h2>
<table width="100%" class="table">
	<tr>
		<th><?php echo $this->translate('Semester');?></th>
		<th><?php echo $this->translate('Program');?></th>
		
		<th><?php echo $this->translate('Action');?></th>
		<th><?php echo $this->translate('Detail');?></th>
		</tr>
	<?php 
	if($this->target_list){
      foreach($this->target_list as $index => $batch){
	?>
	<tr <?php echo $index%2==0?"class='shade'":""?> >
		<td><?php echo $batch['SemesterMainName'];?></td>
		<td><?php echo $batch['ProgramName']; ?></a></td>
		
		<td align="center">
		  <a href="/servqual/survey/new-target/id/<?php echo $this->idsurvey;?>">Edit</a>
		 </td>
		 <td align="center">
		  <a href="/servqual/survey/view-target/id/<?php echo  $this->idsurvey;?>/prg/<?php echo $batch['IdProgram'];?>/smt/<?php  echo $batch['IdSemester'];?>">View</a>
		 </td>
	</tr>
	<?php 
	  }
	}
	?>
</table>