 
<script>
	$(function(){
		
		$('#check_all').change(function(){
			if( $(this).prop('checked') ){
				$('.check').prop('checked',true);
			}else{
				$('.check').prop('checked',false);
			}
		});
		
	});


	function cetak(){
		window.location="<?php echo $this->url(array('module'=>'finalassignment','controller'=>'proposal','action'=>'student-application-view','proposedby'=>$this->proposal['IdStudentRegistration'],'idtaapplication'=>$this->proposal['IdTAApplication']), 'default', true);?>";
	}
	function cetakpdf(){
		window.location="<?php echo $this->url(array('module'=>'finalassignment','controller'=>'proposal','action'=>'student-application-pdf','proposedby'=>$this->proposal['IdStudentRegistration'],'idtaapplication'=>$this->proposal['IdTAApplication']), 'default', true);?>";
	}
</script>
 

<div class="message toolbar">
	<h2><?php echo $this->title; ?></h2>
	<div class="toolbar-button">
		<ul>
			 <li>
			<a href="#" onclick="cetak();">
				<span class='print'></span>
				Print Screen
			</a>
			
		</li>
		 <li>
			<a href="#" onclick="cetakpdf();">
				<span class='print'></span>
				Print Pdf
			</a>
			
		</li>
		</ul>
	</div>
</div>
<?php if(isset($this->noticeMessage)){?>
<div class="message notice"><strong><?php echo $this->noticeMessage;?></strong>.</div>
<br />
<?php }?>
<?php if(isset($this->noticeSuccess)){?>
<div class="message success"><strong><?php echo $this->noticeSuccess;?></strong>.</div>
<br />
<?php }?>
<?php if(isset($this->noticeError)){?>
<div class="message error"><strong><?php echo $this->noticeError;?></strong>.</div>

<br /> 
<?php }?>
<br />
<fieldset><legend ><?php echo $this->translate('Student Info');?></legend>
<table>
<tr><td><?php echo $this->translate('NIM');?></td><td>:</td><td><?php echo $this->student['registrationId'];?></td>
<tr><td><?php echo $this->translate('Name');?></td><td>:</td><td><?php echo $this->student['appl_fname'].' '.$this->student['appl_mname'].' '.$this->student['appl_lname'];?></td>
<tr><td><?php echo $this->translate('Majoring');?></td><td>:</td><td><?php echo $this->student['majoring'];?></td>
<tr><td><?php echo $this->translate('Credit Hours Transcript/All');?></td><td>:</td><td><?php echo $this->student['credithours'].'/'.$this->student['credithoursall'];?></td>
<tr><td><?php echo $this->translate('CGPA Transcript/All');?></td><td>:</td><td><?php echo $this->student['cgpa'].'/'.$this->student['cgpaall'];?></td>
 
</table>

</fieldset>
<br />
 
<fieldset><legend><?php echo $this->translate('Previous Proposal')?></legend>
	<table class="table_content" width="100%" cellpadding="5" cellspacing="0" border="0">
	<tr>	<td width="25%"><?php echo $this->translate("Title in Bahasa");?></td><td>:</td>
			<td><?php echo $this->proposal['title_bahasa']; ?></td>  </tr> 
	<tr>	<td width="20%"><?php echo $this->translate("Title in English");?></td><td>:</td>
			<td> <?php echo $this->proposal['title']; ?></td></tr>
	<tr>	<td width="20%"><?php echo $this->translate("First Problem Statement");?></td><td>:</td>
			<td> <?php echo $this->proposal['problem1']; ?></td></tr>
	<tr>	<td width="20%"><?php echo $this->translate("Second Problem Statement");?></td><td>:</td>
			<td> <?php echo $this->proposal['problem2']; ?></td></tr>
	<tr>	<td width="20%"><?php echo $this->translate("Third Problem Statement");?></td><td>:</td>
			<td> <?php echo $this->proposal['problem3']; ?></td></tr>
	<tr>	<td width="20%"><?php echo $this->translate("Abstract");?></td><td>:</td>
			<td> <?php echo $this->proposal['abstrak']; ?></td></tr>
	 
</table>
<br> 
</fieldset>
<br />
<fieldset><legend><?php echo $this->translate('Propose New Topic');?></legend>
<form name="form_new" method="post" action="/finalassignment/change/index">
<input type="hidden" id="IdFlowMain" name="IdFlowMain" value="<?php  echo $this->idflowmain;?>">
<input type="hidden" name="IdStudentRegistration" id="IdStudentRegistration" value="<?php echo $this->student['IdStudentRegistration'];?>">
<input type="hidden" name="IdProgram" id="IdProgram" value="<?php echo $this->student['IdProgram'];?>">
<input type="hidden" name="IdMajor" id="IdMajor" value="<?php echo $this->student['IdProgramMajoring'];?>">
<input type="hidden" name="IdBranch" id="IdBranch" value="<?php echo $this->student['IdBranch'];?>">
<input type="hidden" name="IdTAApplication" id="IdTAApplication" value="<?php echo $this->idtaapplication;?>">
<input type="hidden" name="IdTAChange" id="IdTAChange" value="<?php echo $this->idtachange;?>">

<table class="table" width="100%" cellpadding="5" cellspacing="0" border="0">
	<tr>
			<td>
				<?php echo $this->translate("Cause of Change Topics")?>
			</td>
			<td width="5px">:</td>
			<td>				
				<select name="ChangeCode" id="ChangeCode">
					<?php foreach ($this->change_list as $items) {
						$select = "";
						if ($this->change['ChangeCode']==$items['key'] ){
							$select = 'selected="selected"';
						}?>
					<option value="<?php echo $items['key'];?>" <?php echo $select; ?>> <?php echo $this->translate($items['value']);?> </option>
					 <?php }?>
				</select>
			</td>
		</tr>
	<tr><td width="25%"><?php echo $this->translate("Title in Bahasa");?></td><td width="5px">:</td>
		<td><textarea rows="5" cols="70" id="title_bahasa" name="title_bahasa"><?php echo $this->proposal_new['title_bahasa']; ?></textarea></td>  </tr> 
	<tr><td><?php echo $this->translate("Title in English");?></td><td width="5px">:</td>
			<td><textarea rows="5" cols="70" id="title" name="title"> <?php echo $this->proposal_new['title']; ?></textarea></td></tr>
	<tr><td width="20%"><?php echo $this->translate("Problem Statement");?></td><td width="5px">:</td>
		<td> <textarea rows="10" cols="70" id="problem" name="problem"><?php echo $this->proposal_new['problem']; ?></textarea></td></tr>
	<tr><td colspan="3" align="center"><input type="submit" id="submit" name="submit></td></tr>
	</table>
</form>
</fieldset>

<br>
<fieldset><legend><?php echo $this->translate('Status of Process');?></legend>
<table class="table" width="100%" cellpadding="5" cellspacing="0" border="0">
<tr>
	<th><?php echo $this->translate('Name of Process');?></th>
	<th><?php echo $this->translate('Authority of');?></th>
	<th><?php echo $this->translate('PIC');?></th>
	<th><?php echo $this->translate('Status of Process');?></th>
	<th><?php echo $this->translate('Date of entry');?></th>
	<th><?php echo $this->translate('Latest Date of Approval');?></th>
	<th><?php echo $this->translate('Date of Approval');?></th>
	<th><?php echo $this->translate('Documents');?></th>
</tr>
<?php  if ($this->process_status) {
	foreach ($this->process_status as $status) {
		if ($status['ApprovalStatus']==0) 
			$statusApp="Waiting for Approval";
		else if ($status['ApprovalStatus']==1) 
			$statusApp="Approved";
		else if ($status['ApprovalStatus']==2) 
			$statusApp="Pending";
		else  if ($status['ApprovalStatus']==3) 
			$statusApp="Rejected";
		?>
	<tr>
	<td><?php echo $status['ProcessName'];?></td>
	<td><?php echo $status['StaffAs'];?></td>
	<td><?php echo $status['FullName'];?></td>
	<td><?php echo $this->translate($statusApp);?></td>
	<td><?php echo $status['dt_entry'];?></td>
	<td><?php echo $status['dt_latest'];?></td>
	<td><?php echo $status['dt_Approved'];?></td>
	<?php if (isset($status['doc_url']) && $status['doc_url']!='') {?>
		<td><?php echo 'download document';?></td>
	<?php } else  {?>
		<td><?php echo $this->translate('no document');?></td>
	<?php }?>
</tr>
<?php }
} else echo '<tr><td> No Status of Process </td></tr>'?>
</table>
</fieldset>
 