<script type="text/javascript">
	function del(){
		var id = $('input[name=activity_id]:checked').val();

		if(!id){
			alert('Please select any activity first');
		}else{
			if(confirm('Are you sure to delete this activity?')){
				window.location = "<?php echo $this->url(array('module'=>'anr-setup','controller'=>'activity', 'action'=>'delete'),'default',true); ?>/id/"+id;
			}
		}
	}
	
	function add(){
		window.location="<?php echo $this->url(array('module'=>'anr-setup','controller'=>'activity', 'action'=>'add'),'default',true);?>";
	}

	function edit(){
		var id = $('input[name=activity_id]:checked').val();

		if(!id){
			alert('Please select any activity first');
		}else{
			window.location="<?php echo $this->url(array('module'=>'anr-setup','controller'=>'activity', 'action'=>'edit'),'default',true);?>/id/"+id;
		}
	}

</script>

<div class="message toolbar">
	<h2><?php echo $this->title; ?></h2>
	<div class="toolbar-button">
		<ul>
			<li>
				<a href="#" onclick="javascript:add()">
					<span class='add'></span>
					Add
				</a>
			</li>
			<li>
				<a href="#" onclick="javascript:edit()">
					<span class='edit'></span>
					Edit
				</a>
			</li>
			<li>
				<a href="#" onclick="javascript:del()">
					<span class='delete'></span>
					Delete
				</a>
			</li>
			<li class="divider"></li>
			<li>
				<a href="#" >
					<span class='info'></span>
					Info
				</a>
			</li>
		</ul>
	</div>
</div>
<br />

<div style="width:50%;">
<?php 
	echo $this->paginationControl($this->paginator,'Sliding','paginationTop.phtml');
?>
<table class="table" width="100%" cellpadding="5" cellspacing="0" border="0">
	<tr>
		<th width="25px">&nbsp;</th>
		<th>Activity Name</th>
	</tr>
	
	<?php 
	$i=0;
	foreach ($this->paginator as $entry): 
	?>
	<tr <?php echo $i%2==0?"class='shade'":""; ?>>
		<td>
			<input type="radio" name="activity_id" value="<?php echo $entry['id']; ?>">
		</td>
		<td><?php echo $entry['name']; ?></td>
	</tr>
	<?php 
	$i++;
	endforeach 
	?>

</table>
<?php 
	echo $this->paginationControl($this->paginator,'Sliding','paginationBottom.phtml');
?>
</div>