<script type="text/javascript">
	$(function() {
		// a workaround for a flaw in the demo system (http://dev.jqueryui.com/ticket/4375), ignore!
		$( "#dialog:ui-dialog" ).dialog( "destroy" );
	
		$( "#dialog-info" ).dialog({
			modal: true,
			autoOpen: false,
			width: 600,
			buttons: {
				"Save": function() { 
					dialog_nomor = $("#dialog_nomor").val(); 
					dialog_decree_date = $("#dialog_decree_date").val(); 

					//alert(dialog_nomor+'--'+dialog_decree_date);
					$("#nomor").val(dialog_nomor);
					$("#decree_date").val(dialog_decree_date); 
					
					//$(this).dialog("close"); 
					$("#myform").submit(); 
				}, 
				"Cancel": function() { 
					$(this).dialog("close"); 
				}
				
			}
		});


		$("#dialog_decree_date").datepicker({
			"dateFormat":"yy-mm-dd",
			"changeMonth":"true"		
			
		});
		
		
	});


	function save(){
		$( "#dialog-info" ).dialog('open');
		
		//document.myform.submit();
	}

	
	function printPreview(){
		
		url = "<?php echo $this->url(array('module'=>'application','controller'=>'selection-highschool','action'=>'print-batch-dean-rating','faculty_id'=>$this->faculty_id,'program_code'=>$this->program_code,'academic_year'=>$this->ayear,'period'=>$this->period),'default',true);?>";
		window.open (url, "mywindow","location=1,status=1,scrollbars=1, width=500,height=500");
	}

	function printNilaiRaport(){
		
		url = "<?php echo $this->url(array('module'=>'application','controller'=>'selection-highschool','action'=>'print-nilai-raport','faculty_id'=>$this->faculty_id,'program_code'=>$this->program_code,'academic_year'=>$this->ayear,'period'=>$this->period),'default',true);?>";
		window.open (url, "mywindow","location=1,status=1,scrollbars=1, width=500,height=500");
	}

	function getProgramme(element,targetElement){
		var faculty_id = $(element).val();
		
		$.ajax({
			url: "<?php echo $this->url(array('module'=>'application','controller'=>'selection-highschool', 'action'=>'ajax-get-program'),'default',true);?>",
			data: {'faculty_id':$(element).val()},
			type: 'POST',
			dataType: 'json'	
		}).done(function ( data ) {

			
			$(targetElement).empty().append('<option value=""> <?php echo $this->translate("All"); ?> </option>');
		
			$.each(data, function(index) {
				$(targetElement).append('<option value="'+data[index].ProgramCode+'"> '+data[index].ProgramName+' </option>');
			});
		});
	}
	
		
	
</script>

<div class="message toolbar">
	<h2><?php echo $this->title; ?></h2>
	<div class="toolbar-button">
		<ul>		
		
		   <?php if(isset($this->paginator)){?>
			<li>
				<a onclick="printPreview();" href="javascript:void(0);" >
					<span class='print'></span>
					<?php echo $this->translate("cetak surat dekan")?>
				</a>
			</li>
			<!--<li>
				<a onclick="printNilaiRaport();" href="javascript:void(0);" >
					<span class='print'></span>
					<?php echo $this->translate("cetak nilai raport")?>
				</a>
			</li>
			-->
			
			<li>
				<a href="<?php echo $this->url(array('module'=>'application','controller'=>'selection-highschool','action'=>'download-batch-dean-rating','faculty_id'=>$this->faculty_id,'program_code'=>$this->program_code,'academic_year'=>$this->ayear,'period'=>$this->period),'default',true);?>" >
					<span class='dcsv'></span>
					<?php echo $this->translate("download")?>
				</a>
			</li>
			<li class="divider"></li>
			<li>
				<a href="<?php echo $this->url(array('module'=>'application','controller'=>'selection-highschool','action'=>'upload-batch-dean-rating','faculty_id'=>$this->faculty_id,'program_code'=>$this->program_code,'academic_year'=>$this->ayear,'period'=>$this->period),'default',true);?>" >
					<span class='upload'></span>
					<?php echo $this->translate("upload")?>
				</a>
			</li>
			<li>
				<a onclick="save();">
					<span class='save'></span>
					<?php echo $this->translate("save")?>
				</a>
			</li>
			<?php } ?>
			
			<li>
				<a href="#" >
					<span class='info'></span>
					<?php echo $this->translate("info")?>
				</a>
			</li>
		</ul>
	</div>
</div>


<?if(isset($this->noticeMessage)){?>
<div class="message notice"><strong><? echo $this->noticeMessage;?></strong>.</div>
<?}?>
<?if(isset($this->noticeSuccess)){?>
<div class="message success"><strong><? echo $this->noticeSuccess;?></strong>.</div>
<?}?>
<?if(isset($this->noticeError)){?>
<div class="message error"><strong><? echo $this->noticeError;?></strong>.</div>
<?}?>

<div style="width:100%;">
<?php echo $this->form;?>
<br>

<?php if(isset($this->paginator)){?>


<?php echo $this->translate("to_download_batch_rating_format");?>&nbsp;
<a href="http://<?php echo APP_HOSTNAME;?>/documents/template/dean_rating_format.csv"><?php echo $this->translate("please_click_here");?></a>
<br>
<br>
				
				
				<form name="myform" id="myform" method="post" action="<?php echo $this->url(array('module'=>'application','controller'=>'selection-highschool','action'=>'save-dean-rating'),'default',true);?>">
				
				<input type="hidden" name="nomor" id="nomor"  value="">
				<input type="hidden" name="decree_date" id="decree_date" value="">
				
				<table class="table" width="100%" cellpadding="5" cellspacing="2" border="0">
					<tr>
						<th><?php echo $this->translate("no");?></th>			
						<th><?php echo $this->translate("applicantID");?></th>
						<th><?php echo $this->translate("name");?></th>	
						<th><?php echo $this->translate("program");?></th>	
						<th><?php echo $this->translate("mark");?></th>		
						<th><?php echo $this->translate("rank")?></th>
						<th><?php echo $this->translate("status")?></th>
						
					</tr>
					
					<?php 					
					$no=1;
					foreach ($this->paginator as $entry){
						
					//get education average mark
					$educationDB = new App_Model_Application_DbTable_ApplicantEducation();
					//$education = $educationDB->getEducationDetail($entry["appl_id"]);
					$everage_mark = $educationDB->getAverageMark($entry["appl_id"]);
						
					
					
					?>
					<tr>
						<td align="center"><?php echo $no;?></td>		
						<td><?php echo $entry["applicantID"]?></td>
						<td><?php echo $entry["appl_fname"].' '.$entry["appl_mname"].' '.$entry["appl_lname"]?></td>
						<td><?php echo $entry["program_name_indonesia"]?></td>	
						<td align="center"><?php echo round($everage_mark,2);?></td>	
						
						<td align="center">
						    <input type="hidden" name="transaction_id[]" value="<?php echo $entry["transaction_id"]?>"></input>
							<select name="dean_rating[]">
								<option value="1">1</option>
								<option value="2">2</option>
								<option value="3">3</option>
							</select></td>
						<td align="center">						    
							<select name="dean_status[]">
								<option value="1"><?php echo $this->translate("accept")?></option>
								<option value="2"><?php echo $this->translate("reject")?></option>
								<option value="3"><?php echo $this->translate("pending")?></option>
							</select></td>			
						
					</tr>
					<?php $no++;}//end paginator 
					?>
						
				</table>
				</form>

	
	
<?php }//end paginator?>
</div>


<div id="dialog-info" title="Details Info">
	<table width="100%" class="table5">
		<tr>
			<td>
				<?php echo $this->translate("nomor")?>
			</td>
			<td width="5px">:</td>
			<td>
				<input type="text" name="dialog_nomor" id="dialog_nomor" style="width:250px" />
			</td>
		</tr>
		<tr>
			<td>
				<?php echo $this->translate("date")?>
			</td>
			<td width="5px">:</td>
			<td>
				<input type="text" name="dialog_decree_date" id="dialog_decree_date" style="width:250px" readonly />
			</td>
		</tr>
		
	</table>

</div>
