


<table   width="100%" cellpadding="5" cellspacing="2" border=0>
	<tr >
		<td valign="top" rowspan="2" align="center"><img src="<?php echo $this->baseUrl(); ?>/images/logo.png"></td>
		<td>
			<table>
				
				<tr>
					<td>Nomor</td>
					<td>:</td>
					<td></td>
				</tr>
				<tr>
					<td>Tanggal</td>
					<td>:</td>
					<td></td>
				</tr>
				<tr>
					<td>Facultas</td>
					<td>:</td>
					<td><?php echo $this->faculty_name;?></td>
				</tr>
				<tr>
					<td>Lampiran</td>
					<td>:</td>
					<td>1 (satu) berkas</td>
				</tr>
				<tr valign="top">
					<td>Perihal</td>
					<td>:</td>
					<td>Hasil seleksi PSSB <br> 
					    <?php echo ($this->period_name);?> <br> 
					   Tahun Akademik <?php echo $this->current_academic_year?>




</td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td align="center">&nbsp;
</td>
	</tr>
	
	
	
	
	<tr>
	
	<td colspan=2>
	<br>
	
	
	
	<table class="table4" width="100%" cellpadding="5" cellspacing="2" border="0">
	<tr>
	   <th><?php echo $this->translate("no");?></th>				
		<th><?php echo $this->translate("applicantID");?></th>
		<th><?php echo $this->translate("name");?></th>
		<th><?php echo $this->translate("program");?></th>		
	    <th><?php echo $this->translate("dean_rank");?></th>
		<th><?php echo $this->translate("dean_status");?></th>
		<th><?php echo $this->translate("rector_rank");?></th>
		<th><?php echo $this->translate("rector_status");?></th>			
		<th><?php echo $this->translate("approval")?></th>
		
	</tr>
	
	<?php 
	if(isset($this->applicant)){
		$no=1;
	foreach ($this->applicant as $entry){
			
	//get dean rating
	$assessmentDB=new App_Model_Application_DbTable_ApplicantAssessment();
	$rate = $assessmentDB->getData($entry["transaction_id"]);
	?>
	<tr>
	   <td><?php echo $no;?></td>	
		<td><?php echo $entry["applicantID"]?>&nbsp;</td>
		<td><?php echo $entry["appl_fname"].' '.$entry["appl_mname"].' '.$entry["appl_lname"]?></td>	
		<td><?php echo $entry["program_name_indonesia"]?></td>	
		<td align="center"><?php echo $rate["aar_rating_dean"];?></td>
		<td align="center">
		<?php 
			if($rate["aar_dean_status"]==1){ echo $this->translate("accept"); }
			if($rate["aar_dean_status"]==2){ echo $this->translate("reject"); }
		?></td>
		<td align="center"><?php echo $rate["aar_rating_rector"];?></td>
		<td align="center">
		<?php
			if($rate["aar_rector_status"]==1){ echo $this->translate("accept"); }
			if($rate["aar_rector_status"]==2){ echo $this->translate("reject"); }
		?></td>			
		<td align="left">
		<input type="checkbox" value="Offer">Offer<br>
		<input type="checkbox" value="Reject">Reject<br>
		</td>
	</tr>
	<?php $no++;}//end paginator 
	}?>
		
</table>
<br>
  </td></tr>
	<tr>
	<td colspan=2>Adapun JADWAL REGISTRASI  adalah <?php echo $this->registrasi["StartDate"]?> s.d <?php echo $this->registrasi["EndDate"]?>
	</td>
	</tr>
	<tr>
	<td colspan=2>Demikian kami sampaikan. Atas perhatian dan kerjasamanya diucapka terima kasih.
	</td>
	</tr>
<tr>
	<td>&nbsp;</td>
	<td>
	<br>
	<br>
	<br>
	<br>
	
	<table align=right  width="60%" border=0>
								
				<tr>
					
					<td  align="center"> 					
					<p>a.n. WAKIL REKTOR BIDANG AKADEMIK,</p><br><br></td>	
				</tr>
				<tr >
					
					<td valign="bottom" height="100"  align="center"> 	
<strong><p>Ir.Bani Nugroho, MT <br>
( Kepala Biro Adm.Akademik )
</p></strong>
</td>
					
				</tr>
			</table>
			
	</td>
</tr>
</table>




	

