<div class="message toolbar">
	<h2><?php echo $this->title; ?></h2>
	<div class="toolbar-button">
		<ul>		
			
			<li>
				<a href="<?php echo $this->url(array('module'=>'application','controller'=>'selection-highschool', 'action'=>'batch-approval','faculty_id'=>$this->faculty_id,'program_code'=>$this->program_code,'academic_year'=>$this->ayear,'period'=>$this->period));?>" >
					<span class='back'></span>
					Back
				</a>
			</li>
		
			
			<li>
				<a href="#" >
					<span class='info'></span>
					<?php echo $this->translate("info")?>
				</a>
			</li>
		</ul>
	</div>
</div>


<?if(isset($this->noticeMessage)){?>
<div class="message notice"><strong><? echo $this->noticeMessage;?></strong>.</div>
<?}?>
<?if(isset($this->noticeSuccess)){?>
<div class="message success"><strong><? echo $this->noticeSuccess;?></strong>.</div>
<?}?>
<?if(isset($this->noticeError)){?>
<div class="message error"><strong><? echo $this->noticeError;?></strong>.</div>
<?}?>

<?php echo $this->form;?>